
package net.nanopay.kotak.xmlns.cms_generic_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import net.nanopay.kotak.schemas.cms_generic.payment_request.RequestHeaderType;
import net.nanopay.kotak.schemas.cms_generic.payment_response.Acknowledgement;
import net.nanopay.kotak.schemas.cms_generic.payment_response.FaultListType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebAPI", targetNamespace = "http://xmlns.kotak.com/CMS_Generic_Service")
@XmlSeeAlso({
    net.nanopay.kotak.schemas.cms_generic.payment_request.ObjectFactory.class,
    net.nanopay.kotak.schemas.cms_generic.payment_response.ObjectFactory.class,
    net.nanopay.kotak.schemas.cms_generic.reversal_request.ObjectFactory.class,
    net.nanopay.kotak.schemas.cms_generic.reversal_response.ObjectFactory.class
})
public interface WebAPI {


    /**
     * 
     * @param ackHeader
     * @param faultList
     * @param instrumentList0
     * @param requestHeader
     * @param instrumentList
     */
    @WebMethod(operationName = "Payment", action = "/BusinessServices/StarterProcesses/CMS_Generic_Service.serviceagent/Payment")
    @RequestWrapper(localName = "Payment", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Payment_Request.xsd", className = "net.nanopay.kotak.schemas.cms_generic.payment_request.InitiateRequest")
    @ResponseWrapper(localName = "Payment", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Payment_Response.xsd", className = "net.nanopay.kotak.schemas.cms_generic.payment_response.AcknowledgementType")
    public void payment(
      @WebParam(name = "RequestHeader", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Payment_Request.xsd")
        RequestHeaderType requestHeader,
      @WebParam(name = "InstrumentList", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Payment_Request.xsd")
        net.nanopay.kotak.schemas.cms_generic.payment_request.InstrumentListType instrumentList,
      @WebParam(name = "AckHeader", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Payment_Response.xsd", mode = WebParam.Mode.OUT)
        Holder<Acknowledgement> ackHeader,
      @WebParam(name = "InstrumentList", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Payment_Response.xsd", mode = WebParam.Mode.OUT)
        Holder<net.nanopay.kotak.schemas.cms_generic.payment_response.InstrumentListType> instrumentList0,
      @WebParam(name = "FaultList", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Payment_Response.xsd", mode = WebParam.Mode.OUT)
        Holder<FaultListType> faultList);

    /**
     * 
     * @param header0
     * @param header
     * @param details
     * @param details0
     */
    @WebMethod(operationName = "Reversal", action = "/BusinessServices/StarterProcesses/CMS_Generic_Service.serviceagent/Reversal")
    @RequestWrapper(localName = "Reversal", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Reversal_Request.xsd", className = "net.nanopay.kotak.schemas.cms_generic.reversal_request.Reversal")
    @ResponseWrapper(localName = "Reversal", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Reversal_Response.xsd", className = "net.nanopay.kotak.schemas.cms_generic.reversal_response.Reversal")
    public void reversal(
      @WebParam(name = "Header", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Reversal_Request.xsd")
        net.nanopay.kotak.schemas.cms_generic.reversal_request.Header header,
      @WebParam(name = "Details", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Reversal_Request.xsd")
        net.nanopay.kotak.schemas.cms_generic.reversal_request.Details details,
      @WebParam(name = "Header", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Reversal_Response.xsd", mode = WebParam.Mode.OUT)
        Holder<net.nanopay.kotak.schemas.cms_generic.reversal_response.Header> header0,
      @WebParam(name = "Details", targetNamespace = "http://www.kotak.com/schemas/CMS_Generic/Reversal_Response.xsd", mode = WebParam.Mode.OUT)
        Holder<net.nanopay.kotak.schemas.cms_generic.reversal_response.Details> details0);

}
