/**
 * @license
 * Copyright 2025 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */
foam.POM({
  name: "auth",
  projects: [
    { name: 'test/pom',                                               flags: "test"}
  ],

  files: [
    { name: "LifecycleState",                                         flags: "js|java" },
    { name: "LifecycleAware",                                         flags: "js|java" },
    { name: "LifecycleAwareDAO",                                      flags: "js|java" },
    { name: "User",                                                   flags: "js|java" },
    { name: "CreatedAware",                                           flags: "js|java" },
    { name: "CreatedAwareDAO",                                        flags: "js|java" },
    { name: "CreatedAwareMixin",                                      flags: "js" },
    { name: "CreatedByAware",                                         flags: "js|java" },
    { name: "CreatedByAwareDAO",                                      flags: "js|java" },
    { name: "CreatedByAwareMixin",                                    flags: "js" },
    { name: "DeletedAware",                                           flags: "js|java" },
    { name: "DeletedAwareDAO",                                        flags: "js|java" },
    { name: "DeletedAwareDAOTest",                                    flags: "js&test|java&test" },
    { name: "EnabledAware",                                           flags: "js|java" },
    { name: "FailedLoginAuthService",                                 flags: "js|java" },
    { name: "LastModifiedAware",                                      flags: "js|java" },
    { name: "LastModifiedAwareDAO",                                   flags: "js|java" },
    { name: "LastModifiedByAware",                                    flags: "js|java" },
    { name: "LastModifiedByAwareDAO",                                 flags: "js|java" },
    { name: "LastModifiedAwareMixin",                                 flags: "js" },
    { name: "LastModifiedByAwareMixin",                               flags: "js" },
    { name: "LastModifiedByAgentNameAware",                           flags: "js|java" },
    { name: "LoginAttempt",                                           flags: "js|java" },
    { name: "ServiceProvider",                                        flags: "js|java" },
    { name: "ServiceProviderAware",                                   flags: "js|java" },
    { name: "ServiceProviderAwareDAO",                                flags: "js|java" },
    { name: "ServiceProviderAwarePredicate",                          flags: "js|java" },
    { name: "ServiceProviderAwareSink",                               flags: "js|java" },
    { name: "ServiceProviderAwareSupport",                            flags: "js|java" },

    { name: "UserCitationView",                                       flags: "web" },
    { name: "UserNotFoundException",                                  flags: "js|java" },
    { name: "UserAndGroupAuthService",                                flags: "js|java" },
    { name: "UserQueryService",                                       flags: "js|java" },
    { name: "Authorizable",                                           flags: "js|java" },
    { name: "Authorizer",                                             flags: "js|java" },
    { name: "PropertyType",                                           flags: "js|java" },
    { name: "Country",                                                flags: "js|java" },
    { name: "Region",                                                 flags: "js|java" },
    { name: "Address",                                                flags: "js|java" },
    { name: "PKAddress",                                              flags: "js|java" },
    { name: "GBAddress",                                              flags: "js|java" },
    { name: "AccessDeniedException",                                  flags: "js|java" },
    { name: "AccountLockedException",                                 flags: "js|java" },
    { name: "AccountDisabledException",                               flags: "js|java" },
    { name: "AgentJunctionStatus",                                    flags: "js|java" },
    { name: "AuthenticationException",                                flags: "js|java" },
    { name: "AuthorizationException",                                 flags: "js|java" },
    { name: "AuthorizationDAO",                                       flags: "js|java" },
    { name: "CreateUserCapabilityJunctionOnSpidSet",                  flags: "js|java" },
    { name: "Credential",                                             flags: "js|java" },
    { name: "DuplicateEmailException",                                flags: "js|java" },
    { name: "DuplicateUserNameException",                             flags: "js|java" },
    { name: "FilterBySpidService",                                    flags: "js|java" },
    { name: "Group",                                                  flags: "js|java" },
    { name: "GroupPermissionJunctionRefinement",                      flags: "js|java" },
    { name: "InvalidPasswordException",                               flags: "js|java" },
    { name: "Language",                                               flags: "js|java" },
    { name: "PreventDuplicateEmailLoginService",                      flags: "js|java" },
    { name: "SetUserServiceProviderJunctionRuleAction",               flags: "js|java" },
    { name: "UnverifiedEmailException",                               flags: "js|java" },
    { name: "PasswordPolicy",                                         flags: "js|java" },
    { name: "PermissionTableView",                                    flags: "js" },
    { name: "SpidPermissionTableView",                                flags: "js" },
    { name: "UserPermissionTableView",                                flags: "js" },
    { name: "LanguageChoiceView",                                     flags: "web" },
    { name: "Login",                                                  flags: "js" },
    { name: "Permission",                                             flags: "js|java" },
    { name: "Phone",                                                  flags: "js|java" },
    { name: "HtmlDoc",                                                flags: "js|java" },
    { name: "SignOutView",                                            flags: "js" },
    { name: "email/EmailDocInterface",                                flags: "js|java" },
    { name: "email/EmailDocService",                                  flags: "js|java" },
    { name: "email/ClientEmailDocService",                            flags: "js|java" },
    { name: "resetPassword/SuccessView",                              flags: "js" },
    { name: "resetPassword/ResetPasswordTokenService",                flags: "js|java" },
    { name: "token/TokenService",                                     flags: "js|java" },
    { name: "token/ClientTokenService",                               flags: "js|java" },
    { name: "token/Token",                                            flags: "js|java" },
    { name: "token/AbstractTokenService",                             flags: "js|java" },
    { name: "token/TokenExpiredException",                            flags: "js|java" },
    { name: "token/TokenInvalidException",                            flags: "js|java" },
    { name: "ChangePasswordView",                                     flags: "js" },
    { name: "resetPassword/ResetPassword",                            flags: "js|java" },
    { name: "resetPassword/ResetPasswordByCode",                      flags: "js|java" },
    { name: "resetPassword/ResetPasswordByToken",                     flags: "js|java" },
    { name: "resetPassword/SetNewPassword",                           flags: "js|java" },
    { name: 'resetPassword/ResetPasswordService',                     flags: 'js|java' },
    { name: 'resetPassword/ServerResetPasswordService',               flags: 'js|java' },
    { name: "RetrievePassword",                                       flags: "js|java" },
    { name: "UpdatePassword",                                         flags: "js" },
    { name: "Subject",                                                flags: "js|java" },
    { name: "PriorPassword",                                          flags: "js|java" },
    { name: "UserLifecycleDeletedRuleAction",                         flags: "js|java" },
    { name: "UserLifecycleStateDAO",                                  flags: "js|java" },
    { name: "UserLifecycleTicket",                                    flags: "js|java" },
    { name: "UserLifecycleTicketSink",                                flags: "js|java" },
    { name: "UserLifecycleTicketRuleAction",                          flags: "js|java" },
    { name: "UserLifecycleTicketUpdate",                              flags: "js|java" },
    { name: "ruler/AddPasswordHistoryAction",                         flags: "js|java" },
    { name: "ruler/PreventDuplicateEmailAction",                      flags: "js|java" },
    { name: "ruler/PreventDuplicateUsernameAction",                   flags: "js|java" },
    { name: "ruler/PreventInvalidUsernameAction",                     flags: "js|java" },
    { name: "ruler/EnsurePropertyOnCreateRule",                       flags: "js|java" },
    { name: "PermissionedPropertyDAO",                                flags: "js|java" },
    { name: "ProfilePictureView",                                     flags: "web" },
    { name: "twofactor/OTPAuthService",                               flags: "js|java" },
    { name: "twofactor/AbstractOTPAuthService",                       flags: "js|java" },
    { name: "twofactor/AbstractTOTPAuthService",                      flags: "js|java" },
    { name: "twofactor/ClientOTPAuthService",                         flags: "js|java" },
    { name: "twofactor/GoogleTOTPAuthService",                        flags: "js|java" },
    { name: "twofactor/TwoFactorAuthService",                         flags: "js|java" },
    { name: "twofactor/TwoFactorSignInView",                          flags: "js" },
    { name: "twofactor/UserRefinements",                              flags: "js" },
    { name: "twofactor/ThemeRefinements",                             flags: "js" },
    { name: "SimpleUserQueryService",                                 flags: "js|java" },
    { name: "ResetSpidBeforeLoginAuthService",                        flags: "js|java" },
    { name: "LocaleSupport",                                          flags: "js|java" },
    { name: "PasswordExpiryAuthService",                              flags: "js|java" },
    { name: "SystemAuthService",                                      flags: "js|java" },
    { name: "LoggingAuthService",                                     flags: "js|java" },
    { name: "SubjectAuthService",                                     flags: "js|java" },
    { name: "LogoutDisabledUserDAO",                                  flags: "js|java" },
    { name: "EnabledCheckAuthService",                                flags: "js|java" },
    { name: "UserPropertyAvailabilityService",                        flags: "js|java" },
    { name: "UserPropertyAvailabilityServiceInterface",               flags: "js|java" },
    { name: "ClientUserPropertyAvailabilityService",                  flags: "js|java" },
    { name: "UserMDCitationView",                                     flags: "js" },
    { name: "UserRegistrationDAO",                                    flags: "js|java" },
    { name: "UserRegistrationSanitationDAO",                          flags: "js|java" },
    { name: "CommonPassword",                                         flags: "js|java" },
    { name: "AddressConfig",                                          flags: "js|java" },
    { name: "AuthorizeAnonymousClientDecorator",                      flags: "js" },
    { name: "predicate/IsAnonymousPredicate",                         flags: "js|java" },
    { name: "Relationships",                                          flags: "js|java" },
    { name: "twofactor/OTPKey",                                       flags: "js|java" },
    { name: "LoginService",                                           flags: "js|java" },
    { name: "AuthService",                                            flags: "js|java" },
    { name: "ProxyAuthService",                                       flags: "js|java" },
    { name: "CachedAuthServiceProxy",                                 flags: "js" },
    { name: "ClientAuthService",                                      flags: "js|java" },
    { name: "ClientLoginAuthService",                                 flags: "js|java" },
    { name: "AgentAuthService",                                       flags: "js|java" },
    { name: "AgentAuthClient",                                        flags: "js|java" },
    { name: "ClientAgentAuthService",                                 flags: "js|java" },
    { name: "UniqueUserService",                                      flags: "js|java" },
    { name: "PMAuthService",                                          flags: "js|java" },
    { name: "CapabilityAuthService",                                  flags: "js|java" },
    { name: 'email/EmailVerificationCode',                            flags: 'js|java' },
    { name: 'email/VerificationCodeView',                             flags: 'js' },
    { name: 'email/EmailVerificationService',                         flags: 'js|java' },
    { name: 'email/ServerEmailVerificationService',                   flags: 'js|java' },
    { name: 'email/VerifyEmail',                                      flags: 'js|java' },
    { name: 'email/VerificationCodeException',                        flags: 'js|java' },
    { name: 'email/wizard/EmailVerificationCodeLoader',               flags: 'web' },
    { name: "login/SignIn",                                           flags: "js|java" },
    { name: "login/SignUp",                                           flags: "js|java" },
    { name: "login/ClientLoginService",                               flags: "js" },
    { name: "login/LoginView",                                        flags: "js" },
    { name: "email/EmailVerificationDAO",                             flags: "js|java" },
    { name: "UserPasswordHashingDAO",                                 flags: "js|java" }
  ],
  javaFiles: [
    { name: "StandardAuthorizer" },
    { name: "GlobalFindOrPutAuthorizer" },
    { name: "GlobalPutAuthorizer" },
    { name: "GlobalFindAuthorizer" },
    { name: "AuthorizableAuthorizer" },
    { name: "GlobalReadAuthorizer" },
    { name: "CachingAuthService" },
    { name: "AgentUserAuthService" },
    { name: "Challenge" },
    { name: "RegionService" },
    { name: "CountryService" },
    { name: "validators/UserGroupAndSpidValidator" }
  ]
});
