/**
 * @license
 * Copyright 2023 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.CLASS({
  package: 'foam.nanos.referral',
  name: 'CreateReferralCodeRuleAction',

  documentation: `Create a referral code on user creation.`,

  implements: ['foam.nanos.ruler.RuleAction'],

  javaImports: [
    'foam.core.ContextAgent',
    'foam.core.X',
    'foam.dao.DAO',
    'foam.nanos.app.AppConfig',
    'foam.nanos.auth.User'
  ],

  methods: [
    {
      name: 'applyAction',
      javaCode: `
      agency.submit(x, new ContextAgent() {
        @Override
        public void execute(X x) {
          User user = (User) obj;
          AppConfig config = (AppConfig) x.get("appConfig");
          DAO referralCodeDAO = (DAO) ruler.getX().get("referralCodeDAO");
          ReferralCode referralCode = new ReferralCode();
          referralCode.setMenu("sign-up");
          referralCode.setWebsite(config.getUrl()+ "/?referral=");
          referralCode.setReferrer(user.getId());
          referralCode.setSpid(user.getSpid());
          referralCode.setAutoGenerated(true);
          referralCodeDAO.put_(ruler.getX(), referralCode);
        }
      }, "Creating a referral code");
      `
    }
  ]
});
