/**
 * NANOPAY CONFIDENTIAL
 *
 * [2020] nanopay Corporation
 * All Rights Reserved.
 *
 * NOTICE:  All information contained herein is, and remains
 * the property of nanopay Corporation.
 * The intellectual and technical concepts contained
 * herein are proprietary to nanopay Corporation
 * and may be covered by Canadian and Foreign Patents, patents
 * in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from nanopay Corporation.
 */

foam.CLASS({
  package: 'net.nanopay.sme.ui',
  name: 'PersonalSettingsView',
  extends: 'foam.u2.Controller',

  documentation: 'Personal settings page for Ablii',

  imports: [
    'subject',
    'twofactor'
  ],

  requires: [
    'foam.u2.dialog.Popup',
  ],

  css: `
    ^ {
      margin: auto;
      max-width: 1100px;
    }
    ^two-factor-card {
      padding: 24px;
      min-width: 350px;
    }
    ^two-factor-instr {
      margin: 0 auto;
    }
    ^two-factor-instr-left {
      display: inline-block;
      width: 380px;
      margin-bottom: 15px;
    }
    ^step-1 span {
      font-family: /*%FONT1%*/ Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size: 14px;
      font-weight: normal;
      font-style: normal;
      font-stretch: normal;
      line-height: 1.5;
      letter-spacing: normal;
      color: #8e9090;
    }
    ^two-factor-link {
      color: #604aff;
      display: inline-block;
      text-decoration: none;
    }
    ^step-2 {
      margin-top: 32px;
    }
    ^step-2 span {
      font-family: /*%FONT1%*/ Roboto, 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size: 14px;
      font-weight: normal;
      font-style: normal;
      font-stretch: normal;
      line-height: 1.5;
      letter-spacing: normal;
      color: #8e9090;
    }
    ^two-factor-instr-right {
      display: inline-block;
      vertical-align: top;
    }
    @media only screen and (max-width: 767px) {
      ^ .validation-input {
        margin-top: 15px;
      }
      ^two-factor-enable {
        margin-top: 15px;
      }

    }
    @media only screen and (min-width: 1133px) {
      ^two-factor-instr-right {
        margin-left: 20px;
      }
  `,

  constants: [
    {
      type: 'String',
      name: 'IOS_LINK',
      value: 'https://itunes.apple.com/ca/app/google-authenticator/id388497605?mt=8'
    },
    {
      type: 'String',
      name: 'ANDROID_LINK',
      value: 'https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en'
    },
  ],

  properties: [
    {
      class: 'String',
      name: 'twoFactorQrCode',
      documentation: 'Two-factor authentication QR code string'
    },
    {
      class: 'String',
      name: 'twoFactorToken',
      documentation: 'Two-factor token generated by authenticator app',
    }
  ],

  messages: [
    { name: 'TITLE', message: 'Personal settings' },
    { name: 'TWO_FACTOR_SUBTITLE', message: 'Two-factor authentication' },
    { name: 'TWO_FACTOR_INSTR1', message: 'Two-factor authentication provides an added layer of security against impersonation and prevents access to sensitive account information' },
    { name: 'TWO_FACTOR_INSTR2', message: 'Step 1: On your mobile device, download the Google Authenticator ' },
    { name: 'TWO_FACTOR_INSTR3', message: 'Step 2: Scan the QR code, or type the 16-digit key into the Google Authenticator app' },
    { name: 'TWO_FACTOR_INSTR4', message: 'Step 3: The app will provide a verification code. Enter the code and select ‘Verify’' },
    { name: 'IOS_NAME', message: 'iOS' },
    { name: 'ANDROID_NAME', message: 'Android' },
    { name: 'OR', message: ' or ' },
    { name: 'STEP_ONE', message: 'Step 1' },
    { name: 'STEP_TWO', message: 'Step 2' }
  ],

  methods: [
    function initE() {
      this
      .addClass(this.myClass())
      .start('h1').add(this.TITLE).end()

      .start().addClass('card')
        .start().tag({
          class: foam.nanos.auth.ChangePasswordView,
          modelOf: 'foam.nanos.auth.UpdatePassword',
          showHeader: false,
          isHorizontal: true
        }).end()
      .end()

      .br()

      .start().addClass('card').addClass(this.myClass('two-factor-card'))
        .start()
          .addClass('sub-heading')
          .add(this.TWO_FACTOR_SUBTITLE)
        .end()
        .add(this.slot(function(twoFactorEnabled) {
          if ( ! twoFactorEnabled ) {
            // two factor disabled
            return this.E()
              .start().addClass(this.myClass('two-factor-instr'))
                .start().addClass(this.myClass('two-factor-instr-left'))
                  .start().addClass(this.myClass('step-1'))
                    .br()
                    .start('span')
                      .add(this.TWO_FACTOR_INSTR1)
                      .br()
                      .add(this.TWO_FACTOR_INSTR2)
                      .start('a').addClass(this.myClass('two-factor-link'))
                        .add(this.IOS_NAME)
                        .attrs({ href: this.IOS_LINK, target: '_blank' })
                      .end()
                      .add(this.OR)
                      .start('a').addClass(this.myClass('two-factor-link'))
                        .add(this.ANDROID_NAME)
                        .attrs({ href: this.ANDROID_LINK, target: '_blank' })
                      .end()
                      .br()
                      .add(this.TWO_FACTOR_INSTR3)
                      .br()
                      .add(this.TWO_FACTOR_INSTR4)
                    .end()
                  .end()
                .end()
                .start({
                  class: 'net.nanopay.sme.ui.TwoFactorAuthView',
                  hideDisableButton: false
                })
                  .addClass(this.myClass('two-factor-instr-right'))
                .end()
              .end();
          } else {
            // two factor enabled
            return this.E()
              .start({
                class: 'net.nanopay.sme.ui.TwoFactorAuthView',
                hideDisableButton: false
              })
              .end();
          }
        }, this.subject.realUser.twoFactorEnabled$))
      .end();
    }
  ]
});
