#Concatenate files into one services file
cd ../
find foam2/src NANOPAY/**/src -type f -name accounts -exec cat {} \; > accounts
find foam2/src NANOPAY/**/src -type f -name branches -exec cat {} \; > branches
find foam2/src NANOPAY/**/src -type f -name bankAccounts -exec cat {} \; > bankAccounts
find foam2/src NANOPAY/**/src -type f -name branches -exec cat {} \; > branches
find foam2/src NANOPAY/**/src -type f -name brokers -exec cat {} \; > brokers
find foam2/src NANOPAY/**/src -type f -name businesses -exec cat {} \; > businesses
find foam2/src NANOPAY/**/src -type f -name canadaTransactions -exec cat {} \; > canadaTransactions
find foam2/src NANOPAY/**/src -type f -name cicoServiceProviders -exec cat {} \; > cicoServiceProviders
find foam2/src NANOPAY/**/src -type f -name countries -exec cat {} \; > countries
find foam2/src NANOPAY/**/src -type f -name countryAgents -exec cat {} \; > countryAgents
find foam2/src NANOPAY/**/src -type f -name cronjobs -exec cat {} \; > cronjobs
find foam2/src NANOPAY/**/src -type f -name currency -exec cat {} \; > currency
find foam2/src NANOPAY/**/src -type f -name devices -exec cat {} \; > devices
find foam2/src NANOPAY/**/src -type f -name dateofbirth -exec cat {} \; > dateofbirth
find foam2/src NANOPAY/**/src -type f -name exchangeRates -exec cat {} \; > exchangeRates
find foam2/src NANOPAY/**/src -type f -name exportDriverRegistrys -exec cat {} \; > exportDriverRegistrys
find foam2/src NANOPAY/**/src -type f -name groups -exec cat {} \; > groups
find foam2/src NANOPAY/**/src -type f -name historyRecords -exec cat {} \; > historyRecords
find foam2/src NANOPAY/**/src -type f -name indiaTransactions -exec cat {} \; > indiaTransactions
find foam2/src NANOPAY/**/src -type f -name identification -exec cat {} \; > identification
find foam2/src NANOPAY/**/src -type f -name invoices -exec cat {} \; > invoices
find foam2/src NANOPAY/**/src -type f -name invoiceResolutions -exec cat {} \; > invoiceResolutions
find foam2/src NANOPAY/**/src -type f -name languages -exec cat {} \; > languages
find foam2/src NANOPAY/**/src -type f -name menus -exec cat {} \; > menus
find foam2/src NANOPAY/**/src -type f -name pacs8india -exec cat {} \; > pacs8india
find foam2/src NANOPAY/**/src -type f -name pacs8iso -exec cat {} \; > pacs8iso
find foam2/src NANOPAY/**/src -type f -name payees -exec cat {} \; > payees
find foam2/src NANOPAY/**/src -type f -name permissions -exec cat {} \; > permissions
find foam2/src NANOPAY/**/src -type f -name regions -exec cat {} \; > regions
find foam2/src NANOPAY/**/src -type f -name scripts -exec cat {} \; > scripts
find foam2/src NANOPAY/**/src -type f -name services -exec cat {} \; > services
find foam2/src NANOPAY/**/src -type f -name tests -exec cat {} \; > tests
find foam2/src NANOPAY/**/src -type f -name transactions -exec cat {} \; > transactions
find foam2/src NANOPAY/**/src -type f -name users -exec cat {} \; > users
