foam.POM({"name":"sweeper","version":3,"files":[
{"name":"../../../foam/core/lib","flags":"web"},
{"name":"../../../foam/core/stdlib","flags":"web"},
{"name":"../../../foam/core/events","flags":"web"},
{"name":"../../../foam/core/Context","flags":"web"},
{"name":"../../../foam/core/LocalStorage","flags":"js"},
{"name":"../../../foam/core/Boot","flags":"web"},
{"name":"../../../foam/core/FObject","flags":"web"},
{"name":"../../../foam/core/Model","flags":"web"},
{"name":"../../../foam/core/Property","flags":"web"},
{"name":"../../../foam/core/Simple","flags":"web"},
{"name":"../../../foam/core/Method","flags":"web"},
{"name":"../../../foam/core/Boolean","flags":"web"},
{"name":"../../../foam/core/AxiomArray","flags":"web"},
{"name":"../../../foam/core/EndBoot","flags":"web"},
{"name":"../../../foam/core/Script","flags":"web"},
{"name":"../../../foam/pattern/Faceted","flags":"web"},
{"name":"../../../foam/core/Glyph","flags":"web"},
{"name":"../../../foam/core/types","flags":"web"},
{"name":"../../../foam/core/Duration","flags":"web"},
{"name":"../../../foam/core/FObjectArray","flags":"web"},
{"name":"../../../foam/core/Constant","flags":"web"},
{"name":"../../../foam/core/Topic","flags":"web"},
{"name":"../../../foam/core/InnerClass","flags":"web"},
{"name":"../../../foam/core/InnerEnum","flags":"web"},
{"name":"../../../foam/core/Mixin","flags":"web"},
{"name":"../../../foam/core/Implements","flags":"web"},
{"name":"../../../foam/core/ImportsExports","flags":"web"},
{"name":"../../../foam/core/Listener","flags":"web"},
{"name":"../../../foam/core/IDSupport","flags":"web"},
{"name":"../../../foam/core/Requires","flags":"web"},
{"name":"../../../foam/core/Slot","flags":"web"},
{"name":"../../../foam/core/Proxy","flags":"web"},
{"name":"../../../foam/core/Latch","flags":"web"},
{"name":"../../../foam/core/Lock","flags":"web"},
{"name":"../../../foam/core/CountingSemaphore","flags":"web"},
{"name":"../../../foam/core/Promised","flags":"web"},
{"name":"../../../foam/core/Interface","flags":"web"},
{"name":"../../../foam/core/Type","flags":"web"},
{"name":"../../../foam/core/Axiom","flags":"web"},
{"name":"../../../foam/core/ContextMethod","flags":"web"},
{"name":"../../../foam/core/Exception","flags":"web"},
{"name":"../../../foam/core/FOAMException","flags":"web"},
//{"name":"../../../foam/core/FOAMExceptionTest","flags":"web"},
{"name":"../../../foam/core/Window","flags":"web"},
{"name":"../../../foam/core/ContextMultipleInheritence","flags":"web"},
{"name":"../../../foam/core/Argument","flags":"web"},
{"name":"../../../foam/core/MultiMethod","flags":"web"},
{"name":"../../../foam/core/debug","flags":"web"},
// {"name":"../../../foam/core/CoreTypesValidationTest","flags":"web"},
{"name":"../../../foam/pattern/Singleton","flags":"web"},
{"name":"../../../foam/pattern/Multiton","flags":"web"},
{"name":"../../../foam/core/Enum","flags":"web"},
//{"name":"../../../foam/core/JSON","flags":"web"},
//{"name":"../../../foam/core/XML","flags":"web"},
{"name":"../../../foam/core/holders","flags":"web"},
{"name":"../../../foam/core/CompoundException","flags":"web"},
//{"name":"../../../foam/lib/csv/DynamicHeaderCSVParser","flags":"web"},
{"name":"../../../foam/core/Validator","flags":"web"},
{"name":"../../../foam/core/ValidationException","flags":"web"},
{"name":"../../../foam/core/ClientRuntimeException","flags":"web"},
{"name":"../../../foam/core/OptionalBoolean","flags":"web"},
// {"name":"../../../foam/parse/parse","flags":"web"},
// {"name":"../../../foam/core/templates","flags":"web"},
{"name":"../../../foam/i18n/Messages","flags":"web"},
{"name":"../../../foam/core/Validation","flags":"web"},
{"name":"../../../foam/core/Action","flags":"web"},
{"name":"../../../foam/core/Static","flags":"web"},
{"name":"../../../foam/core/Reaction","flags":"web"},
{"name":"../../../foam/core/Serializable","flags":"web"},
{"name":"../../../foam/core/Freezable","flags":"web"},
{"name":"../../../foam/core/Detachable","flags":"web"},
{"name":"../../../foam/core/ContextAgent","flags":"web"},
{"name":"../../../foam/core/CompoundContextAgency","flags":"web"},
{"name":"../../../foam/core/Validatable","flags":"web"},
{"name":"../../../foam/core/AxiomCloner","flags":"web"},
{"name":"../../../foam/core/Agency","flags":"web"},
{"name":"../../../foam/core/AbstractAgency","flags":"web"},
{"name":"../../../foam/core/PropertyInfo","flags":"web"},
{"name":"../../../foam/core/Fluent","flags":"web"},
// {"name":"../../../foam/util/Timer","flags":"web"},
{"name":"../../../foam/u2/ViewSpec","flags":"web"},
{"name":"../../../foam/u2/ControllerMode","flags":"web"},
{"name":"../../../foam/u2/DisplayMode","flags":"web"},
{"name":"../../../foam/u2/CSS","flags":"web"},
{"name":"../../../foam/u2/Element","flags":"web"},
{"name":"../../../foam/u2/CSSToken","flags":"web"},
// {"name":"../../../foam/version/VersionTrait","flags":"web"},
// {"name":"../../../foam/version/VersionedClass","flags":"web"},
// {"name":"../../../foam/version/VersionedClassFactory","flags":"web"},
// {"name":"../../../foam/dao/DAOProperty","flags":"web"},
 {"name":"../../../foam/dao/SQLStatement","flags":"web"}, // needed by comparator
//{"name":"../../../foam/dao/CSVSink","flags":"web"},
// {"name":"../../../foam/mlang/order/Comparator","flags":"web"},
// {"name":"../../../foam/mlang/mlang","flags":"web"},
//{"name":"../../../foam/dao/index/TreeIndex","flags":"web"},
//{"name":"../../../foam/dao/sync/SyncRecord","flags":"web"},
//{"name":"../../../foam/parse/QueryParser","flags":"web"},
//{"name":"../../../foam/net/web/WebSocket","flags":"web"},
//{"name":"../../../foam/net/web/WebSocketService","flags":"web"},
//{"name":"../../../foam/net/web/HTTPResponse","flags":"web"},
//{"name":"../../../foam/net/web/HTTPRequest","flags":"web"},
//{"name":"../../../foam/core/StubMethod","flags":"web"},
//{"name":"../../../foam/core/StubAction","flags":"web"},
//{"name":"../../../foam/core/Stub","flags":"web"},
//{"name":"../../../foam/box/HTTPAuthorizationType","flags":"web"},
//{"name":"../../../foam/core/async","flags":"web"},
{"name":"../../../foam/core/NullAgent","flags":"web"},
// {"name":"../../../foam/u2/TableView","flags":"web"},
{"name":"../../../foam/u2/ButtonStyle","flags":"web"},
{"name":"../../../foam/u2/ActionButtonStyleRefinement","flags":"web"},
{"name":"../../../foam/u2/tag/Image","flags":"web"},
// {"name":"../../../foam/u2/view/ChoiceView","flags":"web"},
// {"name":"../../../foam/u2/view/Formatter","flags":"web"},
// {"name":"../../../foam/u2/view/FnFormatter","flags":"web"},
//{"name":"../../../foam/u2/view/TableCellFormatter","flags":"web"},
//{"name":"../../../foam/u2/filter/FilterRefinements","flags":"web"},
{"name":"../../../foam/apploader/ModelRefines","flags":"web"},
{"name":"../../../foam/apploader/NoClassLoader","flags":"web"},
{"name":"../../../foam/u2/FoamTagLoader","flags":"web"},
{"name":"../../../foam/core/ContextAware","flags":"web"},
//{"name":"../../../foam/core/FObjectTest","flags":"web"},
// {"name":"../../../org/chartjs/AbstractChartCView","flags":"web"},
//{"name":"../../../foam/u2/layout/GridColumns","flags":"web"},
//{"name":"../../../foam/layout/SectionAxiom","flags":"web"},
{"name":"../../../foam/core/Unit","flags":"web"},
//{"name":"../../../foam/core/Currency","flags":"web"},
//{"name":"../../../foam/core/NumberSet","flags":"web"},
//{"name":"../../../foam/u2/table/UnstyledTableView","flags":"web"},
//{"name":"../../../foam/u2/memento/Memento","flags":"web"},
//{"name":"../../../foam/core/FOAMExceptionTestTestException","flags":"web"},
{"name":"../../../foam/core/Identifiable","flags":"web"},
//{"name":"../../../foam/demos/u2/AllViews","flags":"web"},
{"name":"../../../foam/audio/Speak","flags":"web"},
{"name":"Game","flags":"web"},
{"name":"Board","flags":"web"},
{"name":"Cell","flags":"web"}]});
