/**
 * @license
 * Copyright 2017 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

FOAM_FILES([
  { name: "foam/nanos/client/ClientBuilder" },
  { name: "foam/nanos/controller/AppStyles", flags: ["web"] },
  { name: "foam/nanos/logger/LogMessage", flags: [ "java" ] },
  { name: "foam/nanos/logger/LogMessageDAO", flags: [ "java" ] },
  { name: "foam/nanos/logger/AbstractLogger", flags: [ "java" ] },
  { name: "foam/nanos/logger/ProxyLogger", flags: [ "java" ] },
  { name: "foam/nanos/logger/LoggerJDAO", flags: [ "java" ] },
  { name: "foam/nanos/logger/LogLevelFilterLogger", flags: [ "java" ] },
  { name: "foam/nanos/logger/NotificationLogMessageDAO", flags: [ "java" ] },
  { name: "foam/nanos/logger/RepeatLogMessageDAO", flags: [ "java" ] },
  { name: "foam/nanos/logger/StdoutLoggerDAO", flags: [ "java" ] },
  { name: "foam/nanos/logger/benchmark/LoggerBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/fs/File", flags: [ "java" ] },
  { name: "foam/nanos/fs/FileLabel", flags: [ "java" ] },
  { name: "foam/nanos/fs/FileType", flags: [ "java" ] },
  { name: "foam/nanos/fs/FileProperty" },
  { name: "foam/nanos/fs/FileDAODecorator" },
  { name: "foam/nanos/fs/FileArray" },
  { name: "foam/nanos/fs/FileArrayDAODecorator" },
  { name: "foam/nanos/fs/FileArrayInCapablePayloadsDecorator" },
  { name: "foam/nanos/fs/FileSizeView", flags: ["web"] },
  { name: "foam/nanos/fs/fileDropZone/FileDropZone", flags: ["web"] },
  { name: "foam/nanos/fs/fileDropZone/FilePreview", flags: ["web"] },
  { name: "foam/nanos/fs/fileDropZone/FileCard", flags: ["web"] },
  { name: "foam/nanos/fs/fileDropZone/FileUploader", flags: ["web"] },
  { name: "foam/nanos/fs/TempFile", flags: [ "java" ] },
  { name: "foam/nanos/crunch/AssociatedEntity", flags: [ "java" ] },
  { name: "foam/nanos/crunch/CapabilityGrantMode", flags: [ "java" ] },
  { name: "foam/nanos/crunch/Capability", flags: [ "java" ] },
  { name: "foam/nanos/auth/ServiceProvider", flags: [ "java" ] },
  { name: "foam/nanos/auth/test/DummySp", flags: [ "java" ] },
  { name: "foam/nanos/fs/TextSaveView", flags: ["web"] },
  { name: "foam/nanos/app/AppConfig", flags: ["java"] },
  { name: "foam/nanos/app/AppConfigService", flags: [ "java" ] },
  { name: "foam/nanos/app/ContextLookupAppConfigService", flags: [ "java" ] },
  { name: "foam/nanos/app/Health", flags: [ "java" ] },
  { name: "foam/nanos/app/HealthFactory", flags: [ "java" ] },
  { name: "foam/nanos/app/HealthHeartbeatMonitor", flags: [ "java" ] },
  { name: "foam/nanos/app/HealthHeartbeatService", flags: [ "java" ] },
  { name: "foam/nanos/app/HealthStatus", flags: [ "java" ] },
  { name: "foam/nanos/app/Mode", flags: ["java"] },
  { name: "foam/nanos/app/SupportConfig", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/SMTPConfig", flags: [ "java" ] },
  { name: "foam/nanos/app/ClientAppConfigService" },
  { name: "foam/nanos/controller/WindowHash" },
  { name: "foam/nanos/controller/Memento" },
  { name: "foam/nanos/controller/MementoMixin" },
  { name: "foam/nanos/controller/ApplicationController" },
  { name: "foam/nanos/alarming/AddAlarmNameDAO", flags: [ "java" ] },
  { name: "foam/nanos/alarming/Alarm", flags: [ "java" ] },
  { name: "foam/nanos/alarming/AlarmAndMonitoring", flags: [ "java" ] },
  { name: "foam/nanos/alarming/AlarmConfig", flags: [ "java" ] },
  { name: "foam/nanos/alarming/AlarmingUniqueNameDAO", flags: [ "java" ] },
  { name: "foam/nanos/alarming/AlarmIdRefines", flags: ["java"] },
  { name: "foam/nanos/alarming/AlarmHostnameRuleAction", flags: [ "java" ] },
  { name: "foam/nanos/alarming/AlarmLoggingDAO", flags: [ "java" ] },
  { name: "foam/nanos/alarming/AlarmNotificationDAO", flags: [ "java" ] },
  { name: "foam/nanos/alarming/AlarmReason", flags: [ "java" ] },
  { name: "foam/nanos/alarming/CandlestickAlarm", flags: [ "web", "java" ] },
  { name: "foam/nanos/alarming/CandlestickAlarmDAO", flags: [ "java" ] },
  { name: "foam/nanos/alarming/MonitoringReport", flags: [ "java" ] },
  { name: "foam/nanos/alarming/MonitorType", flags: [ "java" ] },
  { name: "foam/nanos/alarming/OMName", flags: [ "java" ] },
  { name: "foam/nanos/alarming/test/CandlestickAlarmTest", flags: [ "java" ] },
  { name: "foam/nanos/auth/PropertyType", flags: [ "java" ] },
  { name: "foam/nanos/auth/Country", flags: [ "java" ] },
  { name: "foam/nanos/auth/Region", flags: [ "java" ] },
  { name: "foam/nanos/auth/Address", flags: [ "java" ] },
  { name: "foam/nanos/auth/AgentJunctionStatus", flags: [ "java" ] },
  { name: "foam/nanos/auth/AccountLockedException", flags: [ "java" ] },
  { name: "foam/nanos/auth/AccountDisabledException", flags: [ "java" ] },
  { name: "foam/nanos/auth/AuthenticationException", flags: [ "java" ] },
  { name: "foam/nanos/auth/AuthorizationException", flags: [ "java" ] },
  { name: "foam/nanos/auth/DeletedAware", flags: [ "java" ] },
  { name: "foam/nanos/auth/DeletedAwareDAOTest", flags: [ "java" ] },
  { name: "foam/nanos/auth/DuplicateEmailException", flags: [ "java" ] },
  { name: "foam/nanos/auth/DuplicateUserNameException", flags: [ "java" ] },
  { name: "foam/nanos/auth/PasswordPolicy", flags: [ "java" ] },
  { name: "foam/nanos/auth/Group", flags: ["java"] },
  { name: "foam/nanos/auth/HumanNameTrait", flags: [ "java" ] },
  { name: "foam/nanos/auth/InvalidPasswordException", flags: [ "java" ] },
  { name: "foam/nanos/auth/LifecycleState", flags: [ "java" ] },
  { name: "foam/nanos/auth/LifecycleAware", flags: [ "java" ] },
  { name: "foam/nanos/notification/Notifiable", flags: [ "java" ] },
  { name: "foam/nanos/auth/CreatedAware", flags: [ "java" ] },
  { name: "foam/nanos/auth/Language", flags: [ "java" ] },
  { name: "foam/nanos/theme/Theme", flags: [ "java" ] },
  { name: "foam/nanos/theme/ThemeGlyphs", flags: [ "java" ] },
  { name: "foam/nanos/theme/ThemeDomain", flags: [ "java" ] },
  { name: "foam/nanos/theme/ThemeDomainsDAO", flags: [ "java" ] },
  { name: "foam/nanos/theme/Themes", flags: [ "java" ] },
  { name: "foam/nanos/auth/User", flags: ["java"] },
  { name: "foam/nanos/auth/UserNotFoundException", flags: [ "java" ] },
  { name: "foam/nanos/auth/PermissionTableView" },
  { name: "foam/nanos/auth/LastModifiedAware", flags: [ "java" ] },
  { name: "foam/nanos/auth/LastModifiedByAware", flags: [ "java" ] },
//  { name: "foam/nanos/auth/ServiceProviderAware", flags: [ "java" ] },
  { name: "foam/nanos/auth/ServiceProviderAwareDAO", flags: [ "java" ] },
  { name: "foam/nanos/auth/ServiceProviderAwarePredicate", flags: [ "java" ] },
  { name: "foam/nanos/auth/ServiceProviderAwareSink", flags: [ "java" ] },
  { name: "foam/nanos/auth/ServiceProviderAwareSupport", flags: [ "java" ] },
  { name: "foam/nanos/auth/test/ServiceProviderAwareTest", flags: [ "java" ] },
  { name: "foam/nanos/auth/test/UserAndGroupPermissionTest", flags: [ "java" ] },
  { name: "foam/nanos/auth/LanguageChoiceView", flags: ["web"] },
  { name: "foam/nanos/auth/CreatedAwareDAO", flags: [ "java" ] },
  { name: "foam/nanos/auth/LastModifiedAwareDAO", flags: [ "java" ] },
  { name: "foam/nanos/auth/LifecycleAwareDAO", flags: [ "java" ] },
  { name: "foam/nanos/auth/Login" },
  { name: "foam/nanos/auth/Permission", flags: [ "java" ] },
  { name: "foam/nanos/auth/ResendVerificationEmail", flags: ["web"] },
  { name: "foam/nanos/auth/Phone", flags: [ "java" ] },
  { name: "foam/nanos/auth/HtmlDoc", flags: [ "java" ] },
  { name: "foam/nanos/auth/SignOutView" },
  { name: "foam/nanos/auth/email/EmailTokenService", flags: [ "java" ] },
  { name: "foam/nanos/auth/email/EmailDocInterface", flags: [ "java" ] },
  { name: "foam/nanos/auth/email/EmailDocService", flags: [ "java" ] },
  { name: "foam/nanos/auth/email/ClientEmailDocService", flags: [ "java" ] },
  { name: "foam/nanos/auth/email/EmailVerificationWebAgent", flags: [ "java" ] },
  { name: "foam/nanos/auth/resetPassword/SuccessView" },
  { name: "foam/nanos/auth/resetPassword/ResetPasswordTokenService", flags: [ "java" ] },
  { name: "foam/nanos/auth/token/TokenService", flags: [ "java" ] },
  { name: "foam/nanos/auth/token/ClientTokenService", flags: [ "java" ] },
  { name: "foam/nanos/auth/token/Token", flags: [ "java" ] },
  { name: "foam/nanos/auth/token/AbstractTokenService", flags: [ "java" ] },
  { name: "foam/nanos/auth/token/TokenExpiredException", flags: [ "java" ] },
  { name: "foam/nanos/auth/token/TokenInvalidException", flags: [ "java" ] },
  { name: "foam/nanos/auth/ChangePasswordView" },
  { name: "foam/nanos/auth/ResetPassword" },
  { name: "foam/nanos/auth/RetrievePassword" },
  { name: "foam/nanos/auth/UpdatePassword" },
  { name: "foam/nanos/auth/CreatedByAware", flags: [ "java" ] },
  { name: "foam/nanos/auth/CreatedByAwareDAO", flags: [ "java" ] },
  { name: "foam/nanos/auth/Subject", flags: [ "java" ] },
  { name: "foam/nanos/auth/PriorPassword", flags: [ "java" ] },
  { name: "foam/nanos/auth/ruler/AddPasswordHistoryAction", flags: [ "java" ] },
  { name: "foam/nanos/auth/ruler/PreventDuplicateEmailAction", flags: [ "java" ] },
  { name: "foam/nanos/auth/ruler/PreventDuplicateUsernameAction", flags: [ "java" ] },
  { name: "foam/nanos/auth/ruler/EnsurePropertyOnCreateRule", flags: [ "java" ] },
  { name: "foam/nanos/auth/test/PasswordPolicyTest", flags: [ "java" ] },
  { name: "foam/nanos/auth/LastModifiedByAwareDAO", flags: [ "java" ] },
  { name: "foam/nanos/auth/PermissionedPropertyDAO", flags: [ "java" ] },
  { name: "foam/nanos/auth/ProfilePictureView", flags: ["web"] },
  { name: "foam/nanos/auth/twofactor/OTPAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/twofactor/AbstractOTPAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/twofactor/AbstractTOTPAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/twofactor/ClientOTPAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/twofactor/TwoFactorSignInView" },
  { name: "foam/nanos/auth/twofactor/UserRefinements" },
  { name: "foam/nanos/auth/twofactor/ThemeRefinements" },
  { name: "foam/nanos/auth/UserAndGroupAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/UserQueryService", flags: [ "java" ] },
  { name: "foam/nanos/auth/SimpleUserQueryService", flags: [ "java" ] },
  { name: "foam/nanos/auth/ResetSpidBeforeLoginAuthService", flags: [ "java" ] },
  { name: "foam/nanos/bench/Benchmark", flags: [ "java" ] },
  { name: "foam/nanos/bench/BenchmarkResult", flags: [ "java" ] },
  { name: "foam/nanos/bench/BenchmarkResultReportingDAO", flags: [ "java" ] },
  { name: "foam/nanos/bench/BenchmarkResultSystemDAO", flags: [ "java" ] },
  { name: "foam/nanos/bench/BenchmarkRunner", flags: [ "java" ] },
  { name: "foam/nanos/bench/BenchmarkRunnerScript", flags: [ "java" ] },
  { name: "foam/nanos/bench/Relationships" },
  { name: "foam/nanos/bench/TestScriptBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/benchmark/AuthorizerBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/boot/NSpec", flags: [ "java" ] },
  { name: "foam/nanos/boot/NSpecAware", flags: [ "java" ] },
  { name: "foam/nanos/boot/DAOConfigSummaryView", flags: ["web"] },
  { name: "foam/nanos/boot/DAONSpecMenu", flags: [ "java" ] },
  { name: "foam/nanos/session/LocalSetting", flags: [ "java" ] },
  { name: "foam/nanos/session/Session", flags: [ "java" ] },
  { name: "foam/nanos/session/SessionTimer" },
  { name: "foam/nanos/session/SessionService", flags: [ "java" ] },
  { name: "foam/nanos/session/SessionNotFoundException", flags: [ "java" ] },
  { name: "foam/nanos/menu/XRegistration", flags: [ "java" ] },
  { name: "foam/nanos/menu/AbstractMenu", flags: [ "java" ] },
  { name: "foam/nanos/menu/DAOMenu" },
  { name: "foam/nanos/menu/DAOMenu2" },
  { name: "foam/nanos/menu/DocumentMenu" },
  { name: "foam/nanos/menu/DocumentFileMenu", flags: [ "java" ] },
  { name: "foam/nanos/menu/LinkMenu" },
  { name: "foam/nanos/menu/ListMenu" },
  { name: "foam/nanos/menu/Menu", flags: [ "java" ] },
  { name: "foam/nanos/menu/MenuBar" },
  { name: "foam/nanos/menu/PopupMenu" },
  { name: "foam/nanos/menu/SequenceMenu" },
  { name: "foam/nanos/menu/SubMenu" },
  { name: "foam/nanos/menu/SubMenuView" },
  { name: "foam/nanos/menu/TabsMenu" },
  { name: "foam/nanos/menu/VerticalMenu" },
  { name: "foam/nanos/menu/ViewMenu" },
  { name: "foam/nanos/menu/ScriptMenu", flags: [ "java" ] },
  { name: "foam/nanos/menu/TreeAltView", flags: ["web"] },
  { name: "foam/nanos/menu/TreeGraphAltView" },
  { name: "foam/nanos/medusa/AccessMode", flags: [ "java" ] },
  { name: "foam/nanos/medusa/AnnouncePrimaryDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/BlockingDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClientElectoralService", flags: [ "java" ] },
  { name: "foam/nanos/medusa/Clusterable", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterableMixin" },
  { name: "foam/nanos/medusa/ClusterConfig", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterConfigMonitor", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterConfigMonitorAgent", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterConfigNARegionReplayDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterConfigReplayDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterConfigReplayingInfoDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterConfigStatusDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterConfigSupport", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterException", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ClusterTopology" },
  { name: "foam/nanos/medusa/ClusterTopologyView" },
  { name: "foam/nanos/medusa/DaggerException", flags: [ "java" ] },
  { name: "foam/nanos/medusa/DaggerService", flags: [ "java" ] },
  { name: "foam/nanos/medusa/DaggerLink", flags: [ "java" ] },
  { name: "foam/nanos/medusa/DaggerLinks", flags: [ "java" ] },
  { name: "foam/nanos/medusa/DefaultDaggerService", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ElectoralService", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ElectoralServiceState", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ElectoralServiceServer", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaEntry", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaEntrySupport", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaEntryTimeoutException", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaException", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaHealth", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaHealthFactory", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaHealthStatusDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaAdapterDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaBroadcastDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaBroadcastNARegionDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaBroadcastNARegionNodesDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaBroadcast2NodesDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaConsensusDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaConsensusMonitor", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaHashingDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaInternalDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaMessage", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaNodeJDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaNodeBootstrapAgent", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaRegistry", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaRegistryService", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaReplayIssue", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaNOPRegistryService", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaSigningDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaSetNodeDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaStatusWatcher", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaTestingDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaType", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MedusaUniqueDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/MultiplePrimariesException", flags: [ "java" ] },
  { name: "foam/nanos/medusa/NodeCView" },
  { name: "foam/nanos/medusa/PrimaryMediatorDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/PrimaryNotFoundException", flags: [ "java" ] },
  { name: "foam/nanos/medusa/PromotedPurgeAgent", flags: [ "java" ] },
  { name: "foam/nanos/medusa/PurgeSink", flags: [ "java" ] },
  { name: "foam/nanos/medusa/RegionCView" },
  { name: "foam/nanos/medusa/RegionStatus", flags: [ "java" ] },
  { name: "foam/nanos/medusa/RenouncePrimaryDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayCmd", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayCompleteCmd", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayDetailsCmd", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayMediatorDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayNodeDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayRequestCmd", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayingDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayingInfo", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayingInfoDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ReplayingInfoCView" },
  { name: "foam/nanos/medusa/ReplayingInfoDetailCView" },
  { name: "foam/nanos/medusa/RetryClientSinkDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/SecondaryMediatorDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/SetNodeSink", flags: [ "java" ] },
  { name: "foam/nanos/medusa/Status", flags: [ "java" ] },
  { name: "foam/nanos/medusa/TimeoutDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/ZoneCView" },
  { name: "foam/nanos/medusa/benchmark/DaggerLinkBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/medusa/benchmark/DaggerVerifyBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/medusa/benchmark/MedusaTestBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/medusa/benchmark/MedusaPingBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/medusa/benchmark/PingDAO", flags: [ "java" ] },
  { name: "foam/nanos/medusa/test/MedusaTestObject", flags: [ "java" ] },
  { name: "foam/nanos/medusa/test/MedusaTestObjectDIGBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/medusa/test/MedusaTestObjectDistributedDIGBenchmarkRunner", flags: [ "java" ] },
  { name: "foam/nanos/security/KeyStoreManager", flags: [ "java" ] },
  { name: "foam/nanos/benchmark/UUIDBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/u2/navigation/TopNavigation", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/ResponsiveTopNav", flags: ['web'] },
  { name: "foam/nanos/u2/navigation/ApplicationSideNav", flags: ['web'] },
  { name: "foam/nanos/u2/navigation/NavigationController", flags: ['web'] },
  { name: "foam/nanos/u2/navigation/FooterView", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/SideNavigation", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/SideNavigationItemView", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/NavigationView", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/BusinessLogoView", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/UserView", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/SubMenuBar", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/ApplicationLogoView", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/UserInfoNavigationView", flags: ["web"] },
  { name: "foam/nanos/u2/navigation/NotificationMenuItem", flags: ["web"] },
  { name: "foam/nanos/script/Language", flags: [ "java" ] },
  { name: "foam/nanos/script/ScriptStatus", flags: [ "java" ] },
  { name: "foam/nanos/script/Script", flags: [ "java" ] },
  { name: "foam/nanos/script/ScriptEvent", flags: [ "java" ] },
  { name: "foam/nanos/script/Relationships" },
  { name: "foam/nanos/script/TestRunnerConfig", flags: [ "java" ] },
  { name: "foam/nanos/script/TestRunnerScript", flags: [ "java" ] },
  { name: "foam/nanos/jetty/HttpServer", flags: [ "java" ] },
  { name: "foam/nanos/servlet/Servlet", flags: [ "java" ] },
  { name: "foam/nanos/servlet/ErrorPageMapping", flags: [ "java" ] },
  { name: "foam/nanos/servlet/FilterMapping", flags: [ "java" ] },
  { name: "foam/nanos/servlet/ServletMapping", flags: [ "java" ] },
  { name: "foam/nanos/servlet/VirtualHostRoutingServlet", flags: [ "java" ] },
  { name: "foam/nanos/test/Test", flags: [ "java" ] },
  { name: "foam/nanos/test/TestBorder" },
  { name: "foam/nanos/cron/Cron", flags: [ "java" ] },
  { name: "foam/nanos/cron/CronJobDAO", flags: [ "java" ] },
  { name: "foam/nanos/cron/CronSchedule", flags: [ "java" ] },
  { name: "foam/nanos/cron/CronScheduler", flags: [ "java" ] },
  { name: "foam/nanos/cron/CronScheduleDAO", flags: [ "java" ] },
  { name: "foam/nanos/cron/IntervalSchedule", flags: [ "java" ] },
  { name: "foam/nanos/cron/MonthlyChoice", flags: [ "java" ] },
  { name: "foam/nanos/cron/NeverSchedule" },
  { name: "foam/nanos/cron/OrSchedule", flags: [ "java" ] },
  { name: "foam/nanos/cron/Schedule", flags: [ "java", "web" ] },
  { name: "foam/nanos/cron/Schedulable", flags: [ "java", "web" ] },
  { name: "foam/nanos/cron/ScheduleEnd", flags: [ "java", "web" ] },
  { name: "foam/nanos/cron/SimpleIntervalSchedule", flags: [ "java", "web" ] },
  { name: "foam/nanos/cron/SymbolicFrequency", flags: [ "java", "web" ] },
  { name: "foam/nanos/cron/TimeHMS", flags: [ "java" ] },
  { name: "foam/nanos/cron/TimeOfDaySchedule", flags: [ "java" ] },
  { name: "foam/nanos/cron/test/IntervalScheduleTest", flags: [ "java" ] },
  { name: "foam/nanos/cron/test/TimeOfDayScheduleTest", flags: [ "java" ] },
  { name: "foam/nanos/export/ClientGoogleSheetsExportService", flags: [ "java" ] },
  { name: "foam/nanos/export/CSVTableExportDriver"},
  { name: "foam/nanos/export/ExportDriverRegistry", flags: [ "java" ] },
  { name: "foam/nanos/export/ExportDriver", flags: [ "java" ] },
  { name: "foam/nanos/export/GoogleSheetsBasedExportDriver", flags: [ "java" ] },
  { name: "foam/nanos/export/GoogleSheetsExport", flags: [ "java" ] },
  { name: "foam/nanos/export/GoogleSheetsExportDriver", flags: [ "java" ] },
  { name: "foam/nanos/export/GoogleSheetsOutputter" },
  { name: "foam/nanos/export/GoogleSheetsPropertyMetadata", flags: [ "java" ] },
  { name: "foam/nanos/export/GoogleSheetsServiceConfig", flags: [ "java" ] },
  { name: "foam/nanos/export/JSONDriver"},
  { name: "foam/nanos/export/JSONJDriver"},
  { name: "foam/nanos/export/XMLDriver"},
  { name: "foam/nanos/export/report/Template", flags: [ "java" ] },
  { name: "foam/nanos/export/PDFGoogleSheetsExportDriver", flags: [ "java" ] },
  { name: "foam/nanos/export/TableExportDriver", flags: [ "java" ] },
  { name: "foam/nanos/google/api/auth/GoogleApiAuthService", flags: [ "java" ] },
  { name: "foam/nanos/google/api/auth/GoogleApiCredentials", flags: [ "java" ] },
  { name: "foam/nanos/google/api/drive/GoogleDriveService", flags: [ "java" ] },
  { name: "foam/nanos/google/api/sheets/views/ClientGoogleSheetsDataImportService" },
  { name: "foam/nanos/google/api/sheets/views/GoogleSheetsImportConfig" },
  { name: "foam/nanos/google/api/sheets/views/GoogleSheetsDataImportService" },
  { name: "foam/nanos/google/api/sheets/views/GoogleSheetsDataImportServiceImpl" },
  { name: "foam/nanos/google/api/sheets/views/GoogleSheetsTransactionsDataImportServiceImpl" },
  { name: "foam/nanos/google/api/sheets/views/ImportDataMessage"},
  { name: "foam/nanos/google/api/sheets/views/modal/ColumnsToPropertiesMappingModal" },
  { name: "foam/nanos/google/api/sheets/views/modal/GoogleSheetImportModal" },
  { name: "foam/nanos/google/api/sheets/views/modal/ImportFromGoogleSheetsForm"},
  { name: "foam/nanos/auth/Relationships", flags: [ "java" ] },
  { name: "foam/nanos/NanoService", flags: [ "java" ] },
  { name: "foam/nanos/auth/twofactor/OTPKey", flags: [ "java" ] },
  { name: "foam/nanos/auth/AuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/ProxyAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/CachedAuthServiceProxy" },
  { name: "foam/nanos/auth/ClientAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/ClientLoginAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/AgentAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/AgentAuthClient", flags: [ "java" ] },
  { name: "foam/nanos/auth/ClientAgentAuthService", flags: [ "java" ] },
  { name: "foam/nanos/auth/UniqueUserService", flags: [ "java" ] },
  { name: "foam/nanos/pm/PMTemperatureCellFormatter" },
  { name: "foam/nanos/pm/NullPM", flags: [ "java" ] },
  { name: "foam/nanos/pm/PM", flags: [ "java" ] },
  { name: "foam/nanos/pm/PMInfo", flags: [ "java" ] },
  { name: "foam/nanos/pm/PMTableView", flags:["web"] },
  { name: "foam/nanos/pm/PMLogger", flags: [ "java" ] },
  { name: "foam/nanos/pm/NullPMLogger", flags: [ "java" ] },
  { name: "foam/nanos/pm/TemperatureCView" },
  { name: "foam/nanos/pm/PMFactory", flags: [ "java" ] },
  { name: "foam/nanos/pool/ThreadPoolAgency", flags: [ "java" ] },
  { name: "foam/nanos/jetty/JettyThreadPoolConfig", flags: [ "java" ] },
  { name: "foam/nanos/auth/PMAuthService", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/EmailConfig", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/EmailMessage", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/EmailService", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/EmailTemplate", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/EmailTemplateSource", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/SMTPEmailService", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/Status", flags: [ "java" ] },
  { name: "foam/nanos/notification/push/PushService", flags: [ "java" ] },
  { name: "foam/nanos/notification/push/FirebasePushService", flags: [ "java" ] },
  { name: "foam/nanos/notification/sms/SMSMessage", flags: [ "java" ] },
  { name: "foam/nanos/notification/sms/SMSService", flags: [ "java" ] },
  { name: "foam/nanos/notification/sms/SMSSetting", flags: [ "java" ] },
  { name: "foam/nanos/notification/sms/SMSStatus", flags: [ "java" ] },
  { name: "foam/nanos/notification/sms/TwilioConfig", flags: [ "java" ] },
  { name: "foam/nanos/notification/sms/TwilioSMSService", flags: [ "java" ] },
  { name: "foam/nanos/demo/DemoObject", flags: [ "java" ] },
  { name: "foam/nanos/demo/Demo" },
  { name: "foam/nanos/http/Format", flags: [ "java" ] },
  { name: "foam/nanos/http/Command", flags: [ "java" ] },
  { name: "foam/nanos/http/WebAgent", flags: [ "java" ] },
  { name: "foam/nanos/http/ProxyWebAgent", flags: [ "java" ] },
  { name: "foam/nanos/http/HttpParameters", flags: [ "java" ] },
  { name: "foam/nanos/http/SendErrorHandler", flags: [ "java" ] },
  { name: "foam/nanos/http/DefaultHttpParameters", flags: [ "java" ] },
  { name: "foam/nanos/dao/Operation", flags: [ "java" ] },
  { name: "foam/nanos/doc/DocumentationView" },
  { name: "foam/nanos/demo/relationship/CourseType", flags: [ "java" ] },
  { name: "foam/nanos/demo/relationship/Course", flags: [ "java" ] },
  { name: "foam/nanos/demo/relationship/Professor", flags: [ "java" ] },
  { name: "foam/nanos/demo/relationship/Student", flags: [ "java" ] }, // demo
  { name: "foam/nanos/demo/relationship/Controller" },
  { name: "foam/nanos/notification/ClientResendNotificationService", flags: [ "java" ] },
  { name: "foam/nanos/notification/EmailSetting", flags: [ "java" ] },
  { name: "foam/nanos/notification/Notification", flags: [ "java" ] },
  { name: "foam/nanos/notification/MyNotificationDAO", flags: [ "java" ] },
  { name: "foam/nanos/notification/ResendNotificationServiceInterface", flags: [ "java" ] },
  { name: "foam/nanos/notification/NotificationView"},
  { name: "foam/nanos/notification/NotificationExpansionDAO", flags: [ "java" ] },
  { name: "foam/nanos/notification/NotificationRowView"},
  { name: "foam/nanos/notification/NotificationSetting", flags: [ "java" ] },
  { name: "foam/nanos/notification/NotificationSettingsView"},
  { name: "foam/nanos/notification/NotificationCitationView"},
  { name: "foam/nanos/notification/NotificationNotificationView"},
  { name: "foam/nanos/notification/NotificationHostnameRuleAction", flags: [ "java" ] },
  { name: "foam/nanos/notification/ScriptRunNotification"},
  { name: "foam/nanos/notification/ScriptRunNotificationNotificationCitationView"},
  { name: "foam/nanos/notification/SlackSetting", flags: [ "java" ] },
  { name: "foam/nanos/notification/ToastNotificationDAO", flags: [ "java" ] },
  { name: "foam/nanos/notification/ToastState", flags: [ "java" ] },
  { name: "foam/nanos/notification/NotificationMessageModal"},
  { name: "foam/nanos/dashboard/Demo" },

  // Ticket
  { name: "foam/nanos/ticket/TicketStatus", flags: [ "java" ] },
  { name: "foam/nanos/ticket/TicketComment", flags: [ "java" ] },
  { name: "foam/nanos/ticket/Ticket", flags: [ "java" ] },
  { name: "foam/nanos/ticket/Relationships" },
  { name: "foam/nanos/ticket/TicketAddCommentDAO", flags: [ "java" ] },
  { name: "foam/nanos/ticket/TicketOwnerDAO", flags: [ "java" ] },
  { name: "foam/nanos/ticket/TicketCommentOwnerDAO", flags: [ "java" ] },
  { name: "foam/nanos/ticket/TicketDAOCreateView" },
  { name: "foam/nanos/ticket/TicketSummaryView" },
  { name: 'foam/nanos/ticket/TicketNotification', flags: [ "java" ] },
  { name: "foam/nanos/ticket/TicketNotificationNotificationCitationView" },
  { name: "foam/nanos/ticket/SummaryCard" },

  // Dig
  { name: "foam/nanos/dig/bench/DIGBenchmark", flags: [ "java" ] },
  { name: "foam/nanos/dig/bench/DistributedDIGBenchmarkRunner", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/DAOPutException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/DAONotFoundException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/DAORequiredException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/DigErrorMessage", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/DigSuccessMessage", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/EmptyDataException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/EmptyParameterException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/ExternalAPIException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/GeneralException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/ParsingErrorException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/TemporaryExternalAPIException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/UnsupportException", flags: [ "java" ] },
  { name: "foam/nanos/dig/exception/UnknownIdException", flags: [ "java" ] },
  { name: "foam/nanos/dig/Argument", flags: [ "java" ] },
  { name: "foam/nanos/dig/DIG", flags: [ "java" ] },
  { name: "foam/nanos/dig/DigFileUploadView" },
  { name: "foam/nanos/dig/DigSnippetView" },
  { name: "foam/nanos/dig/DUGDigestConfig", flags: [ "java" ] },
  { name: "foam/nanos/dig/DUGRule", flags: [ "java" ] },
  { name: "foam/nanos/dig/DUGRuleAction", flags: [ "java" ] },
//  { name: "foam/nanos/dig/ExternalDataAware", flags: [ "java" ] },
  { name: "foam/nanos/dig/ExternalDataAwareMixin" },
  { name: "foam/nanos/dig/LinkView" },
  { name: "foam/nanos/dig/ResultView" },
  { name: "foam/nanos/dig/SUGAR", flags: [ "java" ] },

  { name: "foam/support/model/Ticket", flags: [ "java" ] },
  { name: "foam/support/model/TicketMessage", flags: [ "java" ] },
  { name: "foam/support/model/SupportEmail", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/ClientPOP3EmailService", flags: [ "java" ] },
  { name: "foam/nanos/notification/email/POP3Email", flags: [ "java" ] },

  // foam/nanos/ruler
  { name: "foam/nanos/ruler/RuleGroup", flags: [ "java" ] },
  { name: "foam/nanos/ruler/FindRuledCommand", flags: [ "java" ] },
  { name: "foam/nanos/ruler/Ruled", flags: [ "java" ] },
  { name: "foam/nanos/ruler/Rule", flags: [ "java" ] },
  { name: "foam/nanos/ruler/PermissionedUserRule", flags: [ "java" ] },
  { name: "foam/nanos/ruler/PermissionedUCJRule", flags: [ "java" ] },
  { name: "foam/nanos/ruler/RuleAction", flags: [ "java" ] },
  { name: "foam/nanos/ruler/RuleActionMergeDecorator", flags: [ "java" ] },
  { name: "foam/nanos/ruler/CompositeRuleAction", flags: [ "java" ] },
  { name: "foam/nanos/ruler/StopRulerAction", flags: [ "java" ] },
  { name: "foam/nanos/ruler/RuleHistory", flags: [ "java" ] },
  { name: "foam/nanos/ruler/RuleHistoryStatus", flags: [ "java" ] },
  { name: "foam/nanos/ruler/RuledDAO", flags: [ "java" ] },
  { name: "foam/nanos/ruler/test/RuledDAOTest", flags: [ "java" ] },
  { name: "foam/nanos/ruler/test/RuledDummy", flags: [ "java" ] },
  { name: "foam/nanos/ruler/RulerDAO", flags: [ "java" ] },
  { name: "foam/nanos/ruler/ScriptPredicate", flags: [ "java" ] },
  { name: "foam/nanos/ruler/UpdateRulesListSink", flags: [ "java" ] },
  { name: "foam/nanos/ruler/TestedRule", flags: [ "java" ] },
  { name: "foam/nanos/ruler/RulerProbe", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyChangePredicate", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyEQProperty", flags: [ "java" ] },
  { name: "foam/nanos/ruler/Relationships" },
  { name: "foam/nanos/ruler/action/SendNotification", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyHasValue", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyEQValue", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyNEQValue", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/NewEqOld", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/IsClassPredicate", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/IsInstancePredicate", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyIsInstance", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyIsClass", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/ContextContainsPredicate", flags: [ "java" ] },
  { name: "foam/nanos/ruler/predicate/PropertyIsSetPredicate", flags: [ "java" ] },
  { name: "foam/nanos/ruler/action/AbstractCheckDAOforMatching", flags: [ "java" ] },
  { name: "foam/nanos/ruler/action/ChangePropertyAction", flags: [ "java" ] },
  { name: "foam/nanos/test/EchoService", flags: [ "java" ] },
  { name: "foam/nanos/test/SerializationTestEchoService", flags: [ "java" ] },
  { name: "foam/nanos/analytics/Foldable", flags: [ "java" ] },
  { name: "foam/nanos/analytics/Candlestick", flags: [ "java" ] },
  { name: "foam/nanos/test/ClientEchoService" },

  { name: "foam/dao/jdbc/JDBCConnectionSpec", flags: [ "java" ] },

  // foam/nanos/crunch
  { name: "foam/nanos/crunch/crunchtest/FakeTestObject", flags: [ "java" ] },
  // models
  { name: "foam/nanos/crunch/Renewable", flags: [ "java" ] },
  { name: "foam/nanos/crunch/Refinements" },
  { name: "foam/nanos/crunch/MinMaxCapability", flags: [ "java" ] },
  { name: "foam/nanos/crunch/MinMaxCapabilityData", flags: [ "java" ] },
  { name: "foam/nanos/crunch/CapabilityJunctionStatus", flags: [ "java" ] },
  { name: "foam/nanos/crunch/CapabilityIntercept", flags: [ "java" ] },
  { name: "foam/nanos/crunch/CapabilityJunctionPayload", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/CapablePayloadStatusDAO", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/Capable", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/CapableDAO", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/CapableAdapterDAO", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/CapableObjectData" },
  { name: "foam/nanos/crunch/lite/CapableCompatibleCapability", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/CapabilityRefinement" },
  { name: "foam/nanos/crunch/lite/MinMaxCapabilityRefinement" },
  { name: "foam/nanos/crunch/crunchtest/TestCapable", flags: [ "java" ] },
  { name: "foam/nanos/crunch/CapabilityAvailabilityDAO", flags: [ "java" ] },
  { name: "foam/nanos/crunch/example/ExampleData", flags: [ "java" ] },

  // crunch lite rulers
  { name: "foam/nanos/crunch/lite/ruler/CapableStatusChangeAdjustApprovalsRuleAction", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/ruler/CapablePayloadApprovableRuleAction", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/ruler/CapableCreateApprovalsRuleAction", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/ruler/SetCapablePayloadStatusOnPut", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/ruler/ReputDependantPayloads", flags: [ "java" ] },
  { name: "foam/nanos/crunch/lite/ruler/UCJApprovableValidateAction", flags: [ "java" ] },

  // crunch capability categories
  { name: "foam/nanos/crunch/CapabilityCategory", flags: [ "java" ] },
  { name: "foam/nanos/crunch/UserCapabilityJunctionRefine", flags: [ "java" ] },
  { name: "foam/nanos/crunch/CapabilityCapabilityJunctionRefine" },
  { name: "foam/nanos/crunch/CapabilityCategoryCapabilityJunctionRefine" },
  { name: "foam/nanos/crunch/RenewableData", flags: [ "java" ] },
  { name: "foam/nanos/crunch/UCJProperty" },
  { name: "foam/nanos/crunch/UCJUpdateApprovable", flags: [ "java" ] },
  { name: "foam/nanos/crunch/connection/CapabilityPayload", flags: [ "java" ] },
  { name: "foam/nanos/crunch/connection/CapabilityPayloadRecord", flags: [ "java" ] },
  { name: "foam/nanos/crunch/connection/GrantPathNode", flags: [ "java" ] },
  { name: "foam/nanos/crunch/document/Document", flags: [ "java" ] },
  //daos
  { name: "foam/nanos/crunch/UserCapabilityJunctionDAO", flags: [ "java" ] },
  { name: "foam/nanos/crunch/connection/CapabilityPayloadDAO", flags: [ "java" ] },
  { name: "foam/nanos/crunch/PredicatedPrerequisiteCapabilityJunctionDAO", flags: [ "java" ] },
  //rules
  { name: "foam/nanos/crunch/SendNotificationOnTopLevelCapabilityStatusUpdate", flags: [ "java" ] },
  { name: "foam/nanos/crunch/IsUserCapabilityJunctionStatusUpdate", flags: [ "java" ] },
  { name: "foam/nanos/crunch/RemoveJunctionsOnUserRemoval", flags: [ "java" ] },
  { name: "foam/nanos/crunch/CrunchService", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ClientCrunchService" },
  { name: "foam/nanos/crunch/ReputDependentUCJs", flags: [ "java" ] },
  //predicates
  { name: "foam/nanos/crunch/predicate/CapabilityIsStatus", flags: [ "java" ] },
  { name: "foam/nanos/crunch/predicate/CapabilityPrerequisitesGranted", flags: [ "java" ] },
  { name: "foam/nanos/crunch/predicate/StatusChangedTo", flags: [ "java" ] },
  { name: "foam/nanos/crunch/predicate/IsAgent", flags: [ "java" ] },
  { name: "foam/nanos/crunch/predicate/IsSpid", flags: [ "java" ] },
  { name: "foam/nanos/crunch/predicate/CapabilityJunctionTransitionToStatus", flags: [ "java" ] },
  { name: "foam/nanos/crunch/predicate/IsAgentUpdate", flags: [ "java" ] },
  { name: "foam/nanos/crunch/predicate/IsCapabilityJunctionOf", flags: [ "java" ] },
  //spid
  { name: "foam/nanos/auth/CreateUserCapabilityJunctionOnSpidSet", flags: [ "java" ] },
  { name: "foam/nanos/auth/SetUserServiceProviderJunctionRuleAction", flags: [ "java" ] },
  { name: "foam/nanos/auth/FilterBySpidService", flags: [ "java" ] },
  { name: "foam/nanos/auth/PreventDuplicateEmailLoginService", flags: [ "java" ] },
  //ucjDAO rules
  { name: "foam/nanos/crunch/ruler/AuthorizeUCJStatusOnPut", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ruler/CheckUCJOwnershipOnPut", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ruler/ValidateUCJDataOnPut", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ruler/SetUCJStatusOnPut", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ruler/ConfigureUCJExpiryOnGranted", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ruler/SaveUCJDataOnGranted", flags: [ "java" ] },
  //views
  { name: "foam/nanos/crunch/ui/WizardState", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ui/ApprovableUserCapabilityJunctionWAO" },
  { name: "foam/nanos/crunch/ui/UserCapabilityJunctionWAO" },
  { name: "foam/nanos/crunch/ui/CapableWAO" },
  { name: "foam/nanos/crunch/ui/CapabilityWizardlet", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ui/ReloadSubjectWizardlet" },
  { name: "foam/nanos/crunch/ui/MinMaxCapabilityWizardlet", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ui/MinMaxCapabilityWizardletSection" },
  { name: "foam/nanos/crunch/ui/ReviewCapabilityWizardlet", flags: [ "java" ] },
  { name: "foam/nanos/crunch/ui/ReviewCapabilityView" },
  { name: "foam/nanos/crunch/ui/ReviewUCJView" },
  { name: "foam/nanos/crunch/ui/CapableView" },
  { name: "foam/nanos/crunch/ui/UCJView" },
  { name: "foam/nanos/crunch/ui/PrerequisiteAwareWizardlet", flags: [ "java" ] },
  //boxes
  { name: "foam/nanos/crunch/box/CrunchClientBox", flags: [ "java" ] },
  { name: "foam/nanos/crunch/box/CrunchClientReplyBox", flags: [ "java" ] },
  //extras
  { name: "foam/nanos/crunch/extra/ReviewCapability", flags: [ "java" ] },
  { name: "foam/nanos/crunch/extra/ReviewCapabilityData", flags: [ "java" ] },
  { name: "foam/nanos/crunch/extra/ReviewWizard", flags: [ "java" ] },
  { name: "foam/nanos/crunch/extra/ImplyReviewedAction", flags: [ "java" ] },
  //test
  { name: "foam/nanos/crunch/test/CrunchTestSupport" },

  // approval
  { name: "foam/nanos/approval/ApprovalStatus", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovalRequestClassificationEnum", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovalRequestClassification", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovalRequest", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovalRequestNotification", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovalRequestNotificationNotificationCitationView", flags: ["web"] },
  { name: "foam/nanos/approval/ApprovableAware", flags: [ "java" ] },
  { name: "foam/nanos/approval/PropertiesToUpdateView", flags: ["web"] },
  { name: "foam/nanos/approval/Approvable", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovableAwareDAO", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovableApprovalRequestsPredicate", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovableApprovalRequestsRule", flags: [ "java" ] },
  { name: "foam/nanos/approval/FulfilledApprovablePredicate", flags: [ "java" ] },
  { name: "foam/nanos/approval/FulfilledNestedJournalApprovablePredicate", flags: [ "java" ] },
  { name: "foam/nanos/approval/FulfilledApprovableRule", flags: [ "java" ] },
  { name: "foam/nanos/approval/PopulateApprovalRequestsDAO", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovalRequestAssignedToRule", flags: [ "java" ] },
  { name: "foam/nanos/approval/ApprovalRequestMemoRule", flags: [ "java" ] },
  { name: "foam/nanos/approval/CompositeApprovable", flags: [ "java" ] },
  { name: "foam/nanos/approval/CustomViewReferenceApprovable", flags: [ "java" ] },
  { name: "foam/nanos/approval/FulfilledCompositeApprovableRule", flags: [ "java" ] },
  { name: "foam/nanos/approval/RestrictedApprovableDAO", flags: [ "java" ] },
  { name: "foam/nanos/approval/PopulateApprovalRequestSummariesDAO", flags: [ "java" ] },

  //authservice
  { name: "foam/nanos/auth/CapabilityAuthService", flags: [ "java" ] },
  // google
  { name: "foam/nanos/geocode/GoogleMapsCredentials", flags: [ "java" ] },

  { name: "foam/demos/u2/AllViews" },
  { name: "foam/demos/u2/MDAllViews" },

  //IBAN
  { name: "foam/nanos/iban/IBANInfo", flags: [ "java" ] },
  { name: "foam/nanos/iban/ValidationIBAN", flags: [ "java" ] },
  { name: "foam/nanos/iban/test/ValidationIBANTest", flags: [ "java" ] },

  //notification
  { name: "foam/nanos/crunch/TopLevelCapabilityStatusUpdateNotification", flags: [ "java" ] },

  { name: "foam/nanos/auth/GroupPermissionJunctionRefinement", flags: ["java"] },

  { name: "foam/nanos/om/OMRuleAction", flags: [ "java" ] }

]);
