/**
 * @license
 * Copyright 2017 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.POM({
  name: 'nanos',
  version: 3,

  files: [
  { name: "client/ClientBuilder" },
  { name: "controller/AppStyles", flags: "web" },
  { name: "logger/LogMessage", flags: "java" },
  { name: "logger/LogMessageDAO", flags: "java" },
  { name: "logger/AbstractLogger", flags: "java" },
  { name: "logger/ProxyLogger", flags: "java" },
  { name: "logger/LoggerJDAO", flags: "java" },
  { name: "logger/LogLevelFilterLogger", flags: "java" },
  { name: "logger/NotificationLogMessageDAO", flags: "java" },
  { name: "logger/RepeatLogMessageDAO", flags: "java" },
  { name: "logger/StdoutLoggerDAO", flags: "java" },
  { name: "logger/benchmark/LoggerBenchmark", flags: "java" },
  { name: "fs/File", flags: "java" },
  { name: "fs/FileLabel", flags: "java" },
  { name: "fs/FileType", flags: "java" },
  { name: "fs/FileProperty" },
  { name: "fs/FileDAODecorator" },
  { name: "fs/FileArray" },
  { name: "fs/FileArrayDAODecorator" },
  { name: "fs/FileArrayInCapablePayloadsDecorator" },
  { name: "fs/FileSizeView", flags: "web" },
  { name: "fs/fileDropZone/FileDropZone", flags: "web" },
  { name: "fs/fileDropZone/FilePreview", flags: "web" },
  { name: "fs/fileDropZone/FileCard", flags: "web" },
  { name: "fs/fileDropZone/FileUploader", flags: "web" },
  { name: "fs/TempFile", flags: "java" },
  { name: "crunch/AssociatedEntity", flags: "java" },
  { name: "crunch/CapabilityGrantMode", flags: "java" },
  { name: "crunch/Capability", flags: "java" },
  { name: "auth/ServiceProvider", flags: "java" },
  { name: "auth/test/DummySp", flags: "java" },
  { name: "fs/TextSaveView", flags: "web" },
  { name: "app/AppConfig", flags: "java" },
  { name: "app/AppConfigService", flags: "java" },
  { name: "app/ContextLookupAppConfigService", flags: "java" },
  { name: "app/Health", flags: "java" },
  { name: "app/HealthFactory", flags: "java" },
  { name: "app/HealthHeartbeatMonitor", flags: "java" },
  { name: "app/HealthHeartbeatService", flags: "java" },
  { name: "app/HealthStatus", flags: "java" },
  { name: "app/Mode", flags: "java" },
  { name: "app/SupportConfig", flags: "java" },
  { name: "notification/email/SMTPConfig", flags: "java" },
  { name: "app/ClientAppConfigService" },
  { name: "controller/WindowHash" },
  { name: "controller/Memento" },
  { name: "controller/MementoMixin" },
  { name: "controller/ApplicationController" },
  { name: "alarming/AddAlarmNameDAO", flags: "java" },
  { name: "alarming/Alarm", flags: "java" },
  { name: "alarming/AlarmAndMonitoring", flags: "java" },
  { name: "alarming/AlarmConfig", flags: "java" },
  { name: "alarming/AlarmingUniqueNameDAO", flags: "java" },
  { name: "alarming/AlarmIdRefines", flags: "java" },
  { name: "alarming/AlarmHostnameRuleAction", flags: "java" },
  { name: "alarming/AlarmLoggingDAO", flags: "java" },
  { name: "alarming/AlarmNotificationDAO", flags: "java" },
  { name: "alarming/AlarmReason", flags: "java" },
  { name: "alarming/CandlestickAlarm", flags: [ "web", "java" ] },
  { name: "alarming/CandlestickAlarmDAO", flags: "java" },
  { name: "alarming/MonitoringReport", flags: "java" },
  { name: "alarming/MonitorType", flags: "java" },
  { name: "alarming/OMName", flags: "java" },
  { name: "alarming/test/CandlestickAlarmTest", flags: "java" },
  { name: "auth/PropertyType", flags: "java" },
  { name: "auth/Country", flags: "java" },
  { name: "auth/Region", flags: "java" },
  { name: "auth/Address", flags: "java" },
  { name: "auth/AgentJunctionStatus", flags: "java" },
  { name: "auth/AccountLockedException", flags: "java" },
  { name: "auth/AccountDisabledException", flags: "java" },
  { name: "auth/AuthenticationException", flags: "java" },
  { name: "auth/AuthorizationException", flags: "java" },
  { name: "auth/DeletedAware", flags: "java" },
  { name: "auth/DeletedAwareDAOTest", flags: "java" },
  { name: "auth/DuplicateEmailException", flags: "java" },
  { name: "auth/DuplicateUserNameException", flags: "java" },
  { name: "auth/PasswordPolicy", flags: "java" },
  { name: "auth/Group", flags: "java" },
  { name: "auth/HumanNameTrait", flags: "java" },
  { name: "auth/InvalidPasswordException", flags: "java" },
  { name: "auth/LifecycleState", flags: "java" },
  { name: "auth/LifecycleAware", flags: "java" },
  { name: "notification/Notifiable", flags: "java" },
  { name: "auth/CreatedAware", flags: "java" },
  { name: "auth/Language", flags: "java" },
  { name: "theme/Theme", flags: "java" },
  { name: "theme/ThemeGlyphs", flags: "java" },
  { name: "theme/ThemeDomain", flags: "java" },
  { name: "theme/ThemeDomainsDAO", flags: "java" },
  { name: "theme/Themes", flags: "java" },
  { name: "auth/User", flags: "java" },
  { name: "auth/UserNotFoundException", flags: "java" },
  { name: "auth/PermissionTableView" },
  { name: "auth/LastModifiedAware", flags: "java" },
  { name: "auth/LastModifiedByAware", flags: "java" },
//  { name: "auth/ServiceProviderAware", flags: "java" },
  { name: "auth/ServiceProviderAwareDAO", flags: "java" },
  { name: "auth/ServiceProviderAwarePredicate", flags: "java" },
  { name: "auth/ServiceProviderAwareSink", flags: "java" },
  { name: "auth/ServiceProviderAwareSupport", flags: "java" },
  { name: "auth/test/ServiceProviderAwareTest", flags: "java" },
  { name: "auth/test/UserAndGroupPermissionTest", flags: "java" },
  { name: "auth/LanguageChoiceView", flags: "web" },
  { name: "auth/CreatedAwareDAO", flags: "java" },
  { name: "auth/LastModifiedAwareDAO", flags: "java" },
  { name: "auth/LifecycleAwareDAO", flags: "java" },
  { name: "auth/Login" },
  { name: "auth/Permission", flags: "java" },
  { name: "auth/ResendVerificationEmail", flags: "web" },
  { name: "auth/Phone", flags: "java" },
  { name: "auth/HtmlDoc", flags: "java" },
  { name: "auth/SignOutView" },
  { name: "auth/email/EmailTokenService", flags: "java" },
  { name: "auth/email/EmailDocInterface", flags: "java" },
  { name: "auth/email/EmailDocService", flags: "java" },
  { name: "auth/email/ClientEmailDocService", flags: "java" },
  { name: "auth/email/EmailVerificationWebAgent", flags: "java" },
  { name: "auth/resetPassword/SuccessView" },
  { name: "auth/resetPassword/ResetPasswordTokenService", flags: "java" },
  { name: "auth/token/TokenService", flags: "java" },
  { name: "auth/token/ClientTokenService", flags: "java" },
  { name: "auth/token/Token", flags: "java" },
  { name: "auth/token/AbstractTokenService", flags: "java" },
  { name: "auth/token/TokenExpiredException", flags: "java" },
  { name: "auth/token/TokenInvalidException", flags: "java" },
  { name: "auth/ChangePasswordView" },
  { name: "auth/ResetPassword" },
  { name: "auth/RetrievePassword" },
  { name: "auth/UpdatePassword" },
  { name: "auth/CreatedByAware", flags: "java" },
  { name: "auth/CreatedByAwareDAO", flags: "java" },
  { name: "auth/Subject", flags: "java" },
  { name: "auth/PriorPassword", flags: "java" },
  { name: "auth/ruler/AddPasswordHistoryAction", flags: "java" },
  { name: "auth/ruler/PreventDuplicateEmailAction", flags: "java" },
  { name: "auth/ruler/PreventDuplicateUsernameAction", flags: "java" },
  { name: "auth/ruler/EnsurePropertyOnCreateRule", flags: "java" },
  { name: "auth/test/PasswordPolicyTest", flags: "java" },
  { name: "auth/LastModifiedByAwareDAO", flags: "java" },
  { name: "auth/PermissionedPropertyDAO", flags: "java" },
  { name: "auth/ProfilePictureView", flags: "web" },
  { name: "auth/twofactor/OTPAuthService", flags: "java" },
  { name: "auth/twofactor/AbstractOTPAuthService", flags: "java" },
  { name: "auth/twofactor/AbstractTOTPAuthService", flags: "java" },
  { name: "auth/twofactor/ClientOTPAuthService", flags: "java" },
  { name: "auth/twofactor/TwoFactorSignInView" },
  { name: "auth/twofactor/UserRefinements" },
  { name: "auth/twofactor/ThemeRefinements" },
  { name: "auth/UserAndGroupAuthService", flags: "java" },
  { name: "auth/UserQueryService", flags: "java" },
  { name: "auth/SimpleUserQueryService", flags: "java" },
  { name: "auth/ResetSpidBeforeLoginAuthService", flags: "java" },
  { name: "bench/Benchmark", flags: "java" },
  { name: "bench/BenchmarkResult", flags: "java" },
  { name: "bench/BenchmarkResultReportingDAO", flags: "java" },
  { name: "bench/BenchmarkResultSystemDAO", flags: "java" },
  { name: "bench/BenchmarkRunner", flags: "java" },
  { name: "bench/BenchmarkRunnerScript", flags: "java" },
  { name: "bench/Relationships" },
  { name: "bench/TestScriptBenchmark", flags: "java" },
  { name: "benchmark/AuthorizerBenchmark", flags: "java" },
  { name: "boot/NSpec", flags: "java" },
  { name: "boot/NSpecAware", flags: "java" },
  { name: "boot/DAOConfigSummaryView", flags: "web" },
  { name: "boot/DAONSpecMenu", flags: "java" },
  { name: "session/LocalSetting", flags: "java" },
  { name: "session/Session", flags: "java" },
  { name: "session/SessionTimer" },
  { name: "session/SessionService", flags: "java" },
  { name: "session/SessionNotFoundException", flags: "java" },
  { name: "menu/XRegistration", flags: "java" },
  { name: "menu/AbstractMenu", flags: "java" },
  { name: "menu/DAOMenu" },
  { name: "menu/DAOMenu2" },
  { name: "menu/DocumentMenu" },
  { name: "menu/DocumentFileMenu", flags: "java" },
  { name: "menu/LinkMenu" },
  { name: "menu/ListMenu" },
  { name: "menu/Menu", flags: "java" },
  { name: "menu/MenuBar" },
  { name: "menu/PopupMenu" },
  { name: "menu/SequenceMenu" },
  { name: "menu/SubMenu" },
  { name: "menu/SubMenuView" },
  { name: "menu/TabsMenu" },
  { name: "menu/VerticalMenu" },
  { name: "menu/ViewMenu" },
  { name: "menu/ScriptMenu", flags: "java" },
  { name: "menu/TreeAltView", flags: "web" },
  { name: "menu/TreeGraphAltView" },
  { name: "medusa/AccessMode", flags: "java" },
  { name: "medusa/AnnouncePrimaryDAO", flags: "java" },
  { name: "medusa/BlockingDAO", flags: "java" },
  { name: "medusa/ClientElectoralService", flags: "java" },
  { name: "medusa/Clusterable", flags: "java" },
  { name: "medusa/ClusterableMixin" },
  { name: "medusa/ClusterConfig", flags: "java" },
  { name: "medusa/ClusterConfigMonitor", flags: "java" },
  { name: "medusa/ClusterConfigMonitorAgent", flags: "java" },
  { name: "medusa/ClusterConfigNARegionReplayDAO", flags: "java" },
  { name: "medusa/ClusterConfigReplayDAO", flags: "java" },
  { name: "medusa/ClusterConfigReplayingInfoDAO", flags: "java" },
  { name: "medusa/ClusterConfigStatusDAO", flags: "java" },
  { name: "medusa/ClusterConfigSupport", flags: "java" },
  { name: "medusa/ClusterException", flags: "java" },
  { name: "medusa/ClusterTopology" },
  { name: "medusa/ClusterTopologyView" },
  { name: "medusa/DaggerException", flags: "java" },
  { name: "medusa/DaggerService", flags: "java" },
  { name: "medusa/DaggerLink", flags: "java" },
  { name: "medusa/DaggerLinks", flags: "java" },
  { name: "medusa/DefaultDaggerService", flags: "java" },
  { name: "medusa/ElectoralService", flags: "java" },
  { name: "medusa/ElectoralServiceState", flags: "java" },
  { name: "medusa/ElectoralServiceServer", flags: "java" },
  { name: "medusa/MedusaEntry", flags: "java" },
  { name: "medusa/MedusaEntryNoRemoveDAO", flags: "java" },
  { name: "medusa/MedusaEntrySupport", flags: "java" },
  { name: "medusa/MedusaEntryTimeoutException", flags: "java" },
  { name: "medusa/MedusaException", flags: "java" },
  { name: "medusa/MedusaHealth", flags: "java" },
  { name: "medusa/MedusaHealthFactory", flags: "java" },
  { name: "medusa/MedusaHealthStatusDAO", flags: "java" },
  { name: "medusa/MedusaAdapterDAO", flags: "java" },
  { name: "medusa/MedusaBroadcastDAO", flags: "java" },
  { name: "medusa/MedusaBroadcastNARegionDAO", flags: "java" },
  { name: "medusa/MedusaBroadcastNARegionNodesDAO", flags: "java" },
  { name: "medusa/MedusaBroadcast2NodesDAO", flags: "java" },
  { name: "medusa/MedusaConsensusDAO", flags: "java" },
  { name: "medusa/MedusaConsensusMonitor", flags: "java" },
  { name: "medusa/MedusaHashingDAO", flags: "java" },
  { name: "medusa/MedusaInternalDAO", flags: "java" },
  { name: "medusa/MedusaMessage", flags: "java" },
  { name: "medusa/MedusaNodeJDAO", flags: "java" },
  { name: "medusa/MedusaNodeBootstrapAgent", flags: "java" },
  { name: "medusa/MedusaRegistry", flags: "java" },
  { name: "medusa/MedusaRegistryService", flags: "java" },
  { name: "medusa/MedusaReplayIssue", flags: "java" },
  { name: "medusa/MedusaNOPRegistryService", flags: "java" },
  { name: "medusa/MedusaSigningDAO", flags: "java" },
  { name: "medusa/MedusaSetNodeDAO", flags: "java" },
  { name: "medusa/MedusaStatusWatcher", flags: "java" },
  { name: "medusa/MedusaTestingDAO", flags: "java" },
  { name: "medusa/MedusaType", flags: "java" },
  { name: "medusa/MedusaUniqueDAO", flags: "java" },
  { name: "medusa/MultiplePrimariesException", flags: "java" },
  { name: "medusa/NodeCView" },
  { name: "medusa/PrimaryMediatorDAO", flags: "java" },
  { name: "medusa/PrimaryNotFoundException", flags: "java" },
  { name: "medusa/PromotedPurgeAgent", flags: "java" },
  { name: "medusa/PurgeSink", flags: "java" },
  { name: "medusa/RegionCView" },
  { name: "medusa/RegionStatus", flags: "java" },
  { name: "medusa/RenouncePrimaryDAO", flags: "java" },
  { name: "medusa/ReplayCmd", flags: "java" },
  { name: "medusa/ReplayCompleteCmd", flags: "java" },
  { name: "medusa/ReplayDetailsCmd", flags: "java" },
  { name: "medusa/ReplayMediatorDAO", flags: "java" },
  { name: "medusa/ReplayNodeDAO", flags: "java" },
  { name: "medusa/ReplayRequestCmd", flags: "java" },
  { name: "medusa/ReplayingDAO", flags: "java" },
  { name: "medusa/ReplayingInfo", flags: "java" },
  { name: "medusa/ReplayingInfoDAO", flags: "java" },
  { name: "medusa/ReplayingInfoCView" },
  { name: "medusa/ReplayingInfoDetailCView" },
  { name: "medusa/RetryClientSinkDAO", flags: "java" },
  { name: "medusa/SecondaryMediatorDAO", flags: "java" },
  { name: "medusa/SetNodeSink", flags: "java" },
  { name: "medusa/Status", flags: "java" },
  { name: "medusa/TimeoutDAO", flags: "java" },
  { name: "medusa/ZoneCView" },
  { name: "medusa/benchmark/DaggerLinkBenchmark", flags: "java" },
  { name: "medusa/benchmark/DaggerVerifyBenchmark", flags: "java" },
  { name: "medusa/benchmark/MedusaTestBenchmark", flags: "java" },
  { name: "medusa/benchmark/MedusaPingBenchmark", flags: "java" },
  { name: "medusa/benchmark/PingDAO", flags: "java" },
  { name: "medusa/test/MedusaTestObject", flags: "java" },
  { name: "medusa/test/MedusaTestObjectDIGBenchmark", flags: "java" },
  { name: "medusa/test/MedusaTestObjectDistributedDIGBenchmarkRunner", flags: "java" },
  { name: "security/KeyStoreManager", flags: "java" },
  { name: "benchmark/UUIDBenchmark", flags: "java" },
  { name: "u2/navigation/TopNavigation", flags: "web" },
  { name: "u2/navigation/ResponsiveTopNav", flags: "web" },
  { name: "u2/navigation/ApplicationSideNav", flags: "web" },
  { name: "u2/navigation/NavigationController", flags: "web" },
  { name: "u2/navigation/FooterView", flags: "web" },
  { name: "u2/navigation/SideNavigation", flags: "web" },
  { name: "u2/navigation/SideNavigationItemView", flags: "web" },
  { name: "u2/navigation/NavigationView", flags: "web" },
  { name: "u2/navigation/BusinessLogoView", flags: "web" },
  { name: "u2/navigation/UserView", flags: "web" },
  { name: "u2/navigation/SubMenuBar", flags: "web" },
  { name: "u2/navigation/ApplicationLogoView", flags: "web" },
  { name: "u2/navigation/UserInfoNavigationView", flags: "web" },
  { name: "u2/navigation/NotificationMenuItem", flags: "web" },
  { name: "script/Language", flags: "java" },
  { name: "script/ScriptStatus", flags: "java" },
  { name: "script/Script", flags: "java" },
  { name: "script/ScriptEvent", flags: "java" },
  { name: "script/Relationships" },
  { name: "script/TestRunnerConfig", flags: "java" },
  { name: "script/TestRunnerScript", flags: "java" },
  { name: "jetty/HttpServer", flags: "java" },
  { name: "servlet/Servlet", flags: "java" },
  { name: "servlet/ErrorPageMapping", flags: "java" },
  { name: "servlet/FilterMapping", flags: "java" },
  { name: "servlet/ServletMapping", flags: "java" },
  { name: "servlet/VirtualHostRoutingServlet", flags: "java" },
  { name: "test/Test", flags: "java" },
  { name: "test/TestBorder" },
  { name: "cron/Cron", flags: "java" },
  { name: "cron/CronJobDAO", flags: "java" },
  { name: "cron/CronSchedule", flags: "java" },
  { name: "cron/CronScheduler", flags: "java" },
  { name: "cron/CronScheduleDAO", flags: "java" },
  { name: "cron/IntervalSchedule", flags: "java" },
  { name: "cron/MonthlyChoice", flags: "java" },
  { name: "cron/NeverSchedule" },
  { name: "cron/OrSchedule", flags: [ "java" ] },
  { name: "cron/Schedule", flags: [ "java" ] },
  { name: "cron/Schedulable", flags: [ "java" ] },
  { name: "cron/ScheduleEnd", flags: [ "java" ] },
  { name: "cron/SimpleIntervalSchedule", flags: [ "java" ] },
  { name: "cron/SymbolicFrequency", flags: [ "java" ] },
  { name: "cron/TimeHMS", flags: [ "java" ] },
  { name: "cron/TimeOfDaySchedule", flags: [ "java" ] },
  { name: "cron/NextDate", flags: [ "java" ] },
  { name: "cron/NextDateService", flags: [ "java" ] },
  { name: "cron/ClientNextDateService", flags: [ "java" ] },
  { name: "cron/test/IntervalScheduleTest", flags: [ "java" ] },
  { name: "cron/test/TimeOfDayScheduleTest", flags: [ "java" ] },
  { name: "export/ClientGoogleSheetsExportService", flags: [ "java" ] },
  { name: "export/CSVTableExportDriver"},
  { name: "export/ExportDriverRegistry", flags: "java" },
  { name: "export/ExportDriver", flags: "java" },
  { name: "export/GoogleSheetsBasedExportDriver", flags: "java" },
  { name: "export/GoogleSheetsExport", flags: "java" },
  { name: "export/GoogleSheetsExportDriver", flags: "java" },
  { name: "export/GoogleSheetsOutputter" },
  { name: "export/GoogleSheetsPropertyMetadata", flags: "java" },
  { name: "export/GoogleSheetsServiceConfig", flags: "java" },
  { name: "export/JSONDriver"},
  { name: "export/JSONJDriver"},
  { name: "export/XMLDriver"},
  { name: "export/report/Template", flags: "java" },
  { name: "export/PDFGoogleSheetsExportDriver", flags: "java" },
  { name: "export/TableExportDriver", flags: "java" },
  { name: "google/api/auth/GoogleApiAuthService", flags: "java" },
  { name: "google/api/auth/GoogleApiCredentials", flags: "java" },
  { name: "google/api/drive/GoogleDriveService", flags: "java" },
  { name: "google/api/sheets/views/ClientGoogleSheetsDataImportService" },
  { name: "google/api/sheets/views/GoogleSheetsImportConfig" },
  { name: "google/api/sheets/views/GoogleSheetsDataImportService" },
  { name: "google/api/sheets/views/GoogleSheetsDataImportServiceImpl" },
  { name: "google/api/sheets/views/GoogleSheetsTransactionsDataImportServiceImpl" },
  { name: "google/api/sheets/views/ImportDataMessage"},
  { name: "google/api/sheets/views/modal/ColumnsToPropertiesMappingModal" },
  { name: "google/api/sheets/views/modal/GoogleSheetImportModal" },
  { name: "google/api/sheets/views/modal/ImportFromGoogleSheetsForm"},
  { name: "auth/Relationships", flags: "java" },
  { name: "NanoService", flags: "java" },
  { name: "auth/twofactor/OTPKey", flags: "java" },
  { name: "auth/AuthService", flags: "java" },
  { name: "auth/ProxyAuthService", flags: "java" },
  { name: "auth/CachedAuthServiceProxy" },
  { name: "auth/ClientAuthService", flags: "java" },
  { name: "auth/ClientLoginAuthService", flags: "java" },
  { name: "auth/AgentAuthService", flags: "java" },
  { name: "auth/AgentAuthClient", flags: "java" },
  { name: "auth/ClientAgentAuthService", flags: "java" },
  { name: "auth/UniqueUserService", flags: "java" },
  { name: "pm/PMTemperatureCellFormatter" },
  { name: "pm/NullPM", flags: "java" },
  { name: "pm/PM", flags: "java" },
  { name: "pm/PMInfo", flags: "java" },
  { name: "pm/PMTableView", flags:"web" },
  { name: "pm/PMLogger", flags: "java" },
  { name: "pm/NullPMLogger", flags: "java" },
  { name: "pm/TemperatureCView" },
  { name: "pm/PMFactory", flags: "java" },
  { name: "pool/ThreadPoolAgency", flags: "java" },
  { name: "jetty/JettyThreadPoolConfig", flags: "java" },
  { name: "auth/PMAuthService", flags: "java" },
  { name: "notification/email/EmailConfig", flags: "java" },
  { name: "notification/email/EmailMessage", flags: "java" },
  { name: "notification/email/EmailMessagePropertyServiceRuleAction", flags: "java" },
  { name: "notification/email/EmailMessageStatusRuleAction", flags: "java" },
  { name: "notification/email/EmailService", flags: "java" },
  { name: "notification/email/EmailTemplate", flags: "java" },
  { name: "notification/email/EmailTemplateSource", flags: "java" },
  { name: "notification/email/SMTPEmailService", flags: "java" },
  { name: "notification/email/Status", flags: "java" },
  { name: "notification/email/test/EmailMessageRuleTest", flags: "java" },
  { name: "notification/push/PushService", flags: "java" },
  { name: "notification/push/FirebasePushService", flags: "java" },
  { name: "notification/sms/SMSMessage", flags: "java" },
  { name: "notification/sms/SMSService", flags: "java" },
  { name: "notification/sms/SMSSetting", flags: "java" },
  { name: "notification/sms/SMSStatus", flags: "java" },
  { name: "notification/sms/TwilioConfig", flags: "java" },
  { name: "notification/sms/TwilioSMSService", flags: "java" },
  { name: "demo/DemoObject", flags: "java" },
  { name: "demo/Demo" },
  { name: "http/Format", flags: "java" },
  { name: "http/Command", flags: "java" },
  { name: "http/WebAgent", flags: "java" },
  { name: "http/ProxyWebAgent", flags: "java" },
  { name: "http/HttpParameters", flags: "java" },
  { name: "http/SendErrorHandler", flags: "java" },
  { name: "http/DefaultHttpParameters", flags: "java" },
  { name: "dao/Operation", flags: "java" },
  { name: "doc/DocumentationView" },
  { name: "demo/relationship/CourseType", flags: "java" },
  { name: "demo/relationship/Course", flags: "java" },
  { name: "demo/relationship/Professor", flags: "java" },
  { name: "demo/relationship/Student", flags: "java" }, // demo
  { name: "demo/relationship/Controller" },
  { name: "notification/ClientResendNotificationService", flags: "java" },
  { name: "notification/EmailSetting", flags: "java" },
  { name: "notification/Notification", flags: "java" },
  { name: "notification/MyNotificationDAO", flags: "java" },
  { name: "notification/ResendNotificationServiceInterface", flags: "java" },
  { name: "notification/NotificationView"},
  { name: "notification/NotificationExpansionDAO", flags: "java" },
  { name: "notification/NotificationRowView"},
  { name: "notification/NotificationSetting", flags: "java" },
  { name: "notification/NotificationSettingsView"},
  { name: "notification/NotificationCitationView"},
  { name: "notification/NotificationNotificationView"},
  { name: "notification/NotificationHostnameRuleAction", flags: "java" },
  { name: "notification/ScriptRunNotification"},
  { name: "notification/ScriptRunNotificationNotificationCitationView"},
  { name: "notification/SlackSetting", flags: "java" },
  { name: "notification/ToastNotificationDAO", flags: "java" },
  { name: "notification/ToastState", flags: "java" },
  { name: "notification/NotificationMessageModal"},
  { name: "dashboard/Demo" },

  // Ticket
  { name: "ticket/TicketStatus", flags: "java" },
  { name: "ticket/TicketComment", flags: "java" },
  { name: "ticket/Ticket", flags: "java" },
  { name: "ticket/Relationships" },
  { name: "ticket/TicketAddCommentDAO", flags: "java" },
  { name: "ticket/TicketOwnerDAO", flags: "java" },
  { name: "ticket/TicketCommentOwnerDAO", flags: "java" },
  { name: "ticket/TicketDAOCreateView" },
  { name: "ticket/TicketSummaryView" },
  { name: 'ticket/TicketNotification', flags: "java" },
  { name: "ticket/TicketNotificationNotificationCitationView" },
  { name: "ticket/SummaryCard" },

  // Dig
  { name: "dig/bench/DIGBenchmark", flags: "java" },
  { name: "dig/bench/DistributedDIGBenchmarkRunner", flags: "java" },
  { name: "dig/exception/DAOPutException", flags: "java" },
  { name: "dig/exception/DAONotFoundException", flags: "java" },
  { name: "dig/exception/DAORequiredException", flags: "java" },
  { name: "dig/exception/DigErrorMessage", flags: "java" },
  { name: "dig/exception/DigSuccessMessage", flags: "java" },
  { name: "dig/exception/EmptyDataException", flags: "java" },
  { name: "dig/exception/EmptyParameterException", flags: "java" },
  { name: "dig/exception/ExternalAPIException", flags: "java" },
  { name: "dig/exception/GeneralException", flags: "java" },
  { name: "dig/exception/ParsingErrorException", flags: "java" },
  { name: "dig/exception/TemporaryExternalAPIException", flags: "java" },
  { name: "dig/exception/UnsupportException", flags: "java" },
  { name: "dig/exception/UnknownIdException", flags: "java" },
  { name: "dig/Argument", flags: "java" },
  { name: "dig/DIG", flags: "java" },
  { name: "dig/DigFileUploadView" },
  { name: "dig/DigSnippetView" },
  { name: "dig/DUGDigestConfig", flags: "java" },
  { name: "dig/DUGRule", flags: "java" },
  { name: "dig/DUGRuleAction", flags: "java" },
//  { name: "dig/ExternalDataAware", flags: "java" },
  { name: "dig/ExternalDataAwareMixin" },
  { name: "dig/LinkView" },
  { name: "dig/ResultView" },
  { name: "dig/SUGAR", flags: "java" },

  { name: "notification/email/ClientPOP3EmailService", flags: "java" },
  { name: "notification/email/POP3Email", flags: "java" },

  // ruler
  { name: "ruler/RuleGroup", flags: "java" },
  { name: "ruler/FindRuledCommand", flags: "java" },
  { name: "ruler/Ruled", flags: "java" },
  { name: "ruler/Rule", flags: "java" },
  { name: "ruler/PermissionedUserRule", flags: "java" },
  { name: "ruler/PermissionedUCJRule", flags: "java" },
  { name: "ruler/RuleAction", flags: "java" },
  { name: "ruler/RuleActionMergeDecorator", flags: "java" },
  { name: "ruler/CompositeRuleAction", flags: "java" },
  { name: "ruler/StopRulerAction", flags: "java" },
  { name: "ruler/RuleHistory", flags: "java" },
  { name: "ruler/RuleHistoryStatus", flags: "java" },
  { name: "ruler/RuledDAO", flags: "java" },
  { name: "ruler/test/RuledDAOTest", flags: "java" },
  { name: "ruler/test/RuledDummy", flags: "java" },
  { name: "ruler/RulerDAO", flags: "java" },
  { name: "ruler/ScriptPredicate", flags: "java" },
  { name: "ruler/UpdateRulesListSink", flags: "java" },
  { name: "ruler/TestedRule", flags: "java" },
  { name: "ruler/RulerProbe", flags: "java" },
  { name: "ruler/predicate/PropertyChangePredicate", flags: "java" },
  { name: "ruler/predicate/PropertyEQProperty", flags: "java" },
  { name: "ruler/Relationships" },
  { name: "ruler/action/SendNotification", flags: "java" },
  { name: "ruler/predicate/PropertyHasValue", flags: "java" },
  { name: "ruler/predicate/PropertyEQValue", flags: "java" },
  { name: "ruler/predicate/PropertyNEQValue", flags: "java" },
  { name: "ruler/predicate/NewEqOld", flags: "java" },
  { name: "ruler/predicate/IsClassPredicate", flags: "java" },
  { name: "ruler/predicate/IsInstancePredicate", flags: "java" },
  { name: "ruler/predicate/PropertyIsInstance", flags: "java" },
  { name: "ruler/predicate/PropertyIsClass", flags: "java" },
  { name: "ruler/predicate/ContextContainsPredicate", flags: "java" },
  { name: "ruler/predicate/PropertyIsSetPredicate", flags: "java" },
  { name: "ruler/action/AbstractCheckDAOforMatching", flags: "java" },
  { name: "ruler/action/ChangePropertyAction", flags: "java" },
  { name: "test/EchoService", flags: "java" },
  { name: "test/SerializationTestEchoService", flags: "java" },
  { name: "analytics/Foldable", flags: "java" },
  { name: "analytics/Candlestick", flags: "java" },
  { name: "test/ClientEchoService" },

  // crunch
  { name: "crunch/crunchtest/FakeTestObject", flags: "java" },
  // models
  { name: "crunch/Renewable", flags: "java" },
  { name: "crunch/Refinements" },
  { name: "crunch/MinMaxCapability", flags: "java" },
  { name: "crunch/MinMaxCapabilityData", flags: "java" },
  { name: "crunch/CapabilityJunctionStatus", flags: "java" },
  { name: "crunch/CapabilityIntercept", flags: "java" },
  { name: "crunch/CapabilityJunctionPayload", flags: "java" },
  { name: "crunch/lite/CapablePayloadStatusDAO", flags: "java" },
  { name: "crunch/lite/Capable", flags: "java" },
  { name: "crunch/lite/CapableDAO", flags: "java" },
  { name: "crunch/lite/CapableAdapterDAO", flags: "java" },
  { name: "crunch/lite/CapableObjectData" },
  { name: "crunch/lite/CapableCompatibleCapability", flags: "java" },
  { name: "crunch/lite/CapabilityRefinement" },
  { name: "crunch/lite/MinMaxCapabilityRefinement" },
  { name: "crunch/crunchtest/TestCapable", flags: "java" },
  { name: "crunch/CapabilityAvailabilityDAO", flags: "java" },
  { name: "crunch/example/ExampleData", flags: "java" },

  // crunch lite rulers
  { name: "crunch/lite/ruler/CapableStatusChangeAdjustApprovalsRuleAction", flags: "java" },
  { name: "crunch/lite/ruler/CapablePayloadApprovableRuleAction", flags: "java" },
  { name: "crunch/lite/ruler/CapableCreateApprovalsRuleAction", flags: "java" },
  { name: "crunch/lite/ruler/SetCapablePayloadStatusOnPut", flags: "java" },
  { name: "crunch/lite/ruler/ReputDependantPayloads", flags: "java" },
  { name: "crunch/lite/ruler/UCJApprovableValidateAction", flags: "java" },

  // crunch capability categories
  { name: "crunch/CapabilityCategory", flags: "java" },
  { name: "crunch/UserCapabilityJunctionRefine", flags: "java" },
  { name: "crunch/CapabilityCapabilityJunctionRefine" },
  { name: "crunch/CapabilityCategoryCapabilityJunctionRefine" },
  { name: "crunch/RenewableData", flags: "java" },
  { name: "crunch/UCJProperty" },
  { name: "crunch/UCJUpdateApprovable", flags: "java" },
  { name: "crunch/connection/CapabilityPayload", flags: "java" },
  { name: "crunch/connection/CapabilityPayloadRecord", flags: "java" },
  { name: "crunch/connection/GrantPathNode", flags: "java" },
  { name: "crunch/document/Document", flags: "java" },
  //daos
  { name: "crunch/UserCapabilityJunctionDAO", flags: "java" },
  { name: "crunch/connection/CapabilityPayloadDAO", flags: "java" },
  { name: "crunch/PredicatedPrerequisiteCapabilityJunctionDAO", flags: "java" },
  //rules
  { name: "crunch/SendNotificationOnTopLevelCapabilityStatusUpdate", flags: "java" },
  { name: "crunch/IsUserCapabilityJunctionStatusUpdate", flags: "java" },
  { name: "crunch/RemoveJunctionsOnUserRemoval", flags: "java" },
  { name: "crunch/CrunchService", flags: "java" },
  { name: "crunch/ClientCrunchService" },
  { name: "crunch/ReputDependentUCJs", flags: "java" },
  //predicates
  { name: "crunch/predicate/CapabilityIsStatus", flags: "java" },
  { name: "crunch/predicate/CapabilityPrerequisitesGranted", flags: "java" },
  { name: "crunch/predicate/StatusChangedTo", flags: "java" },
  { name: "crunch/predicate/IsAgent", flags: "java" },
  { name: "crunch/predicate/IsSpid", flags: "java" },
  { name: "crunch/predicate/CapabilityJunctionTransitionToStatus", flags: "java" },
  { name: "crunch/predicate/IsAgentUpdate", flags: "java" },
  { name: "crunch/predicate/IsCapabilityJunctionOf", flags: "java" },
  //spid
  { name: "auth/CreateUserCapabilityJunctionOnSpidSet", flags: "java" },
  { name: "auth/SetUserServiceProviderJunctionRuleAction", flags: "java" },
  { name: "auth/FilterBySpidService", flags: "java" },
  { name: "auth/PreventDuplicateEmailLoginService", flags: "java" },
  //ucjDAO rules
  { name: "crunch/ruler/AuthorizeUCJStatusOnPut", flags: "java" },
  { name: "crunch/ruler/CheckUCJOwnershipOnPut", flags: "java" },
  { name: "crunch/ruler/ValidateUCJDataOnPut", flags: "java" },
  { name: "crunch/ruler/SetUCJStatusOnPut", flags: "java" },
  { name: "crunch/ruler/ConfigureUCJExpiryOnGranted", flags: "java" },
  { name: "crunch/ruler/SaveUCJDataOnGranted", flags: "java" },
  //views
  { name: "crunch/ui/WizardState", flags: "java" },
  { name: "crunch/ui/ApprovableUserCapabilityJunctionWAO" },
  { name: "crunch/ui/UserCapabilityJunctionWAO" },
  { name: "crunch/ui/CapableWAO" },
  { name: "crunch/ui/CapabilityWizardlet", flags: "java" },
  { name: "crunch/ui/ReloadSubjectWizardlet" },
  { name: "crunch/ui/MinMaxCapabilityWizardlet", flags: "java" },
  { name: "crunch/ui/MinMaxCapabilityWizardletSection" },
  { name: "crunch/ui/ReviewCapabilityWizardlet", flags: "java" },
  { name: "crunch/ui/ReviewCapabilityView" },
  { name: "crunch/ui/ReviewUCJView" },
  { name: "crunch/ui/CapableView" },
  { name: "crunch/ui/UCJView" },
  { name: "crunch/ui/PrerequisiteAwareWizardlet", flags: "java" },
  { name: "crunch/ui/LiftingAwareWizardlet", flags: "java" },
  //boxes
  { name: "crunch/box/CrunchClientBox", flags: "java" },
  { name: "crunch/box/CrunchClientReplyBox", flags: "java" },
  //extras
  { name: "crunch/extra/ReviewCapability", flags: "java" },
  { name: "crunch/extra/ReviewCapabilityData", flags: "java" },
  { name: "crunch/extra/ReviewWizard", flags: "java" },
  { name: "crunch/extra/ImplyReviewedAction", flags: "java" },
  //test
  { name: "crunch/test/CrunchTestSupport" },

  // approval
  { name: "approval/ApprovalStatus", flags: "java" },
  { name: "approval/ApprovalRequestClassificationEnum", flags: "java" },
  { name: "approval/ApprovalRequestClassification", flags: "java" },
  { name: "approval/ApprovalRequest", flags: "java" },
  { name: "approval/ApprovalRequestNotification", flags: "java" },
  { name: "approval/ApprovalRequestNotificationNotificationCitationView", flags: "web" },
  { name: "approval/ApprovableAware", flags: "java" },
  { name: "approval/PropertiesToUpdateView", flags: "web" },
  { name: "approval/Approvable", flags: "java" },
  { name: "approval/ApprovableAwareDAO", flags: "java" },
  { name: "approval/ApprovableApprovalRequestsPredicate", flags: "java" },
  { name: "approval/ApprovableApprovalRequestsRule", flags: "java" },
  { name: "approval/FulfilledApprovablePredicate", flags: "java" },
  { name: "approval/FulfilledNestedJournalApprovablePredicate", flags: "java" },
  { name: "approval/FulfilledApprovableRule", flags: "java" },
  { name: "approval/PopulateApprovalRequestsDAO", flags: "java" },
  { name: "approval/ApprovalRequestAssignedToRule", flags: "java" },
  { name: "approval/ApprovalRequestMemoRule", flags: "java" },
  { name: "approval/CompositeApprovable", flags: "java" },
  { name: "approval/CustomViewReferenceApprovable", flags: "java" },
  { name: "approval/FulfilledCompositeApprovableRule", flags: "java" },
  { name: "approval/RestrictedApprovableDAO", flags: "java" },
  { name: "approval/PopulateApprovalRequestSummariesDAO", flags: "java" },

  //authservice
  { name: "auth/CapabilityAuthService", flags: "java" },

  // google
  { name: "geocode/GoogleMapsCredentials", flags: "java" },

//  { name: "foam/demos/u2/AllViews" },
//  { name: "foam/demos/u2/MDAllViews" },

  //notification
  { name: "crunch/TopLevelCapabilityStatusUpdateNotification", flags: "java" },

  { name: 'om/OMRuleAction', flags: "java" },
  { name: 'om/CCOMRuleAction', flags: "java" },

  { name: "theme/customisation/ThemeFacade", flags: 'web' },
  { name: "theme/customisation/ThemeCustomisation", flags: 'web' },
  { name: "theme/customisation/ThemeImageUploadView", flags: 'web' },
  { name: "notification/broadcast/BroadcastNotification", flags: 'java' },
  { name: "notification/broadcast/SendNotificationView", flags: 'web' },
  { name: "notification/broadcast/BroadcastNotificationFacade", flags: 'web' },
  { name: "notification/broadcast/BroadcastNotificationNotificationCitationView", flags: 'web' },
  ]
});
