FOAM_FILES([
  { name: 'net/nanopay/client/Client' },
  { name: 'net/nanopay/model/Account' },
  { name: 'net/nanopay/model/AccountInfo' },
  { name: 'net/nanopay/model/AccountLimit' },
  { name: 'net/nanopay/model/Bank' },
  { name: 'net/nanopay/model/BankAccountInfo' },
  { name: 'net/nanopay/model/PadAccount' },
  { name: 'net/nanopay/model/Phone' },
  { name: 'net/nanopay/model/User' },
  { name: 'net/nanopay/model/UserAccountInfo' },
  { name: 'net/nanopay/ui/SignIn' },
  { name: 'net/nanopay/ui/wizardView/WizardView' },
  { name: 'net/nanopay/ui/wizardView/WizardViewOverview' },
  { name: 'net/nanopay/ui/wizardView/WizardSubView' },
]);