foam.POM({
  name: 'console',
  projects: [
    { name: 'parser/pom' },
    { name: 'dashboard/pom' },
    { name: "pivottest/pom" },
    { name: "example/pom" },
    { name: "canvas/pom" },
    { name: "ai/pom" },
    { name: "perf/pom" },
    { name: "graph/pom" },
    { name: "test/pom", flags: "test" }
  ],
  files: [
    { name: '../../demos/spacewars/SpaceWar', flags: 'js' },
    { name: '../../demos/pong/Pong',      flags: 'js' },
    { name: '../../doc/DIGApiDoc',        flags: 'js' },
    { name: '../../doc/ModelDiagramView', flags: 'js' },
    { name: '../../u2/mlang/Table',    flags: 'js|java' },
    { name: '../../u2/mlang/Pie',      flags: 'js|java' },
    { name: 'AbstractDAOAgent',        flags: 'js' },
    { name: 'BadBlock',                flags: 'js' },
    { name: 'SetDAOAgent',             flags: 'js' },
    { name: 'DAOResolverMixin',        flags: 'js' },
    { name: 'Check',                   flags: 'js' },
    { name: 'CitationSink',            flags: 'js|java' },
    { name: 'Clock',                   flags: 'js' },
    { name: 'Console',                 flags: 'js' },
    { name: 'DependencyScanner',       flags: 'js' },
    { name: 'Block',                   flags: 'js' },
    { name: 'ConsoleZACClient',        flags: 'js' },
    { name: 'DAOCreate',               flags: 'js' },
    { name: 'DAOFilterPrompt',         flags: 'js' },
    { name: 'DAOPrompt',               flags: 'js' },
    { name: 'ClassLink',               flags: 'js' },
    { name: 'Doc',                     flags: 'js' },
    { name: 'Markdown',                flags: 'js' },
    { name: 'Image',                   flags: 'js' },
    { name: 'Link',                    flags: 'js' },
    { name: 'DocumentReadWriteView',   flags: 'js' },
    { name: 'DuplicateSink',           flags: 'js|java' },
    { name: 'EditSink',                flags: 'js|java' },
    { name: 'ErrorView',               flags: 'js' },
    { name: 'FlowableTree',            flags: 'js' },
    { name: 'FlowAccess',              flags: 'js|java' },
    { name: 'UserFlowAccess',          flags: 'js|java' },
    { name: 'Flow',                    flags: 'js|java' },
    { name: 'Pivot',                   flags: 'js|java' },
    { name: 'PivotTableView',          flags: 'js' },
    { name: 'GridBy',                  flags: 'js|java' },
    { name: 'GridByView',              flags: 'js' },
    { name: 'Header',                  flags: 'js' },
    { name: 'JSONSink',                flags: 'js|java' },
    { name: 'SinkAgent',               flags: 'js|java' },
    { name: 'CommandItemView',         flags: 'js' },
    { name: 'ReflowToolBar',           flags: 'js' },
    { name: 'ReflowConfigView',        flags: 'web' },
    { name: 'LayoutBlock',             flags: 'web' },
    { name: 'ModelDAO',                flags: 'js' },
    { name: 'PropertyChoiceView',      flags: 'js' },
    { name: 'PropertyExprView',        flags: 'js' },
    { name: 'PropertySuggestedField',  flags: 'js' },
    { name: 'PropertyOptionCitationView',   flags: 'js' },
    { name: 'ComparatorSuggestedField', flags: 'js' },
    { name: 'PredicateSuggestedField', flags: 'js' },
    { name: 'PropertyListView',        flags: 'js' },
    { name: 'PropertyOrderChoiceView', flags: 'js' },
    { name: 'ReactiveDetailView',      flags: 'js' },
    { name: 'DynamicReflowData',       flags: 'js' },
    { name: 'DynamicReflowComponents', flags: 'js' },
    { name: 'DynamicReflowHelp',       flags: 'js' },
    { name: 'Script',                  flags: 'js' },
    { name: 'Signature',               flags: 'js' },
    { name: 'SinkView',                flags: 'js' },
    { name: 'CopyFromBorder',          flags: 'js' },
    { name: 'Upload',                  flags: 'js' },
    { name: 'UploadSink',              flags: 'js' },
    { name: 'UploadAgent',             flags: 'js|java' },
    { name: 'ViewSink',                flags: 'js|java' },
    { name: 'XHR',                     flags: 'js' },
    { name: 'float/Test',              flags: 'js' },
    { name: 'XMLSink',                 flags: 'js|java' },
    { name: 'cmd/Commands',            flags: 'js|java' },
    { name: 'cmd/DAO',                 flags: 'js|java' },
    { name: 'cmd/DAORowView',          flags: 'js' },
    { name: 'cmd/Info',                flags: 'js|java' },
    { name: 'ColumnParser',            flags: 'js' },
    { name: 'Prompt',                  flags: 'js' },
    { name: 'lib',                     flags: 'js' },
    { name: 'Mapping',                 flags: 'js|java' },
    { name: 'DateFormatCitationView',  flags: 'js' },
    { name: 'NumberFormatCitationView', flags: 'js' },
    { name: 'FromCsvRefines',          flags: 'js' },
    { name: 'ToolbarControl',          flags: 'js|java' },
    { name: 'control/HelpControl',     flags: 'js' },
    { name: 'control/AutoControl',     flags: 'js' },
    { name: 'control/AutoGrammar',     flags: 'js' },
    { name: 'control/CollectionsControl', flags: 'js' },
    { name: 'control/FlowsControl',     flags: 'js' },
    { name: 'control/ComponentsControl', flags: 'js' },
    { name: 'FlowBrowserView',         flags: 'js' },
    { name: 'FilteredDAOAgent',        flags: 'js' },
    { name: 'cells/Cells',             flags: 'js' },
    { name: 'cells/CellsDAOAgent',     flags: 'js' },
    { name: 'cells/CellsSink',         flags: 'js|java' }
  ]
});
