/**
 * @license
 * Copyright 2022 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.POM({
  name: "core",
  version: 3,
  licenses: [
    `
    Copyright 2023 The FOAM Authors. All Rights Reserved.
    http://www.apache.org/licenses/LICENSE-2.0
    `,
    `
    Copyright 2016 Google Inc. All Rights Reserved.
    http://www.apache.org/licenses/LICENSE-2.0
    `
  ],
  projects: [
    { name: "app/pom" },
    { name: "auth/pom" },
    { name: "grant/pom" },
    { name: "browser/pom" },
    { name: "reflow/pom" },
    { name: "er/pom" },
    { name: "jetty/pom" },
    { name: "medusa/pom" },
    { name: "place/pom" },
    { name: "pii/pom" },
    { name: "referral/pom" },
    { name: "ruler/pom" },
    { name: "crunch/pom" }, // NOTE: must follow ruler - direct reference to RULE_PREDICATE
    { name: "notification/email/ms/pom" },
    { name: "security/pom" },
    { name: "so/pom" },
    { name: "ai/pom" },
    { name: "bench/pom",                               flags: "test" },
    { name: "test/pom",                                flags: "test" },
    { name: "theme/pom" },
    { name: "partition/pom" },
    { name: "license/pom" }
  ],
  files: [
    { name: "client/ClientBuilder",                                                       flags: "js" },
    { name: "client/ClientBuilderServer",                                                 flags: "js|java" },
    { name: "column/ColumnConfigPropertyValue",                                           flags: "js|java" },
    { name: "column/CommonColumnHandler",                                                 flags: "js" },
    { name: "column/CSVTableOutputter",                                                   flags: "js" },
    { name: "column/NestedPropertiesExpression",                                          flags: "js|java" },
    { name: "column/TableColumnOutputter",                                                flags: "js|java" },
    { name: "column/test/CSVTableOutputterJSTest",                                        flags: "js&test|java&test" },
    { name: "column/test/TableColumnOutputterJSTest",                                     flags: "js&test|java&test" },
    { name: "controller/AppStyles",                                                       flags: "web" },
    { name: "controller/Fonts",                                                           flags: "web" },
    { name: "logger/DAOLogger",                                                           flags: "js|java" },
    { name: "logger/Logger",                                                              flags: "js|java" },
    { name: "logger/LoggingDAO",                                                          flags: "js|java" },
    { name: "logger/LogMessage",                                                          flags: "js|java" },
    { name: "logger/LogMessageCitationView",                                              flags: "js" },
    { name: "logger/LogMessageDAO",                                                       flags: "js|java" },
    { name: "logger/AbstractLogger",                                                      flags: "js|java" },
    { name: "logger/ProxyLogger",                                                         flags: "js|java" },
    { name: "logger/LoggerJDAO",                                                          flags: "js|java" },
    { name: "logger/LoggerJournal",                                                       flags: "js|java" },
    { name: "logger/LogLevelFilterLogger",                                                flags: "js|java" },
    { name: "logger/NotificationLogMessageDAO",                                           flags: "js|java" },
    { name: "logger/RepeatLogMessageDAO",                                                 flags: "js|java" },
    { name: "logger/StdoutLogger",                                                        flags: "js|java" },
    { name: "logger/StdoutLoggerDAO",                                                     flags: "js|java" },
    { name: "logger/benchmark/LoggerBenchmark",                                           flags: "js&test|java&test" },
    { name: "logger/LoggerUserInfo",                                                      flags: "js|java" },
    { name: "fs/AgreementView",                                                           flags: "js" },
    { name: "fs/FileCitationView",                                                        flags: "js" },
    { name: "fs/File",                                                                    flags: "js|java" },
    { name: "fs/FileLabel",                                                               flags: "js|java" },
    { name: "fs/FileType",                                                                flags: "js|java" },
    { name: "fs/FileProperty",                                                            flags: "js" },
    { name: "fs/FileDAODecorator",                                                        flags: "js" },
    { name: "fs/FileArray",                                                               flags: "js" },
    { name: "fs/FileArrayDAODecorator",                                                   flags: "js" },
    { name: "fs/FileArrayInCapablePayloadsDecorator",                                     flags: "js" },
    { name: "fs/FileSizeView",                                                            flags: "web" },
    { name: "fs/FileDataClearSink",                                                       flags: "js|java" },
    { name: "fs/FileDataDAO",                                                             flags: "js|java" },
    { name: "fs/FileUpdateDecorator",                                                     flags: "js|java" },
    { name: "fs/FSFile",                                                                  flags: "js|java" },
    { name: "fs/FSFileContent",                                                           flags: "js|java" },
    { name: "fs/FSFileDAO",                                                               flags: "java" },
    { name: "fs/FSFileContentDAO",                                                        flags: "java" },
    { name: "fs/Relationships",                                                           flags: "js|java" },
    { name: "fs/Watcher",                                                                 flags: "js|java" },
    { name: "fs/SourceChange",                                                            flags: "js|java" },
    { name: "fs/SourceWatcher",                                                           flags: "js|java" },
    { name: "fs/test/RecordingWatcher",                                                   flags: "js&test|java&test" },
    { name: "fs/test/WatcherTest",                                                        flags: "js&test|java&test" },
    { name: "fs/test/SourceWatcherTest",                                                  flags: "js&test|java&test" },
    { name: "fs/test/SourceWatcherCpuTest",                                               flags: "js&test|java&test" },
    { name: "fs/fileDropZone/FileDropZone",                                               flags: "web" },
    { name: "fs/fileDropZone/FilePreview",                                                flags: "web" },
    { name: "fs/fileDropZone/FileCard",                                                   flags: "web" },
    { name: "fs/fileDropZone/FileUploader",                                               flags: "web" },
    { name: "fs/TempFile",                                                                flags: "js|java" },
    { name: "fs/TempFileDAO",                                                             flags: "js|java" },
    { name: "fs/TextSaveView",                                                            flags: "web" },
    { name: "controller/Memento",                                                         flags: "js" },
    { name: "controller/ApplicationController",                                           flags: "js" },
    { name: "alarming/AddAlarmNameDAO",                                                   flags: "js|java" },
    { name: "alarming/Alarm",                                                             flags: "js|java" },
    { name: "alarming/AlarmAndMonitoring",                                                flags: "js|java" },
    { name: "alarming/AlarmCitationView",                                                 flags: "js" },
    { name: "alarming/AlarmConfig",                                                       flags: "js|java" },
    { name: "alarming/AlarmConfigOMNameDAO",                                              flags: "js|java" },
    { name: "alarming/AlarmConfigOMNameSink",                                             flags: "js|java" },
    { name: "alarming/AlarmingUniqueNameDAO",                                             flags: "js|java" },
    { name: "alarming/AlarmIdRefines",                                                    flags: "js|java" },
    { name: "alarming/AlarmHostnameRuleAction",                                           flags: "js|java" },
    { name: "alarming/AlarmLoggingDAO",                                                   flags: "js|java" },
    { name: "alarming/AlarmNotificationDAO",                                              flags: "js|java" },
    { name: "alarming/AlarmReason",                                                       flags: "js|java" },
    { name: "alarming/CandlestickAlarm",                                                  flags: "web|java" },
    { name: "alarming/CandlestickAlarmDAO",                                               flags: "js|java" },
    { name: "alarming/MonitoringReport",                                                  flags: "js|java" },
    { name: "alarming/MonitorType",                                                       flags: "js|java" },
    { name: "alarming/OMName",                                                            flags: "js|java" },
    { name: "alarming/DiskSpaceMonitoringCron",                                           flags: "js|java" },
    { name: "alarming/test/CandlestickAlarmTest",                                         flags: "js&test|java&test" },
    { name: "oauth/OAuthProvider",                                                        flags: "js|java" },
    { name: "oauth/OAuthCredential",                                                      flags: "js|java" },
    { name: "oauth/OAuthTokenRefreshCron",                                                flags: "java" },
    { name: "benchmark/AuthorizerBenchmark",                                              flags: "js&test|java&test" },
    { name: "boot/CSpec",                                                                 flags: "js|java" },
    { name: "boot/CSpecAware",                                                            flags: "js|java" },
    { name: "boot/CSpecStatus",                                                           flags: "js|java" },
    // { name: "boot/CSpecCitationView",                                                     flags: "js" },
    { name: "boot/DataManagement",                                                        flags: "web" },
    { name: "boot/DAOCSpecMenu",                                                          flags: "js|java" },
    { name: "session/GroupResetSessionRuleAction",                                        flags: "js|java" },
    { name: "session/LocalSetting",                                                       flags: "js|java" },
    { name: "session/LocalSettingSessionDAO",                                             flags: "js|java" },
    { name: "session/Session",                                                            flags: "js|java" },
    { name: "session/SessionTimer",                                                       flags: "js" },
    { name: "session/SessionService",                                                     flags: "js|java" },
    { name: "session/SessionNotFoundException",                                           flags: "js|java" },
    { name: "session/SimpleSessionService",                                               flags: "js|java" },
    { name: "menu/XRegistration",                                                         flags: "js|java" },
    { name: "menu/AbstractMenu",                                                          flags: "js|java" },
    { name: "menu/AuthorizationStatus",                                                   flags: "js|java" },
    { name: "menu/DAOMenu",                                                               flags: "js" },
    { name: "menu/DAOMenu2",                                                              flags: "web" },
    { name: "menu/DocumentMenu",                                                          flags: "js" },
    { name: "menu/FlowMenu",                                                              flags: "js" },
    { name: "menu/LimitedEditFlowMenu",                                                     flags: "js" },
    { name: "menu/SeparatorMenu",                                                         flags: "js" },
    { name: "menu/DocumentFileMenu",                                                      flags: "js|java" },
    { name: "menu/LinkMenu",                                                              flags: "js" },
    { name: "menu/ListMenu",                                                              flags: "js" },
    { name: "menu/Menu",                                                                  flags: "js|java" },
    { name: "menu/PredicatedMenu",                                                        flags: "web" },
    { name: "menu/PseudoMenu",                                                            flags: "js|java" },
    { name: "menu/PseudoMenuView",                                                        flags: "web" },
    { name: "menu/MenuBar",                                                               flags: "js" },
    { name: "menu/MenuToolBar",                                                           flags: "js" },
    { name: "menu/PopupMenu",                                                             flags: "js" },
    { name: "menu/SequenceMenu",                                                          flags: "js" },
    { name: "menu/SessionLinkMenu",                                                       flags: "js" },
    { name: "menu/SubMenu",                                                               flags: "js" },
    { name: "menu/SubMenuView",                                                           flags: "js" },
    { name: "menu/TabsMenu",                                                              flags: "js" },
    { name: "menu/VerticalMenu",                                                          flags: "js" },
    { name: "menu/ViewMenu",                                                              flags: "js" },
    { name: "menu/WizardMenu",                                                            flags: "js" },
    { name: "menu/RedirectMenu",                                                          flags: "js" },
    { name: "menu/ScriptMenu",                                                            flags: "js|java" },
    { name: "menu/TreeAltView",                                                           flags: "web" },
    { name: "menu/TreeGraphAltView",                                                      flags: "js" },
    { name: "benchmark/UUIDBenchmark",                                                    flags: "js&test|java&test" },
    { name: "u2/ButtonRefinement",                                                        flags: "web" },
    { name: "u2/navigation/IFrameTopNavigation",                                          flags: "web" },
    { name: "u2/navigation/TopNavigation",                                                flags: "web" },
    { name: "u2/navigation/ResponsiveTopNav",                                             flags: "web" },
    { name: "u2/navigation/ApplicationSideNav",                                           flags: "web" },
    { name: "u2/navigation/NavigationController",                                         flags: "web" },
    { name: "u2/navigation/FooterView",                                                   flags: "web" },
    { name: "u2/navigation/SideNavigation",                                               flags: "web" },
    { name: "u2/navigation/SideNavigationItemView",                                       flags: "web" },
    { name: "u2/navigation/NavigationView",                                               flags: "web" },
    { name: "u2/navigation/BusinessLogoView",                                             flags: "web" },
    { name: "u2/navigation/UserView",                                                     flags: "web" },
    { name: "u2/navigation/SubMenuBar",                                                   flags: "web" },
    { name: "u2/navigation/ApplicationLogoView",                                          flags: "web" },
    { name: "u2/navigation/UserInfoNavigationView",                                       flags: "web" },
    { name: "u2/navigation/NotificationMenuItem",                                         flags: "web" },
    { name: "u2/navigation/Stack",                                                        flags: "web" },
    { name: "u2/navigation/PopupManager",                                                 flags: "web" },
    { name: "script/Language",                                                            flags: "js|java" },
    { name: "script/Script",                                                              flags: "js|java" },
    { name: "script/ScriptEvent",                                                         flags: "js|java" },
    { name: "script/ScriptParameter",                                                     flags: "js|java" },
    { name: "script/ScriptRunnerDAO",                                                     flags: "js|java" },
    { name: "script/ScriptStatus",                                                        flags: "js|java" },
    { name: "script/Relationships",                                                       flags: "js" },
    { name: "servlet/ErrorPageMapping",                                                   flags: "js|java" },
    { name: "servlet/FilterMapping",                                                      flags: "js|java" },
    { name: "servlet/ProxyMapping",                                                       flags: "js|java" },
    { name: "servlet/Servlet",                                                            flags: "js|java" },
    { name: "servlet/ServletMapping",                                                     flags: "js|java" },
    { name: "servlet/VirtualHostRoutingServlet",                                          flags: "js|java" },
    { name: "cron/Cron",                                                                  flags: "js|java" },
    { name: "cron/CronCitationView",                                                      flags: "js" },
    { name: "cron/CronSchedule",                                                          flags: "js|java" },
    { name: "cron/CronScheduler",                                                         flags: "js|java" },
    { name: "cron/CronScheduleDAO",                                                       flags: "js|java" },
    { name: "cron/CronScheduledComparator",                                               flags: "java" },
    { name: "cron/IntervalSchedule",                                                      flags: "js|java" },
    { name: "cron/MonthlyChoice",                                                         flags: "js|java" },
    { name: "cron/NeverSchedule",                                                         flags: "js" },
    { name: "cron/OrSchedule",                                                            flags: "js|java" },
    { name: "cron/Schedule",                                                              flags: "js|java" },
    { name: "cron/Schedulable",                                                           flags: "js|java" },
    { name: "cron/ScheduleEnd",                                                           flags: "js|java" },
    { name: "cron/SimpleIntervalSchedule",                                                flags: "js|java" },
    { name: "cron/SymbolicFrequency",                                                     flags: "js|java" },
    { name: "cron/TimeHMS",                                                               flags: "js|java" },
    { name: "cron/TimeOfDaySchedule",                                                     flags: "js|java" },
    { name: "cron/NextDate",                                                              flags: "js|java" },
    { name: "cron/NextDateService",                                                       flags: "js|java" },
    { name: "cron/ClientNextDateService",                                                 flags: "js|java" },
    { name: "cron/test/CronScheduleTest",                                                 flags: "js&test|java&test" },
    { name: "cron/test/IntervalScheduleTest",                                             flags: "js&test|java&test" },
    { name: "cron/test/TimeOfDayScheduleTest",                                            flags: "js&test|java&test" },
    { name: "cron/test/OrScheduleTest",                                                   flags: "js&test|java&test" },
    { name: "cron/ui/SchedulableSuccessWizardletView",                                    flags: "web" },
    { name: "cron/ScheduleSchedulableRuleAction",                                         flags: "js|java" },
    { name: "cron/UnscheduleSchedulableRuleAction",                                       flags: "js|java" },
    { name: "cron/SchedulableObject",                                                     flags: "js|java" },
    { name: "export/ClientGoogleSheetsExportService",                                     flags: "js|java" },
    { name: "export/CSVTableExportDriver",                                                flags: "js" },
    { name: "export/ExportDriverRegistry",                                                flags: "js|java" },
    { name: "export/ExportDriver",                                                        flags: "js|java" },
    { name: "export/GoogleSheetsBasedExportDriver",                                       flags: "js|java" },
    { name: "export/GoogleSheetsExport",                                                  flags: "js|java" },
    { name: "export/GoogleSheetsExportDriver",                                            flags: "js|java" },
    { name: "export/GoogleSheetsOutputter",                                               flags: "js" },
    { name: "export/GoogleSheetsPropertyMetadata",                                        flags: "js|java" },
    { name: "export/GoogleSheetsServiceConfig",                                           flags: "js|java" },
    { name: "export/FLOWExportDriver",                                                    flags: "js" },
    { name: "export/JSONDriver",                                                          flags: "js" },
    { name: "export/JSONJDriver",                                                         flags: "js" },
    { name: "export/XMLDriver",                                                           flags: "js" },
    { name: "export/report/Template",                                                     flags: "js|java" },
    { name: "export/PDFGoogleSheetsExportDriver",                                         flags: "js|java" },
    { name: "export/TableExportDriver",                                                   flags: "js|java" },
    { name: "google/api/auth/GoogleApiAuthService",                                       flags: "js|java" },
    { name: "google/api/auth/GoogleApiCredentials",                                       flags: "js|java" },
    { name: "google/api/drive/GoogleDriveService",                                        flags: "js|java" },
    { name: "google/api/sheets/views/ClientGoogleSheetsDataImportService",                flags: "js" },
    { name: "google/api/sheets/views/GoogleSheetsImportConfig",                           flags: "js|java" },
    { name: "google/api/sheets/views/GoogleSheetsDataImportService",                      flags: "js|java" },
    { name: "google/api/sheets/views/GoogleSheetsDataImportServiceImpl",                  flags: "js|java" },
    { name: "google/api/sheets/views/ImportDataMessage",                                  flags: "js|java" },
    { name: "google/api/sheets/views/wizardModal/WizardModal",                            flags: "js" },
    { name: "google/api/sheets/views/wizardModal/WizardModalNavigationBar",               flags: "js" },
    { name: "google/api/sheets/views/wizardModal/WizardModalSubView",                     flags: "js" },
    { name: "google/api/sheets/views/modal/ColumnsToPropertiesMappingModal",              flags: "js" },
    { name: "google/api/sheets/views/modal/GoogleSheetImportModal",                       flags: "js" },
    { name: "google/api/sheets/views/modal/ImportFromGoogleSheetsForm",                   flags: "js" },
    { name: "COREService",                                                                flags: "js|java" },
    { name: "om/DAOOMLogger",                                                             flags: "js|java" },
    { name: "measure/Measure",                                                            flags: "java"    },
    { name: "cm/CM",                                                                      flags: "js|java" },
    { name: "cm/DatasetCM",                                                               flags: "js|java" },
    { name: "cm/DatasetCMItem",                                                           flags: "js|java" },
    { name: "cm/view/CMGraph",                                                            flags: "web" },
    { name: "cm/view/CMLine",                                                             flags: "web" },
    { name: "cm/view/CMBar",                                                              flags: "web" },
    { name: "cm/view/CMPie",                                                              flags: "web" },
    { name: "cm/CMUpdateDAO",                                                             flags: "java" },
    { name: "pm/PMTemperatureCellFormatter",                                              flags: "js" },
    { name: "pm/NullPM",                                                                  flags: "js|java" },
    { name: "pm/PM",                                                                      flags: "js|java" },
    { name: "pm/PMInfo",                                                                  flags: "js|java" },
    { name: "pm/PMTableView",                                                             flags: "web" },
    { name: "pm/PMLogger",                                                                flags: "js|java" },
    { name: "pm/NullPMLogger",                                                            flags: "js|java" },
    { name: "pm/TemperatureCView",                                                        flags: "js" },
    { name: "pm/PMFactory",                                                               flags: "js|java" },
    { name: "pool/ThreadPoolAgency",                                                      flags: "js|java" },
    { name: "pool/Throttle",                                                              flags: "js|java" },
    { name: "pool/ThrottledAgency",                                                       flags: "js|java" },
    { name: "pool/test/ThrottledAgencyTest",                                              flags: "js&test|java&test" },
    { name: "notification/ClientResendNotificationService",                               flags: "js|java" },
    { name: "notification/DAONotificationRuleAction",                                     flags: "js|java" },
    { name: "notification/EmailSetting",                                                  flags: "js|java" },
    { name: "notification/GoogleChatSetting",                                             flags: "js|java" },
    { name: "notification/MyNotificationDAO",                                             flags: "js|java" },
    { name: "notification/Notifiable",                                                    flags: "js|java" },
    { name: "notification/NotifiableNotificationRuleAction",                              flags: "js|java" },
    { name: "notification/Notification",                                                  flags: "js|java" },
    { name: "notification/NotificationCitationView",                                      flags: "js" },
    { name: "notification/NotificationExpansionDAO",                                      flags: "js|java" },
    { name: "notification/NotificationGoogleChatRefines",                                 flags: "js|java" },
    { name: "notification/NotificationHostnameRuleAction",                                flags: "js|java" },
    { name: "notification/NotificationMessageModal",                                      flags: "js" },
    { name: "notification/NotificationSlackRefines",                                      flags: "js|java" },
    { name: "notification/NotificationTemplateDAO",                                       flags: "js|java" },
    { name: "notification/NotificationView",                                              flags: "js" },
    { name: "notification/NotificationWidget",                                            flags: "js" },
    { name: "notification/NotificationMenu",                                              flags: "js|java" },
    { name: "notification/NotificationRowView",                                           flags: "js" },
    { name: "notification/NotificationSetting",                                           flags: "js|java" },
    { name: "notification/NotificationSettingsView",                                      flags: "js" },
    { name: "notification/NotificationSettingCitationView",                               flags: "js" },
    { name: "notification/EmailSettingNotificationSettingCitationView",                   flags: "js" },
    { name: "notification/NotificationNotificationView",                                  flags: "js" },
    { name: "notification/ResendNotificationServiceInterface",                            flags: "js|java" },
    { name: "notification/ScriptRunNotification",                                         flags: "js" },
    { name: "notification/SlackSetting",                                                  flags: "js|java" },
    { name: "notification/ToastNotificationDAO",                                          flags: "js|java" },
    { name: "notification/ToastState",                                                    flags: "js|java" },
    { name: "notification/UserNotificationDAO",                                           flags: "js|java" },
    { name: "notification/UserNotificationSink",                                          flags: "js|java" },
    { name: "notification/email/EmailConfig",                                             flags: "js|java" },
    { name: "notification/email/EmailFolderAgent",                                        flags: "js|java" },
    { name: "notification/email/EmailMessage",                                            flags: "js|java" },
    { name: "notification/email/EmailMessagePropertyServiceRuleAction",                   flags: "js|java" },
    { name: "notification/email/EmailMessageStatusRuleAction",                            flags: "js|java" },
    { name: "notification/email/EmailServiceConfig",                                      flags: "js|java" },
    { name: "notification/email/EmailTemplate",                                           flags: "js|java" },
    { name: "notification/email/EmailTemplateCitationView",                               flags: "js" },
    { name: "notification/email/EmailTemplateSource",                                     flags: "js|java" },
    { name: "notification/email/SMTPAgent",                                               flags: "js|java" },
    { name: "notification/email/SMTPConfig",                                              flags: "js|java" },
    { name: "notification/email/Status",                                                  flags: "js|java" },
    { name: "notification/email/test/EmailMessageRuleTest",                               flags: "js&test|java&test" },
    { name: "notification/email/test/MockSMTPAgent",                                      flags: "js|java" },
    { name: "notification/email/test/MockSMTPAgentTest",                                  flags: "js&test|java&test" },
    { name: "notification/email/EmailPropertyService",                                    flags: "js|java" },
    { name: "notification/email/EmailTemplateEngine",                                     flags: "js|java" },
    { name: "notification/email/ChainedPropertyService",                                  flags: "js|java" },
    { name: "notification/email/EmailTemplateApplyEmailPropertyService",                  flags: "js|java" },
    { name: "notification/email/GroupEmailTemplateService",                               flags: "js|java" },
    { name: "notification/email/EmailConfigEmailPropertyService",                         flags: "js|java" },
    { name: "notification/email/EmailMessageValidationPropertyService",                   flags: "js|java" },
    { name: "notification/email/ApplyBaseArgumentsEmailPropertyService",                  flags: "js|java" },
    { name: "notification/sms/NullSMSService",                                            flags: "js|java" },
    { name: "notification/sms/ProxySMSService",                                           flags: "js|java" },
    { name: "notification/push/PushService",                                              flags: "js|java" },
    { name: "notification/push/RoutingPushService",                                       flags: "js|java" },
    { name: "notification/push/WebPushService",                                           flags: "js|java" },
    { name: "notification/push/APNSPushService",                                          flags: "js|java" },
    { name: "notification/push/APNSCredential",                                           flags: "js|java" },
    { name: "notification/push/PushSettingNotificationSettingCitationView",               flags: "js" },
    // { name: "notification/push/FirebasePushService",                                      flags: "js|java" },
    { name: "notification/push/PushRegistration",                                         flags: "js|java" },
    { name: "notification/push/iOSNativePushRegistration",                                flags: "js|java" },
    { name: "notification/push/PushRegistry",                                             flags: "js|java" },
    { name: "notification/push/PushRegistryService",                                      flags: "java" },
    { name: "notification/push/PushRegistryAgent",                                        flags: "js|java" },
    { name: "notification/push/PushNotificationClickAgent",                               flags: "js" },
    { name: "notification/push/PushSetting",                                              flags: "js|java" },
    { name: "notification/sms/SMSMessage",                                                flags: "js|java" },
    { name: "notification/sms/SMSService",                                                flags: "js|java" },
    { name: "notification/sms/SMSSetting",                                                flags: "js|java" },
    { name: "notification/sms/SMSStatus",                                                 flags: "js|java" },
    { name: "notification/sms/TwilioConfig",                                              flags: "js|java" },
    { name: "notification/sms/TwilioSMSService",                                          flags: "js|java" },
    { name: "notification/test/DAONotificationTest",                                      flags: "js&test|java&test" },
    { name: "notification/test/EmailNotificationTest",                                    flags: "js&test|java&test" },
    { name: "notification/test/UserNotificationDAOTest",                                  flags: "js&test|java&test" },
    { name: "notification/test/UserNotificationDAOTestRuleAction",                        flags: "js&test|java&test" },
    { name: "demo/DemoObject",                                                            flags: "js|java" },
    { name: "demo/Demo",                                                                  flags: "js" },
    { name: "demo/relationship/test/RelationshipTest",                                    flags: "js&test|java&test" },
    { name: "http/BroadcastWebAgent",                                                     flags: "js|java" },
    { name: "http/Command",                                                               flags: "js|java" },
    { name: "http/DefaultHttpParameters",                                                 flags: "js|java" },
    { name: "http/Format",                                                                flags: "js|java" },
    { name: "http/HttpParameters",                                                        flags: "js|java" },
    { name: "http/HttpVersion",                                                           flags: "js|java" },
    { name: "http/ProxyWebAgent",                                                         flags: "js|java" },
    { name: "http/WebAgent",                                                              flags: "js|java" },
    { name: "http/SendErrorHandler",                                                      flags: "js|java" },
    { name: "http/test/DIGBroadcastWebAgentTest",                                         flags: "js&test|java&test" },
    { name: "dao/Operation",                                                              flags: "js|java" },
    { name: "dao/DAOEventRelayService",                                                   flags: "js" },
    { name: "doc/DocumentationView",                                                      flags: "js" },
    { name: "demo/relationship/CourseType",                                               flags: "js|java" },
    { name: "demo/relationship/Course",                                                   flags: "js|java" },
    { name: "demo/relationship/Professor",                                                flags: "js|java" },
    { name: "demo/relationship/Student",                                                  flags: "js|java" },
    { name: "demo/relationship/Controller",                                               flags: "js" },
    { name: "dashboard/Demo",                                                             flags: "js" },
    { name: "ticket/Ticket",                                                              flags: "js|java" },
    { name: "ticket/TicketComment",                                                       flags: "js|java" },
    { name: "ticket/TicketCompactionSink",                                                flags: "js|java" },
    { name: "ticket/TicketCitationView",                                                  flags: "js" },
    { name: "ticket/TicketStatus",                                                        flags: "js|java" },
    { name: "ticket/Relationships",                                                       flags: "js" },
    { name: "ticket/TicketAddCommentDAO",                                                 flags: "js|java" },
    { name: "ticket/TicketOwnerDAO",                                                      flags: "js|java" },
    { name: "ticket/TicketCommentOwnerDAO",                                               flags: "js|java" },
    { name: "ticket/TicketDAOCreateView",                                                 flags: "js" },
    { name: "ticket/TicketSummaryView",                                                   flags: "js" },
    { name: "ticket/TicketNotification",                                                  flags: "js|java" },
    { name: "ticket/TicketNotificationNotificationCitationView",                          flags: "js" },
    { name: "ticket/SummaryCard",                                                         flags: "js" },
    { name: "ticket/TicketCloseCommand",                                                  flags: "js|java" },
    { name: "ticket/CloseTicketCommandDAO",                                               flags: "js|java" },
    { name: "dig/bench/DIGBenchmark",                                                     flags: "js&test|java&test" },
    { name: "dig/bench/DistributedDIGBenchmarkRunner",                                    flags: "js&test|java&test" },
    { name: "dig/ExternalDataAware",                                                      flags: "js|java" },
    { name: "dig/EmailWebhook",                                                           flags: "js|java" },
    { name: "dig/FieldNameMapGrammar",                                                    flags: "js|java" },
    { name: "dig/drivers/DigFormatDriver",                                                flags: "js|java" },
    { name: "dig/drivers/DigCsvDriver",                                                   flags: "js|java" },
    { name: "dig/drivers/DigCsvSheetsDriver",                                             flags: "js|java" },
    { name: "dig/drivers/DigHtmlDriver",                                                  flags: "js|java" },
    { name: "dig/drivers/DigJsonDriver",                                                  flags: "js|java" },
    { name: "dig/drivers/DigJsonJDriver",                                                 flags: "js|java" },
    { name: "dig/drivers/DigXmlDriver",                                                   flags: "js|java" },
    { name: "dig/format/DigFormat",                                                       flags: "js|java" },
    { name: "dig/exception/DAOPutException",                                              flags: "js|java" },
    { name: "dig/exception/DAONotFoundException",                                         flags: "js|java" },
    { name: "dig/exception/DAORequiredException",                                         flags: "js|java" },
    { name: "dig/exception/DigErrorMessage",                                              flags: "js|java" },
    { name: "dig/exception/DigSuccessMessage",                                            flags: "js|java" },
    { name: "dig/exception/EmptyDataException",                                           flags: "js|java" },
    { name: "dig/exception/EmptyParameterException",                                      flags: "js|java" },
    { name: "dig/exception/ExternalAPIException",                                         flags: "js|java" },
    { name: "dig/exception/GeneralException",                                             flags: "js|java" },
    { name: "dig/exception/ParsingErrorException",                                        flags: "js|java" },
    { name: "dig/exception/TemporaryExternalAPIException",                                flags: "js|java" },
    { name: "dig/exception/UnsupportException",                                           flags: "js|java" },
    { name: "dig/exception/UnknownIdException",                                           flags: "js|java" },
    { name: "dig/Argument",                                                               flags: "js|java" },
    { name: "dig/DIG",                                                                    flags: "js|java" },
    { name: "dig/DIGDetailView",                                                          flags: "js" },
    { name: "dig/DigFileUploadView",                                                      flags: "js" },
    { name: "dig/DigSnippetView",                                                         flags: "js" },
    { name: "dig/DUGDigestConfig",                                                        flags: "js|java" },
    { name: "dig/DUGRule",                                                                flags: "js|java" },
    { name: "dig/DUGRuleAction",                                                          flags: "js|java" },
    { name: "dig/DUGLoopback",                                                            flags: "js|java" },
    { name: "dig/DUGLoopbackWebAgent",                                                    flags: "js|java" },
    { name: "dig/LinkView",                                                               flags: "js" },
    { name: "dig/ResultView",                                                             flags: "js" },
    { name: "dig/SUGAR",                                                                  flags: "js|java" },
    { name: "dig/test/DigCsvDriverTest",                                                  flags: "js&test|java&test" },
    { name: "dig/test/DigJsonDriverTest",                                                 flags: "js&test|java&test" },
    { name: "dig/test/DUGLoopbackTest",                                                   flags: "js&test|java&test" },
    { name: "notification/email/ClientPOP3EmailService",                                  flags: "js|java" },
    { name: "notification/email/POP3Email",                                               flags: "js|java" },
    { name: "analytics/AnalyticEvent",                                                    flags: "js|java" },
    { name: "analytics/AnalyticEventTimestampDAO",                                        flags: "js|java" },
    { name: "analytics/AnalyticEventOMDAO",                                               flags: "js|java" },
    { name: "analytics/Analyticable",                                                     flags: "js|java" },
    { name: "analytics/ruler/LogAnalyticEventRuleAction",                                 flags: "js|java" },
    { name: "analytics/Candlestick",                                                      flags: "js|java" },
    { name: "analytics/CandlestickChartView",                                             flags: "js" },
    { name: "analytics/CandlestickChartCitationView",                                     flags: "js" },
    { name: "analytics/CandlestickKeyView",                                               flags: "js" },
    { name: "analytics/CandlestickUniqueKeyPredicate",                                    flags: "js|java" },
    { name: "analytics/DemoChartView",                                                    flags: "js" },
    { name: "analytics/Foldable",                                                         flags: "js|java" },
    { name: "analytics/PostToWindow",                                                     flags: "web" },
    { name: "analytics/test/AnalyticEventDAOSecurityTest",                                flags: "js&test|java&test" },
    { name: "analytics/GoogleTagAgent",                                                   flags: "web" },
    { name: "analytics/LogVisitAgent",                                                    flags: "web" },
    { name: "approval/ApprovalDAO",                                                       flags: "js|java" },
    { name: "approval/ApprovalStatus",                                                    flags: "js|java" },
    { name: "approval/ApprovalRequest",                                                   flags: "js|java" },
    { name: "approval/ApprovalRequestClassificationEnum",                                 flags: "js|java" },
    { name: "approval/ApprovalRequestClassification",                                     flags: "js|java" },
    { name: "approval/ApprovalRequestCompactionSink",                                     flags: "js|java" },
    { name: "approval/ApprovalRequestNotification",                                       flags: "js|java" },
    { name: "approval/ApprovalRequestNotificationNotificationCitationView",               flags: "web" },
    { name: "approval/ApprovableAware",                                                   flags: "js|java" },
    { name: "approval/PropertiesToUpdateView",                                            flags: "web" },
    { name: "approval/Approvable",                                                        flags: "js|java" },
    { name: "approval/ApprovableAwareDAO",                                                flags: "js|java" },
    { name: "approval/ApprovableApprovalRequestsPredicate",                               flags: "js|java" },
    { name: "approval/ApprovableApprovalRequestsRule",                                    flags: "js|java" },
    { name: "approval/ApprovableCompactionSink",                                          flags: "js|java" },
    { name: "approval/FulfilledApprovablePredicate",                                      flags: "js|java" },
    { name: "approval/FulfilledNestedJournalApprovablePredicate",                         flags: "js|java" },
    { name: "approval/FulfilledApprovableRule",                                           flags: "js|java" },
    { name: "approval/PopulateApprovalRequestsDAO",                                       flags: "js|java" },
    { name: "approval/ApprovalRequestAssignedToRule",                                     flags: "js|java" },
    { name: "approval/ApprovalRequestMemoRule",                                           flags: "js|java" },
    { name: "approval/AuthenticatedApprovalDAOAuthorizer",                                flags: "js|java" },
    { name: "approval/CompositeApprovable",                                               flags: "js|java" },
    { name: "approval/CustomViewReferenceApprovable",                                     flags: "js|java" },
    { name: "approval/FulfilledCompositeApprovableRule",                                  flags: "js|java" },
    { name: "approval/RestrictedApprovableDAO",                                           flags: "js|java" },
    { name: "approval/ReleaseCashInApprovalType",                                         flags: "js|java" },
    { name: "approval/PopulateApprovalRequestSummariesDAO",                               flags: "js|java" },
    { name: "approval/SendGroupRequestApprovalDAO",                                       flags: "js|java" },
    { name: "approval/UCJApprovable",                                                     flags: "js|java" },
    { name: "geocode/GoogleMapsAddressComponent",                                         flags: "js|java" },
    { name: "geocode/GoogleMapsCoordinates",                                              flags: "js|java" },
    { name: "geocode/GoogleMapsGeocodeResponse",                                          flags: "js|java" },
    { name: "geocode/GoogleMapsGeocodeResult",                                            flags: "js|java" },
    { name: "geocode/GoogleMapsGeometry",                                                 flags: "js|java" },
    { name: "geocode/GoogleMapsBoundary",                                                 flags: "js|java" },
    { name: "geocode/GoogleMapsAddressParser",                                            flags: "js|java" },
    { name: "geocode/GoogleMapsPlacesPredictions",                                        flags: "js|java" },
    { name: "geocode/GoogleMapsPlacesResponse",                                           flags: "js|java" },
    { name: "geocode/GoogleMapsCredentials",                                              flags: "js|java" },
    { name: "om/OMRuleAction",                                                            flags: "js|java" },
    { name: "om/CCOMRuleAction",                                                          flags: "js|java" },
    { name: "notification/broadcast/BroadcastNotification",                               flags: "js|java" },
    { name: "notification/broadcast/SendNotificationView",                                flags: "web" },
    { name: "notification/broadcast/BroadcastNotificationFacade",                         flags: "web|js|java" },
    { name: "notification/broadcast/BroadcastNotificationNotificationCitationView",       flags: "web" },
    { name: "ndiff/NDiff",                                                                flags: "js|java" },
    { name: "ndiff/NDiffDAO",                                                             flags: "js|java" },
    { name: "ndiff/NDiffJournal",                                                         flags: "js|java" },
    { name: "ndiff/NDiffRuntimeDAO",                                                      flags: "js|java" },
    { name: "http/csp/CSPDirective",                                                      flags: "js|java" },
    { name: "http/csp/CSPFilter",                                                         flags: "java" },
    { name: "http/csp/CSPReportWebAgent",                                                 flags: "java" },
    { name: "http/csp/CSPViolation",                                                      flags: "js|java" },
    { name: "http/csp/test/CSPDirectiveTest",                                             flags: "js&test|java&test" },
    { name: "actioncommand/ActionCommand",                            flags: "js|java" },
    { name: "pool/AbstractFixedThreadPool",                           flags: "js|java" },
    { name: "om/OMLogger",                                            flags: "js|java" },
    { name: "google/api/sheets/GoogleSheetsApiService",               flags: "js|java" },
    { name: "actioncommand/ActionCommandDAO",                         flags: "js|java" },
    { name: "audit/AuditDAO",                                         flags: "js|java" },
    { name: "geocode/GoogleMapsGeocodingDAO",                         flags: "js|java" },
    { name: "analytics/FoldManager",                                  flags: "js|java" },
    { name: "analytics/FoldManagerDAODecorator",                      flags: "js|java" },
    { name: "analytics/DAOFoldManager",                               flags: "js|java" },
    { name: "analytics/DAOReduceManager",                             flags: "js|java" },
    { name: "cron/SimpleIntervalScheduleView",                        flags: "web" },
    { name: "benchmark/DateFormatBenchmark",                          flags: "js&test|java&test" },
    { name: "benchmark/JournalReplayBenchmark",                       flags: "js&test|java&test" },
    { name: "benchmark/LoggingBenchmark",                             flags: "js&test|java&test" },
    { name: "benchmark/JSONOutputterEscapeBenchmark",                 flags: "js&test|java&test" },
    { name: "benchmark/FUIDBenchmark",                                flags: "js&test|java&test" },
    { name: "benchmark/TimestampBenchmark",                           flags: "js&test|java&test" },
    { name: "benchmark/JSONOutputterBenchmark",                       flags: "js&test|java&test" },
    { name: "benchmark/JSONUtilEscapeBenchmark",                      flags: "js&test|java&test" },
    { name: "benchmark/PMBenchmark",                                  flags: "js&test|java&test" },
    { name: "benchmark/F3FileJournalBenchmark",                       flags: "js&test|java&test" },
    { name: "benchmark/JSONFormatterBenchmark",                       flags: "js&test|java&test" },
    { name: "benchmark/F3JournalReplayBenchmark",                     flags: "js&test|java&test" },
    { name: "benchmark/FileJournalBenchmark",                         flags: "js&test|java&test" },
    { name: "notification/NotificationGroupingDAOList",               flags: "web" },
    { name: "analytics/ChangeAnalyticEvent",                          flags: 'js|java'           }
  ],

  javaFiles: [
    { name: "alarming/test/OMAlarmTest",                              flags: "test" },
    { name: "pm/DAOPMLogger" },
    { name: "pm/PipelinePMLocator" },
    { name: "pm/PMInfoMDAO" },
    { name: "pm/FoldReducePMLogger" },
    { name: "pm/PMWebAgent" },
    { name: "servlet/ImageServlet" },
    { name: "servlet/RedirectServlet" },
    { name: "servlet/ResourceImageServlet" },
    { name: "box/COREServiceRouter" },
    { name: "oauth/OAuthWebAgent" },
    { name: "logger/PrefixLogger" },
    { name: "logger/PostfixLogger" },
    { name: "logger/JavaHandler" },
    { name: "logger/NullLogger" },
    { name: "logger/Loggers" },
    { name: "logger/CompositeLogger" },
    { name: "logger/SubjectLogger" },
    { name: "boot/ShutdownHook" },
    { name: "boot/AltFactory" },
    { name: "boot/ByServiceProviderFactory" },
    { name: "boot/CSpecFactory" },
    { name: "boot/Boot" },
    { name: "notification/ResendNotificationService" },
    { name: "notification/email/POP3EmailService" },
    { name: "notification/email/EmailTemplateSupport" },
    { name: "google/api/sheets/views/GoogleSheetsParsingHelper" },
    { name: "script/BeanShellExecutor" },
    { name: "script/JShellExecutor" },
    { name: "script/jShell/ReadLineByLine" },
    { name: "script/jShell/EvalInstruction" },
    { name: "script/jShell/InstructionPresentation" },
    { name: "http/UnauthenticatedFileService" },
    { name: "http/ThreadsWebAgent" },
    { name: "http/ServletHandler" },
    { name: "http/ShowSessionWebAgent" },
    { name: "http/MemoryWebAgent" },
    { name: "http/HttpContextListener" },
    { name: "http/RefreshWebAgent" },
    { name: "http/UptimeWebAgent" },
    { name: "http/FileWebAgent" },
    { name: "http/ClassesWebAgent" },
    { name: "http/TraceWebAgent" },
    { name: "http/WebAgentQueryParser" },
    { name: "http/NanoHttpHandler" },
    { name: "http/ServiceWebAgent" },
    { name: "http/AuthWebAgent" },
    { name: "http/HttpParametersWebAgent" },
    { name: "http/WebAgentServlet" },
    { name: "http/ServicesWebAgent" },
    { name: "http/NanoRouter" },
    { name: "http/SessionWebAgent" },
    { name: "http/NanoHttpServer" },
    { name: "http/PingService" },
    { name: "dig/DigWebAgent" },
    { name: "dig/HTTPDigestSink" },
    { name: "dig/DigUtil" },
    { name: "dig/SugarWebAgent" },
    { name: "export/ExportService" },
    { name: "fs/Storage" },
    { name: "fs/AbstractStorage" },
    { name: "fs/ResourceStorage" },
    { name: "fs/FallbackStorage" },
    { name: "fs/FileSystemStorage" },
    { name: "blob/HttpBlobService" },
    { name: "blob/FileService" },
    { name: "pool/ThreadPoolWebAgent" },
    { name: "ws/NanoWebSocket" },
    { name: "cron/RemoveExpiredNotificationCronjob" },
    { name: "approval/ApprovalRequestUtil" },
    { name: "approval/PopulateApprovalRequestSummariesAdapter" },
    { name: "approval/ApprovalTester" }, // not test, used by ApprovalRequestUtil
    { name: "session/cron/ExpireSessionsCron" }
  ],
  journalFiles: [
    { name: "benchmark/benchmarks",                                   flags: "test" },
    { name: "benchmark/benchmarkRunners",                             flags: "test" },
    { name: "demo/relationship/test/tests",                           flags: "test" },
    { name: "bench/services",                                         flags: "test" },
    { name: "bench/strategyReferences",                               flags: "test" },
    { name: "referral/test/tests",                                    flags: "test" },
    { name: "test/services",                                          flags: "test" },
    { name: "notification/test/tests",                                flags: "test" },
    { name: "notification/email/test/tests",                          flags: "test" },
    { name: "alarming/test/tests",                                    flags: "test" },
    { name: "http/tests",                                             flags: "test" },
    { name: "http/test/tests",                                        flags: "test" },
    { name: "dig/bench/strategyReferences",                           flags: "test" },
    { name: "dig/test/tests",                                         flags: "test" },
    { name: "pool/tests",                                             flags: "test" },
    { name: "cron/tests",                                             flags: "test" },
    { name: "analytics/test/tests",                                   flags: "test" },
    { name: "boot/test/bootscripts",                                  flags: "test" },
    { name: "fs/test/tests",                                          flags: "test" }
  ]
});
