/**
 * @license
 * Copyright 2016 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
  Parse combinator library.

  Create complex parsers by composing simple parsers.

  A PStream is a "Parser Stream", the input format accepted by
  FOAM parsers.

  PStreams have the following interface:
    get int     pos   - The character position in the input stream.

    get Char    head  - The first character in the stream.

    get PStream tail  - A PStream for the next position in the input steam.

    get Object  value - 'Value' associated with this PStream.

    PStream setValue(Object value) - Create a new PStream at the same position
        but with a new 'value'. The value is used to hold the result of a
        (sub-)parse.

  PStreams are immutable, which greatly simplifies backtracking.

  A parser has the following interface:
    PStream parse(PStream stream);

  It takes as input a PStream, and returns either a PStream
  advanced to the point after all input consumed by the parser,
  or undefined if the parse failed. The value generated by the parser
  is stored in the .value property of the returned PStream.
*/

foam.INTERFACE({
  package: 'foam.parse',
  name: 'JSParser',

  methods: [
    {
      name: 'parse',
      type: 'foam.parse.JSPStream',
      args: [
        {
          name: 'ps',
          type: 'foam.parse.JSPStream'
        },
        {
          // optional
          name: 'grammar',
          type: 'foam.parse.Grammar'
        }
      ]
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Suggestion',

  properties: [
    {
      class: 'String',
      name: 'text'
    },
    {
      class: 'String',
      name: 'hint'
    },
    {
      class: 'String',
      name: 'category'
    },
    {
      class: 'String',
      name: 'label',
      documentation: 'Label to display in the UI. If not set, text will be used.',
      expression: function(text) { return text; }
    },
    { name: 'tooltip',
      class: 'String',
      documentation: 'Label to display in the UI as a tooltip, but doesn\'t actually make a concrete text suggestion.'
    },
    { name: 'view',
      class: 'foam.u2.ViewSpec'
    },
    {
      class: 'Boolean',
      name: 'prependSpaceOnSelect',
      documentation: 'Adds a whitespace before appending suggestion.',
      value: true
    },
    {
      class: 'Boolean',
      name: 'showText',
      documentation: 'If true the suggestion will show both the text and label.',
      value: true
    }
  ],

  methods: [
    // An optionally async function which adds Suggestions to an array.
    // In the normal case it just adds 'this', but if gives the Suggestion
    // to add a different Suggestion or Suggestions
    // delta -- the remaining text
    function expand(a, delta) {
      if ( this.view || ! this.text || this.matches(delta) ) a.push(this);
    },
    function matches(str) {
      /** Return true iff this suggestions matches the partially typed str input. **/

      function containsIC(str, sub) {
        return str.length != sub.length && str.toLowerCase().indexOf(sub.toLowerCase()) != -1;
      }

      return containsIC(this.text, str) || containsIC(this.label, str);
    }
  ]
});


/*
foam.CLASS({
  package: 'foam.parse',
  name: 'AltSuggestion',
  extends: 'foam.parse.Suggestion',

  properties: [
    { name: 'parsers' },
    {
      name: 'suggestions',
      factory: function() { this.parsers.map(p => p.suggest()).filter(s => s); }
    },
    {
      name: 'label',
      factory: function() { return '< ' + this.suggestions.map(s => s.label).join(' | ') + ' >'; }
    }
  ]
});
*/


foam.CLASS({
  package: 'foam.parse',
  name: 'AbstractParser',
  implements: ['foam.parse.JSParser'],
  abstract: true,

  requires:[ 'foam.parse.StringPStream' ],

  methods: [
    function match(str) {
      var ps = this.StringPStream.create();
      ps.setString(str);

      while ( ps.valid ) {
        var res;

        if ( res = ps.apply(this, this) ) {
          return res.value;
        }

        ps = ps.tail;
      }

      return;
    },

    function matchAll(str) {
      const a = [];

      var ps = this.StringPStream.create();
      ps.setString(str);

      while ( ps.valid ) {
        var res;
        if ( res = ps.apply(this, this) ) {
          a.push(res.value);
          ps = res;
        } else {
          ps = ps.tail;
        }
      }

      return a;
    },

    function parseString(str, _, opt_apply) {
      var result = this.parse(this.StringPStream.create({apply: opt_apply, str: str}));
      return result && result.value;
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'ParserArray',
  extends: 'FObjectArray',

  properties: [
    ['of', 'foam.lib.parse.Parser'],
    ['adapt', function(_, a) {
      if ( ! a ) return [];
      var b = new Array(a.length);
      for ( var i = 0 ; i < a.length ; i++ ) {
        b[i] = typeof a[i] === 'string' ?
          foam.parse.Literal.create({s: a[i]}) :
          a[i];
      }
      return b;
    }]
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'ParserProperty',
  extends: 'Property',

  properties: [
    {
      name: 'adapt',
      value: function(_, v) {
        return typeof v === 'string' ? foam.parse.Literal.create({s: v}) : v;
      }
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'ParserDecorator',
  extends: 'foam.parse.AbstractParser',
  abstract: true,

  properties: [
    {
      name: 'p',
      class: 'foam.parse.ParserProperty',
      final: true
    }
  ],

  methods: [
    function toString() { return this.p.toString(); }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Literal',
  implements: ['foam.parse.JSParser'],

  documentation: 'Matches a literal with the parse stream (case sensitive)',

  axioms: [
    {
      // Lots of identical Literal parsers are created so cache instances
      installInClass: function(cls) {
        let map = {};
        let oldCreate = cls.create;
        cls.create = function(args) {
          if ( args && args.s && ! args.value ) {
            let key = args.s;

            if ( ! map[key] ) {
              map[key] = oldCreate.apply(this, arguments);
            }
            return map[key];
          }

          return oldCreate.apply(this, arguments);
        };
      }
    }
  ],

  properties: [
    {
      name: 's',
      final: true
    },
    {
      // optional substitute return value
      name: 'value',
      final: true
    }
  ],

  methods: [
    function parse(ps) {
      var str = this.s;
      for ( var i = 0 ; i < str.length ; i++, ps = ps.tail ) {
        if ( str.charAt(i) !== ps.head ) {
          return undefined;
        }
      }
      return ps.setValue(this.value !== undefined ? this.value : str);
    },

    function toString() {
      return '"' + this.s + '"';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'LiteralIC',
  implements: ['foam.parse.JSParser'],

  documentation: 'Matches a literal with the parse stream (case insensitive)',

  properties: [
    {
      name: 's',
      final: true,
      postSet: function(old, nu) {
        this.lower = nu.toLowerCase();
      }
    },
    {
      name: 'lower',
      final: true
    },
    {
      name: 'value',
      final: true
    }
  ],

  methods: [
    function parse(ps) {
      var str = this.lower;
      for ( var i = 0 ; i < str.length ; i++, ps = ps.tail ) {
        if ( ! ps.head || str.charAt(i) !== ps.head.toLowerCase() ) {
          return undefined;
        }
      }
      return ps.setValue(this.value !== undefined ? this.value : this.s);
    },

    function toString() {
      return 'ignoreCase("' + this.lower + '")';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'EOF',
  implements: ['foam.parse.JSParser'],

  documentation: 'Matches the literal EOF of the input stream, useful if you want to force your grammar to only succeed if it consumes the entire input.',

  axioms: [ foam.pattern.Singleton.create() ],


  methods: [
    function parse(ps) {
      return ps.valid ? undefined : ps.setValue('');
    },

    function toString() {
      return 'eof()';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Alternate',
  extends: 'foam.parse.AbstractParser',
//  implements: ['foam.parse.JSParser'],

  documentation: 'Attempts to match one of the parser properties to the parse stream.',

  properties: [
    {
      name: 'args',
      final: true,
      class: 'foam.parse.ParserArray'
    }
  ],

  methods: [
    function parse(ps, obj) {
      // TODO(adamvy): Should we remove the obj argument in favour of
      // passing the obj along via context or something?
      var args = this.args;
      for ( var i = 0, p ; p = args[i] ; i++ ) {
        var ret = ps.apply(p, obj);
        if ( ret ) return ret;
      }
      return undefined;
    },

    function toString() {
      var args = this.args;
      var strs = new Array(args.length);
      for ( var i = 0; i < args.length; i++ ) {
        strs[i] = args[i].toString();
      }
      return 'alt(' + strs.join(', ') + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Sequence',
  implements: ['foam.parse.JSParser'],

  documentation: 'Parses the parser properties sequentially.',

  properties: [
    {
      name: 'args',
      final: true,
      class: 'foam.parse.ParserArray'
    }
  ],

  methods: [
    function parse(ps, obj) {
      var ret = [];
      var args = this.args;
      for ( var i = 0, p ; p = args[i] ; i++ ) {
        if ( ! ( ps = ps.apply(p, obj) ) ) return undefined;
        ret.push(ps.value);
      }
      return ps.setValue(ret);
    },

    function toString() {
      var args = this.args;
      var strs = new Array(args.length);
      for ( var i = 0; i < args.length; i++ ) {
        strs[i] = args[i].toString();
      }
      return 'seq(' + strs.join(', ') + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Suggest',
  extends: 'foam.parse.ParserDecorator',
  properties: [
    {
      class: 'FObjectProperty',
      of: 'foam.parse.Suggestion',
      name: 'suggestion'
    }
  ],
  methods: [
    function parse(ps, obj) {
      return ps.apply(this.p, obj);
    },
    function suggest() {
      return this.suggestion;
    },
    function toString() {
      return 'suggest(' + this.SUPER() + ')';
    }
  ]
});


/**
 * Parser decorator that attaches a message to a parser.
 * When the wrapped parser succeeds, the message can be collected
 * via the apply callback (similar to foam.parse.Suggest for suggestions).
 *
 * The message is untyped - can be string, object, array, etc.
 *
 * Usage in grammar:
 *   emptyFile: msg(eof(), 'File is empty')
 *   warning: msg(sym('old'), { warning: 'Deprecated format' })
 */
foam.CLASS({
  package: 'foam.parse',
  name: 'Msg',
  extends: 'foam.parse.ParserDecorator',

  documentation: `
    Parser decorator that attaches a message to a parser.
    When the wrapped parser matches successfully, the message
    is available via the msg() method.

    The message property is untyped - it can store any value
    (string, object, array, etc.). The consuming code is responsible
    for interpreting the message format.

    Usage in grammar:
      emptyFile: msg(eof(), 'File is empty')
      warning: msg(sym('old'), { warning: 'Deprecated format' })
  `,

  properties: [
    {
      name: 'message',
      documentation: 'Message to attach - can be any value (string, object, etc.)'
    }
  ],

  methods: [
    function parse(ps, obj) {
      // Delegate to wrapped parser
      return ps.apply(this.p, obj);
    },

    function msg() {
      // Return the message config (called by apply callback when parse succeeds)
      return this.message;
    },

    function toString() {
      return 'msg(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'String',
  extends: 'foam.parse.ParserDecorator',
  methods: [
    function parse(ps, obj) {
      ps = ps.apply(this.p, obj);
      return ps ? ps.setValue(ps.value.join('')) : undefined;
    },

    function toString() {
      return 'str(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Substring',
  extends: 'foam.parse.ParserDecorator',
  methods: [
    function parse(ps, obj) {
      var start = ps;
      ps = ps.apply(this.p, obj);
      return ps ? ps.setValue(start.substring(ps)) : undefined;
    },

    function toString() {
      return 'substring(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Sequence0',
  implements: ['foam.parse.JSParser'],

  documentation: 'Parses the parser properties sequentially, without returning value',

  properties: [
    {
      name: 'args',
      final: true,
      class: 'foam.parse.ParserArray'
    }
  ],

  methods: [
    function parse(ps, obj) {
      var args = this.args;
      for ( var i = 0, p ; p = args[i] ; i++ ) {
        if ( ! ( ps = ps.apply(p, obj) ) ) return undefined;
      }
      return ps.setValue('');
    },

    function toString() {
      var args = this.args;
      var strs = new Array(args.length);
      for ( var i = 0; i < args.length; i++ ) {
        strs[i] = args[i].toString();
      }
      return 'seq0(' + strs.join(', ') + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Sequence1',
  implements: ['foam.parse.JSParser'],

  documentation: 'Parses the parser properties sequentially, returning the n(th) property value parsed.',

  properties: [
    {
      name: 'args',
      final: true,
      class: 'foam.parse.ParserArray'
    },
    {
      name: 'n',
      final: true
    }
  ],

  methods: [
    function parse(ps, obj) {
      var ret;
      var args = this.args;
      var n = this.n;
      for ( var i = 0, p ; p = args[i] ; i++ ) {
        if ( ! ( ps = ps.apply(p, obj) ) ) return undefined;
        if ( i === n ) ret = ps.value;
      }
      return ps.setValue(ret);
    },

    function toString() {
      var args = this.args;
      var strs = new Array(args.length);
      for ( var i = 0 ; i < args.length ; i++ ) {
        strs[i] = args[i].toString();
      }
      return 'seq1(' + this.n + ', ' + strs.join(', ') + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Optional',
  extends: 'foam.parse.ParserDecorator',

  documentation: 'Refers to an optional parser property.',

  properties: [
    { name: 'default', value: null }
  ],

  methods: [
    function parse(ps, obj) {
      return ps.apply(this.p, obj) || ps.setValue(this.default);
    },

    function toString() {
      return 'opt(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'AnyChar',
  implements: ['foam.parse.JSParser'],

  documentation: `Matches any char within the parse stream.
    Often used under the else clause of the 'not' parser
    property. Ex. 'not(',', anyChar())'`,

  axioms: [ foam.pattern.Singleton.create() ],

  methods: [
    function parse(ps) {
      return ps.head ? ps.tail : undefined;
    },

    function toString() { return 'anyChar()'; }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'NotChars',
  implements: ['foam.parse.JSParser'],

  documentation: `Matches against all but the chars specified
    in the argument string.`,

  properties: [
    {
      name: 'string',
      final: true
    }
  ],

  methods: [
    function parse(ps) {
      return ps.head && this.string.indexOf(ps.head) === -1 ?
        ps.tail : undefined;
    },

    function toString() {
      var str = this.string;
      var chars = new Array(str.length);
      for ( var i = 0; i < str.length; i++ ) {
        chars[i] = str.charAt(i);
      }
      return 'notChars("' + chars.join('", "') + '")';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Chars',
  implements: ['foam.parse.JSParser'],

  documentation: `Matches against any of the chars specified
    in the argument string.`,

  properties: [
    {
      name: 'string',
      final: true
    }
  ],

  methods: [
    function parse(ps) {
      return ps.valid && this.string.indexOf(ps.head) !== -1 ?
        ps.tail : undefined;
    },

    function toString() {
      var str = this.string;
      var chars = new Array(str.length);
      for ( var i = 0; i < str.length; i++ ) {
        chars[i] = str.charAt(i);
      }
      return 'chars("' + chars.join('", "') + '")';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Range',
  implements: ['foam.parse.JSParser'],

  documentation: "Matches against a range of chars specified with from/to. Ex. range('0', '9') for digits",

  properties: [
    {
      name: 'from',
      final: true
    },
    {
      name: 'to',
      final: true
    }
  ],

  methods: [
    function parse(ps) {
      if ( ! ps.head ) return undefined;
      return ( this.from <= ps.head && ps.head <= this.to ) ?
        ps.tail.setValue(ps.head) :
        undefined;
    },

    function toString() {
      return 'range("' + this.from + '", "' + this.to + '")';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Repeat',
  extends: 'foam.parse.ParserDecorator',

  documentation: `Repeats matching to the parser property specified
    with an optional delimiter, and min number of matches.`,

  properties: [
    {
      class: 'foam.parse.ParserProperty',
      name: 'delimiter'
    },
    {
      class: 'Int',
      name: 'minimum'
    },
    {
      class: 'Int',
      name: 'maximum',
      value: Number.MAX_SAFE_INTEGER
    }
  ],

  methods: [
    function parse(ps, obj) {
      var ret   = [];
      var p     = this.p;
      var delim = this.delimiter;

      while ( ps.valid && ret.length < this.maximum ) {
        var res;

        if ( delim && ret.length != 0 ) {
          if ( ! ( res = ps.apply(delim, obj) ) ) break;
        } else {
          res = ps;
        }

        if ( ! ( res = res.apply(p, obj) ) ) break;
        ret.push(res.value);
        ps = res;
      }

      if ( this.minimum > 0 && ret.length < this.minimum ) return undefined;

      return ps.setValue(ret);
    },

    function toString() {
      var str = 'repeat(' + this.SUPER();
      if ( this.delimiter ) str += ', ' + this.delimiter;
      if ( this.minimum   ) str += ', ' + this.minimum;
      str += ')';
      return str;
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Until',
  extends: 'foam.parse.ParserDecorator',

  documentation: 'Matches any characters until the terminating pattern.  Consumes and discards the terminating pattern when found. Fails if termination was never found.',

  methods: [
    function parse(ps, obj) {
      var ret = [];
      var p   = this.p;
      var res;

      // Try terminator before consuming each character.
      // This ordering lets eof() match at end-of-stream since
      // eof() succeeds when ps.valid is false. After the
      // terminator check, bail on EOF to prevent infinite loops.
      while ( true ) {
        if ( res = ps.apply(p, obj) ) return res.setValue(ret);
        if ( ! ps.valid ) return undefined;
        ret.push(ps.head);
        ps = ps.tail;
      }
    },

    function toString() {
      return 'until(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Until0',
  extends: 'foam.parse.ParserDecorator',

  documentation: 'Matches any characters until the terminating pattern without returning a value.  Consumes and discards the terminating pattern when found. Fails if termination was never found.',

  methods: [
    function parse(ps, obj) {
      var p   = this.p;
      var res;

      // Same ordering as Until: try terminator first so eof()
      // can match at end-of-stream, then bail on EOF.
      while ( true ) {
        if ( res = ps.apply(p, obj) ) return res.setValue(null);
        if ( ! ps.valid ) return undefined;
        ps = ps.tail;
      }
    },

    function toString() {
      return 'until0(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'UntilLiteral0',

  documentation: `Optimized version of Until0 for literal string terminators. Uses
String.indexOf() for O(n) native performance instead of per-character
parser invocation. Discards matched content (value is null) and consumes
the terminator — identical semantics to Until0 with a Literal parser.

Returned transparently by the until0() factory when given a String or
Literal argument. Users do not need to reference this class directly.`,

  properties: [
    {
      name: 's',
      class: 'Simple',
      documentation: 'The literal string to search for'
    }
  ],

  methods: [
    function parse(ps) {
      var str = ps.str[0];
      var idx = str.indexOf(this.s, ps.pos);

      if ( idx < 0 ) return undefined;

      // Jump past the terminator (consumes it, same as Until0)
      var target   = ps.cls_.create();
      target.str   = ps.str;
      target.pos   = idx + this.s.length;
      target.apply = ps.apply;
      return target.setValue(null);
    },

    function toString() {
      return 'until0("' + this.s + '")';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'UntilLiteral',

  documentation: `Optimized version of Until for literal string terminators. Uses
String.indexOf() to find the terminator in O(n) native time, then returns
the characters before it as an array — identical semantics to Until with a
Literal parser.

Returned transparently by the until() factory when given a String or
Literal argument. Users do not need to reference this class directly.`,

  properties: [
    {
      name: 's',
      class: 'Simple',
      documentation: 'The literal string to search for'
    }
  ],

  methods: [
    function parse(ps) {
      var str = ps.str[0];
      var idx = str.indexOf(this.s, ps.pos);

      if ( idx < 0 ) return undefined;

      // Collect characters before the terminator (matching Until's return format)
      var res = [];
      for ( var i = ps.pos ; i < idx ; i++ ) {
        res.push(str[i]);
      }

      // Position past the terminator (consumes it, same as Until)
      var target   = ps.cls_.create();
      target.str   = ps.str;
      target.pos   = idx + this.s.length;
      target.apply = ps.apply;
      return target.setValue(res);
    },

    function toString() {
      return 'until("' + this.s + '")';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Join',
  extends: 'foam.parse.ParserDecorator',

  documentation: 'Convenience decorator that joins the value returned by the delegate into a single string',

  methods: [
    function parse(ps, obj) {
      ps = ps.apply(this.p, obj);
      return ps ? ps.setValue(ps.value.join('')) : undefined;
    },

    function toString() {
      return 'join(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Plus',
  extends: 'foam.parse.Repeat',

  documentation: `Repeats matching to a parser property at least one time
    with an optional delimiter.`,

  properties: [
    ['minimum', 1]
  ],

  methods: [
    function toString() {
      var str = 'plus(' + this.p.toString();
      if ( this.delimiter ) str += ', ' + this.delimiter;
      str += ')';
      return str;
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Repeat0',
  extends: 'foam.parse.Repeat',

  documentation: `Repeats matching to a parser property,
    without returning a value. Useful for whitespace.
    Ex. 'repeat0(sym('white'))'`,

  methods: [
    function parse(ps, obj) {
      var p = this.p;
      var last;
      var delim = this.delimiter;
      var i = 0;

      while ( ps && i < this.maximum ) {
        last = ps;
        ps = ps.apply(p, obj);
        if ( ps ) i++;
        if ( delim && ps ) {
          ps = ps.apply(delim, obj) || ps;
        }
      }

      if ( this.minimum > 0 && i < this.minimum ) return undefined;
      return last;
    },

    function toString() {
      var str = 'repeat0(' + this.p.toString();
      if ( this.delimiter ) str += ', ' + this.delimiter;
      if ( this.minimum ) str += ', ' + this.minimum;
      str += ')';
      return str;
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Not',
  extends: 'foam.parse.ParserDecorator',

  documentation: `Ensures the leading char isn't the parser
    property specified. If not, attempts to parse with the
    else clause parser property. Useful for matching all but
    a particular character. Ex. 'not('"', anyChar())'`,

  properties: [
    {
      name: 'else',
      final: true,
      class: 'foam.parse.ParserProperty'
    }
  ],

  methods: [
    function parse(ps, obj) {
      return ps.apply(this.p, obj) ?
        undefined :
        (this.else ? ps.apply(this.else, obj) : ps);
    },

    function toString() {
      var str = 'not(' + this.SUPER();
      if ( this.else ) str += ', ' + this.else.toString();
      str += ')';
      return str;
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Peek',
  extends: 'foam.parse.ParserDecorator',

  documentation: "A parser which peeks ahead and succeeds if the delgate parses, but doesn't consume the input.",

  methods: [
    function parse(ps, obj) {
      return ps.apply(this.p, obj) ?
        ps   :
        null ;
    },

    function toString() {
      return 'peek(' + this.SUPER() + ')';
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'ParserWithAction',
  extends: 'foam.parse.ParserDecorator',

  constants: [
    {
      type: 'Object',
      name: 'NO_PARSE',
      factory: function() { return {}; }
    }
  ],

  properties: [
    'action'
  ],

  methods: [
    function parse(ps, obj) {
      ps = ps.apply(this.p, obj);
      if ( !!! ps ) return undefined;
      var ret = this.action(ps.value);
      return ret === foam.parse.ParserWithAction.NO_PARSE ?
        undefined :
        ps.setValue(ret);
    }
  ]
});

foam.CLASS({
  package: 'foam.parse',
  name: 'DebugParser',
  extends: 'foam.parse.ParserDecorator',

  methods: [
    function parse(ps, obj) {
      debugger;
      return ps.apply(this.p, obj);
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Symbol',
  implements: ['foam.parse.JSParser'],

  constants: { DEPTH: [0] },

  documentation: 'Parses based on the parser property named.',

  properties: [
    {
      name: 'name',
      final: true
    },
    {
      class: 'Boolean',
      name: 'debug'
    }
  ],

  methods: [
    function parse(ps, grammar) {
      var p = this.parser || ( this.parser = grammar.getSymbol(this.name) );
      if ( ! p ) {
        console.error('No symbol found for', this.name);
        return undefined;
      }
      if ( this.debug ) {
        try {
          console.log(' '.repeat(this.DEPTH[0]) + 'Call: ' + this.toString());
        } catch(x) {
        }
        this.DEPTH[0]++;
      }
      const ret = ps.apply(p, grammar);
      if ( this.debug ) {
        this.DEPTH[0]--;
        try {
          console.log(' '.repeat(this.DEPTH[0]) + 'Return: ' + this.toString() + ' =', ret ? ret.value : 'NO PARSE', ps.str[0].substring(ps.pos, ps.pos+20));
        } catch(x) {
        }
      }
      return ret;
    },

    function toString() { return 'sym("' + this.name + '")'; }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Parsers',

  requires: [
    'foam.parse.Alternate',
    'foam.parse.AnyChar',
    'foam.parse.Chars',
    'foam.parse.DebugParser',
    'foam.parse.Literal',
    'foam.parse.LiteralIC',
    'foam.parse.EOF',
    'foam.parse.Msg',
    'foam.parse.Not',
    'foam.parse.NotChars',
    'foam.parse.Optional',
    'foam.parse.Peek',
    'foam.parse.Plus',
    'foam.parse.Range',
    'foam.parse.Repeat',
    'foam.parse.Repeat0',
    'foam.parse.Sequence',
    'foam.parse.Sequence0',
    'foam.parse.Sequence1',
    'foam.parse.String',
    'foam.parse.StringPStream',
    'foam.parse.Substring',
    'foam.parse.Suggest',
    'foam.parse.Symbol',
    'foam.parse.Until',
    'foam.parse.Until0',
    'foam.parse.UntilLiteral',
    'foam.parse.UntilLiteral0',
    'foam.parse.Join',
    'foam.parse.ParserWithAction'
  ],

  axioms: [ foam.pattern.Singleton.create() ],

  methods: [
    function stringPStream(s) {
      // return this.StringPStream.create({str: s}); // Why doesn't this work?
      var ps = this.StringPStream.create();
      ps.setString(s);
      return ps;
    },

    function action(p, f) {
      return this.ParserWithAction.create({
        p: p,
        action: f
      });
    },

    function debug(p) {
      return this.DebugParser.create({
        p: p
      })
    },

    function cut(p) {
      // A parser decorator which destroys the input PStream if the delegate
      // succeeds. This is used so that memory can be freed, thus making parsing
      // long strings possible. The name comes from:
      // https://en.wikipedia.org/wiki/Cut_(logic_programming)
      return {
        parse: function(ps, obj) {
          var ret = p.parse(ps, obj);
          if ( ret ) {
            // TODO: there should be a detach() method on the PStream interface
            ps.instance_ = ps.apply = ps.str = ps.pos = undefined;
          }
          return ret;
        }
      };
    },

    function seq() {
      return this.Sequence.create({
        args: Array.from(arguments)
      });
    },

    function nChars(n) {
      // TODO: make a fixed size parser which does the same but more efficiently
      return this.str(this.repeat(this.anyChar(), null, n, n));
    },

    function rep(p, delim, min, max = Number.MAX_SAFE_INTEGER) {
      return this.Repeat.create({
        p:         p,
        minimum:   min || 0,
        maximum:   max,
        delimiter: delim
      });
    },

    function repeat(p, delim, min, max) { return this.rep(p, delim, min, max); },

    function rep0(p, delim, min, max = Number.MAX_SAFE_INTEGER) {
      return this.Repeat0.create({
        p: p,
        minimum: min || 0,
        maximum: max,
        delimiter: delim
      });
    },

    function repeat0(p, delim, min, max) { return this.rep0(p, delim, min, max); },

    function simpleAlt() {
      return this.Alternate.create({
        args: Array.from(arguments)
      });
    },

    function alt() {
      return this.Alternate.create({
        args: Array.from(arguments)
      });
    },

    function nop() {
      // A parser which always fails
      return this.alt();
    },

    function sym(name) {
      return this.Symbol.create({ name: name });
    },

    function seq1(n) {
      return this.Sequence1.create({
        n: n,
        args: Array.from(arguments).slice(1)
      });
    },

    function seq0() {
      return this.Sequence0.create({
        args: Array.from(arguments)
      });
    },

    function sug(p, s) {
      return this.Suggest.create({
        p: p,
        suggestion: s
      });
    },

    /**
     * Create a parser that attaches a message.
     * Message is collected when the parser succeeds (via apply callback).
     *
     * @param {Parser} p - The parser to wrap
     * @param {*} m - Message to attach (can be any value - string, object, etc.)
     * @returns {Msg} Parser decorator with message
     *
     * Usage in grammar:
     *   msg(eof(), 'File is empty')
     *   msg(sym('old'), { warning: 'Deprecated format' })
     */
    function msg(p, m) {
      return this.Msg.create({ p: p, message: m });
    },

    function until(p) {
      if ( typeof p === 'string' ) {
        return this.UntilLiteral.create({ s: p });
      }
      if ( foam.parse.Literal.isInstance(p) ) {
        return this.UntilLiteral.create({ s: p.s });
      }
      return this.Until.create({ p: p });
    },

    function until0(p) {
      if ( typeof p === 'string' ) {
        return this.UntilLiteral0.create({ s: p });
      }
      if ( foam.parse.Literal.isInstance(p) ) {
        return this.UntilLiteral0.create({ s: p.s });
      }
      return this.Until0.create({ p: p });
    },

    function join(p) {
      return this.Join.create({
        p: p
      });
    },

    function plus(p, delim) {
      return this.Plus.create({
        p: p,
        delimiter: delim
      });
    },

    function str(p) {
      return this.String.create({
        p: p
      });
    },

    function substring(p) {
      return this.Substring.create({
        p: p
      });
    },

    function range(a, b) {
      return this.Range.create({
        from: a,
        to: b
      });
    },

    function notChars(s) {
      return this.NotChars.create({
        string: s
      });
    },

    function chars(s) {
      return this.Chars.create({
        string: s
      });
    },

    function not(p, opt_else) {
      return this.Not.create({
        p: p,
        else: opt_else
      });
    },

    function peek(p) {
      return this.Peek.create({
        p: p
      });
    },

    function opt(p, opt_default) {
      return this.Optional.create({
        p: p,
        default: opt_default || null
      });
    },

    function optional(p, opt_default) { return this.opt(p, opt_default); },

    function lit(s, value) {
      return this.Literal.create({
        s: s,
        value: value
      });
    },

    function literal(s, value) { return this.lit(s, value); },

    function litIC(s, value) {
      return this.LiteralIC.create({
        s: s,
        value: value
      });
    },

    function literalIC(s, value) { return this.litIC(s, value); },

    function eof() {
      return this.EOF.create();
    },

    function anyChar() {
      return this.AnyChar.create();
    },

    function any() {
      return this.AnyChar.create();
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'PSymbol',

  documentation: 'Symbol definition, stored in Grammary.symbols array.',

  properties: ['name', 'parser']
});


foam.CLASS({
  package: 'foam.parse',
  name: 'Grammar',
  extends: 'foam.parse.AbstractParser',

  requires: [
    'foam.parse.StringPStream',
    'foam.parse.ParserWithAction',
    'foam.parse.Parsers'
  ],

  properties: [
    {
      class: 'FObjectArray',
      of: 'foam.parse.PSymbol',
      name: 'symbols',
      factory: function() {
        // Can be more easily set by defining a method named 'grammar'
        return foam.parse.Grammar.SYMBOLS.adapt.call(this, null, this.grammar);
      },
      adapt: function(_, o) {
        if ( Array.isArray(o) ) return o;

        if ( typeof o === 'function' ) {
          var args = o.toString().match(/\((.*?)\)/);
          if ( ! args ) {
            throw 'Could not parse arguments from parser factory function';
          }

          o = foam.Function.withArgs(o, this.Parsers.create(), this);
        }

        var a = [];
        for ( var key in o ) {
          a.push(foam.parse.PSymbol.create({
            name: key,
            parser: o[key]
          }));
        }
        return a;
      }
    },
    {
      name: 'symbolMap_',
      expression: function(symbols) {
        var m = {};
        for ( var i = 0 ; i < symbols.length ; i++ ) {
          if ( m[symbols[i].name] ) {
            console.error('Duplicate symbol found', symbols[i].name);
          }
          m[symbols[i].name] = symbols[i];
        }
        return m;
      }
    },
  ],

  methods: [
    function init() {
      this.SUPER();

      // Add semantic actions for any symbol where there is a method named: <sym>Action
      this.symbols.forEach(s => {
        var m = this[s.name + 'Action'];
        if ( m ) {
          this.addAction(s.name, m.bind(this));
        }
      });
    },

    function getSymParser(name) {
      // Let's you access individual symbol parsers as stand-alone parsers
      return {
        parse: ps => ps.apply(this.getSymbol(name), this),
        parseString: (str, __,opt_apply) => this.parseString(str, name, opt_apply),
        toString: () => name
      };
    },

    function parseString(str, opt_name, opt_apply) {
      opt_name = opt_name || 'START';

      var start = this.getSymbol(opt_name);
      foam.assert(start, 'No symbol found for', opt_name);

      var result = start.parse(this.StringPStream.create({apply: opt_apply, str: str}), this);
      return result && result.value;
    },

    function parse(ps, x, opt_name) {
      // Let's Grammar object be used directly as a parser
      opt_name = opt_name || 'START';
      var start = this.getSymbol(opt_name);
      foam.assert(start, 'No symbol found for', opt_name);
      return start.parse(ps, this);
    },

    function getLastError(str, opt_name, opt_apply) {
      opt_name = opt_name || 'START';
      var start = this.getSymbol(opt_name);

      var errorPs = foam.parse.ErrorReportingPStream.create();

      var ps = this.StringPStream.create({apply: opt_apply, str: str});

      errorPs.delegate = ps;

      var lastError;
      function report(ps, p, obj) {
        if ( ! lastError )
          lastError = [ps, p, obj];
        else if ( ps.compareTo(lastError[0]) > 0 )
          lastError = [ps, p, obj];
      }

      errorPs.report = report;

      errorPs.apply(start, this);

      if ( ! lastError ) return;

      // Determine valid characters
      var validChars = [];

      var trap = foam.parse.TrapPStream.create();

      var ps = foam.parse.StringPStream.create();
      for ( var i = 0 ; i <= 255 ; i++ ) {
        var str = String.fromCodePoint(i);
        ps.setString(str);
        trap.delegate = ps;
        try {
          trap.apply(lastError[1], lastError[2]);
        } catch ( e ) {
          if ( e === "trap" )
            validChars.push(str);
          else
            throw e;
        }
      }

      function toPrintable(s) {
        var ret = "";
        for ( var i = 0 ; i < s.length; i++ ) {
          var code = s.codePointAt(i);
          if ( code < 32 ) ret += "\\u" + code.toString(16);
          else ret += s[i];
        }
        return ret;
      }

      return "Unexpected character '" + lastError[0].head + "' at index: " +
        lastError[0].pos + ", Expected one of: [" +
        toPrintable(validChars.join(',')) + "], Text leading up to this was: " +
        lastError[0].getIntroString();
    },

    function getSymbol(name) {
      foam.assert(this.symbolMap_[name], "No symbol found for '", name, "'");

      return this.symbolMap_[name].parser;
    },

    function addSymbol(name, parser) {
      this.symbols.push(foam.parse.PSymbol.create({
        name: name, parser: parser
      }));
    },

    function addActions(map) {
      for ( var key in map ) {
        this.addAction(key, map[key]);
      }
      return this;
    },

    function addAction(name, action) {
      for ( var i = 0 ; i < this.symbols.length ; i++ ) {
        if ( this.symbols[i].name === name ) {
          this.symbols[i].parser = this.ParserWithAction.create({
            p: this.symbols[i].parser,
            action: action
          });
        }
      }

      // TODO(adamvy): Array property should help me here
      this.pub('propertyChange', 'symbols', this.slot('symbols'));
      return this;
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'GrammarAxiom',

  properties: [
    {
      class: 'String',
      name: 'name'
    },
    {
      class: 'String',
      name: 'language',
      value: 'foam.parse.Parsers'
    },
    {
      name: 'symbols'
    },
    {
      class: 'Array',
      name: 'actions',
      adapt: function(_, v) {
        if ( foam.Array.isInstance(v) ) return v;
        if ( foam.Object.isInstance(v) ) {
          var a = [];
          for ( var key in v ) {
            a.push({
              name: key,
              code: v[key]
            });
          }
          v = a;
        }
        return v;
      }
    },
    {
      class: 'Boolean',
      documentation: `When true, use foam.Function.withArgs() to evaluate
          symbols function in its original script closure context. Otherwise,
          use with(language) { eval(symbols()); }.`,
      name: 'withArgs'
    }
  ],

  methods: [
    function installInProto(proto) {
      var name  = this.name;
      var axiom = this;
      Object.defineProperty(proto, name, {
        get: function() {
          var g = this.getPrivate_(name);

          if ( ! g ) {
            this.setPrivate_(name, g = axiom.buildGrammar(this));
          }

          return this.getPrivate_(name);
        }
      });
    },
    function buildGrammar(obj) {
      var g = foam.lookup('foam.parse.Grammar').create(null, obj);

      var symbols;

      if ( typeof this.symbols == 'function' ) {
        var language = foam.lookup(this.language).create();
        if (this.withArgs) {
          symbols = foam.Function.withArgs(this.symbols, language);
        } else {
          with(foam.lookup(this.language).create()) {
            symbols = eval('(' + this.symbols.toString() + ')()');
          }
        }
      } else {
        symbols = this.symbols;
      }

      for ( var key in symbols ) {
        g.addSymbol(key, symbols[key]);
      }

      for ( var i = 0 ; i < this.actions.length ; i++ ) {
        g.addAction(this.actions[i].name, (this.actions[i].code || this.actions[i]).bind(obj));
      }

      return g;
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'ModelGrammarsRefinement',
  refines: 'foam.lang.Model',

  properties: [
    {
      class: 'AxiomArray',
      name: 'grammars',
      of: 'foam.parse.GrammarAxiom'
    }
  ]
});


foam.CLASS({
  package: 'foam.parse',
  name: 'ImperativeGrammar',
  extends: 'foam.parse.Grammar'
});
