package net.nanopay.iso8583.packager;

import net.nanopay.iso8583.AbstractISOPackager;
import net.nanopay.iso8583.ISOFieldPackager;
import net.nanopay.iso8583.type.*;

/**
 * ISO 8583:1987 packager
 */
public class ISO87Packager
  extends AbstractISOPackager
{
  public ISO87Packager() {
    super(new ISOFieldPackager[] {
      /* 000 */ new ISONumeric    (   4, "MESSAGE TYPE INDICATOR"),
      /* 001 */ new ISOBitMap     (  16, "BIT MAP"),
      /* 002 */ new ISOLLNumeric  (  19, "PAN - PRIMARY ACCOUNT NUMBER"),
      /* 003 */ new ISONumeric    (   6, "PROCESSING CODE"),
      /* 004 */ new ISONumeric    (  12, "AMOUNT, TRANSACTION"),
      /* 005 */ new ISONumeric    (  12, "AMOUNT, SETTLEMENT"),
      /* 006 */ new ISONumeric    (  12, "AMOUNT, CARDHOLDER BILLING"),
      /* 007 */ new ISONumeric    (  10, "TRANSMISSION DATE AND TIME"),
      /* 008 */ new ISONumeric    (   8, "AMOUNT, CARDHOLDER BILLING FEE"),
      /* 009 */ new ISONumeric    (   8, "CONVERSION RATE, SETTLEMENT"),
      /* 010 */ new ISONumeric    (   8, "CONVERSION RATE, CARDHOLDER BILLING"),
      /* 011 */ new ISONumeric    (   6, "SYSTEM TRACE AUDIT NUMBER"),
      /* 012 */ new ISONumeric    (   6, "TIME, LOCAL TRANSACTION"),
      /* 013 */ new ISONumeric    (   4, "DATE, LOCAL TRANSACTION"),
      /* 014 */ new ISONumeric    (   4, "DATE, EXPIRATION"),
      /* 015 */ new ISONumeric    (   4, "DATE, SETTLEMENT"),
      /* 016 */ new ISONumeric    (   4, "DATE, CONVERSION"),
      /* 017 */ new ISONumeric    (   4, "DATE, CAPTURE"),
      /* 018 */ new ISONumeric    (   4, "MERCHANTS TYPE"),
      /* 019 */ new ISONumeric    (   3, "ACQUIRING INSTITUTION COUNTRY CODE"),
      /* 020 */ new ISONumeric    (   3, "PAN EXTENDED COUNTRY CODE"),
      /* 021 */ new ISONumeric    (   3, "FORWARDING INSTITUTION COUNTRY CODE"),
      /* 022 */ new ISONumeric    (   3, "POINT OF SERVICE ENTRY MODE"),
      /* 023 */ new ISONumeric    (   3, "CARD SEQUENCE NUMBER"),
      /* 024 */ new ISONumeric    (   3, "NETWORK INTERNATIONAL IDENTIFIER"),
      /* 025 */ new ISONumeric    (   2, "POINT OF SERVICE CONDITION CODE"),
      /* 026 */ new ISONumeric    (   2, "POINT OF SERVICE PIN CAPTURE CODE"),
      /* 027 */ new ISONumeric    (   1, "AUTHORIZATION IDENTIFICATION RESP LEN"),
      /* 028 */ new ISOAmount     ( 1+8, "AMOUNT, TRANSACTION FEE"),
      /* 029 */ new ISOAmount     ( 1+8, "AMOUNT, SETTLEMENT FEE"),
      /* 030 */ new ISOAmount     ( 1+8, "AMOUNT, TRANSACTION PROCESSING FEE"),
      /* 031 */ new ISOAmount     ( 1+8, "AMOUNT, SETTLEMENT PROCESSING FEE"),
      /* 032 */ new ISOLLNumeric  (  11, "ACQUIRING INSTITUTION IDENT CODE"),
      /* 033 */ new ISOLLNumeric  (  11, "FORWARDING INSTITUTION IDENT CODE"),
      /* 034 */ new ISOLLChar     (  28, "PAN EXTENDED"),
      /* 035 */ new ISOLLNumeric  (  37, "TRACK 2 DATA"),
      /* 036 */ new ISOLLLChar    ( 104, "TRACK 3 DATA"),
      /* 037 */ new ISOChar       (  12, "RETRIEVAL REFERENCE NUMBER"),
      /* 038 */ new ISOChar       (   6, "AUTHORIZATION IDENTIFICATION RESPONSE"),
      /* 039 */ new ISOChar       (   2, "RESPONSE CODE"),
      /* 040 */ new ISOChar       (   3, "SERVICE RESTRICTION CODE"),
      /* 041 */ new ISOChar       (   8, "CARD ACCEPTOR TERMINAL IDENTIFICATION"),
      /* 042 */ new ISOChar       (  15, "CARD ACCEPTOR IDENTIFICATION CODE" ),
      /* 043 */ new ISOChar       (  40, "CARD ACCEPTOR NAME/LOCATION"),
      /* 044 */ new ISOLLChar     (  25, "ADDITIONAL RESPONSE DATA"),
      /* 045 */ new ISOLLChar     (  76, "TRACK 1 DATA"),
      /* 046 */ new ISOLLLChar    ( 999, "ADDITIONAL DATA - ISO"),
      /* 047 */ new ISOLLLChar    ( 999, "ADDITIONAL DATA - NATIONAL"),
      /* 048 */ new ISOLLLChar    ( 999, "ADDITIONAL DATA - PRIVATE"),
      /* 049 */ new ISOChar       (   3, "CURRENCY CODE, TRANSACTION"),
      /* 050 */ new ISOChar       (   3, "CURRENCY CODE, SETTLEMENT"),
      /* 051 */ new ISOChar       (   3, "CURRENCY CODE, CARDHOLDER BILLING"   ),
      /* 052 */ new ISOBinary     (   8, "PIN DATA"   ),
      /* 053 */ new ISONumeric    (  16, "SECURITY RELATED CONTROL INFORMATION"),
      /* 054 */ new ISOLLLChar    ( 120, "ADDITIONAL AMOUNTS"),
      /* 055 */ new ISOLLLChar    ( 999, "RESERVED ISO"),
      /* 056 */ new ISOLLLChar    ( 999, "RESERVED ISO"),
      /* 057 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL"),
      /* 058 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL"),
      /* 059 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL"),
      /* 060 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE"),
      /* 061 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE"),
      /* 062 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE"),
      /* 063 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE"),
      /* 064 */ new ISOBinary     (   8, "MESSAGE AUTHENTICATION CODE FIELD"),
      /* 065 */ new ISOBinary     (   1, "BITMAP, EXTENDED"),
      /* 066 */ new ISONumeric    (   1, "SETTLEMENT CODE"),
      /* 067 */ new ISONumeric    (   2, "EXTENDED PAYMENT CODE"),
      /* 068 */ new ISONumeric    (   3, "RECEIVING INSTITUTION COUNTRY CODE"),
      /* 069 */ new ISONumeric    (   3, "SETTLEMENT INSTITUTION COUNTRY CODE"),
      /* 070 */ new ISONumeric    (   3, "NETWORK MANAGEMENT INFORMATION CODE"),
      /* 071 */ new ISONumeric    (   4, "MESSAGE NUMBER"),
      /* 072 */ new ISONumeric    (   4, "MESSAGE NUMBER LAST"),
      /* 073 */ new ISONumeric    (   6, "DATE ACTION"),
      /* 074 */ new ISONumeric    (  10, "CREDITS NUMBER"),
      /* 075 */ new ISONumeric    (  10, "CREDITS REVERSAL NUMBER"),
      /* 076 */ new ISONumeric    (  10, "DEBITS NUMBER"),
      /* 077 */ new ISONumeric    (  10, "DEBITS REVERSAL NUMBER"),
      /* 078 */ new ISONumeric    (  10, "TRANSFER NUMBER"),
      /* 079 */ new ISONumeric    (  10, "TRANSFER REVERSAL NUMBER"),
      /* 080 */ new ISONumeric    (  10, "INQUIRIES NUMBER"),
      /* 081 */ new ISONumeric    (  10, "AUTHORIZATION NUMBER"),
      /* 082 */ new ISONumeric    (  12, "CREDITS, PROCESSING FEE AMOUNT"),
      /* 083 */ new ISONumeric    (  12, "CREDITS, TRANSACTION FEE AMOUNT"),
      /* 084 */ new ISONumeric    (  12, "DEBITS, PROCESSING FEE AMOUNT"),
      /* 085 */ new ISONumeric    (  12, "DEBITS, TRANSACTION FEE AMOUNT"),
      /* 086 */ new ISONumeric    (  16, "CREDITS, AMOUNT"),
      /* 087 */ new ISONumeric    (  16, "CREDITS, REVERSAL AMOUNT"),
      /* 088 */ new ISONumeric    (  16, "DEBITS, AMOUNT"),
      /* 089 */ new ISONumeric    (  16, "DEBITS, REVERSAL AMOUNT"),
      /* 090 */ new ISONumeric    (  42, "ORIGINAL DATA ELEMENTS"),
      /* 091 */ new ISOChar       (   1, "FILE UPDATE CODE"),
      /* 092 */ new ISOChar       (   2, "FILE SECURITY CODE"),
      /* 093 */ new ISOChar       (   6, "RESPONSE INDICATOR"),
      /* 094 */ new ISOChar       (   7, "SERVICE INDICATOR"),
      /* 095 */ new ISOChar       (  42, "REPLACEMENT AMOUNTS"),
      /* 096 */ new ISOBinary     (  16, "MESSAGE SECURITY CODE"),
      /* 097 */ new ISOAmount     (1+16, "AMOUNT, NET SETTLEMENT"),
      /* 098 */ new ISOChar       (  25, "PAYEE"),
      /* 099 */ new ISOLLNumeric  (  11, "SETTLEMENT INSTITUTION IDENT CODE"),
      /* 100 */ new ISOLLNumeric  (  11, "RECEIVING INSTITUTION IDENT CODE"),
      /* 101 */ new ISOLLChar     (  17, "FILE NAME"),
      /* 102 */ new ISOLLChar     (  28, "ACCOUNT IDENTIFICATION 1"),
      /* 103 */ new ISOLLChar     (  28, "ACCOUNT IDENTIFICATION 2"),
      /* 104 */ new ISOLLLChar    ( 100, "TRANSACTION DESCRIPTION"),
      /* 105 */ new ISOLLLChar    ( 999, "RESERVED ISO USE"),
      /* 106 */ new ISOLLLChar    ( 999, "RESERVED ISO USE"),
      /* 107 */ new ISOLLLChar    ( 999, "RESERVED ISO USE"),
      /* 108 */ new ISOLLLChar    ( 999, "RESERVED ISO USE"),
      /* 109 */ new ISOLLLChar    ( 999, "RESERVED ISO USE"),
      /* 110 */ new ISOLLLChar    ( 999, "RESERVED ISO USE"),
      /* 111 */ new ISOLLLChar    ( 999, "RESERVED ISO USE"),
      /* 112 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"),
      /* 113 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"),
      /* 114 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"   ),
      /* 115 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"),
      /* 116 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"  ),
      /* 117 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"),
      /* 118 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"),
      /* 119 */ new ISOLLLChar    ( 999, "RESERVED NATIONAL USE"),
      /* 120 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 121 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 122 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 123 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 124 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 125 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 126 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 127 */ new ISOLLLChar    ( 999, "RESERVED PRIVATE USE"),
      /* 128 */ new ISOBinary     (   8, "MAC 2"),
    });
  }
}
