package net.nanopay.iso8583.packager;

import net.nanopay.iso8583.AbstractISOPackager;
import net.nanopay.iso8583.ISOFieldPackager;
import net.nanopay.iso8583.type.*;

public class ISO87Packager
  extends AbstractISOPackager
{
  public ISO87Packager() {
    super(new ISOFieldPackager[] {
      new ISONumeric    (  4, "MESSAGE TYPE INDICATOR"),
      new ISOBitMap     ( 16, "BIT MAP"),
      new ISOLLNumeric  ( 19, "PAN - PRIMARY ACCOUNT NUMBER"),
      new ISONumeric    (  6, "PROCESSING CODE"),
      new ISONumeric    ( 12, "AMOUNT, TRANSACTION"),
      new ISONumeric    ( 12, "AMOUNT, SETTLEMENT"),
      new ISONumeric    ( 12, "AMOUNT, CARDHOLDER BILLING"),
      new ISONumeric    ( 10, "TRANSMISSION DATE AND TIME"),
      new ISONumeric    (  8, "AMOUNT, CARDHOLDER BILLING FEE"),
      new ISONumeric    (  8, "CONVERSION RATE, SETTLEMENT"),
      new ISONumeric    (  8, "CONVERSION RATE, CARDHOLDER BILLING"),
      new ISONumeric    (  6, "SYSTEM TRACE AUDIT NUMBER"),
      new ISONumeric    (  6, "TIME, LOCAL TRANSACTION"),
      new ISONumeric    (  4, "DATE, LOCAL TRANSACTION"),
      new ISONumeric    (  4, "DATE, EXPIRATION"),
      new ISONumeric    (  4, "DATE, SETTLEMENT"),
      new ISONumeric    (  4, "DATE, CONVERSION"),
      new ISONumeric    (  4, "DATE, CAPTURE"),
      new ISONumeric    (  4, "MERCHANTS TYPE"),
      new ISONumeric    (  3, "ACQUIRING INSTITUTION COUNTRY CODE"),
      new ISONumeric    (  3, "PAN EXTENDED COUNTRY CODE"),
      new ISONumeric    (  3, "FORWARDING INSTITUTION COUNTRY CODE"),
      new ISONumeric    (  3, "POINT OF SERVICE ENTRY MODE"),
      new ISONumeric    (  3, "CARD SEQUENCE NUMBER"),
      new ISONumeric    (  3, "NETWORK INTERNATIONAL IDENTIFIER"),
      new ISONumeric    (  2, "POINT OF SERVICE CONDITION CODE"),
      new ISONumeric    (  2, "POINT OF SERVICE PIN CAPTURE CODE"),
      new ISONumeric    (  1, "AUTHORIZATION IDENTIFICATION RESP LEN"),
      new ISOAmount     (  9, "AMOUNT, TRANSACTION FEE"),
      new ISOAmount     (  9, "AMOUNT, SETTLEMENT FEE"),
      new ISOAmount     (  9, "AMOUNT, TRANSACTION PROCESSING FEE"),
      new ISOAmount     (  9, "AMOUNT, SETTLEMENT PROCESSING FEE"),
      new ISOLLNumeric  ( 11, "ACQUIRING INSTITUTION IDENT CODE"),
      new ISOLLNumeric  ( 11, "FORWARDING INSTITUTION IDENT CODE"),
      new ISOLLChar     ( 28, "PAN EXTENDED"),
      new ISOLLNumeric  ( 37, "TRACK 2 DATA"),
      new ISOLLLChar    (104, "TRACK 3 DATA"),
      new ISOChar       ( 12, "RETRIEVAL REFERENCE NUMBER"),
      new ISOChar       (  6, "AUTHORIZATION IDENTIFICATION RESPONSE"),
      new ISOChar       (  2, "RESPONSE CODE"),
      new ISOChar       (  3, "SERVICE RESTRICTION CODE"),
      new ISOChar       (  8, "CARD ACCEPTOR TERMINAL IDENTIFICATION"),
      new ISOChar       ( 15, "CARD ACCEPTOR IDENTIFICATION CODE" ),
      new ISOChar       ( 40, "CARD ACCEPTOR NAME/LOCATION"),
      new ISOLLChar     ( 25, "ADDITIONAL RESPONSE DATA"),
      new ISOLLChar     ( 76, "TRACK 1 DATA"),
      new ISOLLLChar    (999, "ADDITIONAL DATA - ISO"),
      new ISOLLLChar    (999, "ADDITIONAL DATA - NATIONAL"),
      new ISOLLLChar    (999, "ADDITIONAL DATA - PRIVATE"),
      new ISOChar       (  3, "CURRENCY CODE, TRANSACTION"),
      new ISOChar       (  3, "CURRENCY CODE, SETTLEMENT"),
      new ISOChar       (  3, "CURRENCY CODE, CARDHOLDER BILLING"   ),
      new ISOBinary     (  8, "PIN DATA"   ),
      new ISONumeric    ( 16, "SECURITY RELATED CONTROL INFORMATION"),
      new ISOLLLChar    (120, "ADDITIONAL AMOUNTS"),
      new ISOLLLChar    (999, "RESERVED ISO"),
      new ISOLLLChar    (999, "RESERVED ISO"),
      new ISOLLLChar    (999, "RESERVED NATIONAL"),
      new ISOLLLChar    (999, "RESERVED NATIONAL"),
      new ISOLLLChar    (999, "RESERVED NATIONAL"),
      new ISOLLLChar    (999, "RESERVED PRIVATE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE"),
      new ISOBinary     (  8, "MESSAGE AUTHENTICATION CODE FIELD"),
      new ISOBinary     (  1, "BITMAP, EXTENDED"),
      new ISONumeric    (  1, "SETTLEMENT CODE"),
      new ISONumeric    (  2, "EXTENDED PAYMENT CODE"),
      new ISONumeric    (  3, "RECEIVING INSTITUTION COUNTRY CODE"),
      new ISONumeric    (  3, "SETTLEMENT INSTITUTION COUNTRY CODE"),
      new ISONumeric    (  3, "NETWORK MANAGEMENT INFORMATION CODE"),
      new ISONumeric    (  4, "MESSAGE NUMBER"),
      new ISONumeric    (  4, "MESSAGE NUMBER LAST"),
      new ISONumeric    (  6, "DATE ACTION"),
      new ISONumeric    ( 10, "CREDITS NUMBER"),
      new ISONumeric    ( 10, "CREDITS REVERSAL NUMBER"),
      new ISONumeric    ( 10, "DEBITS NUMBER"),
      new ISONumeric    ( 10, "DEBITS REVERSAL NUMBER"),
      new ISONumeric    ( 10, "TRANSFER NUMBER"),
      new ISONumeric    ( 10, "TRANSFER REVERSAL NUMBER"),
      new ISONumeric    ( 10, "INQUIRIES NUMBER"),
      new ISONumeric    ( 10, "AUTHORIZATION NUMBER"),
      new ISONumeric    ( 12, "CREDITS, PROCESSING FEE AMOUNT"),
      new ISONumeric    ( 12, "CREDITS, TRANSACTION FEE AMOUNT"),
      new ISONumeric    ( 12, "DEBITS, PROCESSING FEE AMOUNT"),
      new ISONumeric    ( 12, "DEBITS, TRANSACTION FEE AMOUNT"),
      new ISONumeric    ( 16, "CREDITS, AMOUNT"),
      new ISONumeric    ( 16, "CREDITS, REVERSAL AMOUNT"),
      new ISONumeric    ( 16, "DEBITS, AMOUNT"),
      new ISONumeric    ( 16, "DEBITS, REVERSAL AMOUNT"),
      new ISONumeric    ( 42, "ORIGINAL DATA ELEMENTS"),
      new ISOChar       (  1, "FILE UPDATE CODE"),
      new ISOChar       (  2, "FILE SECURITY CODE"),
      new ISOChar       (  6, "RESPONSE INDICATOR"),
      new ISOChar       (  7, "SERVICE INDICATOR"),
      new ISOChar       ( 42, "REPLACEMENT AMOUNTS"),
      new ISOBinary     ( 16, "MESSAGE SECURITY CODE"),
      new ISOAmount     ( 17, "AMOUNT, NET SETTLEMENT"),
      new ISOChar       ( 25, "PAYEE"),
      new ISOLLNumeric  ( 11, "SETTLEMENT INSTITUTION IDENT CODE"),
      new ISOLLNumeric  ( 11, "RECEIVING INSTITUTION IDENT CODE"),
      new ISOLLChar     ( 17, "FILE NAME"),
      new ISOLLChar     ( 28, "ACCOUNT IDENTIFICATION 1"),
      new ISOLLChar     ( 28, "ACCOUNT IDENTIFICATION 2"),
      new ISOLLLChar    (100, "TRANSACTION DESCRIPTION"),
      new ISOLLLChar    (999, "RESERVED ISO USE"),
      new ISOLLLChar    (999, "RESERVED ISO USE"),
      new ISOLLLChar    (999, "RESERVED ISO USE"),
      new ISOLLLChar    (999, "RESERVED ISO USE"),
      new ISOLLLChar    (999, "RESERVED ISO USE"),
      new ISOLLLChar    (999, "RESERVED ISO USE"),
      new ISOLLLChar    (999, "RESERVED ISO USE"),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"   ),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"  ),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"),
      new ISOLLLChar    (999, "RESERVED NATIONAL USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOLLLChar    (999, "RESERVED PRIVATE USE"),
      new ISOBinary     (  8, "MAC 2"),
    });
  }
}
