package net.nanopay.iso8583.packager;

import net.nanopay.iso8583.AbstractISOPackager;
import net.nanopay.iso8583.ISOFieldPackager;
import net.nanopay.iso8583.type.*;

public class ISO87Packager
  extends AbstractISOPackager
{
  public ISO87Packager() {
    super(new ISOFieldPackager[] {
      new ISONumericField   (  4, "MESSAGE TYPE INDICATOR"),
      new ISOBitMapField    ( 16, "BIT MAP"),
      new ISOLLNumericField ( 19, "PAN - PRIMARY ACCOUNT NUMBER"),
      new ISONumericField   (  6, "PROCESSING CODE"),
      new ISONumericField   ( 12, "AMOUNT, TRANSACTION"),
      new ISONumericField   ( 12, "AMOUNT, SETTLEMENT"),
      new ISONumericField   ( 12, "AMOUNT, CARDHOLDER BILLING"),
      new ISONumericField   ( 10, "TRANSMISSION DATE AND TIME"),
      new ISONumericField   (  8, "AMOUNT, CARDHOLDER BILLING FEE"),
      new ISONumericField   (  8, "CONVERSION RATE, SETTLEMENT"),
      new ISONumericField   (  8, "CONVERSION RATE, CARDHOLDER BILLING"),
      new ISONumericField   (  6, "SYSTEM TRACE AUDIT NUMBER"),
      new ISONumericField   (  6, "TIME, LOCAL TRANSACTION"),
      new ISONumericField   (  4, "DATE, LOCAL TRANSACTION"),
      new ISONumericField   (  4, "DATE, EXPIRATION"),
      new ISONumericField   (  4, "DATE, SETTLEMENT"),
      new ISONumericField   (  4, "DATE, CONVERSION"),
      new ISONumericField   (  4, "DATE, CAPTURE"),
      new ISONumericField   (  4, "MERCHANTS TYPE"),
      new ISONumericField   (  3, "ACQUIRING INSTITUTION COUNTRY CODE"),
      new ISONumericField   (  3, "PAN EXTENDED COUNTRY CODE"),
      new ISONumericField   (  3, "FORWARDING INSTITUTION COUNTRY CODE"),
      new ISONumericField   (  3, "POINT OF SERVICE ENTRY MODE"),
      new ISONumericField   (  3, "CARD SEQUENCE NUMBER"),
      new ISONumericField   (  3, "NETWORK INTERNATIONAL IDENTIFIER"),
      new ISONumericField   (  2, "POINT OF SERVICE CONDITION CODE"),
      new ISONumericField   (  2, "POINT OF SERVICE PIN CAPTURE CODE"),
      new ISONumericField   (  1, "AUTHORIZATION IDENTIFICATION RESP LEN"),
      new ISOAmountField    (  9, "AMOUNT, TRANSACTION FEE"),
      new ISOAmountField    (  9, "AMOUNT, SETTLEMENT FEE"),
      new ISOAmountField    (  9, "AMOUNT, TRANSACTION PROCESSING FEE"),
      new ISOAmountField    (  9, "AMOUNT, SETTLEMENT PROCESSING FEE"),
      new ISOLLNumericField ( 11, "ACQUIRING INSTITUTION IDENT CODE"),
      new ISOLLNumericField ( 11, "FORWARDING INSTITUTION IDENT CODE"),
      new ISOLLCharField    ( 28, "PAN EXTENDED"),
      new ISOLLNumericField ( 37, "TRACK 2 DATA"),
      new ISOLLLCharField   (104, "TRACK 3 DATA"),
      new ISOCharField      ( 12, "RETRIEVAL REFERENCE NUMBER"),
      new ISOCharField      (  6, "AUTHORIZATION IDENTIFICATION RESPONSE"),
      new ISOCharField      (  2, "RESPONSE CODE"),
      new ISOCharField      (  3, "SERVICE RESTRICTION CODE"),
      new ISOCharField      (  8, "CARD ACCEPTOR TERMINAL IDENTIFICATION"),
      new ISOCharField      ( 15, "CARD ACCEPTOR IDENTIFICATION CODE" ),
      new ISOCharField      ( 40, "CARD ACCEPTOR NAME/LOCATION"),
      new ISOLLCharField    ( 25, "ADDITIONAL RESPONSE DATA"),
      new ISOLLCharField    ( 76, "TRACK 1 DATA"),
      new ISOLLLCharField   (999, "ADDITIONAL DATA - ISO"),
      new ISOLLLCharField   (999, "ADDITIONAL DATA - NATIONAL"),
      new ISOLLLCharField   (999, "ADDITIONAL DATA - PRIVATE"),
      new ISOCharField      (  3, "CURRENCY CODE, TRANSACTION"),
      new ISOCharField      (  3, "CURRENCY CODE, SETTLEMENT"),
      new ISOCharField      (  3, "CURRENCY CODE, CARDHOLDER BILLING"   ),
      new ISOBinaryField    (  8, "PIN DATA"   ),
      new ISONumericField   ( 16, "SECURITY RELATED CONTROL INFORMATION"),
      new ISOLLLCharField   (120, "ADDITIONAL AMOUNTS"),
      new ISOLLLCharField   (999, "RESERVED ISO"),
      new ISOLLLCharField   (999, "RESERVED ISO"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE"),
      new ISOBinaryField    (  8, "MESSAGE AUTHENTICATION CODE FIELD"),
      new ISOBinaryField    (  1, "BITMAP, EXTENDED"),
      new ISONumericField   (  1, "SETTLEMENT CODE"),
      new ISONumericField   (  2, "EXTENDED PAYMENT CODE"),
      new ISONumericField   (  3, "RECEIVING INSTITUTION COUNTRY CODE"),
      new ISONumericField   (  3, "SETTLEMENT INSTITUTION COUNTRY CODE"),
      new ISONumericField   (  3, "NETWORK MANAGEMENT INFORMATION CODE"),
      new ISONumericField   (  4, "MESSAGE NUMBER"),
      new ISONumericField   (  4, "MESSAGE NUMBER LAST"),
      new ISONumericField   (  6, "DATE ACTION"),
      new ISONumericField   ( 10, "CREDITS NUMBER"),
      new ISONumericField   ( 10, "CREDITS REVERSAL NUMBER"),
      new ISONumericField   ( 10, "DEBITS NUMBER"),
      new ISONumericField   ( 10, "DEBITS REVERSAL NUMBER"),
      new ISONumericField   ( 10, "TRANSFER NUMBER"),
      new ISONumericField   ( 10, "TRANSFER REVERSAL NUMBER"),
      new ISONumericField   ( 10, "INQUIRIES NUMBER"),
      new ISONumericField   ( 10, "AUTHORIZATION NUMBER"),
      new ISONumericField   ( 12, "CREDITS, PROCESSING FEE AMOUNT"),
      new ISONumericField   ( 12, "CREDITS, TRANSACTION FEE AMOUNT"),
      new ISONumericField   ( 12, "DEBITS, PROCESSING FEE AMOUNT"),
      new ISONumericField   ( 12, "DEBITS, TRANSACTION FEE AMOUNT"),
      new ISONumericField   ( 16, "CREDITS, AMOUNT"),
      new ISONumericField   ( 16, "CREDITS, REVERSAL AMOUNT"),
      new ISONumericField   ( 16, "DEBITS, AMOUNT"),
      new ISONumericField   ( 16, "DEBITS, REVERSAL AMOUNT"),
      new ISONumericField   ( 42, "ORIGINAL DATA ELEMENTS"),
      new ISOCharField      (  1, "FILE UPDATE CODE"),
      new ISOCharField      (  2, "FILE SECURITY CODE"),
      new ISOCharField      (  6, "RESPONSE INDICATOR"),
      new ISOCharField      (  7, "SERVICE INDICATOR"),
      new ISOCharField      ( 42, "REPLACEMENT AMOUNTS"),
      new ISOBinaryField    ( 16, "MESSAGE SECURITY CODE"),
      new ISOAmountField    ( 17, "AMOUNT, NET SETTLEMENT"),
      new ISOCharField      ( 25, "PAYEE"),
      new ISOLLNumericField ( 11, "SETTLEMENT INSTITUTION IDENT CODE"),
      new ISOLLNumericField ( 11, "RECEIVING INSTITUTION IDENT CODE"),
      new ISOLLCharField    ( 17, "FILE NAME"),
      new ISOLLCharField    ( 28, "ACCOUNT IDENTIFICATION 1"),
      new ISOLLCharField    ( 28, "ACCOUNT IDENTIFICATION 2"),
      new ISOLLLCharField   (100, "TRANSACTION DESCRIPTION"),
      new ISOLLLCharField   (999, "RESERVED ISO USE"),
      new ISOLLLCharField   (999, "RESERVED ISO USE"),
      new ISOLLLCharField   (999, "RESERVED ISO USE"),
      new ISOLLLCharField   (999, "RESERVED ISO USE"),
      new ISOLLLCharField   (999, "RESERVED ISO USE"),
      new ISOLLLCharField   (999, "RESERVED ISO USE"),
      new ISOLLLCharField   (999, "RESERVED ISO USE"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"   ),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"  ),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"),
      new ISOLLLCharField   (999, "RESERVED NATIONAL USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOLLLCharField   (999, "RESERVED PRIVATE USE"),
      new ISOBinaryField    (  8, "MAC 2"),
    });
  }
}
