package net.nanopay.iso8583.packager;

import net.nanopay.iso8583.AbstractISOPackager;
import net.nanopay.iso8583.ISOFieldPackager;
import net.nanopay.iso8583.type.*;

public class ISO93Packager
  extends AbstractISOPackager
{
  public ISO93Packager() {
    super(new ISOFieldPackager[] {
      new ISONumeric    (   4, "Message Type Indicator"),
      new ISOBitMap     (  16, "Bitmap"),
      new ISOLLNumeric  (  19, "Primary Account number"),
      new ISONumeric    (   6, "Processing Code"),
      new ISONumeric    (  12, "Amount, Transaction"),
      new ISONumeric    (  12, "Amount, Reconciliation"),
      new ISONumeric    (  12, "Amount, Cardholder billing"),
      new ISONumeric    (  10, "Date and time, transmission"),
      new ISONumeric    (   8, "Amount, Cardholder billing fee"),
      new ISONumeric    (   8, "Conversion rate, Reconciliation"),
      new ISONumeric    (   8, "Conversion rate, Cardholder billing"),
      new ISONumeric    (   6, "Systems trace audit number"),
      new ISONumeric    (  12, "Date and time, Local transaction"),
      new ISONumeric    (   4, "Date, Effective"),
      new ISONumeric    (   4, "Date, Expiration"),
      new ISONumeric    (   6, "Date, Settlement"),
      new ISONumeric    (   4, "Date, Conversion"),
      new ISONumeric    (   4, "Date, Capture"),
      new ISONumeric    (   4, "Merchant type"),
      new ISONumeric    (   3, "Country code, Acquiring institution"),
      new ISONumeric    (   3, "Country code, Primary account number"),
      new ISONumeric    (   3, "Country code, Forwarding institution"),
      new ISOChar       (  12, "Point of service data code"),
      new ISONumeric    (   3, "Card sequence number"),
      new ISONumeric    (   3, "Function code"),
      new ISONumeric    (   4, "Message reason code"),
      new ISONumeric    (   4, "Card acceptor business code"),
      new ISONumeric    (   1, "Approval code length"),
      new ISONumeric    (   6, "Date, Reconciliation"),
      new ISONumeric    (   3, "Reconciliation indicator"),
      new ISONumeric    (  24, "Amounts, original"),
      new ISOLLChar     (  99, "Acquirer reference data"),
      new ISOLLNumeric  (  11, "Acquirer institution identification code"),
      new ISOLLNumeric  (  11, "Forwarding institution identification code"),
      new ISOLLChar     (  28, "Primary account number, extended"),
      new ISOLLChar     (  37, "Track 2 data"),
      new ISOLLLChar    ( 104, "Track 3 data"),
      new ISOChar       (  12, "Retrieval reference number"),
      new ISOChar       (   6, "Approval code"),
      new ISONumeric    (   3, "Action code"),
      new ISONumeric    (   3, "Service code"),
      new ISOChar       (   8, "Card acceptor terminal identification"),
      new ISOChar       (  15, "Card acceptor identification code"),
      new ISOLLChar     (  99, "Card acceptor name/location"),
      new ISOLLChar     (  99, "Additional response data"),
      new ISOLLChar     (  76, "Track 1 data"),
      new ISOLLLChar    ( 204, "Amounts, Fees"),
      new ISOLLLChar    ( 999, "Additional data - national"),
      new ISOLLLChar    ( 999, "Additional data - private"),
      new ISOChar       (   3, "Currency code, Transaction"),
      new ISOChar       (   3, "Currency code, Reconciliation"),
      new ISOChar       (   3, "Currency code, Cardholder billing"),
      new ISOBinary     (   8, "Personal identification number (PIN) data"),
      new ISOLLBinary   (  48, "Security related control information"),
      new ISOLLLChar    ( 120, "Amounts, additional"),
      new ISOLLLBinary  ( 255, "IC card system related data"),
      new ISOLLNumeric  (  35, "Original data elements"),
      new ISONumeric    (   3, "Authorization life cycle code"),
      new ISOLLNumeric  (  11, "Authorizing agent institution Id Code"),
      new ISOLLLChar    ( 999, "Transport data"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for private use"),
      new ISOLLLChar    ( 999, "Reserved for private use"),
      new ISOBinary     (   8, "Message authentication code field"),
      new ISOBinary     (   8, "Reserved for ISO use"),
      new ISOLLLChar    ( 204, "Amounts, original fees"),
      new ISONumeric    (   2, "Extended payment data"),
      new ISONumeric    (   3, "Country code, receiving institution"),
      new ISONumeric    (   3, "Country code, settlement institution"),
      new ISONumeric    (   3, "Country code, authorizing agent Inst."),
      new ISONumeric    (   8, "Message number"),
      new ISOLLLChar    ( 999, "Data record"),
      new ISONumeric    (   6, "Date, action"),
      new ISONumeric    (  10, "Credits, number"),
      new ISONumeric    (  10, "Credits, reversal number"),
      new ISONumeric    (  10, "Debits, number"),
      new ISONumeric    (  10, "Debits, reversal number"),
      new ISONumeric    (  10, "Transfer, number"),
      new ISONumeric    (  10, "Transfer, reversal number"),
      new ISONumeric    (  10, "Inquiries, number"),
      new ISONumeric    (  10, "Authorizations, number"),
      new ISONumeric    (  10, "Inquiries, reversal number"),
      new ISONumeric    (  10, "Payments, number"),
      new ISONumeric    (  10, "Payments, reversal number"),
      new ISONumeric    (  10, "Fee collections, number"),
      new ISONumeric    (  16, "Credits, amount"),
      new ISONumeric    (  16, "Credits, reversal amount"),
      new ISONumeric    (  16, "Debits, amount"),
      new ISONumeric    (  16, "Debits, reversal amount"),
      new ISONumeric    (  10, "Authorizations, reversal number"),
      new ISONumeric    (   3, "Country code, transaction Dest. Inst."),
      new ISONumeric    (   3, "Country code, transaction Orig. Inst."),
      new ISOLLNumeric  (  11, "Transaction Dest. Inst. Id code"),
      new ISOLLNumeric  (  11, "Transaction Orig. Inst. Id code"),
      new ISOLLChar     (  99, "Card issuer reference data"),
      new ISOLLLBinary  ( 999, "Key management data"),
      new ISOAmount     (1+16, "Amount, Net reconciliation"),
      new ISOChar       (  25, "Payee"),
      new ISOLLChar     (  11, "Settlement institution Id code"),
      new ISOLLNumeric  (  11, "Receiving institution Id code"),
      new ISOLLChar     (  17, "File name"),
      new ISOLLChar     (  28, "Account identification 1"),
      new ISOLLChar     (  28, "Account identification 2"),
      new ISOLLLChar    ( 100, "Transaction description"),
      new ISONumeric    (  16, "Credits, Chargeback amount"),
      new ISONumeric    (  16, "Debits, Chargeback amount"),
      new ISONumeric    (  10, "Credits, Chargeback number"),
      new ISONumeric    (  10, "Debits, Chargeback number"),
      new ISOLLChar     (  84, "Credits, Fee amounts"),
      new ISOLLChar     (  84, "Debits, Fee amounts"),
      new ISOLLLChar    ( 999, "Reserved for ISO use"),
      new ISOLLLChar    ( 999, "Reserved for ISO use"),
      new ISOLLLChar    ( 999, "Reserved for ISO use"),
      new ISOLLLChar    ( 999, "Reserved for ISO use"),
      new ISOLLLChar    ( 999, "Reserved for ISO use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for national use"),
      new ISOLLLChar    ( 999, "Reserved for private use"),
      new ISOLLLChar    ( 999, "Reserved for private use"),
      new ISOLLLChar    ( 999, "Reserved for private use"),
      new ISOLLLChar    ( 999, "Reserved for private use"),
      new ISOLLLChar    ( 999, "Reserved for private use"),
      new ISOBinary     (   8, "Message authentication code field")
    });
  }
}
