package net.nanopay.iso8583.packager;

import net.nanopay.iso8583.AbstractISOPackager;
import net.nanopay.iso8583.ISOFieldPackager;
import net.nanopay.iso8583.type.*;

public class ISO93Packager
  extends AbstractISOPackager
{
  public ISO93Packager() {
    super(new ISOFieldPackager[] {
      new ISONumericField   (   4, "Message Type Indicator"),
      new ISOBitMapField    (  16, "Bitmap"),
      new ISOLLNumericField (  19, "Primary Account number"),
      new ISONumericField   (   6, "Processing Code"),
      new ISONumericField   (  12, "Amount, Transaction"),
      new ISONumericField   (  12, "Amount, Reconciliation"),
      new ISONumericField   (  12, "Amount, Cardholder billing"),
      new ISONumericField   (  10, "Date and time, transmission"),
      new ISONumericField   (   8, "Amount, Cardholder billing fee"),
      new ISONumericField   (   8, "Conversion rate, Reconciliation"),
      new ISONumericField   (   8, "Conversion rate, Cardholder billing"),
      new ISONumericField   (   6, "Systems trace audit number"),
      new ISONumericField   (  12, "Date and time, Local transaction"),
      new ISONumericField   (   4, "Date, Effective"),
      new ISONumericField   (   4, "Date, Expiration"),
      new ISONumericField   (   6, "Date, Settlement"),
      new ISONumericField   (   4, "Date, Conversion"),
      new ISONumericField   (   4, "Date, Capture"),
      new ISONumericField   (   4, "Merchant type"),
      new ISONumericField   (   3, "Country code, Acquiring institution"),
      new ISONumericField   (   3, "Country code, Primary account number"),
      new ISONumericField   (   3, "Country code, Forwarding institution"),
      new ISOCharField      (  12, "Point of service data code"),
      new ISONumericField   (   3, "Card sequence number"),
      new ISONumericField   (   3, "Function code"),
      new ISONumericField   (   4, "Message reason code"),
      new ISONumericField   (   4, "Card acceptor business code"),
      new ISONumericField   (   1, "Approval code length"),
      new ISONumericField   (   6, "Date, Reconciliation"),
      new ISONumericField   (   3, "Reconciliation indicator"),
      new ISONumericField   (  24, "Amounts, original"),
      new ISOLLCharField    (  99, "Acquirer reference data"),
      new ISOLLNumericField (  11, "Acquirer institution identification code"),
      new ISOLLNumericField (  11, "Forwarding institution identification code"),
      new ISOLLCharField    (  28, "Primary account number, extended"),
      new ISOLLCharField    (  37, "Track 2 data"),
      new ISOLLLCharField   ( 104, "Track 3 data"),
      new ISOCharField      (  12, "Retrieval reference number"),
      new ISOCharField      (   6, "Approval code"),
      new ISONumericField   (   3, "Action code"),
      new ISONumericField   (   3, "Service code"),
      new ISOCharField      (   8, "Card acceptor terminal identification"),
      new ISOCharField      (  15, "Card acceptor identification code"),
      new ISOLLCharField    (  99, "Card acceptor name/location"),
      new ISOLLCharField    (  99, "Additional response data"),
      new ISOLLCharField    (  76, "Track 1 data"),
      new ISOLLLCharField   ( 204, "Amounts, Fees"),
      new ISOLLLCharField   ( 999, "Additional data - national"),
      new ISOLLLCharField   ( 999, "Additional data - private"),
      new ISOCharField      (   3, "Currency code, Transaction"),
      new ISOCharField      (   3, "Currency code, Reconciliation"),
      new ISOCharField      (   3, "Currency code, Cardholder billing"),
      new ISOBinaryField    (   8, "Personal identification number (PIN) data"),
      new ISOLLBinaryField  (  48, "Security related control information"),
      new ISOLLLCharField   ( 120, "Amounts, additional"),
      new ISOLLLBinaryField ( 255, "IC card system related data"),
      new ISOLLNumericField (  35, "Original data elements"),
      new ISONumericField   (   3, "Authorization life cycle code"),
      new ISOLLNumericField (  11, "Authorizing agent institution Id Code"),
      new ISOLLLCharField   ( 999, "Transport data"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for private use"),
      new ISOLLLCharField   ( 999, "Reserved for private use"),
      new ISOBinaryField    (   8, "Message authentication code field"),
      new ISOBinaryField    (   8, "Reserved for ISO use"),
      new ISOLLLCharField   ( 204, "Amounts, original fees"),
      new ISONumericField   (   2, "Extended payment data"),
      new ISONumericField   (   3, "Country code, receiving institution"),
      new ISONumericField   (   3, "Country code, settlement institution"),
      new ISONumericField   (   3, "Country code, authorizing agent Inst."),
      new ISONumericField   (   8, "Message number"),
      new ISOLLLCharField   ( 999, "Data record"),
      new ISONumericField   (   6, "Date, action"),
      new ISONumericField   (  10, "Credits, number"),
      new ISONumericField   (  10, "Credits, reversal number"),
      new ISONumericField   (  10, "Debits, number"),
      new ISONumericField   (  10, "Debits, reversal number"),
      new ISONumericField   (  10, "Transfer, number"),
      new ISONumericField   (  10, "Transfer, reversal number"),
      new ISONumericField   (  10, "Inquiries, number"),
      new ISONumericField   (  10, "Authorizations, number"),
      new ISONumericField   (  10, "Inquiries, reversal number"),
      new ISONumericField   (  10, "Payments, number"),
      new ISONumericField   (  10, "Payments, reversal number"),
      new ISONumericField   (  10, "Fee collections, number"),
      new ISONumericField   (  16, "Credits, amount"),
      new ISONumericField   (  16, "Credits, reversal amount"),
      new ISONumericField   (  16, "Debits, amount"),
      new ISONumericField   (  16, "Debits, reversal amount"),
      new ISONumericField   (  10, "Authorizations, reversal number"),
      new ISONumericField   (   3, "Country code, transaction Dest. Inst."),
      new ISONumericField   (   3, "Country code, transaction Orig. Inst."),
      new ISOLLNumericField (  11, "Transaction Dest. Inst. Id code"),
      new ISOLLNumericField (  11, "Transaction Orig. Inst. Id code"),
      new ISOLLCharField    (  99, "Card issuer reference data"),
      new ISOLLLBinaryField ( 999, "Key management data"),
      new ISOAmountField    (1+16, "Amount, Net reconciliation"),
      new ISOCharField      (  25, "Payee"),
      new ISOLLCharField    (  11, "Settlement institution Id code"),
      new ISOLLNumericField (  11, "Receiving institution Id code"),
      new ISOLLCharField    (  17, "File name"),
      new ISOLLCharField    (  28, "Account identification 1"),
      new ISOLLCharField    (  28, "Account identification 2"),
      new ISOLLLCharField   ( 100, "Transaction description"),
      new ISONumericField   (  16, "Credits, Chargeback amount"),
      new ISONumericField   (  16, "Debits, Chargeback amount"),
      new ISONumericField   (  10, "Credits, Chargeback number"),
      new ISONumericField   (  10, "Debits, Chargeback number"),
      new ISOLLCharField    (  84, "Credits, Fee amounts"),
      new ISOLLCharField    (  84, "Debits, Fee amounts"),
      new ISOLLLCharField   ( 999, "Reserved for ISO use"),
      new ISOLLLCharField   ( 999, "Reserved for ISO use"),
      new ISOLLLCharField   ( 999, "Reserved for ISO use"),
      new ISOLLLCharField   ( 999, "Reserved for ISO use"),
      new ISOLLLCharField   ( 999, "Reserved for ISO use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for national use"),
      new ISOLLLCharField   ( 999, "Reserved for private use"),
      new ISOLLLCharField   ( 999, "Reserved for private use"),
      new ISOLLLCharField   ( 999, "Reserved for private use"),
      new ISOLLLCharField   ( 999, "Reserved for private use"),
      new ISOLLLCharField   ( 999, "Reserved for private use"),
      new ISOBinaryField    (   8, "Message authentication code field")
    });
  }
}
