FOAM_FILES([
  // flinks front model(add all model)
  // { name: 'net/nanopay/flinks/model/FlinksAccount'},
  // { name: 'net/nanopay/flinks/model/FlinksRespMsg'},
  //
  { name: 'net/nanopay/flinks/model/FlinksCall' },
  { name: 'net/nanopay/flinks/model/FlinksRequest' },
  { name: 'net/nanopay/flinks/model/FlinksAuthRequest' },
  { name: 'net/nanopay/flinks/model/FlinksTransactionRequest' },
  { name: 'net/nanopay/flinks/model/FlinksAccountRequest' },
  { name: 'net/nanopay/flinks/model/FlinksAccountSummaryRequest' },
  { name: 'net/nanopay/flinks/model/RefreshDeltaModel' },
  { name: 'net/nanopay/flinks/model/FlinksAccountDetailRequest' },
  { name: 'net/nanopay/flinks/model/FlinksAccountDetailAsyncRequest' },
  { name: 'net/nanopay/flinks/model/FlinksMulAuthRequest' },
  { name: 'net/nanopay/flinks/model/FlinksResponse' },
  { name: 'net/nanopay/flinks/model/SecurityChallengeModel' },
  { name: 'net/nanopay/flinks/model/LoginModel' },
  { name: 'net/nanopay/flinks/model/FlinksInvalidResponse' },
  { name: 'net/nanopay/flinks/model/FlinksMFAResponse' },
  { name: 'net/nanopay/flinks/model/BalanceModel' },
  { name: 'net/nanopay/flinks/model/AccountModel' },
  { name: 'net/nanopay/flinks/model/AddressModel' },
  { name: 'net/nanopay/flinks/model/HolderModel' },
  { name: 'net/nanopay/flinks/model/AccountTransactionModel' },
  { name: 'net/nanopay/flinks/model/AccountWithDetailModel' },
  { name: 'net/nanopay/flinks/model/AccountStatementModel' },
  { name: 'net/nanopay/flinks/model/AccountStatementContainerModel' },
  { name: 'net/nanopay/flinks/model/FlinksAccountsDetailResponse' },
  { name: 'net/nanopay/flinks/model/FlinksAccountsSummaryResponse' },
  { name: 'net/nanopay/flinks/model/FlinksCredentials' },
  // flinks service
  { name: 'net/nanopay/flinks/FlinksAuth' },
  { name: 'net/nanopay/flinks/FlinksResponseService' },
  { name: 'net/nanopay/flinks/ClientFlinksAuthService' },
  { name: 'net/nanopay/flinks/MaskedFlinksAccountDAO' },
  { name: 'net/nanopay/flinks/RefinedFlinksAccountDAO' },
  { name: 'net/nanopay/flinks/exception/FlinksInvalidAccountException' },
  { name: 'net/nanopay/flinks/exception/FlinksInvalidLoginIdException' },
  { name: 'net/nanopay/flinks/exception/FlinksOnboardingFailureException' },
  { name: 'net/nanopay/flinks/external/AsyncStatus' },
  { name: 'net/nanopay/flinks/external/BusinessOverrideData' },
  { name: 'net/nanopay/flinks/external/CancelInProgressAsyncDAO' },
  { name: 'net/nanopay/flinks/external/FlinksLoginId' },
  { name: 'net/nanopay/flinks/external/FlinksLoginIdAsync' },
  { name: 'net/nanopay/flinks/external/FlinksLoginIdAsyncDAO' },
  { name: 'net/nanopay/flinks/external/FlinksLoginIdDAO' },
  { name: 'net/nanopay/flinks/external/FlinksLoginIdRequest' },
  { name: 'net/nanopay/flinks/external/FlinksOverrides' },
  { name: 'net/nanopay/flinks/external/OnboardingType' },
  { name: 'net/nanopay/flinks/external/OverrideData' },
  { name: 'net/nanopay/flinks/external/UserOverrideData' },
  // flinks views
  { name: 'net/nanopay/flinks/view/FlinksView' },
  { name: 'net/nanopay/flinks/view/form/FlinksForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksBankPadAuthorization', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksInstitutionForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksAccountForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksConnectForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/element/AccountCard', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/element/CheckBoxes', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksSubHeader', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksMFAForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksDoneForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksThreeQA', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksThreeOptionForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksSecurityChallenge', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksMultipleChoiceForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksXQuestionAnswerForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksXSelectionAnswerForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/element/JumpWizardView', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksFailForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/form/FlinksImageForm', flages: ['web'] },
  { name: 'net/nanopay/flinks/view/element/StringArrayInput', flages: ['web'] },
  // flinks widget
  { name: 'net/nanopay/flinks/widget/FlinksException' },
  { name: 'net/nanopay/flinks/widget/FlinksWidgetView', flags: ['web'] },
  { name: 'net/nanopay/flinks/widget/drivers/FlinksDriver' },
  { name: 'net/nanopay/flinks/widget/drivers/RequestToPayFlinksDriver' },

  // modals
  { name: 'net/nanopay/flinks/view/FlinksInstitutionsView', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/element/FlinksModalHeader', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalForm', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalConnect', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalSecurity', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalSecurityReset', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalSecurityQuestionAnswer', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalSecurityImage', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalAccountSelect', flags: ['web'] },
  { name: 'net/nanopay/flinks/view/modalForm/FlinksModalPAD', flags: ['web'] }
]);
