global.FOAM_FLAGS.src = __dirname + '/../src/';
require('../src/net/nanopay/files.js');

var classes = [
  'net.nanopay.auth.sms.PhoneVerificationTokenService',
  'net.nanopay.auth.ExternalInvoiceTokenService',
  'net.nanopay.cico.model.EFTReturnRecord',
  'net.nanopay.cico.model.EFTConfirmationFileRecord',
  'net.nanopay.cico.model.EFTReturnFileCredentials',
  'net.nanopay.tx.TxnProcessor',
  'net.nanopay.plaid.config.PlaidCredential',
  'net.nanopay.tx.Transfer',
  'net.nanopay.tx.ExternalTransfer',
  'net.nanopay.tx.ComplianceTransaction',
  'net.nanopay.tx.CompletedTransactionDAO',
  'net.nanopay.tx.TxnProcessorUserReference',
  'net.nanopay.tx.RetailTransactionPlanDAO',
  'net.nanopay.tx.CompositeTransaction',
  'net.nanopay.tx.CreateExpediteApprovalRequest',
  'net.nanopay.tx.cico.VerificationTransaction',
  'net.nanopay.tx.cico.CITransaction',
  'net.nanopay.tx.cico.COTransaction',
  'net.nanopay.tx.cico.InterTrustTransaction',
  'net.nanopay.tx.cico.EFTFile',
  'net.nanopay.tx.cico.EFTFileGenerator',
  'net.nanopay.tx.cico.EFTFileStatus',
  'net.nanopay.tx.cico.ReverseCIRule',
  'net.nanopay.tx.cico.ReverseCORule',
  'net.nanopay.tx.cico.ReverseInterTrustRule',
  'net.nanopay.tx.client.ClientTransactionLimitService',
  'net.nanopay.tx.alterna.AlternaFormat',
  'net.nanopay.tx.alterna.SFTPService',
  'net.nanopay.tx.alterna.AlternaSFTPService',
  'net.nanopay.tx.alterna.client.ClientAlternaSFTPService',
  'net.nanopay.tx.alterna.AlternaCOTransaction',
  'net.nanopay.tx.alterna.AlternaCITransaction',
  'net.nanopay.tx.alterna.AlternaVerificationTransaction',
  'net.nanopay.tx.stripe.StripeTransaction',
  'net.nanopay.tx.stripe.StripeCustomer',
  'net.nanopay.tx.realex.RealexTransaction',
  'net.nanopay.tx.ruler.TransactionLimitState',
  'net.nanopay.tx.ruler.MicroDepositSuccessed',
  'net.nanopay.tx.ruler.MicroDepositFailed',
  'net.nanopay.tx.ruler.MicroDepositSent',
  'net.nanopay.tx.ruler.InvoiceTransactionAfterPutRule',
  'net.nanopay.tx.ruler.SendCompleteRetailTransactionNotificationRule',
  'net.nanopay.tx.ruler.SummaryTransactionAfterPutRule',
  'net.nanopay.tx.ruler.SummaryTransactionUpdateDUGRule',
  'net.nanopay.tx.BulkTransaction',
  'net.nanopay.tx.test.BulkTransactionTest',
  'net.nanopay.cico.service.BankAccountVerifier',
  'net.nanopay.cico.service.ClientBankAccountVerifierService',
  'net.nanopay.cico.paymentCard.model.PaymentCard',
  'net.nanopay.cico.paymentCard.model.StripePaymentCard',
  'net.nanopay.cico.paymentCard.model.RealexPaymentCard',
  'net.nanopay.cico.paymentCard.model.PaymentCardType',
  'net.nanopay.cico.paymentCard.model.PaymentCardNetwork',
  'net.nanopay.payment.CreatePaymentCode',
  'net.nanopay.payment.Institution',
  'net.nanopay.payment.InstitutionAuthorizerTest',
  'net.nanopay.payment.InstitutionPurposeCode',
  'net.nanopay.payment.PaymentCode',
  'net.nanopay.payment.PaymentService',
  'net.nanopay.payment.Payroll',
  'net.nanopay.payment.PayrollEntry',
  'net.nanopay.payment.client.ClientPaymentService',
  'net.nanopay.payment.PaymentProvider',
  'net.nanopay.payment.PaymentProviderAware',
  'net.nanopay.payment.PaymentMethod',
  'net.nanopay.payment.PaymentProviderCorridor',
  'net.nanopay.payment.CountryCapability',
  'net.nanopay.payment.SourceTargetType',
  'net.nanopay.payment.CorridorService',
  'net.nanopay.payment.ClientCorridorService',
  'net.nanopay.payment.InstitutionPaymentProvider',
  'net.nanopay.payment.PADType',
  'net.nanopay.payment.PADTypeLineItem',
  'net.nanopay.payment.PADTypeCheckDAO',
  'net.nanopay.payment.PaymentProviderPrerequisiteRule',
  'net.nanopay.payment.PaymentProviderCorridorAddCountryRule',
  'net.nanopay.payment.PaymentProviderCorridorAuthorizer',
  'net.nanopay.payment.DestinationCorridorAuthorizer',
  'net.nanopay.tx.IBAN',
  'net.nanopay.account.Balance',
  'net.nanopay.account.InsufficientBalanceException',
  'net.nanopay.account.DuplicateEntryRule',
  'net.nanopay.account.DuplicateCABankAccountRule',
  'net.nanopay.account.DuplicateUSBankAccountRule',
  'net.nanopay.account.EnforceOneDefaultDigitalAccountPerCurrencyDAO',
  'net.nanopay.model.Branch',
  'net.nanopay.model.BusinessUserJunction',
  'net.nanopay.account.Account',
  'net.nanopay.account.Accountable',
  'net.nanopay.account.DigitalAccount',
  'net.nanopay.account.DebtAccount',
  'net.nanopay.account.Debtable',
  'net.nanopay.account.OverdraftAccount',
  'net.nanopay.account.DigitalAccountInfo',
  'net.nanopay.account.DigitalAccountServiceInterface',
  'net.nanopay.account.ClientDigitalAccountService',
  'net.nanopay.account.MultiTrustDigitalAccountService',
  'net.nanopay.account.AggregateAccount',
  'net.nanopay.account.ZeroAccount',
  'net.nanopay.account.ZeroAccountUserAssociation',
  'net.nanopay.account.TrustAccount',
  'net.nanopay.account.ShadowAccount',
  'net.nanopay.account.LossesAccount',
  'net.nanopay.account.LoanAccount',
  'net.nanopay.account.LoanedTotalAccount',
  'net.nanopay.account.HoldingAccount',
  'net.nanopay.account.AuthenticatedAccountDAOTest',
  'net.nanopay.account.NoBalanceRule',
  'net.nanopay.account.NoPendingTransactionsRule',
  'net.nanopay.account.NoChildrenRule',
  'net.nanopay.account.SecuritiesAccount',
  'net.nanopay.account.SecurityAccount',
  'net.nanopay.account.SecuritiesTrustAccount',
  'net.nanopay.account.SetBankAccountOnContact',
  'net.nanopay.account.BrokerAccount',
  'net.nanopay.account.CreateDefaultDigitalAccountOnUserCreateRule',
  'net.nanopay.bank.BankAccount',
  'net.nanopay.bank.EstimationAccount',
  'net.nanopay.bank.EUBankAccount',
  'net.nanopay.bank.CABankAccount',
  'net.nanopay.bank.USBankAccount',
  'net.nanopay.bank.INBankAccount',
  'net.nanopay.bank.PKBankAccount',
  'net.nanopay.bank.BRBankAccount',
  'net.nanopay.bank.GBBankAccount',
  'net.nanopay.bank.HKBankAccount',
  'net.nanopay.bank.ATBankAccount',
  'net.nanopay.bank.BEBankAccount',
  'net.nanopay.bank.CYBankAccount',
  'net.nanopay.bank.EEBankAccount',
  'net.nanopay.bank.FIBankAccount',
  'net.nanopay.bank.FRBankAccount',
  'net.nanopay.bank.DEBankAccount',
  'net.nanopay.bank.GRBankAccount',
  'net.nanopay.bank.IEBankAccount',
  'net.nanopay.bank.ITBankAccount',
  'net.nanopay.bank.LVBankAccount',
  'net.nanopay.bank.LTBankAccount',
  'net.nanopay.bank.LUBankAccount',
  'net.nanopay.bank.MTBankAccount',
  'net.nanopay.bank.NLBankAccount',
  'net.nanopay.bank.PTBankAccount',
  'net.nanopay.bank.SKBankAccount',
  'net.nanopay.bank.SIBankAccount',
  'net.nanopay.bank.ESBankAccount',
  'net.nanopay.bank.CNBankAccount',
  'net.nanopay.bank.SEBankAccount',
  'net.nanopay.bank.BankAccountStatus',
  'net.nanopay.bank.CanReceiveCurrency',
  'net.nanopay.bank.GetDefaultCurrency',
  'net.nanopay.bank.StrategizedBankAccount',
  'net.nanopay.bank.ruler.VerifyBankRule',
  'net.nanopay.bank.ruler.CapabilityAddBankAccountRule',
  'net.nanopay.country.br.ruler.BRBankAccountCapabilityOnGrantRule',
  'net.nanopay.bank.test.BankAccountIBANTest',
  'net.nanopay.model.CurrencyAmount',
  'net.nanopay.model.Broker',
  'net.nanopay.model.Business',
  'net.nanopay.model.BusinessUserJunctionRefinement',
  'net.nanopay.model.BeneficialOwner',
  'net.nanopay.model.BusinessDirector',
  'net.nanopay.model.BusinessSector',
  'net.nanopay.model.BusinessType',
  'net.nanopay.model.PadAccount',
  'net.nanopay.model.PadCapture',
  'net.nanopay.model.CAPadCapture',
  'net.nanopay.model.USPadCapture',
  'net.nanopay.model.Identification',
  'net.nanopay.model.DateAndPlaceOfBirth',
  'net.nanopay.model.Invitation',
  'net.nanopay.model.InvitationStatus',
  'net.nanopay.model.IdentificationType',
  'net.nanopay.model.PersonalIdentification',
  'net.nanopay.model.JobTitle',
  'net.nanopay.model.SigningOfficer',
  'net.nanopay.bank.AddBankAccountAction',
  'net.nanopay.bank.BankHoliday',
  'net.nanopay.bank.BankHolidayService',
  'net.nanopay.bank.test.USBankAccountTest',
  'net.nanopay.bank.BankWeekend',
  'net.nanopay.bank.DefaultBankAccountRule',
  'net.nanopay.bank.IsDefaultRule',
  'net.nanopay.bank.ruler.AccountVerifiedNotificationRule',
  'net.nanopay.bank.ruler.AccountDeletedNotificationRule',
  'net.nanopay.bank.ruler.AccountAddedNotificationRule',
  'net.nanopay.bank.ruler.CorridorAuthorizationRule',
  'net.nanopay.bank.ruler.BankInfoToIbanAndSwiftCodeTranslation',
  'net.nanopay.bank.ruler.IbanToSwiftCodeTranslation',
  'net.nanopay.bank.ruler.SwiftCodeToBankRoutingCodeTranslation',
  'net.nanopay.plaid.PlaidAccountDetailTest',
  'net.nanopay.plaid.PlaidResultReportAuthorizer',
  'net.nanopay.plaid.PlaidResultReportAuthorizerTest',
  'net.nanopay.bank.BankAccountValidationService',
  'net.nanopay.bank.MockBankAccountValidationService',

  // Util
  'net.nanopay.util.Tag',

  //Exchangeable
  'net.nanopay.exchangeable.Security',
  'net.nanopay.exchangeable.AssetClass',

  // sps
  'net.nanopay.sps.GeneralRequestPacket',
  'net.nanopay.sps.GeneralRequestResponse',
  'net.nanopay.sps.BatchDetailRequestPacket',
  'net.nanopay.sps.BatchDetailGeneralResponse',
  'net.nanopay.sps.DetailResponse',
  'net.nanopay.sps.RequestMessageAndErrors',
  'net.nanopay.sps.HostError',
  'net.nanopay.sps.TxnDetail',
  'net.nanopay.sps.PayerInfo',
  'net.nanopay.sps.DetailResponseItemContent',
  'net.nanopay.sps.RequestPacket',
  'net.nanopay.sps.ResponsePacket',
  'net.nanopay.sps.SPSCredentials',
  'net.nanopay.sps.SPSTransaction',
  'net.nanopay.sps.SPSRejectFileRecord',
  'net.nanopay.sps.SPSSettlementFileRecord',

  // kotak
  'net.nanopay.kotak.Kotak',
  'net.nanopay.kotak.KotakCredentials',
  'net.nanopay.tx.KotakPaymentPurposeLineItem',
  'net.nanopay.tx.KotakAccountRelationshipLineItem',

  // AFEX
  'net.nanopay.fx.FXSummaryTransaction',
  'net.nanopay.fx.afex.AFEXTransaction',
  'net.nanopay.fx.afex.AFEX',
  'net.nanopay.fx.afex.AFEXAddCurrencyPermissionRule',
  'net.nanopay.fx.afex.AFEXUser',
  'net.nanopay.fx.afex.AFEXUser',
  'net.nanopay.fx.afex.AFEXPayableMenuCapabilityRule',
  'net.nanopay.fx.afex.GrantAFEXPaymentProviderCapRule',
  'net.nanopay.fx.afex.AFEXBusinessCreatedPredicate',
  'net.nanopay.fx.afex.AFEXBusinessDisabledPredicate',
  'net.nanopay.fx.afex.AFEXRemoveCurrencyPermissionRule',
  'net.nanopay.fx.afex.AFEXBusinessCreatedNotificationRule',
  'net.nanopay.fx.afex.AFEXCoridorEnabledNotificationRule',
  'net.nanopay.fx.afex.AFEXCredentials',
  'net.nanopay.fx.afex.AFEXBeneficiary',
  'net.nanopay.fx.afex.AFEXBeneficiaryComplianceTransaction',
  'net.nanopay.fx.afex.AFEXComplianceTransactionPredicate',
  'net.nanopay.fx.afex.AFEXComplianceTransactionRule',
  'net.nanopay.fx.afex.AFEXFundingBalance',
  'net.nanopay.fx.afex.AFEXLog',
  'net.nanopay.fx.afex.Token',
  'net.nanopay.fx.afex.AccountEntityType',
  'net.nanopay.fx.afex.OnboardAFEXClientRequest',
  'net.nanopay.fx.afex.OnboardAFEXClientResponse',
  'net.nanopay.fx.afex.GetClientAccountStatusResponse',
  'net.nanopay.fx.afex.RetrieveClientAccountDetailsResponse',
  'net.nanopay.fx.afex.CreateBeneficiaryRequest',
  'net.nanopay.fx.afex.CreateBeneficiaryResponse',
  'net.nanopay.fx.afex.UpdateBeneficiaryRequest',
  'net.nanopay.fx.afex.UpdateBeneficiaryResponse',
  'net.nanopay.fx.afex.DisableBeneficiaryRequest',
  'net.nanopay.fx.afex.FindBeneficiaryRequest',
  'net.nanopay.fx.afex.FindBeneficiaryResponse',
  'net.nanopay.fx.afex.FindBankByNationalIDRequest',
  'net.nanopay.fx.afex.FindBankByNationalIDResponse',
  'net.nanopay.fx.afex.GetRateRequest',
  'net.nanopay.fx.afex.GetRateResponse',
  'net.nanopay.fx.afex.Quote',
  'net.nanopay.fx.afex.GetQuoteRequest',
  'net.nanopay.fx.afex.GetConfirmationPDFRequest',
  'net.nanopay.fx.afex.CreateTradeRequest',
  'net.nanopay.fx.afex.CreateTradeResponse',
  'net.nanopay.fx.afex.CheckTradeStatusRequest',
  'net.nanopay.fx.afex.CheckTradeStatusResponse',
  'net.nanopay.fx.afex.CreatePaymentRequest',
  'net.nanopay.fx.afex.CreatePaymentResponse',
  'net.nanopay.fx.afex.CreateFundingBalanceRequest',
  'net.nanopay.fx.afex.CreateFundingBalanceResponse',
  'net.nanopay.fx.afex.CreateInstantBeneficiaryRequest',
  'net.nanopay.fx.afex.CreateInstantBeneficiaryResponse',
  'net.nanopay.fx.afex.FundingBalance',
  'net.nanopay.fx.afex.GetFundingBalanceResponse',
  'net.nanopay.fx.afex.KeyIndividual',
  'net.nanopay.fx.afex.ValidateInstantBenefiaryRequest',
  'net.nanopay.fx.afex.ValidateInstantBenefiaryResponse',
  'net.nanopay.fx.afex.CheckPaymentStatusRequest',
  'net.nanopay.fx.afex.CheckPaymentStatusResponse',
  'net.nanopay.fx.afex.AddCompanyOfficerRequest',
  'net.nanopay.fx.afex.AFEXPaymentStatus',
  'net.nanopay.fx.afex.AFEXBusinessApprovalRequest',
  'net.nanopay.fx.afex.AFEXBusinessApprovalRequestRule',
  'net.nanopay.fx.afex.DirectDebitEnrollmentRequest',
  'net.nanopay.fx.afex.DirectDebitEnrollmentResponse',
  'net.nanopay.fx.afex.DirectDebitUnenrollmentRequest',
  'net.nanopay.fx.afex.DirectDebitUnenrollmentResponse',
  'net.nanopay.fx.afex.AFEXBankOnboardingRule',
  'net.nanopay.fx.afex.AFEXBankUploadingRule',
  'net.nanopay.fx.afex.AFEXBankUploadingRule2',
  'net.nanopay.fx.afex.AFEXCreateTradePredicate',
  'net.nanopay.fx.afex.AFEXCreateTradeRule',
  'net.nanopay.fx.afex.AFEXSubmitPaymentPredicate',
  'net.nanopay.fx.afex.AFEXSubmitPaymentRule',
  'net.nanopay.fx.afex.AFEXBeneficialOwnerRule',
  'net.nanopay.fx.afex.AFEXBusinessDirectorRule',
  'net.nanopay.fx.afex.AFEXBankUpdatingRule',
  'net.nanopay.fx.afex.TransactionInvalidBankAccountRule',
  'net.nanopay.fx.afex.TransactionVerifyBankAccountRule',
  'net.nanopay.fx.afex.AFEXFundingTransaction',
  'net.nanopay.fx.afex.AFEXCreateFundingBalancesRule',
  'net.nanopay.fx.afex.AFEXSubmitFundingTxnRule',
  'net.nanopay.fx.afex.AFEXGetPDFRule',
  'net.nanopay.fx.afex.IsIbanRequest',
  'net.nanopay.fx.afex.IsIbanResponse',

  // Partners
  'net.nanopay.partners.ui.PartnerInvitationNotification',
  'net.nanopay.auth.PublicUserInfo',

  // Contacts
  'net.nanopay.contacts.Contact',
  'net.nanopay.contacts.PersonalContact',
  'net.nanopay.contacts.ContactStatus',
  'net.nanopay.contacts.ContactMigrationRule',
  'net.nanopay.contacts.ExternalContactToken',
  'net.nanopay.contacts.ClientPaymentCodeService',
  'net.nanopay.contacts.ClientContactService',
  'net.nanopay.contacts.AFEXContactCapabilityRule',
  'net.nanopay.contacts.AFEXCNBeneficiaryCapability',

  // invite
  'net.nanopay.admin.model.ComplianceStatus',
  'net.nanopay.admin.model.AccountStatus',
  'net.nanopay.onboarding.model.Question',
  'net.nanopay.onboarding.model.Questionnaire',
  'net.nanopay.onboarding.InvitationTokenService',
  'net.nanopay.onboarding.FirebaseInvitationTokenService',
  'net.nanopay.admin.SkipUserEmailVerification',
  'net.nanopay.admin.predicate.IsCurrentUser',
  'net.nanopay.sme.ruler.BusinessInvitationAndTokenCancelRule',
  'net.nanopay.sme.ruler.InvitationAntiSpamCheckRule',

  // compliance Email notification
  'net.nanopay.sme.ruler.BusinessCompliancePassedEmailRule',

  // sme cron
  'net.nanopay.sme.cron.WelcomeEmailCron',
  'net.nanopay.sme.cron.SigningOfficerReminderCron',
  'net.nanopay.sme.cron.OnboardingReminderCron',
  // sme onboarding
  'net.nanopay.sme.onboarding.model.SuggestedUserTransactionInfo',
  'net.nanopay.sme.onboarding.BusinessOnboarding',
  'net.nanopay.sme.onboarding.OnboardingStatus',
  'net.nanopay.sme.onboarding.BusinessOnboardingDAO',
  'net.nanopay.sme.onboarding.BusinessOnboardingDAOTest',
  'net.nanopay.sme.onboarding.CanadaUsBusinessOnboarding',
  'net.nanopay.sme.onboarding.CanadaUsBusinessOnboardingDAO',
  'net.nanopay.sme.onboarding.ReceiveOnlyOnboarding',
  'net.nanopay.sme.onboarding.ReceiveOnlyOnboardingDAO',
  'net.nanopay.sme.onboarding.ReceiveOnlyOnboardingDAO',
  'net.nanopay.sme.onboarding.USBusinessOnboardingDAO',
  'net.nanopay.sme.OnboardingPaymentOpsNotification',
  'net.nanopay.sme.onboarding.model.AnnualRevenueEnum',
  'net.nanopay.sme.onboarding.model.AnnualTxnFrequencyEnum',
  'net.nanopay.sme.onboarding.model.TransactionsPurposeEnum',
  'net.nanopay.sme.ruler.OnboardingPaymentOperationNotification',
  'net.nanopay.onboarding.email.NewBankAccountAddedEmailDAO',
  'net.nanopay.onboarding.email.NewUserOnboardedEmailDAO',
  'net.nanopay.onboarding.ruler.NotificationSettingsRule',
  'net.nanopay.onboarding.ruler.SetSubmitByRule',
  'net.nanopay.onboarding.model.BusinessOnboardingExtra',

  // sme business setting
  'net.nanopay.sme.ruler.AccessControlChangeNotificationRule',

  // sign up
  'net.nanopay.sme.ruler.CheckUserNameAvailabilityRule',

  // banner
  'net.nanopay.ui.banner.BannerData',
  'net.nanopay.ui.banner.BannerMode',

  // invoice
  'net.nanopay.invoice.ruler.TrevisoInvoiceCapabilityRule',
  'net.nanopay.invoice.ruler.CapabilityValidateRule',
  'net.nanopay.invoice.ruler.NoCapabilityCheckRule',
  'net.nanopay.invoice.model.PaymentStatus',
  'net.nanopay.invoice.model.InvoiceStatus',
  'net.nanopay.invoice.model.RecurringInvoice',
  'net.nanopay.invoice.model.Invoice',
  'net.nanopay.invoice.model.BillingInvoice',
  'net.nanopay.invoice.notification.NewInvoiceNotification',
  'net.nanopay.invoice.notification.InvoicePaymentNotification',
  'net.nanopay.invoice.ruler.RequestPaymentNotificationRule',
  'net.nanopay.invoice.service.InvoicePaymentService',
  'net.nanopay.invoice.service.ClientInvoicePaymentService',
  'net.nanopay.invoice.InvoiceNotificationDAO',
  'net.nanopay.invoice.InvoiceLineItem',
  'net.nanopay.invoice.DetailedInvoiceDAO',
  'net.nanopay.invoice.ruler.CompleteInvoiceNotificationRule',
  'net.nanopay.invoice.ruler.IsCompletePayment',
  'net.nanopay.invoice.ruler.InvoiceVoidEmailRule',
  'net.nanopay.invoice.ruler.SetProcessingDateRule',
  'net.nanopay.invoice.ruler.SetReceivedDateRule',
  'net.nanopay.invoice.ruler.SetPaymentSentDateRule',
  'net.nanopay.invoice.ruler.TransactionNatureCodeUpdateRule',
  'net.nanopay.invoice.test.invoiceHistoryAuthorizerTest',
  'net.nanopay.invoice.InvoiceHistoryAuthorizer',
  'net.nanopay.invoice.ruler.InvoiceQuotingRule',
  'net.nanopay.invoice.ruler.InvoiceTransactionSubmitRule',
  'net.nanopay.invoice.ruler.InvoiceRequestTransactionRule',

   // accounting
   'net.nanopay.accounting.ClientIntegrationService',
   'net.nanopay.accounting.IntegrationCode',
   'net.nanopay.accounting.IntegrationService',
   'net.nanopay.accounting.ResultResponse',
   'net.nanopay.accounting.AccountingResultReport',
   'net.nanopay.accounting.AccountingResultReportAuthorizerTest',
   'net.nanopay.accounting.ResultResponseWrapper',
   'net.nanopay.accounting.AccountingBankAccount',
   'net.nanopay.accounting.ContactMismatchPair',
   'net.nanopay.accounting.ContactMismatchCode',
   'net.nanopay.accounting.AccountingContactEmailCache',
   'net.nanopay.accounting.AccountingErrorCodes',

   // xero
   'net.nanopay.accounting.xero.XeroToken',
   'net.nanopay.accounting.xero.XeroConfig',
   'net.nanopay.accounting.xero.model.XeroContact',
   'net.nanopay.accounting.xero.model.XeroInvoice',

   // liquidity
   'net.nanopay.liquidity.LiquiditySettings',
   'net.nanopay.liquidity.Liquidity',
   'net.nanopay.liquidity.LiquidityAuth',
   'net.nanopay.liquidity.LiquidNotification',
   'net.nanopay.liquidity.LiquidityRule',
   'net.nanopay.liquidity.PreventAccountLiquidityLoopRule',
   'net.nanopay.liquidity.PreventLiquiditySettingsLoopRule',
   'net.nanopay.liquidity.ui.dashboard.cicoShadow.TransactionCICOType',
   'net.nanopay.liquidity.approvalRequest.OutstandingRequestsPreventDeletionPredicate',
   'net.nanopay.liquidity.approvalRequest.OutstandingRequestsPreventDeletionRule',
   'net.nanopay.liquidity.approvalRequest.AccountApprovableAwareDAO',
   'net.nanopay.liquidity.approvalRequest.AccountApprovableAware',
   'net.nanopay.liquidity.approvalRequest.AccountRoleApprovalRequest',
   'net.nanopay.liquidity.approvalRequest.LiquidityApprovalRequestNotification',
   'net.nanopay.liquidity.approvalRequest.LiquidityApprovalStatus',
   'net.nanopay.liquidity.crunch.ApproverLevel',
   'net.nanopay.liquidity.crunch.LiquidCapability',
   'net.nanopay.liquidity.crunch.LiquidCapabilityAuthService',
   'net.nanopay.liquidity.crunch.AccountTemplate',
   'net.nanopay.liquidity.crunch.AccountMap',
   'net.nanopay.liquidity.crunch.AccountApproverMap',
   'net.nanopay.liquidity.crunch.CapabilityAccountTemplate',
   'net.nanopay.liquidity.crunch.AccountData',
   'net.nanopay.liquidity.crunch.CapabilityAccountData',
   'net.nanopay.liquidity.crunch.LiquidAuthorizer',
   'net.nanopay.liquidity.crunch.LiquidTransactionAuthorizer',
   'net.nanopay.liquidity.crunch.LiquidApprovalRequestAuthorizer',
   'net.nanopay.liquidity.crunch.RoleAssignment',
   'net.nanopay.liquidity.crunch.RoleAssignmentOperations',
   'net.nanopay.liquidity.crunch.CheckSelfRefRoleAssignmentAction',
   'net.nanopay.liquidity.crunch.CreateUserCapabilityJunctionOnRequestApproval',
   'net.nanopay.liquidity.crunch.AddAccountToUserCapabilityJunctionOnCreate',
   'net.nanopay.liquidity.crunch.RemoveAccountBasedUCJIfAccountsEmpty',
   'net.nanopay.liquidity.crunch.ApprovedRoleAssignmentPredicate',
   'net.nanopay.liquidity.crunch.RemoveJunctionsOnCapabilityRemoval',
   'net.nanopay.liquidity.crunch.RemoveAccountFromUcjDataOnAccountRemoval',
   'net.nanopay.liquidity.crunch.RootAccounts',
   'net.nanopay.liquidity.crunch.RoleTemplate',
   'net.nanopay.liquidity.crunch.RemoveDeletedAccountFromAccountTemplate',
   'net.nanopay.liquidity.crunch.LiquidEnabledActionsAuth',
   'net.nanopay.liquidity.crunch.RemoveAccountFromRootAccounts',

   'net.nanopay.util.Frequency',
   'net.nanopay.liquidity.ruler.AccountTemplateContains',
   'net.nanopay.liquidity.ruler.ApprovalRuleActionOnCreate',
   'net.nanopay.liquidity.ruler.CheckSelfRefAction',
   'net.nanopay.liquidity.ruler.CheckSelfRefPredicate',
   'net.nanopay.liquidity.ruler.IsSystemOrAdminUser',
   'net.nanopay.liquidity.ruler.LogoutUserOnAssignmentAction',
   'net.nanopay.liquidity.ruler.LogoutUserOnCapabilityUpdateAction',
   'net.nanopay.liquidity.ruler.AccountLSValidationPredicate',
   'net.nanopay.liquidity.tx.BusinessRule',
   'net.nanopay.liquidity.tx.BusinessRuleAction',
   'net.nanopay.liquidity.tx.BusinessRuleNotificationAction',
   'net.nanopay.liquidity.tx.BusinessRuleTransactionPredicate',
   'net.nanopay.liquidity.tx.ExceptionRuleAction',
   'net.nanopay.liquidity.tx.GenericBusinessRule',
   'net.nanopay.liquidity.tx.IsChildAccountPredicate',
   'net.nanopay.liquidity.tx.L2TransactionApprovalRule',
   'net.nanopay.liquidity.tx.TxLimitAction',
   'net.nanopay.liquidity.tx.TxLimitEntityType',
   'net.nanopay.liquidity.tx.TxLimitPredicate',
   'net.nanopay.liquidity.tx.TxLimitRule',
   'net.nanopay.liquidity.tx.CheckSelfRefTxLimitRuleAction',
   'net.nanopay.liquidity.tx.RestrictAccountsRule',
   'net.nanopay.liquidity.tx.RestrictUsersRule',
   'net.nanopay.liquidity.tx.AccountHierarchy',
   'net.nanopay.liquidity.tx.ClientAccountHierarchyService',

   'net.nanopay.liquidity.ucjQuery.AccountUCJQueryService',
   'net.nanopay.liquidity.ucjQuery.CachedAccountUCJQueryService',
   'net.nanopay.liquidity.ucjQuery.UCJQueryService',
   'net.nanopay.liquidity.ucjQuery.CachedUCJQueryService',
   'net.nanopay.liquidity.ucjQuery.RoleUserQueryService',

   // quick
   'net.nanopay.accounting.quickbooks.QuickbooksConfig',
   'net.nanopay.accounting.quickbooks.QuickbooksOauth',
   'net.nanopay.accounting.quickbooks.QuickbooksToken',
   'net.nanopay.accounting.quickbooks.model.QuickbooksContact',
   'net.nanopay.accounting.quickbooks.model.QuickbooksInvoice',
   'net.nanopay.accounting.resultresponse.ContactResponseItem',
   'net.nanopay.accounting.resultresponse.InvoiceResponseItem',

  // fx
  'net.nanopay.tx.CreateManualFxRule',
  'net.nanopay.fx.ExchangeRateInterface',
  'net.nanopay.fx.interac.model.RequiredUserFields',
  'net.nanopay.fx.interac.model.RequiredAddressFields',
  'net.nanopay.fx.interac.model.RequiredIdentificationFields',
  'net.nanopay.fx.interac.model.RequiredAccountFields',
  'net.nanopay.fx.interac.model.RequiredAgentFields',
  'net.nanopay.fx.interac.model.RequiredDocumentFields',
  'net.nanopay.fx.ExchangeRateStatus',
  'net.nanopay.fx.ExchangeRate',
  'net.nanopay.fx.ExchangeRateService',
  'net.nanopay.fx.ExchangeRateServiceInterface',
  'net.nanopay.account.BalanceServiceInterface',
  'net.nanopay.account.BalanceService',
  'net.nanopay.account.AccountBalanceDAO',
  'net.nanopay.fx.SecurityPrice',
  'net.nanopay.fx.ExchangeRateQuote',
  'net.nanopay.fx.FixerIOExchangeRate',
  'net.nanopay.fx.FXTransaction',
  'net.nanopay.fx.CurrencyFXService',
  'net.nanopay.fx.FXUserStatus',
  'net.nanopay.fx.KotakFxTransaction',
  'net.nanopay.tx.UserTransactionLimit',
  'net.nanopay.tx.client.ClientUserTransactionLimitService',
  'net.nanopay.retail.model.DeviceType',
  'net.nanopay.tx.JackieRuleOnCreate',
  'net.nanopay.tx.JackieRuleOnPut',
  'net.nanopay.tx.ClearingTimeTransaction',
  'net.nanopay.tx.AcceptAware',
  'net.nanopay.tx.AccountRelationship',
  'net.nanopay.tx.AccountRelationshipLineItem',
  'net.nanopay.tx.ETALineItem',
  'net.nanopay.tx.ReferenceLineItem',
  'net.nanopay.tx.ExpiryLineItem',
  'net.nanopay.tx.AttachmentLineItem',
  'net.nanopay.tx.ConfirmationFileLineItem',
  'net.nanopay.fx.ManualFxApprovalRequest',
  'net.nanopay.tx.ManualFxRule',
  'net.nanopay.tx.ModifyCicoStatus',
  'net.nanopay.tx.PurposeGroup',
  'net.nanopay.util.Frequency',
  'net.nanopay.tx.model.TransactionFee',
  'net.nanopay.tx.FeeLineItem',
  'net.nanopay.tx.InvoicedFeeLineItem',
  'net.nanopay.tx.ExpediteCICOApprovalRequest',
  'net.nanopay.tx.ExpenseLineItem',
  'net.nanopay.tx.ServiceLineItem',
  'net.nanopay.tx.FeeTransfer',
  'net.nanopay.tx.InfoLineItem',
  'net.nanopay.tx.TaxLineItem',
  'net.nanopay.tx.LineItemType',
  'net.nanopay.tx.LineItemTypeAccount',
  'net.nanopay.tx.LineItemAmountType',
  'net.nanopay.tx.LineItemAmount',
  'net.nanopay.tx.LineItemFee',
  'net.nanopay.tx.CompliancePlanDAO',
  'net.nanopay.tx.model.TransactionStatus',
  'net.nanopay.tx.HistoricStatus',
  'net.nanopay.tx.model.TransactionEntity',
  'net.nanopay.tx.TransactionEvent',
  'net.nanopay.tx.model.Transaction',
  'net.nanopay.tx.GreenfenceTransaction',
  'net.nanopay.tx.InvoiceTransaction',
  'net.nanopay.tx.DigitalTransaction',
  'net.nanopay.tx.SecurityTransaction',
  'net.nanopay.tx.ruler.IsSecurityQuote',
  'net.nanopay.tx.SaveChainedTransactionDAO',
  'net.nanopay.tx.SummarizingTransaction',
  'net.nanopay.tx.ValueMovementTransaction',
  'net.nanopay.tx.SummaryTransaction',
  'net.nanopay.tx.PropertyCompare',
  'net.nanopay.tx.LiquidSummaryTransaction',
  'net.nanopay.tx.LiquidCashTransactionType',
  'net.nanopay.tx.BulkTransaction',
  'net.nanopay.tx.BulkTransactionDAO',
  'net.nanopay.tx.SourceLineItem',
  'net.nanopay.tx.TransactionLineItem',
  'net.nanopay.tx.DisclosureLineItem',
  'net.nanopay.tx.PurposeCode',
  'net.nanopay.tx.PurposeCodeLineItem',
  'net.nanopay.tx.TransactionQuote',
  'net.nanopay.tx.TransactionSummary',
  'net.nanopay.tx.RefundTransaction',
  'net.nanopay.tx.RetailTransaction',
  'net.nanopay.tx.model.TransactionLimit',
  'net.nanopay.tx.ruler.TransactionLimitProbeInfo',
  'net.nanopay.tx.ruler.TransactionLimitRule',
  'net.nanopay.tx.ruler.PermissionedTransactionRule',
  'net.nanopay.tx.ruler.InvoiceApprovedByRule',
  'net.nanopay.tx.ruler.SlowDownRule',
  'net.nanopay.tx.ruler.LiquidTransactionalBlocks',
  'net.nanopay.tx.ruler.AbliiSendCompletedNotification',
  'net.nanopay.tx.ruler.SendDeclinedCINotification',
  'net.nanopay.tx.ruler.AddStatusHistoryAction',
  'net.nanopay.tx.ruler.CascadingCancelAction',
  'net.nanopay.tx.ruler.CICOTransactionInvalidBankAccountRule',
  'net.nanopay.tx.RepayDebtOnCIRule',
  'net.nanopay.tx.model.TransactionLimitTimeFrame',
  'net.nanopay.tx.model.TransactionLimitType',
  'net.nanopay.tx.model.TransactionLimitDetail',
  'net.nanopay.tx.TransactionPurpose',
  'net.nanopay.tx.PlanTransactionComparator',
  'net.nanopay.tx.PlanCostComparator',
  'net.nanopay.tx.PlanETAComparator',
  'net.nanopay.tx.PlanComparator',
  'net.nanopay.tx.KotakCOTransaction',
  'net.nanopay.tx.KotakPaymentTransaction',
  'net.nanopay.tx.AbliiTransactionDAO',
  'net.nanopay.tx.DebtTransaction',
  'net.nanopay.tx.TestTransaction',
  'net.nanopay.tx.AbliiTransaction',
  'net.nanopay.tx.InterestTransaction',
  'net.nanopay.tx.FailedTransactionNotification',
  'net.nanopay.tx.DebtRepaymentTransaction',
  'net.nanopay.tx.DVPTransaction',
  'net.nanopay.tx.ParentCompleteToPendingRule',
  'net.nanopay.tx.BucketTransaction',
  'net.nanopay.tx.Amount',
  'net.nanopay.tx.PartnerTransaction',
  'net.nanopay.tx.SummaryTransactionDAO',
  'net.nanopay.tx.SummaryTransactionInnerDAO',
  'net.nanopay.tx.ruler.ComplianceTransactionPlanner',
  'net.nanopay.tx.TransactionException',
  'net.nanopay.tx.UnsupportedTransactionException',
  'net.nanopay.retail.model.DeviceStatus',
  'net.nanopay.retail.model.Device',
  'net.nanopay.retail.model.P2PTxnRequestStatus',
  'net.nanopay.retail.model.P2PTxnRequest',
  'net.nanopay.fx.FXLineItem',
  'net.nanopay.fx.TotalRateLineItem',
  'net.nanopay.fx.ascendantfx.AscendantFX',
  'net.nanopay.fx.ascendantfx.AscendantFXTransaction',
  'net.nanopay.fx.ascendantfx.AscendantFXUser',
  'net.nanopay.fx.ascendantfx.AscendantFXFeeLineItem',
  'net.nanopay.fx.ascendantfx.AscendantUserPayeeJunction',
  'net.nanopay.fx.ascendantfx.AscendantFXHoldingAccount',
  'net.nanopay.fx.ascendantfx.AscendantFXPaymentMethodType',
  'net.nanopay.fx.ascendantfx.AscendantFXCredientials',
  'net.nanopay.tx.ruler.AscendantFXTransactionAfterPutRule',
  'net.nanopay.fx.lianlianpay.LianLianPay',
  'net.nanopay.fx.lianlianpay.model.ResultCode',
  'net.nanopay.fx.lianlianpay.model.DistributionMode',
  'net.nanopay.fx.lianlianpay.model.InstructionType',
  'net.nanopay.fx.lianlianpay.model.CurrencyBalanceRecord',
  'net.nanopay.fx.lianlianpay.model.InstructionCombined',
  'net.nanopay.fx.lianlianpay.model.InstructionCombinedRequest',
  'net.nanopay.fx.lianlianpay.model.InstructionCombinedSummary',
  'net.nanopay.fx.lianlianpay.model.PreProcessResult',
  'net.nanopay.fx.lianlianpay.model.PreProcessResultResponse',
  'net.nanopay.fx.lianlianpay.model.PreProcessResultSummary',
  'net.nanopay.fx.lianlianpay.model.Reconciliation',
  'net.nanopay.fx.lianlianpay.model.ReconciliationRecord',
  'net.nanopay.fx.lianlianpay.model.Statement',
  'net.nanopay.fx.lianlianpay.model.StatementRecord',
  'net.nanopay.fx.interac.model.ExchangerateApiModel',
  'net.nanopay.fx.interac.model.AcceptRateApiModel',
  'net.nanopay.fx.interac.model.AcceptExchangeRateFields',
  'net.nanopay.fx.AddINCurrencyPermissionRule',
  'net.nanopay.tx.TransactionValidator',
  'net.nanopay.tx.AddLiquidTransactionAction',
  'net.nanopay.tx.LabelLiquidSummaryAction',
  'net.nanopay.tx.SummaryTransactionLineItem',
  'net.nanopay.tx.FeeSummaryTransactionLineItem',
  'net.nanopay.tx.FxSummaryTransactionLineItem',
  'net.nanopay.tx.EtaSummaryTransactionLineItem',
  'net.nanopay.tx.UnsupportedDateException',
  'net.nanopay.tx.ExpiredTransactionException',
  'net.nanopay.tx.ruler.UpdateTxOnApprovalRequestStatusChange',

  // TODO: From Maldives To Be ReWorked
  'net.nanopay.settlement.GroupingAccount',
  'net.nanopay.settlement.ReserveAccount',
  'net.nanopay.settlement.BankPlayAccount',
  'net.nanopay.settlement.SettlementAccount',
  'net.nanopay.settlement.SettlementTransaction',
  'net.nanopay.settlement.MaldivianPlanner',
  'net.nanopay.settlement.BiLateralAccount',
  'net.nanopay.settlement.SettlementAccountBalanceComparator',
  'net.nanopay.settlement.Settlement',
  'net.nanopay.settlement.SettlementTypes',

  'net.nanopay.fx.FXService',
  'net.nanopay.fx.client.ClientFXService',
  'net.nanopay.fx.FXAccepted',
  'net.nanopay.fx.FXDirection',
  'net.nanopay.fx.FXProvider',
  'net.nanopay.fx.localfx.NanopayFXService',

  'net.nanopay.fx.GetFXQuote',
  'net.nanopay.fx.AcceptFXRate',
  'net.nanopay.fx.FXQuote',

  // documents
  'net.nanopay.documents.AcceptanceDocument',
  'net.nanopay.documents.UserAcceptanceDocument',
  'net.nanopay.documents.AcceptanceDocumentService',
  'net.nanopay.documents.ClientAcceptanceDocumentService',
  'net.nanopay.documents.AcceptanceDocumentType',

  // tx tests
  'net.nanopay.tx.model.TransactionParseTest',

  // tax
  'net.nanopay.tax.TaxQuote',
  'net.nanopay.tax.TaxQuoteRequest',
  'net.nanopay.tax.TaxService',
  'net.nanopay.tax.TaxItem',
  'net.nanopay.tax.TaxSummary',
  'net.nanopay.tax.LineItemTax',


  // PaymentAccountInfo
  'net.nanopay.cico.CICOPaymentType',
  'net.nanopay.cico.model.PaymentAccountInfo',
  'net.nanopay.cico.model.RealexPaymentAccountInfo',
  'net.nanopay.cico.model.MobileWallet',

  // auth
  'net.nanopay.auth.BusinessEmployeeDAO',
  'net.nanopay.auth.BusinessToPublicBusinessInfoDAO',
  'net.nanopay.auth.CheckCurrencyRule',
  'net.nanopay.auth.LoginAttempt',
  'net.nanopay.auth.NanopayResetPasswordTokenService',
  'net.nanopay.auth.NanopayUserAndGroupAuthService',
  'net.nanopay.auth.OneTimeAuthenticationTokenService',
  'net.nanopay.auth.PublicBusinessInfo',
  'net.nanopay.auth.ruler.LogoutUserAction',
  'net.nanopay.auth.ruler.PreventDuplicateEmailAction',
  'net.nanopay.auth.ruler.PreventDuplicateUsernameAction',
  'net.nanopay.auth.ruler.SpidLimitedPermissionedUserRule',
  'net.nanopay.auth.ruler.predicate.IsUserInGroups',
  'net.nanopay.security.auth.IPLoggingAuthService',
  'net.nanopay.security.auth.LoginAttemptAuthService',
  'net.nanopay.security.auth.LoginAttempts',

  // SSO
  'net.nanopay.auth.openid.SSOToken',
  'net.nanopay.auth.openid.OTLoginToken',
  'net.nanopay.auth.openid.TokenLoginService',
  'net.nanopay.auth.openid.ClientTokenLoginService',
  'net.nanopay.auth.openid.OAuthService',
  'net.nanopay.auth.openid.ClientOAuthService',
  'net.nanopay.auth.openid.OAuthProvider',

  // PII
  'net.nanopay.security.pii.PII',
  'net.nanopay.security.pii.PIIReportGenerator',
  'net.nanopay.security.pii.ViewPIIRequest',
  'net.nanopay.security.pii.PIIRequestStatus',
  'net.nanopay.security.pii.PIIDisplayStatus',
  'net.nanopay.security.pii.PIIReportDownload',
  'net.nanopay.security.pii.ApprovedPIIRequestDAO',
  'net.nanopay.security.pii.PreventDuplicatePIIRequestsDAO',
  'net.nanopay.security.pii.FreezeApprovedPIIRequestsDAO',

  // security
  'net.nanopay.security.EncryptedObject',
  'net.nanopay.security.EncryptingDAO',
  'net.nanopay.security.KeyStoreManager',
  'net.nanopay.security.AbstractKeyStoreManager',
  'net.nanopay.security.AbstractFileKeyStoreManager',
  'net.nanopay.security.BKSKeyStoreManager',
  'net.nanopay.security.JCEKSKeyStoreManager',
  'net.nanopay.security.JKSKeyStoreManager',
  'net.nanopay.security.PKCS11KeyStoreManager',
  'net.nanopay.security.PKCS12KeyStoreManager',
  'net.nanopay.security.HashingJournal',
  'net.nanopay.security.HashingReplayJournal',
  'net.nanopay.security.HashedJSONParser',
  'net.nanopay.security.csp.CSPViolation',
  'net.nanopay.security.csp.CSPReportWebAgent',

  'net.nanopay.security.KeyPairEntry',
  'net.nanopay.security.PrivateKeyEntry',
  'net.nanopay.security.PublicKeyEntry',
  'net.nanopay.security.KeyPairDAO',
  'net.nanopay.security.PublicKeyDAO',
  'net.nanopay.security.PrivateKeyDAO',
  'net.nanopay.security.UserKeyPairGenerationDAO',
  'net.nanopay.security.MessageDigest',
  'net.nanopay.security.RandomNonceDAO',
  'net.nanopay.security.KeyRight',
  'net.nanopay.security.RightCondition',
  'net.nanopay.security.Signature',
  'net.nanopay.security.PayerAssentTransactionDAO',
  'net.nanopay.security.UserRegistrationSanitationDAO',
  'net.nanopay.security.PGPPublicKeyDAO',
  'net.nanopay.security.PGPPrivateKeyDAO',

  // security tests
  'net.nanopay.security.test.EncryptingDAOTest',
  'net.nanopay.security.test.HashedJSONParserTest',
  'net.nanopay.security.test.HashingJournalTest',
  'net.nanopay.security.test.HashingOutputterTest',
  'net.nanopay.security.test.LoginAttemptAuthServiceTest',
  'net.nanopay.security.test.PayerAssentTransactionDAOTest',
  'net.nanopay.security.test.PKCS11KeyStoreManagerTest',
  'net.nanopay.security.test.PKCS12KeyStoreManagerTest',
  'net.nanopay.security.test.UserKeyPairGenerationDAOTest',
  'net.nanopay.security.test.ViewPIIRequestDAOTest',
  'net.nanopay.security.test.RollingJournalTest',

  // receipt
  'net.nanopay.security.receipt.Receipt',
  'net.nanopay.security.receipt.ReceiptGenerator',
  'net.nanopay.security.receipt.ReceiptGeneratingDAO',

  // password entropy
  'net.nanopay.auth.passwordutil.ClientPasswordEntropy',
  'net.nanopay.auth.passwordutil.PasswordEntropy',
  'net.nanopay.auth.passwordutil.PasswordStrengthCalculator',

  // snapshot
  'net.nanopay.security.snapshooter.RollingJournal',
  'net.nanopay.security.snapshooter.RollingJDAO',

  // tests
  'net.nanopay.test.DateAndPlaceOfBirthDAOTest',
  'net.nanopay.test.BranchDAOTest',
  'net.nanopay.test.BranchDAOAuthorizationTest',
  'net.nanopay.test.BusinessSectorDAOTest',

  'net.nanopay.test.ModelledTest',
  'net.nanopay.auth.PublicUserInfoDAOTest',
  'net.nanopay.auth.TestWidget',
  'net.nanopay.auth.ExternalInvoiceTokenTest',
  'net.nanopay.invoice.AuthenticatedInvoiceDAOTest',
  'net.nanopay.test.TestsReporter',
  'net.nanopay.test.TestReport',
  'net.nanopay.tx.alterna.test.EFTTest',
  'net.nanopay.invoice.model.InvoiceTest',
  'net.nanopay.auth.BusinessAgentAuthService',
  'net.nanopay.auth.email.DoNotSolicit',
  'net.nanopay.auth.email.EmailWhitelistEntry',

  'net.nanopay.security.test.HashingJDAOTestModel',
  'net.nanopay.security.test.HashingJDAOTestElement',

  // iso20022 tests
  'net.nanopay.iso20022.ISODateTest',
  'net.nanopay.iso20022.ISODateTimeTest',
  'net.nanopay.iso20022.ISOTimeTest',
  'net.nanopay.tx.ISO20022Transaction',
  'net.nanopay.tx.PacsTransaction',

  // meter
  'net.nanopay.meter.AdminAccessConfig',
  'net.nanopay.meter.Blacklist',
  'net.nanopay.meter.BlacklistEntityType',
  'net.nanopay.meter.IpHistory',
  'net.nanopay.meter.AdditionalDocumentsUpdatedIpHistoryDAO',
  'net.nanopay.meter.SigningOfficerAssignedIpHistoryDAO',
  'net.nanopay.meter.reports.Report',
  'net.nanopay.meter.SkipNullReferencedPropertyDAO',
  'net.nanopay.meter.BusinessStatusContactDAO',

  // report
  'net.nanopay.meter.report.AbliiBusinessReport',
  'net.nanopay.meter.report.AbliiBusinessReportDAO',
  'net.nanopay.meter.report.TransactionReport',
  'net.nanopay.meter.report.PaymentReport',
  'net.nanopay.meter.report.PaymentReportDAO',
  'net.nanopay.meter.report.TransactionHierarchyDAO',
  'net.nanopay.meter.report.PaymentSummaryReport',
  'net.nanopay.meter.report.PaymentSummaryReportDAO',
  'net.nanopay.meter.report.BusinessSummaryReport',
  'net.nanopay.meter.report.BusinessSummaryReportDAO',
  'net.nanopay.meter.report.UserComplianceSummaryReport',
  'net.nanopay.meter.report.UserComplianceSummaryReportDAO',
  'net.nanopay.meter.report.RejectedTransactionReport',
  'net.nanopay.meter.report.RejectedTransactionReportDAO',
  'net.nanopay.meter.report.ReportStatus',

  // clearing
  'net.nanopay.meter.clearing.ClearingTimeService',
  'net.nanopay.meter.clearing.ClearingTimesTrait',
  'net.nanopay.meter.clearing.ruler.BusinessClearingTimeRule',
  'net.nanopay.meter.clearing.ruler.ClearingTimeRule',
  'net.nanopay.meter.clearing.ruler.EstimateTransactionCompletionDate',
  'net.nanopay.meter.clearing.ruler.SimulateTransactionCompletionDate',
  'net.nanopay.meter.clearing.ruler.InstitutionClearingTimeRule',
  'net.nanopay.meter.clearing.ruler.TransactionTypeClearingTimeRule',
  'net.nanopay.meter.clearing.ruler.predicate.DefaultClearingTimeRulePredicate',

  // compliance
  'net.nanopay.meter.compliance.AbstractComplianceRuleAction',
  'net.nanopay.meter.compliance.ComplianceApprovalRequest',
  'net.nanopay.meter.compliance.ComplianceApprovalRequestEffectiveUserRuleAction',
  'net.nanopay.meter.compliance.ComplianceAuthService',
  'net.nanopay.meter.compliance.ComplianceAware',
  'net.nanopay.meter.compliance.ComplianceItem',
  'net.nanopay.meter.compliance.ComplianceValidationStatus',
  'net.nanopay.meter.compliance.ComplianceService',
  'net.nanopay.meter.compliance.NanopayComplianceService',
  'net.nanopay.meter.compliance.SigningOfficerComplianceStatusDAO',
  'net.nanopay.meter.compliance.SigningOfficerComplianceStatusSink',
  'net.nanopay.meter.reports.DateColumnOfReports',
  'net.nanopay.meter.reports.RowOfBusSumReports',

  // ruler
  'net.nanopay.meter.compliance.ruler.RemoveComplianceApprovalRequest',
  'net.nanopay.meter.compliance.ruler.CanadianSanctionValidator',
  'net.nanopay.meter.compliance.ruler.ComplianceTransactionApproval',
  'net.nanopay.meter.compliance.ruler.PruneApprovalRequests',
  'net.nanopay.meter.compliance.ruler.RequestBeneficialOwnersCompliance',
  'net.nanopay.meter.compliance.ruler.RequestSigningOfficersCompliance',
  'net.nanopay.meter.compliance.ruler.ResetLastModified',
  'net.nanopay.meter.compliance.ruler.SecurefactLEVValidator',
  'net.nanopay.meter.compliance.ruler.SecurefactSIDniValidator',
  'net.nanopay.meter.compliance.ruler.UserComplianceApproval',
  'net.nanopay.meter.compliance.ruler.predicate.AbliiSignup',
  'net.nanopay.meter.compliance.ruler.predicate.B2BTransaction',
  'net.nanopay.meter.compliance.ruler.predicate.BeneficialOwnerComplianceRequested',
  'net.nanopay.meter.compliance.ruler.predicate.BusinessComplianceRequested',
  'net.nanopay.meter.compliance.ruler.predicate.BusinessOnboarding',
  'net.nanopay.meter.compliance.ruler.predicate.CanadianBusinessOnboarded',
  'net.nanopay.meter.compliance.ruler.predicate.CanadianUserOnboarded',
  'net.nanopay.meter.compliance.ruler.predicate.DowJonesApprovalRequested',
  'net.nanopay.meter.compliance.ruler.predicate.IsComplianceTransaction',
  'net.nanopay.meter.compliance.ruler.predicate.IsExpediteCICOApprovalRequest',
  'net.nanopay.meter.compliance.ruler.predicate.IsPendingTransaction',
  'net.nanopay.meter.compliance.ruler.predicate.IsCITransaction',
  'net.nanopay.meter.compliance.ruler.predicate.IsCompletedTransaction',
  'net.nanopay.meter.compliance.ruler.predicate.IsRejectedComplianceApprovalRequest',
  'net.nanopay.meter.compliance.ruler.predicate.IsSentTransaction',
  'net.nanopay.meter.compliance.ruler.predicate.LoginSuccess',
  'net.nanopay.meter.compliance.ruler.predicate.RecurringBeneficialOwnerComplianceCheck',
  'net.nanopay.meter.compliance.ruler.predicate.RecurringUserComplianceCheck',
  'net.nanopay.meter.compliance.ruler.predicate.UserCompliancePassedOrFailed',
  'net.nanopay.meter.compliance.ruler.predicate.UserComplianceRequested',
  'net.nanopay.meter.compliance.ruler.CreateRemoveComplianceItemRule',
  'net.nanopay.meter.compliance.ruler.predicate.UserCompliancePassed',
  'net.nanopay.meter.compliance.ruler.AddDomesticCurrencyPermission',
  'net.nanopay.meter.compliance.ruler.AddFXProvisionPayerPermission',
  'net.nanopay.meter.compliance.ruler.predicate.BankAccountVerified',
  'net.nanopay.meter.compliance.ruler.predicate.BankAccountOwnerIsBusiness',
  'net.nanopay.meter.compliance.ruler.predicate.BusinessCreated',
  'net.nanopay.meter.compliance.ruler.predicate.BusinessCompliancePassed',
  'net.nanopay.meter.compliance.ruler.predicate.BusinessNotOnboarded',
  'net.nanopay.meter.compliance.ruler.predicate.BusinessOnboarded',
  'net.nanopay.meter.compliance.ruler.predicate.BusinessHasVerifiedBankAccount',
  'net.nanopay.meter.compliance.ruler.predicate.UserComplianceNotPassed',
  'net.nanopay.meter.compliance.ruler.RemoveDomesticCurrencyPermission',
  'net.nanopay.meter.compliance.ruler.RemoveFXProvisionPayerPermission',
  'net.nanopay.meter.compliance.ruler.NotifyIdentityMindResponseError',

  // canadian sanction
  'net.nanopay.meter.compliance.canadianSanction.Record',

  // securefact
  'net.nanopay.meter.compliance.secureFact.ResponseError',
  'net.nanopay.meter.compliance.secureFact.SecurefactOnboardingService',
  'net.nanopay.meter.compliance.secureFact.ServerSecurefactOnboardingService',
  'net.nanopay.meter.compliance.secureFact.MockSecurefactOnboardingService',
  'net.nanopay.meter.compliance.secureFact.SecurefactRequest',
  'net.nanopay.meter.compliance.secureFact.SecurefactResponse',
  'net.nanopay.meter.compliance.secureFact.SecurefactService',
  'net.nanopay.meter.compliance.secureFact.MockSecurefactService',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniRequest',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniCustomer',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniName',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniAddress',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniPhone',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniErrorComponent',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniResponse',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniAdditionalMatchInfo',
  'net.nanopay.meter.compliance.secureFact.sidni.SIDniDataSources',
  'net.nanopay.meter.compliance.secureFact.lev.LEVApplicant',
  'net.nanopay.meter.compliance.secureFact.lev.LEVChange',
  'net.nanopay.meter.compliance.secureFact.lev.LEVError',
  'net.nanopay.meter.compliance.secureFact.lev.LEVIndividualScores',
  'net.nanopay.meter.compliance.secureFact.lev.LEVRequest',
  'net.nanopay.meter.compliance.secureFact.lev.LEVResponse',
  'net.nanopay.meter.compliance.secureFact.lev.LEVResult',

  // securefact lev document
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVDocumentDataEntity',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVDocumentDataRequest',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVDocumentDataResponse',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVDocumentOrderRequest',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVDocumentOrderResponse',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVDocumentParty',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVDocumentPartyShareClass',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVEntityAddress',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVLastDocumentFiled',
  'net.nanopay.meter.compliance.secureFact.lev.document.LEVNatureOfBusiness',

  // dow jones
  'net.nanopay.meter.compliance.dowJones.enums.ContentSet',
  'net.nanopay.meter.compliance.dowJones.enums.FilterAMC',
  'net.nanopay.meter.compliance.dowJones.enums.FilterOEL',
  'net.nanopay.meter.compliance.dowJones.enums.FilterOOL',
  'net.nanopay.meter.compliance.dowJones.enums.FilterPEP',
  'net.nanopay.meter.compliance.dowJones.enums.FilterRegion',
  'net.nanopay.meter.compliance.dowJones.enums.FilterRegionKeys',
  'net.nanopay.meter.compliance.dowJones.enums.FilterSIC',
  'net.nanopay.meter.compliance.dowJones.enums.FilterSL',
  'net.nanopay.meter.compliance.dowJones.enums.FilterSOC',
  'net.nanopay.meter.compliance.dowJones.enums.IDTypeKey',
  'net.nanopay.meter.compliance.dowJones.enums.MatchType',
  'net.nanopay.meter.compliance.dowJones.enums.RecordType',
  'net.nanopay.meter.compliance.dowJones.enums.SearchType',
  'net.nanopay.meter.compliance.dowJones.AbstractDowJonesComplianceRuleAction',
  'net.nanopay.meter.compliance.dowJones.DowJonesInvalidResponse',
  'net.nanopay.meter.compliance.dowJones.DowJonesRequest',
  'net.nanopay.meter.compliance.dowJones.DowJonesResponse',
  'net.nanopay.meter.compliance.dowJones.DowJonesResponseBody',
  'net.nanopay.meter.compliance.dowJones.BeneficialOwnerSanctionValidator',
  'net.nanopay.meter.compliance.dowJones.ClientDowJonesService',
  'net.nanopay.meter.compliance.dowJones.DowJonesApprovalRequest',
  'net.nanopay.meter.compliance.dowJones.DowJonesApprovalRequestRule',
  'net.nanopay.meter.compliance.dowJones.DowJonesCall',
  'net.nanopay.meter.compliance.dowJones.DowJonesCredentials',
  'net.nanopay.meter.compliance.dowJones.DowJones',
  'net.nanopay.meter.compliance.dowJones.DowJonesRestInterface',
  'net.nanopay.meter.compliance.dowJones.EntitySanctionValidator',
  'net.nanopay.meter.compliance.dowJones.EntityNameSearchData',
  'net.nanopay.meter.compliance.dowJones.EntityNameSearchRequest',
  'net.nanopay.meter.compliance.dowJones.IDTypeSearchRequest',
  'net.nanopay.meter.compliance.dowJones.Match',
  'net.nanopay.meter.compliance.dowJones.MatchedName',
  'net.nanopay.meter.compliance.dowJones.MatchPayload',
  'net.nanopay.meter.compliance.dowJones.MetadataSearchResponse',
  'net.nanopay.meter.compliance.dowJones.NameSearchRequest',
  'net.nanopay.meter.compliance.dowJones.PersonSanctionValidator',
  'net.nanopay.meter.compliance.dowJones.PersonNameSearchData',
  'net.nanopay.meter.compliance.dowJones.PersonNameSearchRequest',

  // identitymind
  'net.nanopay.meter.compliance.identityMind.AbstractIdentityMindComplianceRuleAction',
  'net.nanopay.meter.compliance.identityMind.AutomatedReviewEngineResult',
  'net.nanopay.meter.compliance.identityMind.ComplianceTransactionValidator',
  'net.nanopay.meter.compliance.identityMind.ConditionResult',
  'net.nanopay.meter.compliance.identityMind.ConsumerKYCValidator',
  'net.nanopay.meter.compliance.identityMind.EntityLoginValidator',
  'net.nanopay.meter.compliance.identityMind.ExternalizedEvaluationResult',
  'net.nanopay.meter.compliance.identityMind.ExternalizedRule',
  'net.nanopay.meter.compliance.identityMind.MerchantKYCValidator',
  'net.nanopay.meter.compliance.identityMind.IdentityMindRequest',
  'net.nanopay.meter.compliance.identityMind.IdentityMindResponse',
  'net.nanopay.meter.compliance.identityMind.IdentityMindResponseEDNA',
  'net.nanopay.meter.compliance.identityMind.IdentityMindService',

  // meter tests
  'net.nanopay.meter.test.BlockDisabledUserTransactionTest',
  'net.nanopay.meter.test.BlockDisabledUserInvoiceTest',
  'net.nanopay.meter.test.ComplianceAwareDummy',

  //screening response
  'net.nanopay.meter.compliance.ruler.CreateScreeningResponse',
  'net.nanopay.meter.report.ScreeningResponseCounter',
  'net.nanopay.meter.report.ScreeningResponseType',

  'net.nanopay.security.auth.LogoutDisabledUserDAO',

  // business
  'net.nanopay.business.EnforceOneBusinessAdminDAO',
  'net.nanopay.business.JoinBusinessTokenService',
  'net.nanopay.business.DeleteAgentJunctionsOnUserDeleteDAO',
  'net.nanopay.business.SetBusinessNameDAO',
  'net.nanopay.business.ruler.JunctionNotificationSettingsRule',
  'net.nanopay.business.ruler.RegistrationLoginDisabledRule',
  'net.nanopay.business.ruler.businessCapabilitySetUp',
  'net.nanopay.business.ruler.InitialBusinessRegistrationRule',

  // settlment Report service
  'net.nanopay.invoice.InvoiceFilteredSettlementReport',

  // BMO EFT integration
  'net.nanopay.tx.bmo.eftfile.BmoBatchControl',
  'net.nanopay.tx.bmo.eftfile.BmoBatchHeader',
  'net.nanopay.tx.bmo.eftfile.BmoBatchRecord',
  'net.nanopay.tx.bmo.eftfile.BmoDetailRecord',
  'net.nanopay.tx.bmo.eftfile.BmoEftFile',
  'net.nanopay.tx.bmo.eftfile.BmoFileControl',
  'net.nanopay.tx.bmo.eftfile.BmoFileHeader',
  'net.nanopay.tx.bmo.BmoAssignedClientValue',
  'net.nanopay.tx.bmo.cico.BmoCITransaction',
  'net.nanopay.tx.bmo.cico.BmoCOTransaction',
  'net.nanopay.tx.bmo.cico.BmoInterTrustTransaction',
  'net.nanopay.tx.bmo.cico.BmoTransaction',
  'net.nanopay.tx.bmo.cico.BmoVerificationTransaction',
  'net.nanopay.tx.bmo.BmoSFTPCredential',
  'net.nanopay.tx.bmo.BmoReferenceNumber',
  'net.nanopay.tx.bmo.BmoTransactionHistory',

  // file ingestion
  'net.nanopay.tx.gs.GsTxCsvRow',
  'net.nanopay.tx.gs.GsRowToTx',
  'net.nanopay.script.CsvUploadScript',
  'net.nanopay.tx.gs.GsTxAssembly',
  'net.nanopay.tx.gs.ProgressBarData',
  'net.nanopay.tx.gs.GSReportAssembly',

  // RBC
  'net.nanopay.tx.rbc.RbcCITransaction',
  'net.nanopay.tx.rbc.RbcCOTransaction',
  'net.nanopay.tx.rbc.RbcInterTrustTransaction',
  'net.nanopay.tx.rbc.RbcVerificationTransaction',
  'net.nanopay.tx.rbc.ftps.RbcFTPSCredential',
  'net.nanopay.tx.rbc.RBCTransactionISO20022Util',
  'net.nanopay.tx.rbc.RbcAssignedClientValue',
  'net.nanopay.tx.rbc.RbcReferenceNumber',
  'net.nanopay.tx.rbc.iso20022file.RbcBatchRecord',
  'net.nanopay.tx.rbc.iso20022file.RbcRecord',
  'net.nanopay.tx.rbc.iso20022file.RbcCIRecord',
  'net.nanopay.tx.rbc.iso20022file.RbcCORecord',
  'net.nanopay.tx.rbc.iso20022file.RbcBatchControl',
  'net.nanopay.tx.rbc.iso20022file.RbcTransmissionHeader',

  //Request to Pay
  'net.nanopay.tx.RequestMoney',
  'net.nanopay.tx.RequestMoneyResponse',
  'net.nanopay.tx.RequestMoneyDAO',

  // Ticket
  'net.nanopay.ticket.SudoTicket',
  'net.nanopay.ticket.SudoTicketApprovalRequestRule',
  'net.nanopay.ticket.SudoTicketApprovalRequestAction',
  'net.nanopay.ticket.SudoTicketApprovalResponseRule',
  'net.nanopay.ticket.SudoTicketApprovalResponseAction',
  'net.nanopay.ticket.test.SudoTicketTest',

  // Planners
  'net.nanopay.tx.planner.PlannerGroup',
  'net.nanopay.tx.planner.SummaryPopulatorDAO',
  'net.nanopay.tx.planner.CorridorQuoteDAO',
  'net.nanopay.tx.planner.TransactionQuotingDAO',
  'net.nanopay.tx.planner.AbstractTransactionPlanner',
  'net.nanopay.tx.planner.ExamplePlanner',
  'net.nanopay.tx.planner.DigitalTransactionPlanner',
  'net.nanopay.tx.planner.GenericCIPlanner',
  'net.nanopay.tx.planner.GenericCOPlanner',
  'net.nanopay.tx.planner.GenericFXPlanner',
  'net.nanopay.tx.planner.predicate.FXPlannerPredicate',
  'net.nanopay.tx.planner.predicate.IsAccountOwnerAFEXUserPredicate',
  'net.nanopay.tx.planner.predicate.ProviderPredicate',
  'net.nanopay.tx.planner.predicate.IsAscendantFXUserPredicate',
  'net.nanopay.tx.planner.predicate.SameUserTxnPredicate',
  'net.nanopay.tx.planner.predicate.CheckReserveAccountFor',
  'net.nanopay.tx.planner.predicate.HasSameReserveAccount',
  'net.nanopay.tx.planner.AscendantFXTransactionPlanner',
  'net.nanopay.tx.planner.KotakSplitTransactionPlanner',
  'net.nanopay.tx.planner.KotakFxTransactionPlanner',
  'net.nanopay.tx.planner.KotakTransactionPlanner',
  'net.nanopay.tx.planner.DVPPlanner',
  'net.nanopay.tx.planner.FOPPlanner',
  'net.nanopay.tx.planner.RbcCITransactionPlanner',
  'net.nanopay.tx.planner.RbcCOTransactionPlanner',
  'net.nanopay.tx.planner.RbcVerificationTransactionPlanner',
  'net.nanopay.tx.planner.SecurityCIPlanner',
  'net.nanopay.tx.planner.SecurityCOPlanner',
  'net.nanopay.tx.planner.SecurityBucketPlanner',
  'net.nanopay.tx.planner.BankDigitalPlanner',
  'net.nanopay.tx.planner.DigitalBankPlanner',
  'net.nanopay.tx.planner.BankToBankPlanner',
  'net.nanopay.tx.planner.IntuitBankToBankPlanner',
  'net.nanopay.tx.planner.VerificationPlanner',
  'net.nanopay.tx.planner.AlternaCITransactionPlanner',
  'net.nanopay.tx.planner.AlternaCOTransactionPlanner',
  'net.nanopay.tx.planner.BmoCITransactionPlanner',
  'net.nanopay.tx.planner.BmoCOTransactionPlanner',
  'net.nanopay.tx.planner.BulkTransactionPlanner',
  'net.nanopay.tx.planner.NanopayFXTransactionPlanner',
  'net.nanopay.tx.planner.LoanTransactionPlanner',
  'net.nanopay.tx.planner.AFEXTransactionPlanner',
  'net.nanopay.tx.planner.DebtRepaymentPlanner',
  'net.nanopay.tx.planner.DebtablePlanner',
  'net.nanopay.tx.planner.IntermediaryDestinationAccountSplitPlanner',
  'net.nanopay.tx.planner.PlanSavingDAO',
  'net.nanopay.tx.planner.AccessPlannerDAO',
  'net.nanopay.tx.planner.TransactionPlan',
  'net.nanopay.tx.planner.TransactionPlannerBlockDAO',
  'net.nanopay.tx.planner.TransactionQuoteDAO',
  'net.nanopay.tx.planner.QuoteFillerDAO',
  'net.nanopay.tx.planner.PlanNotFoundException',
  'net.nanopay.tx.planner.UnableToPlanException',
  'net.nanopay.tx.planner.InterTrustPlanner',
  'net.nanopay.tx.planner.RbcInterTrustPlanner',
  'net.nanopay.tx.planner.BmoInterTrustPlanner',
  'net.nanopay.tx.planner.PartialPlanDAO',

  // Planner Exceptions
  'net.nanopay.tx.planner.exceptions.PlannerValidationException',
  'net.nanopay.tx.planner.exceptions.PlannerCapabilityIncompleteException',
  'net.nanopay.tx.planner.exceptions.PlannerComplianceFailureException',
  'net.nanopay.tx.planner.exceptions.PlannerStatusInactiveException',

  // Billing
  'net.nanopay.tx.billing.Bill',
  'net.nanopay.tx.billing.BillingFee',
  'net.nanopay.tx.billing.BillingServiceInterface',
  'net.nanopay.tx.billing.ChargeDateServiceInterface',
  'net.nanopay.tx.billing.ClientBillingService',
  'net.nanopay.tx.billing.CreateBillsRule',
  'net.nanopay.tx.billing.ErrorFee',

  // Fees
  'net.nanopay.tx.fee.Fee',
  'net.nanopay.tx.fee.FeeExpr',
  'net.nanopay.tx.fee.FeeRateExpr',
  'net.nanopay.tx.fee.FeeType',
  'net.nanopay.tx.fee.FixedFee',
  'net.nanopay.tx.fee.InformationalFee',
  'net.nanopay.tx.fee.PercentageFee',
  'net.nanopay.tx.fee.Rate',
  'net.nanopay.tx.fee.SpotRate',
  'net.nanopay.tx.fee.TransactionFeeRule',
  'net.nanopay.tx.fee.predicate.HasLineItemPredicate',
  'net.nanopay.tx.fee.predicate.IsDomesticTransaction',
  'net.nanopay.tx.fee.predicate.PaymentCorridorPredicate',
  'net.nanopay.tx.fee.test.TransactionFeeRuleTest',
  'net.nanopay.country.br.tx.fee.PTaxRate',

  // Treviso
  'net.nanopay.country.br.CNPJCache',
  'net.nanopay.country.br.CPFCache',
  'net.nanopay.country.br.ExpiredValidationDAO',
  'net.nanopay.country.br.NatureCode',
  'net.nanopay.country.br.NatureCodeData',
  'net.nanopay.country.br.NatureCodeApprovalRequest',
  'net.nanopay.country.br.ApprovedNatureCodeApprovalRequestRuleAction',
  'net.nanopay.country.br.CapableCreateNatureCodeApprovalsRuleAction',
  'net.nanopay.country.br.BrazilBusinessInfoData',
  'net.nanopay.country.br.BrazilVerificationServiceInterface',
  'net.nanopay.country.br.ClientBrazilVerificationService',
  'net.nanopay.country.br.CNAE',
  'net.nanopay.country.br.CNAEClient',
  'net.nanopay.country.br.CNAEDivision',
  'net.nanopay.country.br.CNAEGroup',
  'net.nanopay.country.br.CNAESection',
  'net.nanopay.country.br.CPF',
  'net.nanopay.country.br.crunch.ExchangeServiceOnboardingRule',
  'net.nanopay.country.br.exchange.ArrayOfBoleto',
  'net.nanopay.country.br.exchange.ArrayOfNatureza',
  'net.nanopay.country.br.exchange.ArrayOfParcelas',
  'net.nanopay.country.br.exchange.BancoConfig',
  'net.nanopay.country.br.exchange.Boleto',
  'net.nanopay.country.br.exchange.BoletoStatusResponse',
  'net.nanopay.country.br.exchange.BoletoStatusResult',
  'net.nanopay.country.br.exchange.CotacaoTaxaCambio',
  'net.nanopay.country.br.exchange.CotacaoTaxaCambioResponse',
  'net.nanopay.country.br.exchange.Exchange',
  'net.nanopay.country.br.exchange.ExchangeClientValues',
  'net.nanopay.country.br.exchange.ExchangeCredential',
  'net.nanopay.country.br.exchange.ExchangeCustomer',
  'net.nanopay.country.br.exchange.ExchangeService',
  'net.nanopay.country.br.exchange.GetBoletoStatus',
  'net.nanopay.country.br.exchange.GetCotacaoTaxaCambio',
  'net.nanopay.country.br.exchange.InsertBoleto',
  'net.nanopay.country.br.exchange.InsertBoletoResponse',
  'net.nanopay.country.br.exchange.InsertTitular',
  'net.nanopay.country.br.exchange.InsertTitularResponse',
  'net.nanopay.country.br.exchange.Moeda',
  'net.nanopay.country.br.exchange.Natureza',
  'net.nanopay.country.br.exchange.Pais',
  'net.nanopay.country.br.exchange.Parcelas',
  'net.nanopay.country.br.exchange.ResponseBoleto',
  'net.nanopay.country.br.exchange.ResponseCotacaoTaxa',
  'net.nanopay.country.br.exchange.ResponseTitular',
  'net.nanopay.country.br.exchange.ResponseMoeda',
  'net.nanopay.country.br.exchange.ResponseNatureza',
  'net.nanopay.country.br.exchange.ResponsePais',
  'net.nanopay.country.br.exchange.SearchMoeda',
  'net.nanopay.country.br.exchange.SearchMoedaResponse',
  'net.nanopay.country.br.exchange.SearchNatureza',
  'net.nanopay.country.br.exchange.SearchNaturezaResponse',
  'net.nanopay.country.br.exchange.SearchPais',
  'net.nanopay.country.br.exchange.SearchPaisResponse',
  'net.nanopay.country.br.exchange.SearchTitular',
  'net.nanopay.country.br.exchange.SearchTitularCapFin',
  'net.nanopay.country.br.exchange.SearchTitularCapFinResponse',
  'net.nanopay.country.br.exchange.SearchTitularResponse',
  'net.nanopay.country.br.exchange.ServiceStatus',
  'net.nanopay.country.br.exchange.SearchBoleto',
  'net.nanopay.country.br.exchange.SearchBoletoResponse',
  'net.nanopay.country.br.exchange.Titular',
  'net.nanopay.country.br.exchange.UpdateTitular',
  'net.nanopay.country.br.exchange.UpdateTitularResponse',
  'net.nanopay.country.br.ExpectedBoardingDate',
  'net.nanopay.country.br.NatureCode',
  'net.nanopay.country.br.NatureCodeRate',
  'net.nanopay.country.br.NatureBusinessRelationship',
  'net.nanopay.country.br.OpenData',
  'net.nanopay.country.br.PTaxRate',
  'net.nanopay.country.br.PTaxDollarRateResponse',
  'net.nanopay.country.br.tx.NatureCodeLineItem',
  'net.nanopay.partner.bmo.BMOPaymentProviderCapabilityRule',
  'net.nanopay.partner.intuit.tx.IntuitTransactionSummary',
  'net.nanopay.partner.rbc.RBCPaymentProviderCapabilityRule',
  'net.nanopay.partner.soawebservices.PessoaFisicaNFe',
  'net.nanopay.partner.soawebservices.PessoaJuridicaNFe',
  'net.nanopay.partner.soawebservices.PessoaResponse',
  'net.nanopay.partner.soawebservices.SoaCredenciais',
  'net.nanopay.partner.soawebservices.SoaWebService',
  'net.nanopay.partner.soawebservices.Transacao',
  'net.nanopay.partner.sintegra.CPFResponseData',
  'net.nanopay.partner.sintegra.CNPJResponseData',
  'net.nanopay.partner.sintegra.Sintegra',
  'net.nanopay.partner.treviso.api.Address',
  'net.nanopay.partner.treviso.api.BusinessUnit',
  'net.nanopay.partner.treviso.api.ClientStatus',
  'net.nanopay.partner.treviso.api.CounterPartType',
  'net.nanopay.partner.treviso.api.CurrentPlatform',
  'net.nanopay.partner.treviso.api.Document',
  'net.nanopay.partner.treviso.api.DocumentFormalization',
  'net.nanopay.partner.treviso.api.DocumentImage',
  'net.nanopay.partner.treviso.api.DocumentType',
  'net.nanopay.partner.treviso.api.EconomicGroup',
  'net.nanopay.partner.treviso.api.Entity',
  'net.nanopay.partner.treviso.api.FormOperationType',
  'net.nanopay.partner.treviso.api.FormParameter',
  'net.nanopay.partner.treviso.api.FepWebResponse',
  'net.nanopay.partner.treviso.api.GetDocumentTypeRequest',
  'net.nanopay.partner.treviso.api.GetDocumentTypeResponse',
  'net.nanopay.partner.treviso.api.LoginRequest',
  'net.nanopay.partner.treviso.api.LoginResponse',
  'net.nanopay.partner.treviso.api.Product',
  'net.nanopay.partner.treviso.api.ResponsibleArea',
  'net.nanopay.partner.treviso.api.RmUser',
  'net.nanopay.partner.treviso.api.SaveEntityRequest',
  'net.nanopay.partner.treviso.api.SaveUserFillerRequest',
  'net.nanopay.partner.treviso.api.Segment',
  'net.nanopay.partner.treviso.api.SearchCustomerRequest',
  'net.nanopay.partner.treviso.api.SearchCustomerResponse',
  'net.nanopay.partner.treviso.api.Signatory',
  'net.nanopay.partner.treviso.api.Template',
  'net.nanopay.partner.treviso.api.FepWeb',
  'net.nanopay.partner.treviso.api.UserFillerDTO',
  'net.nanopay.partner.treviso.api.Workflow',
  'net.nanopay.partner.treviso.FepWebClient',
  'net.nanopay.partner.treviso.FepWebOnboardingRule',
  'net.nanopay.partner.treviso.FepWebUserUpdatingRule',
  'net.nanopay.partner.treviso.TrevisoCredientials',
  'net.nanopay.partner.treviso.TrevisoServiceInterface',
  'net.nanopay.partner.treviso.FepWebOnboardingRule',
  'net.nanopay.partner.treviso.tx.TrevisoTransaction',
  'net.nanopay.partner.treviso.tx.planner.TrevisoTransactionPlanner',
  'net.nanopay.partner.treviso.tx.TrevisoCreateExchange',
  'net.nanopay.tx.EtaSummaryTransactionLineItem',
  'net.nanopay.country.br.NatureCodePaymentProviderJunction',
  'net.nanopay.tx.ExpirySummaryTransactionLineItem',
  'net.nanopay.partner.treviso.TrevisoUnlockPaymentTermsAndConditions',
  'net.nanopay.partner.treviso.invoice.TrevisoCapabilityValidateRule',
  'net.nanopay.partner.treviso.invoice.UpdateTransactionOnInvoiceValidationRule',
  'net.nanopay.partner.treviso.invoice.TrevisoNotificationRule',
  'net.nanopay.partner.treviso.TrevisoSendEmailToAllRule',
  'net.nanopay.partner.treviso.onboarding.BusinessDirectorsData',
  'net.nanopay.partner.treviso.onboarding.BRBusinessDirector',
  'net.nanopay.partner.treviso.onboarding.BRBeneficialOwner',
  'net.nanopay.partner.treviso.onboarding.BRBusinessOwnershipData',
  'net.nanopay.partner.treviso.onboarding.BRBankAccountData',
  'net.nanopay.partner.treviso.TrevisoSendEmailToAllNotification',
  'net.nanopay.partner.treviso.invoice.TrevisoNotification',
  'net.nanopay.partner.treviso.report.TrevisoTransactionReport',
  'net.nanopay.partner.treviso.report.TrevisoTransactionReportDAO',
  'net.nanopay.partner.treviso.fx.Cotacoes',
  'net.nanopay.partner.treviso.fx.EnfoqueResponse',
  'net.nanopay.partner.treviso.fx.TrevisoFXService',
  'net.nanopay.partner.treviso.fx.TrevisoFXServiceMock',

  'net.nanopay.partner.br.businessSector.Sector',
  'net.nanopay.partner.br.businessSector.Grupo',
  'net.nanopay.partner.br.businessSector.Divisao',
  'net.nanopay.partner.br.businessSector.Secao',

  // Reporting
  'net.nanopay.reporting.ReconciliationReport',
  'net.nanopay.reporting.ReducedReconciliationReport',
  'net.nanopay.reporting.ServiceFeesReport',
  'net.nanopay.reporting.UserOnboardingReport',

  // bepay
  'net.nanopay.partner.bepay.tx.BePayTransaction',
  'net.nanopay.country.br.tx.PartnerLineItem',
  'net.nanopay.country.br.tx.PartnerReport',
  'net.nanopay.partner.bepay.tx.planner.BePayTransactionPlanner',
  'net.nanopay.partner.bepay.tx.ScreenUsersOnTransactionCreate',

  // accuity
  'net.nanopay.partner.accuity.AccuityCredentials',
  'net.nanopay.partner.accuity.AccuityAPIResponse',
  'net.nanopay.partner.accuity.AccuityBankAccountValidationService',


  // crunch predicates - todo move all predicates used in crunch here
  'net.nanopay.crunch.predicate.IsBusiness',
  'net.nanopay.crunch.predicate.BusinessPassedCompliance',
  'net.nanopay.crunch.predicate.CheckUserCountry',
  'net.nanopay.crunch.predicate.HasVerifiedBankAccount',
  'net.nanopay.crunch.predicate.SigningOfficerQuestionAnswered',
  'net.nanopay.crunch.predicate.SigningOfficerCapabilityInterceptPredicate',
  'net.nanopay.crunch.predicate.SigningOfficerPrivilegesRequested',
  'net.nanopay.crunch.predicate.UserIsSigningOfficerOfBusiness',
  'net.nanopay.crunch.IsSpid',
  'net.nanopay.crunch.ruler.PermissionedUCJRule',

  // crunch onboarding
  'net.nanopay.crunch.onboardingModels.InitialBusinessData',
  'net.nanopay.crunch.onboardingModels.SigningOfficerPersonalData',
  'net.nanopay.partner.treviso.SigningOfficerPersonalDataTreviso',
  'net.nanopay.crunch.onboardingModels.SigningOfficerQuestion',
  'net.nanopay.crunch.onboardingModels.SigningOfficerQuestionOnPut',
  'net.nanopay.crunch.onboardingModels.SigningOfficerPersonalDataOnPut',
  'net.nanopay.crunch.onboardingModels.SigningOfficerByDefaultRule',
  'net.nanopay.crunch.onboardingModels.BusinessInformationData',
  'net.nanopay.crunch.onboardingModels.BusinessTypeAndSector',
  'net.nanopay.crunch.onboardingModels.BusinessOwnershipData',
  'net.nanopay.crunch.onboardingModels.IsPubliclyTradedQuestion',
  'net.nanopay.crunch.onboardingModels.TransactionDetailsData',
  'net.nanopay.crunch.onboardingModels.BusinessDirectorsData',
  'net.nanopay.crunch.onboardingModels.CertifyDataReviewed',
  'net.nanopay.crunch.BusinessOwnershipToBeneficialOwnerDAO',
  'net.nanopay.crunch.onboardingModels.UserBirthDateData',
  'net.nanopay.crunch.onboardingModels.BusinessRegistrationDateData',
  'net.nanopay.crunch.onboardingModels.BusinessLastRegistrationDateData',
  'net.nanopay.crunch.onboardingModels.BusinessIncorporationDateData',
  'net.nanopay.crunch.onboardingModels.TaxIdNumberData',
  'net.nanopay.partner.treviso.TrevisoBusinessAccountData',
  'net.nanopay.partner.treviso.BusinessFundingEnum',
  'net.nanopay.partner.treviso.PrimaryCapitalSourceEnum',
  'net.nanopay.partner.treviso.TrevisoCurrencyAmountInformation',
  'net.nanopay.crunch.onboardingModels.CustomerBasicInformation',

  // crunch notification
  'net.nanopay.crunch.UCJExpiryReminderCron',
  'net.nanopay.crunch.compliance.SendExpiryNotificationRule',

  'net.nanopay.crunch.test.TestCapable',
  'net.nanopay.crunch.test.TestCapableDAO',

  // crunch compliance
  'net.nanopay.crunch.compliance.SetComplianceOnUser',
  'net.nanopay.crunch.compliance.SetComplianceOnBusiness',
  'net.nanopay.crunch.compliance.SetBusinessStatusAction',
  'net.nanopay.crunch.compliance.IsCapabilityOfCertainCategoryAndStatus',
  'net.nanopay.crunch.compliance.IsCapabilityReviewRequired',
  'net.nanopay.crunch.compliance.PassCompliance',
  'net.nanopay.crunch.compliance.PersonSanctionValidator',
  'net.nanopay.crunch.compliance.EntitySanctionValidator',
  'net.nanopay.crunch.compliance.BusinessDirectorSanctionValidator',
  'net.nanopay.crunch.compliance.BeneficialOwnerSanctionValidator',
  'net.nanopay.crunch.compliance.SecurefactSIDniValidator',
  'net.nanopay.crunch.compliance.SecurefactLEVValidator',
  'net.nanopay.crunch.compliance.SendNotificationOnPut',
  'net.nanopay.crunch.compliance.UserComplianceApproval',
  'net.nanopay.crunch.compliance.SetFulfilledComplianceApprovalRequest',
  'net.nanopay.crunch.compliance.GenericSigningOfficerValidator',
  'net.nanopay.crunch.compliance.GenericBusinessValidator',
  'net.nanopay.crunch.compliance.AbstractManualValidator',
  'net.nanopay.crunch.compliance.ManualConsumerKYCValidator',
  'net.nanopay.crunch.compliance.ManualEntitySanctionValidator',
  'net.nanopay.crunch.compliance.ManualMerchantKYCValidator',
  'net.nanopay.crunch.compliance.ManualPersonSanctionValidator',
  'net.nanopay.crunch.compliance.ManualSecurefactSIDniValidator',
  'net.nanopay.crunch.compliance.ManualSecurefactLEVValidator',

  'net.nanopay.partner.afex.AFEXDigitalAccount',

  // crunch afex
  'net.nanopay.partner.afex.crunch.AFEXBusinessOnboardingRule',
  'net.nanopay.partner.afex.crunch.AFEXUserOnboardingRule',
  'net.nanopay.partner.afex.crunch.BusinessHasVerifiedBankAccount',
  'net.nanopay.partner.afex.crunch.BankAccountOwnerIsBusiness',

  // crunch acceptance
  'net.nanopay.crunch.acceptanceDocuments.capabilities.TriPartyAgreementCAD',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.TriPartyAgreementUSD',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.DualPartyAgreementCAD',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AbliiTermsAndConditions',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AbliiPrivacyPolicy',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.CADAFEXTerms',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.USDAFEXTerms',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.NanopayInternationalPaymentsCustomerAgreement',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.CertifyOwnersPercent',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.CertifyBankAccountOwnership',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.CertifyDirectorsListed',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AFXMassachusettsDisclosure',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AFXNewYorkDisclosure',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AFXWashingtonDisclosure',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AFXArizonaDisclosure',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AFXCaliforniaDisclosure',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.AFXColoradoDisclosure',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.CABankAccountAuthAgreement',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.RecourseAgreement',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.ThirdPartyVerificationAFEXTerms',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.CACancellationAgreement',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.USBankAccountAuthAgreement',
  'net.nanopay.crunch.acceptanceDocuments.capabilities.USCancellationAgreement',
  'net.nanopay.crunch.acceptanceDocuments.BaseAcceptanceDocumentCapability',

  // crunch registration
  'net.nanopay.crunch.registration.BusinessDetailData',
  'net.nanopay.crunch.registration.BusinessDetailExpandedData',
  'net.nanopay.crunch.registration.BusinessDirectorList',
  'net.nanopay.crunch.registration.BusinessOwnerList',
  'net.nanopay.crunch.registration.IsSelectedData',
  'net.nanopay.crunch.registration.LimitedAmountCapability',
  'net.nanopay.crunch.registration.PersonalOnboardingTypeData',
  'net.nanopay.crunch.registration.SigningOfficerList',
  'net.nanopay.crunch.registration.UserRegistrationData',
  'net.nanopay.crunch.registration.UserDetailData',
  'net.nanopay.crunch.registration.UserDetailExpandedData',
  'net.nanopay.crunch.registration.businesstypes.BusinessTypeData',
  'net.nanopay.crunch.registration.businesstypes.CorporationData',
  'net.nanopay.crunch.registration.businesstypes.LimitedLiabilityData',
  'net.nanopay.crunch.registration.businesstypes.NonprofitData',
  'net.nanopay.crunch.registration.businesstypes.PartnershipData',
  'net.nanopay.crunch.registration.businesstypes.PubliclyTradedData',
  'net.nanopay.crunch.registration.businesstypes.SoleProprietorData',
  'net.nanopay.crunch.registration.businesstypes.TrustData',

  // crunch documents
  'net.nanopay.crunch.document.Document',
  'net.nanopay.crunch.document.ExpirableDocument',
  'net.nanopay.crunch.document.DateOfIssue',

  // crunch wizardlet
  'net.nanopay.crunch.wizardlet.SigningOfficerQuestionWizardlet',
  'net.nanopay.crunch.wizardlet.RefreshWizardlet',
  'net.nanopay.crunch.wizardlet.UnlockPaymentsWizardConfig',
  'net.nanopay.crunch.wizardlet.BusinessRegistrationWizardConfig',
  'net.nanopay.crunch.wizardlet.SigningOfficerWizardConfig',


  // Notification
  'net.nanopay.notification.PermissionedNotificationSettingRule',
  'net.nanopay.notification.TriggerNotificationTestAction',
  'net.nanopay.notification.TriggerDoNotifyTestAction',

  // msp
  'net.nanopay.msp.MspInfo',
  'net.nanopay.msp.MspSetupDAO',

  // exchange limit
  'net.nanopay.country.br.tx.ruler.ExchangeLimitTransactionRule',
  'net.nanopay.country.br.tx.ExchangeLimitTransaction',
  'net.nanopay.country.br.tx.ExchangeLimitTransactionCronAgent',
  'net.nanopay.country.br.tx.ExchangeLimitTransactionCronAgentSink',

  // DAO decorators
  'net.nanopay.account.AbliiBankAccountAutoverifyDAO',
  'net.nanopay.account.AuthenticatedAccountDAO',
  'net.nanopay.admin.AccountStatusUserDAO',
  'net.nanopay.approval.ApprovalRequestNotificationDAO',
  'net.nanopay.approval.AuthenticatedApprovalDAO',
  'net.nanopay.auth.PublicUserInfoDAO',
  'net.nanopay.auth.email.EmailVerificationDAO',
  'net.nanopay.bank.AscendantFXBankAccountDAO',
  'net.nanopay.bank.BankAccountBranchDAO',
  'net.nanopay.bank.BankAccountInstitutionDAO',
  'net.nanopay.bank.CanReceiveCurrencyDAO',
  'net.nanopay.bank.GetDefaultCurrencyDAO',
  'net.nanopay.bank.RandomDepositBankAccountDAO',
  'net.nanopay.cico.paymentCard.DuplicatePaymentCard',
  'net.nanopay.cico.paymentCard.NetworkedPaymentCardDAO',
  'net.nanopay.cico.paymentCard.PaymentCardSanitizeDAO',
  'net.nanopay.cico.paymentCard.PaymentCardTransientDAO',
  'net.nanopay.cico.paymentCard.RealexPaymentCardStoreDAO',
  'net.nanopay.cico.paymentCard.RealexVerificationPaymentCardDAO',
  'net.nanopay.cico.paymentCard.StripePaymentCardDAO',
  'net.nanopay.cico.paymentCard.ValidatedPaymentCardDAO',
  'net.nanopay.contacts.AddExternalContactToken',
  'net.nanopay.contacts.CheckContactExistingTransaction',
  'net.nanopay.contacts.InvoiceToContactDAO',
  'net.nanopay.contacts.PreventDuplicateContactEmailDAO',
  'net.nanopay.contacts.UpdateSignUpStatusDAO',
  'net.nanopay.fx.afex.AFEXContactDAO',
  'net.nanopay.fx.ascendantfx.AscendantFXTransactionDAO',
  'net.nanopay.invoice.AuthenticatedInvoiceDAO',
  'net.nanopay.invoice.AutoDepositPendingAcceptance',
  'net.nanopay.invoice.PreventRemoveInvoiceDAO',
  'net.nanopay.onboarding.CreateBusinessDAO',
  'net.nanopay.onboarding.NewUserCreateBusinessDAO',
  'net.nanopay.onboarding.UpdateOnboardingDAO',
  'net.nanopay.onboarding.UserRegistrationDAO',
  'net.nanopay.onboarding.email.RegistrationSubmissionEmailDAO',
  'net.nanopay.partners.AuthenticatedInvitationDAO',
  'net.nanopay.partners.AuthenticatedUserUserJunctionDAO',
  'net.nanopay.partners.MakeConnectionDAO',
  'net.nanopay.partners.PartnerInfoDAO',
  'net.nanopay.partners.SendInvitationDAO',
  'net.nanopay.payment.PayrollDAO',
  'net.nanopay.retail.AuthenticatedP2PTxnRequestDAO',
  'net.nanopay.retail.ExistingP2PTxnRequestDAO',
  'net.nanopay.retail.NewP2PTxnRequestDAO',
  'net.nanopay.retail.P2PTxnRequestNotificationDAO',
  'net.nanopay.retail.P2PTxnRequestUserInfoDAO',
  'net.nanopay.retail.PreventDuplicateDeviceDAO',
  'net.nanopay.security.pii.AuthenticatedPIIRequestDAO',
  'net.nanopay.sme.BusinessInvitationDAO',
  'net.nanopay.tx.AuthenticatedTransactionDAO',
  'net.nanopay.tx.AutoCashOutForInvoiceTransactionDAO',
  'net.nanopay.tx.GreenfencePlanDAO',
  'net.nanopay.tx.TransactionDAO',
  'net.nanopay.tx.TransactionEntitiesDAO',
  'net.nanopay.tx.TransactionLimitCheckDAO',
  'net.nanopay.tx.UpdateInvoiceTransactionDAO',
  'net.nanopay.tx.realex.RealexTransactionDAO',
  'net.nanopay.tx.stripe.StripeTransactionDAO',
  'net.nanopay.tx.ChainSummary',
  'net.nanopay.tx.ChargedTo',
  'net.nanopay.tx.TransactionCreateOnInvoiceSubmission',
  'net.nanopay.payment.PayeeCurrencyService',
  'net.nanopay.payment.ClientPayeeCurrencyService',
  'net.nanopay.payment.PayeeCurrency',
  'net.nanopay.payment.RegisterPaymentProviderCapability',

  // support
  'net.nanopay.support.SupportAccount',
  'net.nanopay.support.SupportBusiness',
  'net.nanopay.support.SupportTransaction',
  'net.nanopay.support.SupportUser',

  // rtp
  'net.nanopay.rtp.RequestToPay',
  'net.nanopay.rtp.SendRequestToPayDAO',

  //integration
  'net.nanopay.integration.ErrorCode',

  // notification
  'net.nanopay.bank.ruler.AccountAddedNotification',
  'net.nanopay.sme.cron.WelcomeEmailNotification',
  'net.nanopay.crunch.UCJExpiryReminderNotification',
  'net.nanopay.invoice.ruler.CompleteInvoiceNotification',
  'net.nanopay.crunch.compliance.SendExpiryNotification',
  'net.nanopay.tx.ruler.MicroDepositSentNotification',
  'net.nanopay.sme.cron.OnboardingReminderNotification',
  'net.nanopay.sme.ruler.BusinessCompliancePassedEmailNotification',
];

var abstractClasses = [
];

var skeletons = [
  'net.nanopay.account.DigitalAccountServiceInterface',
  'net.nanopay.documents.AcceptanceDocumentService',
  'net.nanopay.accounting.IntegrationService',
  'net.nanopay.cico.service.BankAccountVerifier',
  'net.nanopay.tx.alterna.SFTPService',
  'net.nanopay.fx.ExchangeRateInterface',
  'net.nanopay.fx.FXService',
  'net.nanopay.tx.UserTransactionLimit',
  'net.nanopay.tx.billing.BillingServiceInterface',
  'net.nanopay.liquidity.LiquidityAuth',
  'net.nanopay.auth.passwordutil.PasswordEntropy',
  'net.nanopay.payment.CorridorService',
  'net.nanopay.payment.PaymentService',
  'net.nanopay.payment.PayeeCurrencyService',
  'net.nanopay.invoice.service.InvoicePaymentService',
  'net.nanopay.liquidity.ucjQuery.AccountUCJQueryService',
  'net.nanopay.fx.ExchangeRateServiceInterface',
  'net.nanopay.account.BalanceServiceInterface',
  'net.nanopay.liquidity.tx.AccountHierarchy',
  'net.nanopay.tx.TransactionLimitServiceInterface',
  'net.nanopay.contacts.PaymentCodeServiceInterface',
  'net.nanopay.interac.service.InteracTransactionDAO',
  'net.nanopay.contacts.ContactServiceInterface',
  'net.nanopay.country.br.BrazilVerificationServiceInterface',
  'net.nanopay.auth.openid.TokenLoginService',
  'net.nanopay.auth.openid.OAuthService'
];

var proxies = [
  'net.nanopay.cico.service.BankAccountVerifier',
  'net.nanopay.tx.TransactionLimitServiceInterface',
  'net.nanopay.contacts.PaymentCodeServiceInterface',
  'net.nanopay.contacts.ContactServiceInterface',
  'net.nanopay.country.br.BrazilVerificationServiceInterface',
  'net.nanopay.payment.PayeeCurrencyService'
];

module.exports = {
    classes: classes,
    abstractClasses: abstractClasses,
    skeletons: skeletons,
    proxies: proxies
};
