#!/usr/bin/env node

globalThis.FOAM_FLAGS = {
node: true,
js: true,
debug: true,
java: true,
swift: true
};

require('../src/foam_node.js');
require('../src/foam/nanos/nanos.js');

foam.classloader.NodeJsModelExecutor.create().fromArgs(process.argv.slice(2)).execute();
