#!/usr/bin/env node

globalThis.FOAM_FLAGS = {
node: true,
c: true,
debug: true,
java: true,
swift: true
};

require('../src/foam_node.c');
require('../src/foam/nanos/nanos.c');

foam.classloader.Nod.cModelExecutor.create().fromArgs(process.argv.slice(2)).execute();
