/**
 * @license
 * Copyright 2023 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

exports.description = 'copies .jrl files into /build/journals';

const fs_   = require('fs');
const path_ = require('path');
const b_    = require('./buildlib');

const journalFiles  = [];
const journalOutput = {};
const imageDirs     = [ 'images' ];

exports.init = function() {
  X.journaldir = X.builddir + '/journals/';
  b_.emptyDir(X.journaldir);
}


exports.visitFile = function(pom, f, fn) {
  if ( f.name.endsWith('.jrl') ) {
    // Disallow wildcard matching for excluding .jrl files, excluded entries must be exact match
    if ( b_.isExcluded(pom, fn, true) ) return;

    verbose('\t\tjournal source:', fn);
    journalFiles.push(fn);

    var i           = fn.lastIndexOf('/');
    var journalName = fn.substring(i+1, fn.length-4);
    var file        = fs_.readFileSync(fn).toString();

    if ( ! file.length ) return;

    file = `// The following ${(file || '').split('\n').length} lines were copied from "${path_.relative(process.cwd(), fn)}"\n` + file + '\n';
    journalOutput[journalName] = (journalOutput[journalName] || '') + file;
  }
}


exports.visitDir = function(pom, f, fn) {
  if ( f.name === 'images' ) {
    imageDirs.push(fn);
  }
}


exports.end = function() {
  console.log(`[Journal Maker] Creating journals to ${X.journaldir} from ${X.pom}`);

  if ( X.pom !== 'pom' ) {
    var poms = X.pom.split(',').map(f => path_.relative(process.cwd(), f)).join(',');
    console.log(`[Journal Maker] Setting POM to ${poms}`);

    journalOutput.services += `
// The following record was generated by JournalMaker
p({
  "class":"foam.nanos.boot.NSpec",
  "name":"appConfig",
  "service": {
    "class":"foam.nanos.app.AppConfig",
    "pom":"${poms}"
  }
})
`;
  }

  if ( imageDirs.length > 1 ) {
    var paths = imageDirs.map(f => path_.relative(process.cwd(), f)).join(':');
    journalOutput.services += `
// The following record was generated by JournalMaker
p({
  "class":"foam.nanos.boot.NSpec",
  "name":"http",
  "service": {
    "class":"foam.nanos.jetty.HttpServer",
    "imageDirs":"${paths}"
  }
})
`;
  }

  Object.keys(journalOutput).forEach(f => {
    fs_.writeFileSync(X.journaldir + f + '.0', journalOutput[f]);
  });

  // Write to journal_files is not needed, just for backward compatibility with find.sh
  fs_.writeFileSync(X.builddir + '/journal_files', journalFiles.join('\n') + '\n');

  console.log(`[Journal Maker] Generating ${Object.keys(journalOutput).length} journal files from ${journalFiles.length} sources.`);
}
