/**
 * @license
 * Copyright 2016 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.POM({
  name: 'foam',
  version: 3,

  files: [
  { name: "foam/core/poly" },
  { name: "foam/core/lib" },
  { name: "foam/core/stdlib" },
  { name: "foam/core/events" },
  { name: "foam/core/cps" },
  { name: "foam/core/Context" },
  { name: "foam/core/Boot" },
  { name: "foam/core/FObject" },
  { name: "foam/core/Model" },
  { name: "foam/core/Property" },
  { name: "foam/core/Simple" },
  { name: "foam/core/Method" },
  { name: "foam/core/Boolean" },
  { name: "foam/core/AxiomArray" },
  { name: "foam/core/EndBoot" },
  { name: "foam/core/Script" },
  { name: "foam/pattern/Faceted" },
  { name: "foam/core/Glyph", flags: "java" },
  { name: "foam/core/types" },
  { name: "foam/core/Duration" },
  { name: "foam/core/FObjectArray" },
  { name: "foam/core/Constant" },
  { name: "foam/core/Topic" },
  { name: "foam/core/InnerClass" },
  { name: "foam/core/InnerEnum" },
  { name: "foam/core/Mixin" },
  { name: "foam/core/Implements" },
  { name: "foam/core/ImportsExports" },
  { name: "foam/core/Listener" },
  { name: "foam/core/IDSupport" },
  { name: "foam/core/Requires" },
  { name: "foam/core/Slot" /*, flags: "java"*/ },
  { name: "foam/core/Proxy" },
  { name: "foam/core/Latch" },
  { name: "foam/core/Lock" },
  { name: "foam/core/CountingSemaphore" },
  { name: "foam/core/Promised" },
  { name: "foam/core/Interface" },
  { name: "foam/core/Type" },
  { name: "foam/core/Axiom", flags: "java" },
  { name: "foam/core/ContextMethod" },
  { name: "foam/core/Exception", flags: "java" },
  { name: "foam/core/ExceptionInterface", flags: "java" },
  { name: "foam/core/FOAMException", flags: "java" },
  { name: "foam/core/FOAMExceptionTest", flags: "java" },
  { name: "foam/core/Window" },
  { name: "foam/core/ContextMultipleInheritence" },
  { name: "foam/core/Argument", flags: "java" },
  { name: "foam/core/MultiMethod" },
  { name: "foam/core/debug", flags: "debug" },
  { name: "foam/core/CoreTypesValidationTest", flags: "java" },
  { name: "foam/pattern/Singleton" },
  { name: "foam/pattern/Multiton" },
  { name: "foam/core/Enum" },
  { name: "foam/core/JSON" },
  { name: "foam/core/XML" },
  { name: "foam/core/holders", flags: "java" },
  { name: "foam/core/CompoundException", flags: "java" },
  { name: "foam/lib/csv/CSVParser" },
  { name: "foam/lib/csv/CSVOutputter", flags: "java" },
  { name: "foam/lib/csv/CSVOutputterImpl", flags: "java" },
  { name: "foam/lib/csv/PrefixedCSVOutputter", flags: "java" },
  { name: "foam/lib/csv/DynamicHeaderCSVParser" },
  { name: "foam/parse/StringPStream" },
  { name: "foam/core/Validator", flags: "java" },
  { name: "foam/core/ValidationException", flags: "java" },
  { name: "foam/core/ClientRuntimeException", flags: "java" },
  { name: "foam/parse/ErrorReportingPStream" },
  { name: "foam/parse/TrapPStream" },
  { name: "foam/parse/InvalidPStream" },
  { name: "foam/parse/parse" },
  { name: "foam/parse/json" },
  { name: "foam/parsers/FON" },
  { name: "foam/core/templates" },
  { name: "foam/i18n/Messages" },
  { name: "foam/core/Validation" },
  { name: "foam/core/Action", flags: "java" },
  { name: "foam/core/Static" },
  { name: "foam/core/Reaction" },
  { name: "foam/core/Serializable", flags: "java" },
  { name: "foam/core/Freezable", flags: "java" },
  { name: "foam/core/Detachable", flags: "java" },
  { name: "foam/core/ContextAgent", flags: "java" },
  { name: "foam/core/CompoundContextAgency", flags: "java" },
  { name: "foam/core/Validatable", flags: "java" },
  { name: "foam/core/AxiomCloner" },
  { name: "foam/u2/ModalOverlay", flags: "web" },
  { name: "foam/core/Agency", flags: "java" },
  { name: "foam/core/AbstractAgency", flags: "java" },
  { name: "foam/nanos/auth/Authorizable", flags: "java" },
  { name: "foam/i18n/TranslationFormatStringParser" },
  { name: "foam/swift/SwiftLib", flags: "swift" },
  { name: "foam/swift/SwiftClass", flags: "swift" },
  { name: "foam/swift/Outputter", flags: "swift" },
  { name: "foam/swift/Protocol", flags: "swift" },
  { name: "foam/swift/Argument", flags: "swift" },
  { name: "foam/swift/ProtocolArgument", flags: "swift" },
  { name: "foam/swift/refines/Action", flags: "swift" },
  { name: "foam/swift/refines/InnerClass", flags: "swift" },
  { name: "foam/swift/refines/AbstractInterface", flags: "swift" },
  { name: "foam/swift/refines/Argument", flags: "swift" },
  { name: "foam/swift/refines/Property", flags: "swift" },
  { name: "foam/swift/refines/FObject", flags: "swift" },
  { name: "foam/swift/refines/AbstractEnum", flags: "swift" },
  { name: "foam/swift/refines/Array", flags: "swift" },
  { name: "foam/swift/refines/FObjectArray", flags: "swift" },
  { name: "foam/swift/refines/Import", flags: "swift" },
  { name: "foam/swift/refines/Constant", flags: "swift" },
  { name: "foam/swift/refines/Message", flags: "swift" },
  { name: "foam/swift/refines/Method", flags: "swift" },
  { name: "foam/swift/refines/Listener", flags: "swift" },
  { name: "foam/swift/refines/Proxy", flags: "swift" },
  { name: "foam/swift/refines/InterfaceMethod", flags: "swift" },
  { name: "foam/swift/ProtocolMethod", flags: "swift" },
  { name: "foam/swift/ProtocolField", flags: "swift" },
  { name: "foam/swift/refines/Model", flags: "swift" },
  { name: "foam/swift/refines/Requires", flags: "swift" },
  { name: "foam/swift/refines/IntProperty", flags: "swift" },
  { name: "foam/swift/refines/String", flags: "swift" },
  { name: "foam/swift/refines/Multiton", flags: "swift" },
  { name: "foam/swift/refines/Singleton", flags: "swift" },
  { name: "foam/swift/Field", flags: "swift" },
  { name: "foam/swift/Method", flags: "swift" },
  { name: "foam/core/PropertyInfo", flags: "genjava|java" },
  { name: "foam/java/Argument", flags: "genjava" },
  { name: "foam/java/ClassInfo", flags: "genjava" },
  { name: "foam/java/Interface", flags: "genjava" },
  { name: "foam/java/Class", flags: "genjava" },
  { name: "foam/java/Code", flags: "genjava" },
  { name: "foam/java/CodeProperty", flags: "genjava" },
  { name: "foam/java/Field", flags: "genjava" },
  { name: "foam/java/JavaImplements", flags: "genjava" },
  { name: "foam/java/InterfaceMethod", flags: "genjava" },
  { name: "foam/java/Method", flags: "genjava" },
  { name: "foam/java/Constant", flags: "genjava" },
  { name: "foam/java/Enum", flags: "genjava" },
  { name: "foam/java/Outputter", flags: "genjava" },
  { name: "foam/java/PropertyInfo", flags: "genjava" },
  { name: "foam/java/Skeleton", flags: "genjava" },
  { name: "foam/java/JavaImport", flags: "genjava" },
  { name: "foam/java/Builder", flags: "genjava" },
  { name: "foam/java/refinements", flags: "genjava" },
  { name: "foam/json2/Json2PropertyRefine" },
  { name: "foam/json2/OutputterOutput" },
  { name: "foam/json2/ProxyOutputterOutput" },
  { name: "foam/json2/SimpleOutputterOutput" },
  { name: "foam/json2/PrettyOutputterOutput" },
  { name: "foam/json2/Outputter" },
  { name: "foam/json2/Serializer" },
  { name: "foam/json2/Deserializer" },
  { name: "foam/java/Util", flags: "java" },
  { name: "foam/core/Fluent" },
  { name: "foam/util/FluentSpec", flags: [ ] },
  { name: "foam/util/Timer" },
  { name: "foam/util/AddressUtil" },
  { name: "foam/util/EmailTest", flags: "java" },
  { name: "foam/util/PasswordTest", flags: "java" },
  { name: "foam/util/SecurityUtilTest", flags: "java" },
  { name: "foam/util/async/Sequence" },
  { name: "foam/util/UIDGenerator", flags: "java" },
  { name: "foam/util/AUIDGenerator", flags: "java" },
  { name: "foam/util/NUIDGenerator", flags: "java" },
  { name: "foam/util/test/DummyNuid", flags: "java" },
  { name: "foam/util/test/UIDGeneratorTest", flags: "java" },
  { name: "foam/util/test/UIDUniquenessTest", flags: "java" },
  { name: "foam/util/test/SafetyUtilTest", flags: "java" },
  { name: "foam/util/uid/GlobalSearchService", flags: "java" },
  { name: "foam/util/uid/FuidSearchService", flags: "java" },
  { name: "foam/util/uid/ClientGlobalSearchService", flags: "java" },
  { name: "foam/util/uid/FuidKey", flags: "java" },
  { name: "foam/util/DeFeedback", flags: "web" },
  { name: "foam/log/LogLevel", flags: "java" },
  { name: "foam/log/Logger" },
  { name: "foam/log/ConsoleLogger" },
  { name: "foam/memento/MementoMgr" },
  { name: "foam/web/DetachedURLState", flags: "web" },
  { name: "foam/web/URLState", flags: "web" },
  { name: "lib/input", flags: "web" },
  { name: "foam/box/Remote" },
  { name: "foam/u2/DeleteModal", flags: "web" },
  { name: "foam/u2/EasyModal", flags: "web" },
  { name: "foam/u2/MemoModal", flags: "web" },
  { name: "foam/u2/PropertyModal", flags: "web" },
  { name: "foam/u2/ModalHeader", flags: "web" },
  { name: "foam/u2/ExportModal", flags: "web" },
  { name: "foam/u2/MultiView" },
  { name: "foam/u2/AttrSlot" },
  { name: "foam/u2/ViewSpec" },
  { name: "foam/u2/Tooltip", flags: "web" },
  { name: "foam/u2/RowFormatter" },
  { name: "foam/u2/WeakMap", flags: "web" },
  { name: "foam/u2/Element"/*, flags: "java" */},
  { name: "foam/u2/MNRowFormatter", flags: "web" },
  { name: "foam/u2/ProgressView", flags: "web" },
  { name: "foam/u2/LoadingSpinner", flags: "web" },
  { name: "foam/u2/ListCreateController", flags: "web" },
  { name: "foam/u2/view/SearchViewWrapper", flags: "web" },
  { name: "foam/u2/view/StringArrayRowView", flags: "web" },
  { name: "foam/u2/borders/BrowserSupportBorder", flags: "web" },
  { name: "foam/u2/borders/NullBorder", flags: "web" },
  { name: "foam/u2/borders/CardBorder", flags: "web" },
  { name: "foam/u2/borders/CollapseBorder", flags: "web" },
  { name: "foam/u2/borders/ExpandableBorder", flags: "web" },
  { name: "foam/u2/borders/MarginBorder", flags: "web" },
  { name: "foam/u2/borders/SplitScreenBorder", flags: "web" },
  { name: "foam/u2/borders/SplitScreenGridBorder", flags: "web" },
  { name: "foam/u2/borders/LoadingBorder", flags: [ "web", "java" ] },
  { name: "foam/u2/borders/Block", flags: "web" },
  { name: "foam/nanos/u2/navigation/IFrameTopNavigation", flags: "web" },
  { name: "foam/version/VersionTrait" },
  { name: "foam/version/VersionedClass" },
  { name: "foam/version/VersionedClassFactory" },
  { name: "foam/dao/NullJournal", flags: "java" },
  { name: "foam/dao/Sink", flags: "java" },
  { name: "foam/dao/DAO", flags: "java" },
  { name: "foam/dao/DOP", flags: "java" },
  { name: "foam/dao/PredicatedDualDelegateDAO", flags: "java" },
  { name: "foam/dao/daoUtils", flags: "java" },
  { name: "foam/dao/ArraySink", flags: "java" },
  { name: "foam/dao/DAOCopySink", flags: "java" },
  { name: "foam/dao/DAOInterceptor", flags: "java" },
  { name: "foam/dao/AbstractDAO", flags: "java" },
  { name: "foam/dao/FilteredDAO", flags: "java" },
  { name: "foam/dao/DAOProperty" },
  { name: "foam/dao/PipelinePMDAO", flags: "java" },
  { name: "foam/dao/SQLStatement", flags: "java" },
  { name: "foam/dao/CSVSink", flags: "java" },
  { name: "foam/dao/LimitedDAO" },
  { name: "foam/dao/LockDAO" },
  { name: "foam/dao/SkipDAO" },
  { name: "foam/dao/OrderedDAO", flags: "web" },
  { name: "foam/dao/InternalException", flags: "java" },
  { name: "foam/dao/ExternalException", flags: "java" },
  { name: "foam/dao/UniqueConstraintException", flags: "java" },
  { name: "foam/dao/CompositeRelationship", flags: "web" },
  { name: "foam/mlang/order/Comparator", flags: "java" },
  { name: "foam/mlang/mlang", flags: "java" },
  { name: "foam/mlang/DOTMQLTest", flags: "java" },
  { name: "foam/mlang/expr/PropertyExpr", flags: "java" },
  { name: "foam/mlang/expr/DateTypes", flags: "java" },
  { name: "foam/mlang/expr/DateGrouping", flags: "java" },
  { name: "foam/mlang/expr/DateGroupingExpr", flags: "java" },
  { name: "foam/mlang/expr/Ref", flags: "java" },
  { name: "foam/mlang/expr/TimeOfDay", flags: "java" },
  { name: "foam/mlang/predicate/ContextUserPredicate", flags: "java" },
  { name: "foam/mlang/predicate/CapabilityAuthServicePredicate", flags: "java" },
  { name: "foam/swift/refines/MLang", flags: "swift" },
  { name: "foam/swift/refines/Predicate", flags: "swift" },
  { name: "foam/swift/refines/AbstractDAO", flags: "swift" },
  { name: "foam/mlang/LabeledValue" },
  { name: "foam/dao/index/Plan" },
  { name: "foam/dao/index/Index" },
  { name: "foam/dao/index/ProxyIndex" },
  { name: "foam/dao/index/AltIndex" },
  { name: "foam/dao/index/ValueIndex" },
  { name: "foam/dao/index/AATree" },
  { name: "foam/dao/index/TreeIndex" },
  { name: "foam/dao/index/AutoIndex" },
  { name: "foam/dao/index/PersistedIndexTest", flags: "java" },
  { name: "foam/dao/MDAO" },
  { name: "foam/dao/ArrayDAO", flags: "java" },
  { name: "foam/dao/TimestampDAO" },
  { name: "foam/dao/CopyFromDAO", flags: "java" },
  { name: "foam/dao/GUIDDAO", flags: "java" },
  { name: "foam/dao/KeyValueDAO", flags: "java" },
  { name: "foam/dao/ReadOnlyDAO", flags: "java" },
  { name: "foam/dao/StoreAndForwardDAO" },
  { name: "foam/dao/Journal", flags: [ "node", "java" ] },
  { name: "foam/dao/CompositeJournal", flags: "java" },
  { name: "foam/dao/AbstractFileJournal", flags: "java" },
  { name: "foam/dao/FileJournal", flags: "java" },
  { name: "foam/dao/JDAO", flags: "web" },
  { name: "foam/dao/java/JDAO", flags: "java" },
  { name: "foam/dao/ReadOnlyFileJournal", flags: "java" },
  { name: "foam/dao/RoutingJournal", flags: "java" },
  { name: "foam/dao/RoutingJournalTest", flags: "java" },
  { name: "foam/dao/RoutingJDAO", flags: "java" },
  { name: "foam/dao/JournalType", flags: "java" },
  { name: "foam/dao/Relationship", flags: "java" },
  { name: "foam/dao/RelationshipDAO", flags: "java" },
  { name: "foam/dao/ManyToManyRelationshipDAO", flags: "java" },
  { name: "foam/dao/grid/ManyToManyGridRecord" },
  { name: "foam/dao/grid/ManyToManyGridDAO" },
  { name: "foam/dao/LazyCacheDAO" },
  { name: "foam/dao/SessionClientDAO" },
  { name: "foam/dao/TTLCachingDAO" },
  { name: "foam/dao/TTLSelectCachingDAO", flags: "java" },
  { name: "foam/dao/CachingDAO" },
  { name: "foam/dao/DeDupDAO" },
  { name: "foam/dao/LRUDAOManager" },
  { name: "foam/dao/QueryCachingDAO", flags: "java" },
  { name: "foam/dao/SequenceNumberDAO", flags: "java" },
  { name: "foam/dao/SequenceNumberDAOTest", flags: "java" },
  { name: "foam/dao/ContextualizingDAO", flags: "java" },
  { name: "foam/dao/VersionNoDAO" },
  { name: "foam/dao/sync/SyncRecord" },
  { name: "foam/dao/SyncDAO" },
  { name: "foam/dao/FUIDDAO", flags: "java" },
  { name: "foam/nanos/approval/AuthenticatedApprovalDAOAuthorizer", flags: "java" },
  { name: "foam/nanos/approval/UCJApprovable", flags: "java" },
  { name: "foam/nanos/alarming/AddAlarmNameDAO", flags: "java" },
  { name: "foam/nanos/approval/ApprovalRequestNotificationNotificationCitationView", flags: "web" },
  { name: "foam/nanos/u2/navigation/SignUp" },
  { name: "foam/nanos/u2/navigation/SignIn" },
  { name: "foam/nanos/boot/NSpec", flags: "java" },
  { name: "foam/nanos/boot/NSpecAware", flags: "java" },
  { name: "foam/nanos/auth/Authorizer", flags: "java" },
  { name: "foam/nanos/auth/AccessDeniedException", flags: "java" },
  { name: "foam/nanos/auth/AuthenticationException", flags: "java" },
  { name: "foam/nanos/auth/AuthorizationException", flags: "java" },
  { name: "foam/nanos/auth/AccountLockedException", flags: "java" },
  { name: "foam/nanos/auth/EnabledAware", flags: "java" },
  { name: "foam/nanos/auth/InvalidPasswordException", flags: "java" },
  { name: "foam/nanos/auth/ServiceProviderAware", flags: "java" },
  { name: "foam/nanos/auth/ServiceProviderAwareSink", flags: "java" },
  { name: "foam/nanos/auth/test/ServiceProviderAwareTest", flags: "java" },
  { name: "foam/nanos/auth/test/ServiceProviderAuthorizerTest", flags: "java" },
  { name: "foam/nanos/auth/token/TokenExpiredException", flags: "java" },
  { name: "foam/nanos/auth/token/TokenInvalidException", flags: "java" },
  { name: "foam/nanos/auth/UserPropertyAvailabilityService", flags: "java" },
  { name: "foam/nanos/auth/UserPropertyAvailabilityServiceInterface", flags: "java" },
  { name: "foam/nanos/auth/ClientUserPropertyAvailabilityService", flags: "java" },
  { name: "foam/nanos/auth/UserMDCitationView" },
  { name: "foam/nanos/auth/CommonPassword", flags: "java" },
  { name: "foam/nanos/auth/AddressConfig", flags: "java" },
  { name: "foam/nanos/auth/UserNotFoundException", flags: "java" },
  { name: "foam/nanos/auth/AuthorizeAnonymousClientDecorator" },
  { name: "foam/nanos/logger/Logger", flags: "java" },
  { name: "foam/nanos/logger/DAOLogger", flags: "java" },
  { name: "foam/nanos/logger/LoggingDAO", flags: "java" },
  { name: "foam/nanos/auth/CreatedAwareMixin" },
  { name: "foam/nanos/auth/CreatedByAwareMixin" },
  { name: "foam/nanos/auth/LastModifiedAwareMixin" },
  { name: "foam/nanos/auth/LastModifiedByAwareMixin" },
  { name: "foam/nanos/auth/LastModifiedByAgentNameAware", flags: "java" },
  { name: "foam/nanos/script/Language", flags: [ "java", "web" ] },
  { name: "foam/dao/EasyDAO", flags: "java" },
  { name: "foam/dao/NoSelectAllDAO" },
  { name: "foam/dao/NullDAO", flags: "java" },
  { name: "foam/dao/TimingDAO" },
  { name: "foam/dao/LoggingDAO" },
  { name: "foam/dao/IDBInternalException", flags: "web" },
  { name: "foam/dao/IDBDAO", flags: "web" },
  { name: "foam/dao/BatchMutationIDBDAO", flags: "web" },
  { name: "foam/dao/RestDAO" },
  { name: "foam/dao/EnabledAwareDAO", flags: "java" },
  { name: "foam/dao/EnabledAwareDAOTest", flags: "java" },
  { name: "foam/dao/ValidationDAODecorator" },
  { name: "foam/dao/ResetDAODecorator", flags: "web" },
  { name: "foam/dao/SQL", flags: [ "sql" ] },
  { name: "foam/dao/NoDisjunctionDAO" },
  { name: "foam/dao/NoNeqDAO" },
  { name: "foam/dao/FixedSizeDAO", flags: "java" },
  { name: "foam/dao/PutOnlyDAO", flags: "java" },
  { name: "foam/glang/glang", flags: "java" },
  { name: "foam/parse/QueryParser" },
  { name: "foam/parse/FScript" },
  { name: "foam/parse/QueryParserUserTest", flags: "java" },
  { name: "foam/physics/Physical" },
  { name: "foam/physics/Collider" },
  { name: "foam/physics/PhysicsEngine" },
  { name: "foam/blob/Blob", flags: "java" },
  { name: "foam/blob/BlobStore", flags: "java" },
  { name: "foam/blob/FdBlob", flags: "java|node" },
  { name: "lib/node/json_dao", flags: "node" },
  { name: "lib/utf8" },
  { name: "foam/net/CIDR", flags: "java" },
  { name: "foam/net/Host", flags: "java" },
  { name: "foam/net/Port", flags: "java" },
  { name: "foam/net/NotConnectedException" },
  { name: "foam/net/ConnectionFailedException" },
  { name: "foam/net/web/WebSocket" },
  { name: "foam/net/web/WebSocketService" },
  { name: "foam/net/web/HTTPResponse", flags: "java" },
  { name: "foam/net/web/HTTPRequest", flags: "java" },
  { name: "foam/net/web/BaseHTTPRequest" },
  { name: "foam/net/web/EventSource" },
  { name: "foam/net/web/XMLHTTPRequest" },
  { name: "foam/net/web/XMLHTTPResponse" },
  { name: "foam/net/web/SafariEventSource" },
  { name: "foam/messageport/MessagePortService", flags: "web" },
  { name: "foam/net/node/Frame", flags: "node" },
  { name: "foam/net/node/Socket", flags: "node" },
  { name: "foam/net/node/SocketService", flags: "node", predicate: function() { return foam.isServer; } },
  { name: "foam/net/node/WebSocket", flags: "node", predicate: function() { return foam.isServer; } },
  { name: "foam/net/node/HTTPRequest", flags: "node", predicate: function() { return foam.isServer; } },
  { name: "foam/net/node/BaseHTTPRequest", flags: "node", predicate: function() { return foam.isServer; } },
  { name: "foam/net/node/HTTPResponse", flags: "node", predicate: function() { return foam.isServer; }  },
  { name: "foam/net/node/WebSocketService", flags: "node", predicate: function() { return foam.isServer; } },
  { name: "lib/firebase" },
  { name: "lib/fcm" },
  { name: "foam/core/StubMethod", flags: "genjava" },
  { name: "foam/core/StubAction", flags: "genjava" },
  { name: "foam/core/Stub", flags: "genjava" },
  { name: "foam/box/Box", flags: "java" },
  { name: "foam/box/AnonymousBox" },
  { name: "foam/box/RemoteException", flags: "java" },
  { name: "foam/box/Skeleton", flags: "java" },
  { name: "foam/box/PromisedBox" },
  { name: "foam/box/ProxyBox", flags: "java" },
  { name: "foam/box/Message", flags: "java" },
  { name: "foam/box/SubBoxMessage", flags: "java" },
  { name: "foam/box/HelloMessage", flags: "java" },
  { name: "foam/box/TimeoutBox" },
  { name: "foam/box/RetryBox" },
  { name: "foam/box/SubBox", flags: "java" },
  { name: "foam/box/NameAlreadyRegisteredException" },
  { name: "foam/box/NoSuchNameException", flags: "java" },
  { name: "foam/box/BoxRegistry", flags: "java" },
  { name: "foam/box/LocalBoxRegistry", flags: "java" },
  { name: "foam/box/BoxRegistryBox", flags: "java" },
  { name: "foam/box/ClientBoxRegistry", flags: "java" },
  { name: "foam/box/PromisedBoxRegistry" },
  { name: "foam/box/RegistrySelector" },
  { name: "foam/box/SelectorRegistry" },
  { name: "foam/box/BroadcastRegistry" },
  { name: "foam/box/LookupBox", flags: "java" },
  { name: "foam/box/NamedBox", flags: "java" },
  { name: "foam/box/ReplyBox", flags: "java" },
  { name: "foam/box/FunctionBox" },
  { name: "foam/box/RPCReturnMessage", flags: "java" },
  { name: "foam/box/RPCErrorMessage", flags: "java" },
  { name: "foam/box/SubscribeMessage", flags: "java" },
  { name: "foam/box/RPCReturnBox", flags: "java" },
  { name: "foam/box/RPCMessage", flags: "java" },
  { name: "foam/box/socket/SocketClientBox", flags: "java" },
  { name: "foam/box/socket/SocketClientReplyBox", flags: "java" },
  { name: "foam/box/socket/SocketConnectionBoxManager", flags: "java" },
  { name: "foam/box/socket/SocketServer", flags: "java" },
  { name: "foam/box/socket/SslContextFactory", flags: "java" },
  { name: "foam/dao/BaseClientDAO", flags: "java" },
  { name: "foam/dao/BaseNotificationClientDAO", flags: "java" },
  { name: "foam/dao/MergeBox" },
  { name: "foam/dao/ClientDAO", flags: "java" },
  { name: "foam/dao/NotificationClientDAO", flags: "java" },
  { name: "foam/dao/PollingClientDAO" },
  { name: "foam/dao/PurgeRecordCmd", flags: "java" },
  { name: "foam/dao/StreamingClientDAO" },
  { name: "foam/dao/RequestResponseClientDAO" },
  { name: "foam/box/InvalidMessageException" },
  { name: "foam/box/EventMessage" },
  { name: "foam/box/EventDispatchBox" },
  { name: "foam/box/SkeletonBox" },
  { name: "foam/box/NullBox", flags: "java" },
  { name: "foam/box/SocketBox" },
  { name: "foam/box/SocketBox2" },
  { name: "foam/box/SocketConnectBox" },
  { name: "foam/box/RawSocketBox" },
  { name: "foam/box/SendFailedError" },
  { name: "foam/box/RegisterSelfMessage", flags: "java" },
  { name: "foam/box/RawWebSocketBox", flags: "java" },
  { name: "foam/box/ReturnBox", flags: "java" },
  { name: "foam/box/RawMessagePortBox" },
  { name: "foam/box/WebSocketBox" },
  { name: "foam/box/ClassWhitelistContext" },
  { name: "foam/box/LoggedLookupContext" },
  { name: "foam/box/Context" /*, flags: "node"*/ },
  { name: "foam/box/BoxService", flags: "java" },
  { name: "foam/box/HTTPReplyBox", flags: "java" },
  { name: "foam/box/AuthenticatedBox" },
  { name: "foam/box/HTTPAuthorizationType", flags: "java" },
  { name: "foam/box/HTTPBox", flags: "java" },
  { name: "foam/box/MessagePortBox" },
  { name: "foam/box/ForwardedMessage" },
  { name: "foam/box/ForwardBox" },
  { name: "foam/box/ForwardingBox" },
  { name: "foam/box/SessionClientBox", flags: [ "web", "java" ] },
  { name: "foam/box/AuthServiceClientBox", flags: "java" },
  { name: "foam/box/OneTimeBox", flags: "java" },
  { name: "foam/box/ExportBox", flags: "java" },
  { name: "foam/swift/refines/Stub", flags: "swift" },
  { name: "foam/swift/refines/Promised", flags: "swift" },
  { name: "foam/swift/refines/Topic", flags: "swift" },
  { name: "foam/swift/refines/Remote", flags: "swift" },
  { name: "foam/nanos/menu/MenuToolBar" },
  { name: "foam/box/LogBox" },
  { name: "foam/box/MultiDelegateBox" },
  { name: "foam/box/BroadcastBox" },
  { name: "foam/box/RoundRobinBox" },
  { name: "foam/core/async" },
  { name: "foam/core/NullAgent", flags: "web" },
  { name: "foam/dao/ClientSink", flags: "java" },
  { name: "foam/u2/ViewFactory", flags: "web" },
  { name: "foam/u2/DAOList", flags: "web" },
  { name: "foam/u2/GroupingDAOList", flags: "web" },
  { name: "foam/u2/TableView", flags: "web" },
  { name: "foam/u2/TableSelection", flags: "web" },
  { name: "foam/u2/Scroller", flags: "web" },
  { name: "foam/u2/ButtonSize", flags: "web" },
  { name: "foam/u2/ButtonStyle", flags: "web" },
  { name: "foam/u2/ActionView", flags: "web" },
  { name: "foam/u2/view/MenuView", flags: "web" },
  { name: "foam/u2/DetailPropertyView", flags: "web" },
  { name: "foam/u2/DetailView", flags: "web" },
  { name: "foam/u2/ContextSensitiveDetailView", flags: "web" },
  { name: "foam/u2/tag/Image", flags: "web" },
  { name: "foam/u2/tag/Input", flags: "web" },
  { name: "foam/u2/tag/TextArea", flags: "web" },
  { name: "foam/u2/tag/Button", flags: "web" },
  { name: "foam/u2/util/NumberShortener", flags: "web" },
  { name: "foam/u2/TextField", flags: "web" },
  { name: "foam/u2/SearchField", flags: "web" },
  { name: "foam/u2/TextInputCSS", flags: "web" },
  { name: "foam/u2/IntView", flags: "web" },
  { name: "foam/u2/FloatView", flags: "web" },
  { name: "foam/u2/CurrencyView", flags: "web" },
  { name: "foam/u2/MDCurrencyView", flags: "web" },
  { name: "foam/u2/CheckBox", flags: "web" },
  { name: "foam/u2/CitationView", flags: "web" },
  { name: "foam/u2/PopupView", flags: "web" },
  { name: "foam/u2/DateView", flags: "web" },
  { name: "foam/u2/DateTimeView", flags: "web" },
  { name: "foam/u2/RangeView", flags: "web" },
  { name: "foam/u2/ReadWriteView", flags: "web" },
  { name: "foam/u2/IFrameHTMLView", flags: "web" },
  { name: "foam/u2/tag/Select", flags: "web" },
  { name: "foam/u2/UnstyledTabs", flags: "web" },
  { name: "foam/u2/Tabs", flags: "web" },
  { name: "foam/u2/TimeView", flags: "web" },
  { name: "foam/u2/history/HistoryItemView", flags: "web" },
  { name: "foam/u2/history/HistoryView", flags: "web" },
  { name: "foam/u2/svg/map2d/PlacementPlan" },
  { name: "foam/u2/svg/map2d/GridPlacementPlan" },
  { name: "foam/u2/svg/map2d/GridPlacementStrategy" },
  { name: "foam/u2/svg/map2d/PredeterminedGridPlacementPlan" },
  { name: "foam/u2/svg/map2d/IdPropertyPlacementPlanDecorator" },
  { name: "foam/graph/map2d/RelationshipGridPlacementStrategy", flags: "web" },
  { name: "foam/graph/map2d/ScaleNodeSecondaryRelationshipStrategy", flags: "web" },
  { name: "foam/graph/Graph" },
  { name: "foam/graph/GraphNode" },
  { name: "foam/graph/GraphBuilder" },
  { name: "foam/graph/TraversalOrder" },
  { name: "foam/graph/GraphTraverser" },
  { name: "foam/u2/svg/arrow/ArrowLine", flags: "web" },
  { name: "foam/u2/svg/arrow/ArrowHead", flags: "web" },
  { name: "foam/u2/svg/graph/ZoomedOutFObjectGraphNodeView", flags: "web" },
  { name: "foam/u2/svg/graph/ArrowDisplaceCellsPlacementPlan", flags: "web" },
  { name: "foam/u2/svg/graph/DAGView", flags: "web" },
  { name: "foam/u2/svg/TreeGraph", flags: "web" },
  { name: "foam/u2/svg/TestView", flags: "web" },
  { name: "foam/u2/view/EnumLegendView", flags: "web" },
  { name: "foam/u2/view/RadioButton", flags: "web" },
  { name: "foam/u2/view/RichTextView", flags: "web" },
  { name: "foam/u2/view/ToggleActionView", flags: "web" },
  { name: "foam/u2/view/LoginView", flags: "web" },
  { name: "foam/u2/view/DocumentUploadView", flags: "web" },
  { name: "foam/u2/view/ValueView", flags: "web" },
  { name: "foam/u2/view/LiteralValueView", flags: "web" },
  { name: "foam/u2/view/PreView", flags: "web" },
  { name: "foam/u2/view/TableCellFormatterReadView", flags: "web" },
  { name: "foam/u2/view/MultiBoxInputView", flags: "web" },
  { name: "foam/u2/FragmentedTextField", flags: "web" },
  { name: "foam/u2/FragmentedTextFieldFragment", flags: "web" },
  { name: "foam/u2/TextFormatter" },
  { name: "foam/u2/FormattedTextField", flags: "web" },
  { name: "foam/u2/view/UserPropertyAvailabilityView", flags: "web" },
  { name: "foam/u2/view/FObjectView", flags: "web" },
  { name: "foam/u2/view/CollapseableDetailView", flags: "web" },
  { name: "foam/u2/view/ReferenceCitationView", flags: "web" },
  { name: "foam/u2/view/ReadReferenceView", flags: "web" },
  { name: "foam/u2/view/ReadManyToManyRelationshipPropertyView", flags: "web" },
  { name: "foam/u2/view/ReferenceArrayView", flags: "web" },
  { name: "foam/u2/view/DraftDetailView", flags: "web" },
  { name: "foam/u2/view/TitledArrayView", flags: "web" },
  { name: "foam/u2/view/FObjectArrayView", flags: "web" },
  { name: "foam/u2/view/ChoiceView", flags: "web" },
  { name: "foam/u2/view/UnstyledChooseNView", flags: "web" },
  { name: "foam/u2/view/ChooseNView", flags: "web" },
  { name: "foam/u2/view/ChoiceWithOtherView", flags: "web" },
  { name: "foam/u2/view/RichChoiceView", flags: "web" },
  { name: "foam/u2/view/RichChoiceSummaryIdRowView", flags: "web" },
  { name: "foam/u2/view/OverlayActionListView", flags: "web" },
  { name: "foam/u2/view/TabChoiceView", flags: "web" },
  { name: "foam/u2/view/IconChoiceView", flags: "web" },
  { name: "foam/u2/view/IconTextFieldView", flags: "web" },
  { name: "foam/u2/view/RadioEnumView", flags: "web" },
  { name: "foam/u2/view/RadioView", flags: "web" },
  { name: "foam/u2/view/TextField", flags: "web" },
  { name: "foam/u2/view/TreeView", flags: "web" },
  { name: "foam/u2/view/FileUploadTextField", flags: "web" },
  { name: "foam/u2/view/AltView", flags: "web" },
  { name: "foam/u2/view/ResponsiveAltView", flags: "web" },
  { name: "foam/u2/view/ObjAltView", flags: "web" },
  { name: "foam/u2/view/ModeAltView", flags: "web" },
  { name: "foam/u2/view/StringView", flags: "web" },
  { name: "foam/u2/view/DateView", flags: "web" },
  { name: "foam/u2/view/DateTimeView", flags: "web" },
  { name: "foam/u2/view/TimeView", flags: "web" },
  { name: "foam/u2/view/FloatView", flags: "web" },
  { name: "foam/u2/view/IntView", flags: "web" },
  { name: "foam/u2/view/CurrencyView", flags: "web" },
  { name: "foam/u2/view/CurrencyInputView", flags: "web" },
  { name: "foam/u2/view/FObjectPropertyView", flags: "web" },
  { name: "foam/u2/view/CodeView", flags: "web" },
  { name: "foam/u2/view/ReferencePropertyView", flags: "web" },
  { name: "foam/u2/view/EnumView", flags: "web" },
  { name: "foam/u2/view/ColorView", flags: "web" },
  { name: "foam/u2/view/ReadColorView", flags: "web" },
  { name: "foam/u2/view/SimpleAltView", flags: "web" },
  { name: "foam/u2/view/DualView", flags: "web" },
  { name: "foam/u2/view/ColorPicker", flags: "web" },
  { name: "foam/u2/view/PasswordView", flags: "web" },
  { name: "foam/u2/view/ChipView", flags: "web" },
  { name: "foam/u2/view/Formatter", flags: [ "js" ] },
  { name: "foam/u2/view/FnFormatter", flags: [ "js" ] },
  { name: "foam/u2/view/TableCellFormatter", flags: [ "js" ] },
  { name: "foam/u2/view/UnstyledTableView", flags: "web" },
  { name: "foam/u2/view/LazyScrollManager", flags: "web" },
  { name: "foam/u2/view/TableView", flags: "web" },
  { name: "foam/u2/view/EditColumnsView", flags: "web" },
  { name: "foam/u2/view/ColumnConfigView", flags: "web" },
  { name: "foam/u2/view/ScrollTableView", flags: "web" },
  { name: "foam/u2/view/EmbeddedTableView", flags: "web" },
  { name: "foam/u2/view/BlobView", flags: "web" },
  { name: "foam/u2/view/FileView", flags: "web" },
  { name: "foam/u2/view/ImageBlobView", flags: "web" },
  { name: "foam/u2/view/StringArrayView", flags: "web" },
  { name: "foam/u2/view/ImageView", flags: "web" },
  { name: "foam/u2/view/ExprView", flags: "web" },
  { name: "foam/u2/view/MultiChoiceView", flags: "web" },
  { name: "foam/u2/view/CardSelectionView", flags: "web" },
  { name: "foam/u2/view/CardSelectView", flags: "web" },
  { name: "foam/u2/view/CardSelectWithRadioView", flags: "web" },
  { name: "foam/u2/view/NoBackStack", flags: "web" },
  { name: "foam/u2/view/ReadOnlyEnumView", flags: "web" },
  { name: "foam/u2/view/ViewReferenceFObjectView", flags: "web" },
  { name: "foam/u2/EnumView", flags: "web" },
  { name: "foam/u2/ClassView", flags: "web" },
  { name: "foam/u2/view/ReferenceView", flags: "web" },
  { name: "foam/u2/view/FullReferenceView" },
  { name: "foam/u2/view/StrategizerChoiceView" },
  { name: "foam/u2/tag/Card", flags: "web" },
  { name: "foam/u2/dialog/Popup", flags: "web" },
  { name: "foam/u2/dialog/StyledModal", flags: "web" },
  { name: "foam/u2/dialog/ConfirmationModal", flags: "web" },
  { name: "foam/u2/Dialog", flags: "web" },
  { name: "foam/u2/dialog/NotificationMessage", flags: "web" },
  { name: "foam/u2/dialog/InlineNotificationMessage", flags: "web" },
  { name: "foam/u2/Autocompleter", flags: "web" },
  { name: "foam/u2/filter/FilterRefinements", flags: "web" },
  { name: "foam/u2/filter/FilterView", flags: "web" },
  { name: "foam/u2/filter/advanced/AdvancedFilterView", flags: "web" },
  { name: "foam/u2/filter/advanced/CriteriaView", flags: "web" },
  { name: "foam/u2/filter/FilterController", flags: "web" },
  { name: "foam/u2/filter/properties/PropertyFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/StringFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/IntegerFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/FloatFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/BooleanFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/DateFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/DateTimeFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/EnumFilterView", flags: "web" },
  { name: "foam/u2/filter/properties/ReferenceFilterView", flags: "web" },
  { name: "foam/u2/search/FilterController", flags: "web" },
  { name: "foam/u2/search/GroupCompleter", flags: "web" },
  { name: "foam/u2/search/GroupAutocompleteSearchView", flags: "web" },
  { name: "foam/u2/search/GroupBySearchView", flags: "web" },
  { name: "foam/u2/search/SearchManager", flags: "web" },
  { name: "foam/u2/search/TextSearchView", flags: "web" },
  { name: "foam/u2/search/IntegerSearchView", flags: "web" },
  { name: "foam/u2/search/FloatSearchView", flags: "web" },
  { name: "foam/u2/search/CurrencySearchView", flags: "web" },
  { name: "foam/u2/search/DateSearchView", flags: "web" },
  { name: "foam/u2/search/Toolbar" },
  { name: "foam/u2/stack/Stack", flags: "web" },
  { name: "foam/u2/stack/StackView", flags: "web" },
  { name: "foam/u2/stack/DesktopStackView", flags: "web" },
  { name: "foam/u2/stack/BreadcrumbView", flags: "web" },
  { name: "foam/u2/stack/StackBlock", flags: "web" },
  { name: "foam/u2/crunch/Style", flags: "web" },
  { name: "foam/u2/crunch/CrunchController", flags: "web" },
  { name: "foam/u2/crunch/UCJReferenceView", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/CapabilityAdaptAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/CheckRootIdAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/CheckPendingAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/GrantedEditAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/CheckNoDataAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/LoadCapabilitiesAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/LoadCapabilityGraphAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/WAOSettingAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/GraphWizardletsAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/CreateWizardletsAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/LoadWizardletsAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/FilterWizardletsAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/FilterGrantModeAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/WizardStateAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/SkipGrantedAgent", flags: [ "web", "java" ] },
  { name: "foam/u2/crunch/wizardflow/RequirementsPreviewAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/AutoSaveWizardletsAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/lite/MaybeDAOPutAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/PutFinalJunctionsAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/PutFinalPayloadsAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/TestAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/LoadTopConfig", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/ShowPreexistingAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/SaveAllAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/SubmitAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/ApprovalRequestAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/CapabilityStoreAgent", flags: "web" },
  { name: "foam/u2/crunch/wizardflow/DebugAgent", flags: [ "web", "debug" ] },
  { name: "foam/u2/crunch/wizardflow/lite/CapableDefaultConfigAgent", flags: "web" },
  { name: "foam/u2/crunch/CapabilityRequirementView", flags: "web" },
  { name: "foam/u2/crunch/CapabilityCardView", flags: "web" },
  { name: "foam/u2/crunch/CapabilityFeatureView", flags: "web" },
  { name: "foam/u2/crunch/CapabilityStore", flags: "web" },
  { name: "foam/u2/crunch/CapabilityInterceptView", flags: "web" },
  { name: "foam/u2/crunch/PermissionsStringArrayView", flags: "web" },
  { name: "foam/u2/crunch/FlatteningCapabilityWizardlet", flags: "web" },
  { name: "foam/u2/crunch/lab/CapabilityGraphNodeView", flags: "web" },
  { name: "foam/u2/crunch/lab/CrunchLab", flags: "web" },
  { name: "foam/apploader/ModelRefines" },
  { name: "foam/foamlink/FoamlinkNodeModelFileDAO", flags: "node" },
  { name: "foam/foamlink/FoamlinkNodeModelFileFetcher", flags: "node" },
  { name: "foam/apploader/ClassLoader" },
  { name: "foam/apploader/SubClassLoader" },
  { name: "foam/classloader/OrDAO", flags: "debug" },
  { name: "foam/apploader/WebModelFileFetcher" },
  { name: "foam/apploader/NodeModelFileFetcher", flags: "node" },
  { name: "foam/apploader/ModelFileDAO" },
  { name: "foam/apploader/WebModelFileDAO", flags: "web" },
  { name: "foam/apploader/NodeModelFileDAO", flags: [ "node", "debug" ] },
  { name: "foam/classloader/NodeJsModelExecutor", flags: [ "node", "debug" ] },
  { name: "foam/apploader/NoClassLoader" },
  { name: "foam/apploader/ClassLoaderContext" },
  { name: "foam/u2/FoamTagLoader", flags: "web" },
  { name: "foam/graphics/CView", flags: "web" },
  { name: "foam/graphics/TreeGraph", flags: "web" },
  { name: "foam/graphics/TreeNode", flags: "web" },
  { name: "foam/graphics/ScrollCView", flags: "web" },
  { name: "foam/physics/PhysicalCircle", flags: "web" },
  { name: "foam/u2/view/SimpleSearch", flags: "web" },
  { name: "foam/comics/SearchMode", flags: [ "web", "java" ] },
  { name: "foam/comics/DAOController" },
  { name: "foam/comics/DAOControllerView", flags: "web" },
  { name: "foam/comics/InlineDAOControllerView", flags: "web" },
  { name: "foam/comics/DAOCreateController" },
  { name: "foam/comics/DAOCreateControllerView", flags: "web" },
  { name: "foam/comics/DAOUpdateController" },
  { name: "foam/comics/DAOUpdateControllerView", flags: "web" },
  { name: "foam/comics/BrowserView", flags: "web" },
  { name: "foam/comics/InlineBrowserView", flags: "web" },
  { name: "foam/comics/RelationshipView", flags: "web" },
  { name: "foam/u2/view/ReciprocalSearch", flags: "web" },
  { name: "lib/net", flags: "web" },
  { name: "lib/netNode", flags: "node", predicate: () => foam.flags.node && ! foam.flags.genjava },
  { name: "foam/net/RetryHTTPRequest" },
  { name: "foam/net/auth/TokenBearerCredential" },
  { name: "foam/net/auth/AuthAwareHTTPRequest" },
  { name: "foam/net/auth/TokenBearerHTTPRequest" },
  { name: "foam/net/auth/AuthAgent" },
  { name: "foam/u2/view/FObjectArrayTableView", flags: "web" },
  { name: "foam/doc/AxiomLink", flags: [ "debug", "web" ] },
  { name: "foam/doc/dao/PropertyPermissionCheckDecorator", flags: [ "debug", "web" ] },
  { name: "foam/doc/dao/AxiomDAO", flags: [ "debug", "web" ] },
  { name: "foam/doc/AxiomTableView", flags: [ "debug", "web" ] },
  { name: "foam/doc/MethodAxiom", flags: [ "debug", "web" ] },
  { name: "foam/doc/AxiomListView", flags: [ "debug", "web" ] },
  { name: "foam/doc/Axiom", flags: [ "debug", "web" ] },
  { name: "foam/doc/PropertyAxiom", flags: [ "debug", "web" ] },
  { name: "foam/doc/AxiomSummaryView", flags: [ "debug", "web" ] },
  { name: "foam/doc/SimpleClassView", flags: [ "debug", "web" ] },
  { name: "foam/doc/ClassLink", flags: [ "debug", "web" ] },
  { name: "foam/doc/CodeTabs" },
  { name: "foam/doc/DocBrowser", flags: [ "debug", "web" ] },
  { name: "foam/doc/ModelBrowser", flags: [ "debug", "web" ] },
  { name: "com/google/net/node/Google2LOAuthAgent", flags: [ "node", "gcloud" ] },
  { name: "com/google/firebase/DefaultFirestoreDocumentID", flags: [ "node", "firebase" ] },
  { name: "com/google/firebase/DefaultFirestoreData", flags: [ "node", "firebase" ] },
  { name: "com/google/firebase/DefaultFObject", flags: [ "node", "firebase" ] },
  { name: "com/google/firebase/AwaitAuthenticationDAO", flags: [ "node", "firebase" ] },
  { name: "com/google/firebase/FirestoreDAO", flags: [ "node", "firebase" ] },
  { name: "foam/net/node/EntityEncoding", flags: "node" },
  { name: "foam/net/node/Route", flags: "node" },
  { name: "foam/net/node/PathnamePrefixRoute", flags: "node" },
  { name: "foam/net/node/PathnameRoute", flags: "node" },
  { name: "foam/net/node/Handler", flags: "node" },
  { name: "foam/net/node/RouteBinding", flags: "node" },
  { name: "foam/net/node/Router", flags: "node" },
  { name: "foam/net/node/BaseHandler", flags: "node" },
  { name: "foam/net/node/ErrorHandler", flags: "node" },
  { name: "foam/net/node/PathnamePrefixHandler", flags: "node" },
  { name: "foam/net/node/PathnameHandler", flags: "node" },
  { name: "foam/net/node/SimpleRouter", flags: "node" },
  { name: "foam/net/node/PathnameRouter", flags: "node" },
  { name: "foam/net/node/RequestIdentifier", flags: "node" },
  { name: "foam/net/node/CacheHandler", flags: "node" },
  { name: "foam/net/node/FileHandler", flags: "node" },
  { name: "foam/net/node/DirTreeHandler", flags: "node" },
  { name: "foam/net/node/RestDAOHandler", flags: "node" },
  { name: "foam/net/node/ServerRequest", flags: "node" },
  { name: "foam/net/node/ServerResponse", flags: "node" },
  { name: "foam/net/node/SimpleServerResponse", flags: "node" },
  { name: "foam/net/node/CachedResponse", flags: "node" },
  { name: "foam/net/node/CachingResponse", flags: "node" },
  { name: "foam/net/node/Server", flags: "node" },
  { name: "foam/parsers/html/lib" },
  { name: "foam/parsers/html/Attribute" },
  { name: "foam/parsers/html/TagType" },
  { name: "foam/parsers/html/Tag" },
  { name: "foam/parsers/html/HTMLLexer" },
  { name: "foam/core/ContextAware", flags: "java" },
  { name: "foam/dao/history/PropertyUpdate", flags: "java" },
  { name: "foam/dao/history/HistoryRecord", flags: "java" },
  { name: "foam/dao/jdbc/ConnectionPool", flags: "java" },
  { name: "foam/lib/Outputter", flags: "java" },
  { name: "foam/lib/PropertyPredicate", flags: "java" },
  { name: "foam/lib/PermissionedPropertyPredicate", flags: "java" },
  { name: "foam/lib/NetworkPropertyPredicate", flags: "java" },
  { name: "foam/lib/StorageOptionalPropertyPredicate", flags: "java" },
  { name: "foam/lib/StoragePropertyPredicate", flags: "java" },
  { name: "foam/lib/AndPropertyPredicate", flags: "java" },
  { name: "foam/lib/json/JSONParser", flags: "java" },
  { name: "foam/lib/json/OutputterMode", flags: "java" },
  { name: "foam/lib/json/ClassReferenceParserTest", flags: "java" },
  { name: "foam/lib/json/PropertyReferenceParserTest", flags: "java" },
  { name: "foam/lib/json/UnknownFObject", flags: "java" },
  { name: "foam/lib/json/OutputJSON", flags: "java" },
  { name: "foam/lib/parse/Parser", flags: "java" },
  { name: "foam/lib/parse/PStream", flags: "java" },
  { name: "foam/lib/parse/BlobPStream", flags: "java" },
  { name: "foam/crypto/hash/Hasher", flags: "java" },
  { name: "foam/crypto/hash/Hashable" },
  { name: "foam/crypto/hash/HashableTest", flags: "java" },
  { name: "foam/crypto/sign/Signer", flags: "java" },
  { name: "foam/crypto/sign/Signable" },
  { name: "foam/crypto/sign/SignableTest", flags: "java" },
  { name: "foam/test/AllProperties" },
  { name: "foam/test/AllSerializableProperties", flags: "java" },
  { name: "foam/test/TestEnum", flags: "java" },
  { name: "foam/test/TestObj", flags: "java" },
  { name: "foam/test/IdentifiedStringHolder", flags: "java" },
  { name: "foam/core/FObjectTest", flags: "java" },
  { name: "foam/flow/Document", flags: "java" },
  { name: "foam/flow/DocumentMenu", flags: "java" },
  { name: "foam/flow/MarkupEditor" },
  { name: "foam/flow/DocumentationFolderDAO", flags: "java" },
  { name: "foam/flow/widgets/AxiomShortSummary" },
  { name: "foam/flow/widgets/MethodShortSummary" },
  { name: "foam/flow/widgets/PropertyShortSummary" },
  { name: "foam/flow/widgets/SequenceSummary" },
  { name: "foam/flow/widgets/ModelSummary" },
  { name: "foam/flow/widgets/EnumSummary" },
  { name: "foam/flow/widgets/TabbedModelDocumentation" },
  { name: "foam/flow/widgets/DocumentationIncomplete" },
  { name: "foam/flow/widgets/TryItSnippet" },
  { name: "foam/flow/widgets/ApiShortSummary" },
  { name: "org/chartjs/Lib" },
  { name: "org/chartjs/ChartCView" },
  { name: "org/chartjs/AbstractChartCView" },
  { name: "org/chartjs/AbstractChartView" },
  { name: "org/chartjs/HorizontalBarDAOChartView" },
  { name: "org/chartjs/CandlestickDAOChartView" },
  { name: "org/chartjs/PieDAOChartView" },
  { name: "org/chartjs/Pie" },
  { name: "org/chartjs/Bar" },
  { name: "org/chartjs/Line" },
  { name: "org/chartjs/Line2" },
  { name: "org/chartjs/Bar2" },
  { name: "org/chartjs/Pie2" },
  { name: "foam/dashboard/model/VisualizationSize" },
  { name: "foam/dashboard/model/Visualization" },
  { name: "foam/dashboard/model/GroupBy" },
  { name: "foam/dashboard/model/Count" },
  { name: "foam/dashboard/model/Table" },
  { name: "foam/dashboard/view/Count" },
  { name: "foam/dashboard/view/Table" },
  { name: "foam/dashboard/view/Pie" },
  { name: "foam/dashboard/view/Bar" },
  { name: "foam/dashboard/view/Line" },
  { name: "foam/dashboard/view/DAOTable" },
  { name: "foam/dashboard/view/HorizontalDAOTable" },
  { name: "foam/dashboard/view/UserGreetingView" },
  { name: "foam/dashboard/view/GroupByDAOTable" },
  { name: "foam/dashboard/view/GroupByCitationView" },
  { name: "foam/dashboard/view/Card" },
  { name: "foam/dashboard/view/Dashboard" },
  { name: "foam/build/Library" },
  { name: "foam/build/EmbeddedModelDAO" },
  { name: "foam/u2/view/JSONTextView" },
  { name: "foam/u2/view/MapView" },
  { name: "foam/u2/view/AnyView" },
  { name: "foam/u2/view/ArrayView" },
  { name: "io/c9/ace/Config" },
  { name: "io/c9/ace/Editor" },
  { name: "io/c9/ace/KeyBinding" },
  { name: "io/c9/ace/Lib" },
  { name: "io/c9/ace/Mode" },
  { name: "io/c9/ace/Theme" },
  { name: "foam/u2/view/date/AbstractDateView" },
  { name: "foam/u2/view/date/RODateView" },
  { name: "foam/u2/view/date/ROMillisecondView" },
  { name: "foam/u2/view/date/CalendarDatePicker" },
  { name: "foam/u2/view/date/DateTimePicker" },
  { name: "foam/u2/view/date/Month" },
  { name: "foam/u2/view/date/Weekday" },
  { name: "foam/u2/view/DAOtoFObjectArrayView" },
  { name: "foam/u2/layout/DisplayWidth", flags: "java" },
  { name: "foam/u2/layout/Layouts" },
  { name: "foam/u2/layout/Grid" },
  { name: "foam/u2/layout/Card" },
  { name: "foam/u2/layout/GUnit" },
  { name: "foam/u2/layout/GridColumns" },
  { name: "foam/comics/v2/CannedQuery", flags: "java" },
  { name: "foam/comics/v2/EnabledActionsAuth", flags: "java" },
  { name: "foam/comics/v2/BasicEnabledActionsAuth", flags: "java" },
  { name: "foam/comics/v2/CRUDEnabledActionsAuth", flags: "java" },
  { name: "foam/comics/v2/DAOBrowseControllerView" },
  { name: "foam/comics/v2/DAOBrowserView" },
  { name: "foam/comics/v2/DAOControllerConfig", flags: "java" },
  { name: "foam/comics/v2/DAOCreateView" },
  { name: "foam/comics/v2/DAOSummaryView" },
  { name: "foam/comics/v2/DAOUpdateView" },
  { name: "foam/comics/v2/NamedViews", flags: "java" },
  { name: "foam/comics/v2/userfeedback/UserFeedbackAware", flags: "java" },
  { name: "foam/comics/v2/userfeedback/UserFeedbackStatus", flags: "java" },
  { name: "foam/comics/v2/userfeedback/UserFeedback", flags: "java" },
  { name: "foam/comics/v2/userfeedback/UserFeedbackException", flags: "java" },
  { name: "foam/layout/Section" },
  { name: "foam/layout/SectionAxiom" },
  { name: "foam/u2/detail/AbstractSectionedDetailView" },
  { name: "foam/u2/detail/ChoiceSectionDetailView" },
  { name: "foam/u2/detail/SectionView" },
  { name: "foam/u2/detail/SectionedDetailView" },
  { name: "foam/u2/detail/VerticalDetailView" },
  { name: "foam/u2/detail/WizardSectionsView" },
  { name: "foam/u2/detail/DAOWizardSectionsView" },
  { name: "foam/u2/detail/TabbedDetailView" },
  { name: "foam/u2/detail/SectionedDetailPropertyView" },
  { name: "foam/u2/dialog/SimpleActionDialog" },
  { name: "foam/u2/tag/CircleIndicator" },
  { name: "foam/u2/wizard/agents/ConfigureFlowAgent", flags: ['web'] },
  { name: "foam/u2/wizard/agents/DeveloperModeAgent", flags: ['web'] },
  { name: "foam/u2/wizard/agents/RootCapabilityAgent", flags: ['web'] },
  { name: "foam/u2/wizard/agents/StepWizardAgent", flags: ['web'] },
  { name: "foam/u2/wizard/agents/SpinnerAgent", flags: ['web'] },
  { name: "foam/u2/wizard/agents/DetachAgent", flags: ['web'] },
  { name: "foam/u2/wizard/agents/WizardletsAgent", flags: ['web'] },
  { name: "foam/u2/wizard/internal/PropertyUpdate" },
  { name: "foam/u2/wizard/internal/FObjectRecursionSlot" },
  { name: "foam/u2/wizard/internal/WizardletAutoSaveSlot" },
  { name: "foam/u2/wizard/internal/lib" },
  { name: "foam/u2/wizard/debug/WizardEvent" },
  { name: "foam/u2/wizard/debug/DebugWAO" },
  { name: "foam/u2/wizard/debug/DebugContextIntercept" },
  { name: "foam/u2/wizard/debug/DebugWizardletView" },
  { name: "foam/u2/wizard/DAOWAO" },
  { name: "foam/u2/wizard/debug/WizardInspector" },
  { name: "foam/u2/wizard/WAO" },
  { name: "foam/u2/wizard/ProxyWAO" },
  { name: "foam/u2/wizard/NullWAO" },
  { name: "foam/u2/wizard/axiom/WizardAction" },
  { name: "foam/u2/wizard/WizardPosition", flags: "java" },
  { name: "foam/u2/wizard/Wizardlet", flags: "java" },
  { name: "foam/u2/wizard/WizardletSection" },
  { name: "foam/u2/wizard/WizardletIndicator", flags: "java" },
  { name: "foam/u2/wizard/BaseWizardlet", flags: "java" },
  { name: "foam/u2/wizard/SubmitWizardlet" },
  { name: "foam/u2/wizard/WizardletAware", flags: "java" },
  { name: "foam/u2/wizard/WizardletView" },
  { name: "foam/u2/wizard/StepWizardConfig", flags: "java" },
  { name: "foam/u2/wizard/StepWizardController" },
  { name: "foam/u2/wizard/StepWizardletStepsView" },
  { name: "foam/u2/wizard/IncrementalStepWizardView" },
  { name: "foam/u2/wizard/WizardletSearchController" },
  { name: "foam/u2/wizard/ScrollingStepWizardView" },
  { name: "foam/u2/wizard/ScrollWizardletView" },
  { name: "foam/u2/wizard/DAOWizardlet" },
  { name: "foam/u2/wizard/FObjectHolder", flags: ["web", "java"] },
  { name: "foam/u2/wizard/XORMinMaxWAO", flags: ["web"] },
  { name: "foam/u2/wizard/PrerequisiteWAO", flags: ["web"] },
  { name: "foam/u2/crunch/wizardflow/SkipMode", flags: [ "web", "java" ] },
  { name: "foam/u2/crunch/EasyCrunchWizard", flags: [ "web", "java" ] },
  { name: "foam/graphics/ZoomMapView" },
  { name: "foam/strategy/StrategyReference", flags: "java" },
  { name: "foam/strategy/StrategizerService", flags: "java" },
  { name: "foam/strategy/BasicStrategizer", flags: "java" },
  { name: "foam/strategy/ClientStrategizerService", flags: "java" },
  { name: "foam/core/Unit", flags: "java" },
  { name: "foam/core/Currency", flags: "java" },
  { name: "foam/core/NumberSet", flags: "java" },
  { name: "foam/util/concurrent/AbstractAssembly", flags: "java" },
  { name: "foam/util/concurrent/Assembly", flags: "java" },
  { name: "foam/foamlink/FoamlinkData" },
  { name: "foam/foamlink/FoamlinkExec" },
  { name: "foam/foamlink/lib" },
  { name: "foam/util/filesystem/FileWalker" },
  { name: "foam/nanos/column/ColumnConfigPropertyValue", flags: "java" },
  { name: "foam/nanos/column/CommonColumnHandler" },
  { name: "foam/nanos/column/CSVTableOutputter" },
  { name: "foam/nanos/column/NestedPropertiesExpression", flags: "java" },
  { name: "foam/nanos/column/TableColumnOutputter", flags: "java" },
  { name: "foam/i18n/XLIFFTranslationValue", flags: "java" },
  { name: "foam/i18n/Locale", flags: "java" },
  { name: "foam/i18n/TranslationService", flags: "java" },
  { name: "foam/i18n/ClientCacheTranslationService" },
  { name: "foam/i18n/TranslationConsole" },
  { name: "foam/i18n/TranslationConsoleMenu" },
  { name: "foam/i18n/ClientTranslationService" },
  { name: "foam/i18n/InlineLocaleEditor" },
  { name: "foam/u2/layout/MDDAOUpdateController" },
  { name: "foam/u2/layout/MDStackView" },
  { name: "foam/u2/layout/MDDAOCreateController" },
  { name: "foam/u2/property/MDInput", flags: "web" },
  { name: "foam/u2/property/MDTextField", flags: "web" },
  { name: "foam/u2/property/MDCalendar", flags: "web" },
  { name: "foam/u2/property/MDDateField", flags: "web" },
  { name: "foam/u2/property/MDDatePicker", flags: "web" },
  { name: "foam/u2/property/MDSelect", flags: "web" },
  { name: "foam/u2/property/MDRichSelect", flags: "web" },
  { name: "foam/u2/property/MDFloatView", flags: "web" },
  { name: "foam/u2/property/MDPopup", flags: "web" },
  { name: "foam/u2/property/MenuElement", flags: "web" },
  { name: "foam/u2/property/MDCheckBox", flags: "web" },
  { name: "foam/u2/property/MDRangeView", flags: "web" },
  { name: "foam/u2/property/AbstractCheckBox", flags: "web" },
  { name: "foam/u2/detail/MDDetailView", flags: "web" },
  { name: "foam/u2/layout/MDSearchView", flags: "web" },
  { name: "foam/u2/layout/MDSideNavigation", flags: "web" },
  { name: "foam/u2/layout/MDProfileImageView", flags: "web" },
  { name: "foam/u2/layout/MDToolbarView", flags: "web" },
  { name: "foam/u2/dao/MDDAOList", flags: "web" },
  { name: "foam/u2/layout/MDRowView", flags: "web" },
  { name: "foam/u2/layout/MDCitationView", flags: "web" },
  { name: "foam/u2/layout/MDDAOController", flags: "web" },
  { name: "foam/u2/md/AppController" },
  { name: "foam/u2/md/OverlayDropdown", flags: "web" },
  { name: "foam/u2/layout/MDLoginView", flags: "web" },
  { name: "foam/u2/layout/MDNotificationMessage", flags: "web" },
  { name: "foam/u2/md/tag/PaperDropdown", flags: "web" },
  { name: "foam/counter/Counter", flags: "java" },
  { name: "foam/dashboard/view/DashboardCitationView" },
  { name: "foam/dashboard/view/DateRangeChoiceView" },
  { name: "foam/nanos/fs/AgreementView" },
  { name: "foam/nanos/crunch/ruler/UCJDataExpiryRule", flags: "java" },
  { name: "foam/time/Hours", flags: "java" },
  { name: "foam/time/TimeZone", flags: "java" },
  { name: "foam/time/DayOfWeek", flags: "java" },
  { name: "foam/time/TimeUnit", flags: "java" },
  { name: "foam/u2/table/TableComponentView", flags: "web" },
  { name: "foam/u2/table/TableView", flags: "web" },
  { name: "foam/u2/table/UnstyledTableGroup", flags: "web" },
  { name: "foam/u2/table/UnstyledTableRow", flags: "web" },
  { name: "foam/u2/table/UnstyledTableView", flags: "web" },
  { name: "foam/u2/table/TableHeaderComponent", flags: "web" },
  { name: "foam/u2/memento/Memento" },
  { name: "foam/util/retry/RetryStrategy", flags: "java" },
  { name: "foam/util/retry/NoRetryStrategy", flags: "java" },
  { name: "foam/util/retry/SimpleRetryStrategy", flags: "java" },
  { name: "foam/util/retry/BackoffRetryStrategy", flags: "java" },
  { name: "foam/util/retry/RetryForeverStrategy", flags: "java" },
  { name: "foam/util/retry/RetryUntilStrategy", flags: "java" },
  { name: "foam/util/retry/RetryStrategyFactory", flags: "java" },
  { name: "foam/util/retry/RetryLimitReachedException", flags: "java" },
  { name: "foam/u2/view/DateChoiceView", flags: "web" },
  { name: "foam/u2/view/DayOfMonthView", flags: "web" },
  { name: "foam/u2/view/DayOfWeekView", flags: "web" },
  { name: "foam/u2/view/DayChoiceView", flags: "web" },
  { name: "foam/core/FOAMExceptionTestTestException", flags: "java" },
  { name: "foam/core/Identifiable", flags: "java" },
  { name: "foam/net/IPSupport", flags: "java" },
  { name: "foam/box/AbstractSkeleton", flags: "java" },
  { name: "foam/demos/heroes/Hero", flags: "web" },
  { name: "com/google/auth/TokenVerifier", flags: "java" },
  { name: "foam/box/sf/SFBOX", flags: "java" },
  { name: "foam/box/sf/SFSink", flags: "java" },
  { name: "foam/box/sf/SFDAO", flags: "java" },
  { name: "foam/box/sf/DUGSFRuleAction", flags: "java" },
  { name: "foam/box/sf/DUGSFRule", flags: "java" },
  { name: "foam/box/sf/SFEntry", flags: "java" },
  { name: "foam/box/sf/SFManager", flags: "java" },
  { name: "foam/box/sf/SF", flags: "java" },
  { name: "foam/box/sf/SFFileJournal", flags: "java" },
  { name: "foam/box/sf/SFTestObject", flags: "java" },
  { name: "foam/box/sf/SFException", flags: "java" },
  { name: "foam/box/sf/SFMonitorDAO", flags: "java" },
  { name: "foam/box/sf/SFMonitor", flags: "java" },
  { name: "foam/nanos/medusa/sf/MedusaSFManager", flags: "java" },
  { name: "foam/nanos/medusa/sf/SFBroadcastDAO", flags: "java" },
  { name: "foam/nanos/medusa/sf/SFBroadcastReceiverDAO", flags: "java" },
  { name: "foam/nanos/medusa/sf/SFMedusaClientDAO", flags: "java" },
  { name: "foam/box/socket/BoxHolder", flags: "java" },
  { name: "foam/box/socket/SocketConnectionBox", flags: "java" },
  { name: "foam/box/socket/SocketConnectionReplyBox", flags: "java" },
  { name: "foam/dao/SlowDAO", flags: "java" },
  { name: "foam/dao/JSONFormatParseDAO", flags: "java" },
  { name: "foam/dao/RemoveChildrenOnRemoveDAO", flags: "java" },
  { name: "foam/dao/AbstractF3FileJournal", flags: "java" },
  { name: "foam/dao/F3FileJournal", flags: "java" },
  { name: "foam/dao/ReadOnlyF3FileJournal", flags: "java" },
  { name: "foam/dao/WriteOnlyJDAO", flags: "java" },
  { name: "foam/dao/WriteOnlyFileJournal", flags: "java" },
  { name: "foam/dao/WriteOnlyF3FileJournal", flags: "java" },
  { name: "foam/dao/PMDAO", flags: "java" },
  { name: "foam/dao/ORBRequest", flags: "java" },
  { name: "foam/dao/ORBitalDAO", flags: "java" },
  { name: "foam/nanos/alarming/AlarmConfigOMNameDAO", flags: "java" },
  { name: "foam/nanos/alarming/AlarmConfigOMNameSink", flags: "java" },
  { name: "foam/nanos/alarming/AlarmIdRefines", flags: "java" },
  { name: "foam/nanos/actioncommand/ActionCommand", flags: "java" },
  { name: "foam/nanos/auth/AuthorizationDAO", flags: "java" },
  { name: "foam/nanos/auth/GroupPermissionJunctionRefinement", flags: "java" },
  { name: "foam/nanos/auth/LocaleSupport", flags: "java" },
  { name: "foam/nanos/auth/DeletedAwareDAO", flags: "java" },
  { name: "foam/nanos/auth/PasswordExpiryAuthService", flags: "java" },
  { name: "foam/nanos/auth/SystemAuthService", flags: "java" },
  { name: "foam/nanos/auth/twofactor/GoogleTOTPAuthService", flags: "java" },
  { name: "foam/nanos/auth/twofactor/TwoFactorAuthService", flags: "java" },
  { name: "foam/nanos/auth/LogoutDisabledUserDAO", flags: "java" },
  { name: "foam/nanos/auth/EnabledCheckAuthService", flags: "java" },
  { name: "foam/nanos/session/LocalSettingSessionDAO", flags: "java" },
  { name: "foam/nanos/session/SimpleSessionService", flags: "java" },
  { name: "foam/nanos/pool/AbstractFixedThreadPool", flags: "java" },
  { name: "foam/nanos/om/OMLogger", flags: "java" },
  { name: "foam/nanos/logger/LoggerUserInfo", flags: "java" },
  { name: "foam/nanos/logger/LoggerJournal", flags: "java" },
  { name: "foam/nanos/notification/email/EmailPropertyService", flags: "java" },
  { name: "foam/nanos/notification/email/EmailTemplateEngine", flags: "java" },
  { name: "foam/nanos/notification/email/NullEmailService", flags: "java" },
  { name: "foam/nanos/notification/email/ChainedPropertyService", flags: "java" },
  { name: "foam/nanos/notification/email/EmailTemplateApplyEmailPropertyService", flags: "java" },
  { name: "foam/nanos/notification/email/GroupEmailTemplateService", flags: "java" },
  { name: "foam/nanos/notification/email/EmailConfigEmailPropertyService", flags: "java" },
  { name: "foam/nanos/notification/email/EmailMessageValidationPropertyService", flags: "java" },
  { name: "foam/nanos/notification/email/ApplyBaseArgumentsEmailPropertyService", flags: "java" },
  { name: "foam/nanos/notification/email/EmailServiceDAO", flags: "java" },
  { name: "foam/nanos/notification/sms/NullSMSService", flags: "java" },
  { name: "foam/nanos/notification/sms/ProxySMSService", flags: "java" },
  { name: "foam/nanos/notification/NotificationTemplateDAO", flags: "java" },
  { name: "foam/nanos/google/api/sheets/GoogleSheetsApiService", flags: "java" },
  { name: "foam/lib/ExternalPropertyPredicate", flags: "java" },
  { name: "foam/lib/StorageTransientPropertyPredicate", flags: "java" },
  { name: "foam/lib/ClusterPropertyPredicate", flags: "java" },
  { name: "foam/lib/parse/SymbolParser", flags: "java" },
  { name: "foam/lib/parse/Grammar", flags: "java" },
  { name: "foam/lib/json/UnknownFObjectArray", flags: "java" },
  { name: "foam/lib/xml/OutputXML", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsAddressComponent", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsCoordinates", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsGeocodeResponse", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsGeocodeResult", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsGeometry", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsBoundary", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsAddressParser", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsPlacesPredictions", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsPlacesResponse", flags: "java" },
  { name: "foam/nanos/demo/relationship/test/RelationshipTest", flags: "java" },
  { name: "foam/nanos/fs/FileDataClearSink", flags: "java" },
  { name: "foam/nanos/fs/FileDataDAO", flags: "java" },
  { name: "foam/nanos/fs/FileUpdateDecorator", flags: "java" },
  { name: "foam/nanos/fs/TempFileDAO", flags: "java" },
  { name: "foam/nanos/dig/FieldNameMapGrammar", flags: "java" },
  { name: "foam/lib/query/TestModel", flags: "java" },
  { name: "foam/lib/query/FooEnum", flags: "java" },
  { name: "foam/nanos/dig/ExternalDataAware", flags: "java" },
  { name: "foam/nanos/dig/drivers/DigFormatDriver", flags: "java" },
  { name: "foam/nanos/dig/drivers/DigCsvDriver", flags: "java" },
  { name: "foam/nanos/dig/drivers/DigHtmlDriver", flags: "java" },
  { name: "foam/nanos/dig/drivers/DigJsonDriver", flags: "java" },
  { name: "foam/nanos/dig/drivers/DigJsonJDriver", flags: "java" },
  { name: "foam/nanos/dig/drivers/DigXmlDriver", flags: "java" },
  { name: "foam/nanos/ruler/RulerData", flags: "java" },
  { name: "foam/nanos/actioncommand/ActionCommandDAO", flags: "java" },
  { name: "foam/nanos/approval/ApprovalDAO", flags: "java" },
  { name: "foam/nanos/approval/SendGroupRequestApprovalDAO", flags: "java" },
  { name: "foam/nanos/audit/AuditDAO", flags: "java" },
  { name: "foam/nanos/auth/email/EmailVerificationDAO", flags: "java" },
  { name: "foam/dao/FreezingDAO", flags: "java" },
  { name: "foam/nanos/geocode/GoogleMapsGeocodingDAO", flags: "java" },
  { name: "foam/dao/history/HistoryDAO", flags: "java" },
  { name: "foam/nanos/script/ScriptRunnerDAO", flags: "java" },
  { name: "foam/dao/UnreliableDAO", flags: "java" },
  { name: "foam/nanos/auth/UserPasswordHashingDAO", flags: "java" },
  { name: "foam/dao/ValidatingDAO", flags: "java" },
  { name: "foam/nanos/test/StockSnapshot", flags: "java" },
  { name: "foam/nanos/analytics/FoldManager", flags: "java" },
  { name: "foam/nanos/analytics/FoldManagerDAODecorator", flags: "java" },
  { name: "foam/nanos/analytics/DAOFoldManager", flags: "java" },
  { name: "foam/nanos/analytics/DAOReduceManager", flags: "java" },
  { name: "foam/dao/jdbc/TestDataForJDBC", flags: "java" },
  { name: "foam/java/ParseTemplateTest", flags: "java" },
  { name: "foam/i18n/LocaleTranslationService", flags: "java" },
  { name: "foam/nanos/ndiff/NDiff", flags: "java" },
  { name: "foam/nanos/ndiff/NDiffDAO", flags: "java" },
  { name: "foam/nanos/ndiff/NDiffJournal", flags: "java" },
  { name: "foam/nanos/ndiff/NDiffRuntimeDAO", flags: "java" },
  { name: "foam/u2/view/ComparisonView" },
  { name: "foam/u2/view/SuggestedTextField", flags: "web" },
  { name: "foam/demos/csv/CsvUploadDemo", flags: "demo|web" }
  ]
});
