/**
 * @license
 * Copyright 2019 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.CLASS({
  package: 'foam.u2.filter.properties',
  name: 'DateFilterView',
  extends: 'foam.u2.Controller',

  documentation: 'A SearchView for properties of type Date.',

  implements: [
    'foam.mlang.Expressions'
  ],

  requires: [
    'foam.u2.view.ChoiceView'
  ],

  messages: [
    { name: 'LABEL_ALL',                message: 'All Time'       },
    { name: 'LABEL_EQUAL',              message: 'Equal'          },
    { name: 'LABEL_AFTER',              message: 'After'          },
    { name: 'LABEL_BEFORE',             message: 'Before'         },
    { name: 'LABEL_BETWEEN',            message: 'Between'        },
    { name: 'LABEL_INCLUSIVE',          message: 'Inclusive'      },
    { name: 'LABEL_LAST_7_DAYS',        message: 'Last 7 days'    },
    { name: 'LABEL_LAST_30_DAYS',       message: 'Last 30 days'   },
    { name: 'LABEL_LAST_3_MONTHS',      message: 'Last 3 months'  },
    { name: 'LABEL_LAST_6_MONTHS',      message: 'Last 6 months'  },
    { name: 'LABEL_LAST_12_MONTHS',     message: 'Last 12 months' }
  ],

  css: `
    ^ {
      padding: 24px 16px;
      box-sizing: border-box;
      min-width: 214px;
    }

    ^ .foam-u2-tag-Select {
      width: 100%;

      border-radius: 3px;
      border: solid 1px #cbcfd4;
      background-color: $backgroundDefault;
    }

    ^ .foam-u2-DateView {
      width: 100%;
      height: 36px;

      margin-top: 16px;

      border-radius: 3px;
      border: solid 1px #cbcfd4;
      background-color: $backgroundDefault;
    }

    ^ .foam-u2-PropertyBorder-inclusive {
      margin-top: 16px;
    }
  `,

  constants: [
    {
      class: 'Long',
      name: 'MILLIS_PER_DAY',
      value: 1000 * 60 * 60 * 24
    }
  ],

  properties: [
    {
      name: 'property',
      documentation: `
        The property that this view is filtering by. Should be of type Date.
      `,
      required: true
    },
    {
      class: 'String',
      name: 'qualifier',
      documentation: 'Lets the user choose a predicate to filter the view by.',
    },
    {
      class: 'Date',
      name: 'date1',
      documentation: `
        A date selectable by the user. Used as the second argument to the
        predicate generated by this view.
      `,
    },
    {
      class: 'Date',
      name: 'date2',
      documentation: `
        A date selectable by the user. Used as the second argument to the
        predicate generated by this view.
      `
    },
    {
      class: 'Boolean',
      name: 'inclusive',
      documentation: `
        Controls whether the start date is included in the 'Between' filter.
        When false (default): excludes start day, includes end day (> start, < end+1).
        When true: includes both start and end days (>= start, < end+1).
      `,
      value: false
    },
    {
      name: 'predicate',
      documentation: `
        All Search Views must have a predicate as required by the
        Filter Controller. When this property changes, the Filter Controller will
        generate a new main predicate and also reciprocate the changes to the
        other Search Views.
      `,
      expression: function(qualifier, date1, date2, inclusive) {
        if ( ! qualifier || qualifier === 'True' ) return this.TRUE;

        if ( qualifier.startsWith('Ls') ) { // If qualifier is a "Last N days/months"
          var amt = Number(qualifier.slice(2, -1)); // Get N
          var today = new Date();
          var lastDate = new Date(today);

          if ( amt == 7 || amt == 30 ) { // Figure out if it's days or months
            lastDate.setDate(lastDate.getDate() - amt);
          } else {
            lastDate.setMonth(lastDate.getMonth() - amt);
          }

          // Results should be >= lastDate but <= today
          return this.AND(this.GTE(this.property, lastDate), this.LTE(this.property, today));
        }

        if ( ! date1 || isNaN(date1.valueOf()) ) return this.TRUE;

        if ( qualifier !== 'Bt' ) {
          return foam.mlang.predicate[qualifier].create({
            arg1: this.property,
            arg2: date1
          });
        }

        if ( ! date2 || isNaN(date2.valueOf()) ) return this.TRUE;

        // Add +1 day to date2 to include the full end day (original behavior)
        var endDate = new Date(date2);
        endDate.setDate(endDate.getDate() + 1);

        if ( inclusive ) {
          // Includes both start and end days
          return this.AND(this.GTE(this.property, date1), this.LT(this.property, endDate));
        }

        // Original behavior: excludes start day, includes end day
        return this.AND(this.GT(this.property, date1), this.LT(this.property, endDate));
      }
    },
    {
      name: 'name',
      documentation: 'Required by Filter Controller.',
      expression: function(property) {
        return property.name;
      }
    },
  ],

  methods: [
    function render() {
      var self = this;
      this.addClass()
        .start(this.ChoiceView, {
              data$: this.qualifier$,
              choices: [
                ['True',  this.LABEL_ALL],
                ['Eq',    this.LABEL_EQUAL],
                ['Gt',    this.LABEL_AFTER],
                ['Lt',    this.LABEL_BEFORE],
                ['Bt',    this.LABEL_BETWEEN],
                ['Ls7d',  this.LABEL_LAST_7_DAYS],
                ['Ls30d', this.LABEL_LAST_30_DAYS],
                ['Ls3m',  this.LABEL_LAST_3_MONTHS],
                ['Ls6m',  this.LABEL_LAST_6_MONTHS],
                ['Ls12m', this.LABEL_LAST_12_MONTHS]
              ],
              defaultValue: 'True'
            })
          .start('div').addClass(this.myClass('carrot')).end()
        .end()
        .add(this.onDetach(this.slot(function(qualifier) {
          if ( ! qualifier || qualifier === 'True' || qualifier.startsWith('Ls') ) return this.E();
          return qualifier === 'Bt' ?
            this.E()
              .add(self.DATE1)
              .add(self.DATE2)
              .start(self.INCLUSIVE, { label: self.LABEL_INCLUSIVE })
              .end() :
            this.E().add(self.DATE1);
        })));
    },

    /**
     * Clears the fields to their default values.
     * Required on all SearchViews. Called by ReciprocalSearch.
     */
    function clear() {
      this.qualifier = 'True';
    },

    /**
     * Restores the view based on passed in predicate
     */
    function restoreFromPredicate(predicate) {
      if ( predicate === this.TRUE ) return;

      var qualifier = predicate.cls_.name;

      if ( qualifier == 'And' ) {
        // Check for a "Last N days/months" predicate
        if ( predicate.args[1].cls_.name === 'Lte' ) {
          var start = predicate.args[0].arg2.value;
          var end   = predicate.args[1].arg2.value;
          var days  = Math.round((end - start) / this.MILLIS_PER_DAY);

          // nearest matching option
          if      ( days <= 15 )  this.qualifier = 'Ls7d';
          else if ( days <= 60 )  this.qualifier = 'Ls30d';
          else if ( days <= 135 ) this.qualifier = 'Ls3m';
          else if ( days <= 270 ) this.qualifier = 'Ls6m';
          else                    this.qualifier = 'Ls12m';
          return;
        }

        // Check if it's inclusive (Gte) or exclusive (Gt) based on first predicate
        this.inclusive = predicate.args[0].cls_.name === 'Gte';
        this.qualifier = 'Bt';
        this.date1 = predicate.args[0].arg2.value;

        // Subtract 1 day from date2 since predicate stores date2+1
        var storedDate2 = new Date(predicate.args[1].arg2.value);
        storedDate2.setDate(storedDate2.getDate() - 1);
        this.date2 = storedDate2;
      } else {
        this.qualifier = qualifier;
        this.date1 = predicate.arg2.value;
      }
    }
  ]
});
