/**
 * @license
 * Copyright 2019 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

foam.CLASS({
  package: 'foam.u2.filter.properties',
  name: 'DateFilterView',
  extends: 'foam.u2.Controller',

  documentation: 'A SearchView for properties of type Date.',

  implements: [
    'foam.mlang.Expressions'
  ],

  requires: [
    'foam.u2.view.ChoiceView'
  ],

  messages: [
    { name: 'LABEL_ALL',       message: 'All Time' },
    { name: 'LABEL_EQUAL',     message: 'Equal' },
    { name: 'LABEL_AFTER',     message: 'After' },
    { name: 'LABEL_BEFORE',    message: 'Before' },
    { name: 'LABEL_BETWEEN',   message: 'Between' },
    { name: 'LABEL_INCLUSIVE',  message: 'Inclusive' }
  ],

  css: `
    ^ {
      padding: 24px 16px;
      box-sizing: border-box;
      min-width: 214px;
    }

    ^ .foam-u2-tag-Select {
      width: 100%;

      border-radius: 3px;
      border: solid 1px #cbcfd4;
      background-color: $backgroundDefault;
    }

    ^ .foam-u2-DateView {
      width: 100%;
      height: 36px;

      margin-top: 16px;

      border-radius: 3px;
      border: solid 1px #cbcfd4;
      background-color: $backgroundDefault;
    }

    ^ .foam-u2-PropertyBorder-inclusive {
      margin-top: 16px;
    }
  `,

  properties: [
    {
      name: 'property',
      documentation: `
        The property that this view is filtering by. Should be of type Date.
      `,
      required: true
    },
    {
      class: 'String',
      name: 'qualifier',
      documentation: 'Lets the user choose a predicate to filter the view by.',
    },
    {
      class: 'Date',
      name: 'date1',
      documentation: `
        A date selectable by the user. Used as the second argument to the
        predicate generated by this view.
      `,
    },
    {
      class: 'Date',
      name: 'date2',
      documentation: `
        A date selectable by the user. Used as the second argument to the
        predicate generated by this view.
      `
    },
    {
      class: 'Boolean',
      name: 'inclusive',
      documentation: `
        Controls whether the start date is included in the 'Between' filter.
        When false (default): excludes start day, includes end day (> start, < end+1).
        When true: includes both start and end days (>= start, < end+1).
      `,
      value: false
    },
    {
      name: 'predicate',
      documentation: `
        All Search Views must have a predicate as required by the
        Filter Controller. When this property changes, the Filter Controller will
        generate a new main predicate and also reciprocate the changes to the
        other Search Views.
      `,
      expression: function(qualifier, date1, date2, inclusive) {
        if ( ! qualifier || ! date1 || isNaN(date1.valueOf()) ) return this.TRUE;

        if ( qualifier !== 'Bt' ) {
          return foam.mlang.predicate[qualifier].create({
            arg1: this.property,
            arg2: date1
          });
        }

        if ( ! date2 || isNaN(date2.valueOf()) ) return this.TRUE;

        // Add +1 day to date2 to include the full end day (original behavior)
        var endDate = new Date(date2);
        endDate.setDate(endDate.getDate() + 1);

        if ( inclusive ) {
          // Includes both start and end days
          return this.AND(this.GTE(this.property, date1), this.LT(this.property, endDate));
        }

        // Original behavior: excludes start day, includes end day
        return this.AND(this.GT(this.property, date1), this.LT(this.property, endDate));
      }
    },
    {
      name: 'name',
      documentation: 'Required by Filter Controller.',
      expression: function(property) {
        return property.name;
      }
    },
  ],

  methods: [
    function render() {
      var self = this;
      this.addClass()
        .start(this.ChoiceView, {
              data$: this.qualifier$,
              choices: [
                ['True', this.LABEL_ALL],
                ['Eq',   this.LABEL_EQUAL],
                ['Gt',   this.LABEL_AFTER],
                ['Lt',   this.LABEL_BEFORE],
                ['Bt',   this.LABEL_BETWEEN]
              ],
              defaultValue: 'True'
            })
          .start('div').addClass(this.myClass('carrot')).end()
        .end()
        .add(this.onDetach(this.slot(function(qualifier) {
          if ( ! qualifier || qualifier === 'True' ) return this.E();
          return qualifier === 'Bt' ?
            this.E()
              .add(self.DATE1)
              .add(self.DATE2)
              .start(self.INCLUSIVE, { label: self.LABEL_INCLUSIVE })
              .end() :
            this.E().add(self.DATE1);
        })));
    },

    /**
     * Clears the fields to their default values.
     * Required on all SearchViews. Called by ReciprocalSearch.
     */
    function clear() {
      this.qualifier = 'True';
    },

    /**
     * Restores the view based on passed in predicate
     */
    function restoreFromPredicate(predicate) {
      if ( predicate === this.TRUE ) return;

      var qualifier = predicate.cls_.name;

      if ( qualifier == 'And' ) {
        // Check if it's inclusive (Gte) or exclusive (Gt) based on first predicate
        this.inclusive = predicate.args[0].cls_.name === 'Gte';
        this.qualifier = 'Bt';
        this.date1 = predicate.args[0].arg2.value;

        // Subtract 1 day from date2 since predicate stores date2+1
        var storedDate2 = new Date(predicate.args[1].arg2.value);
        storedDate2.setDate(storedDate2.getDate() - 1);
        this.date2 = storedDate2;
      } else {
        this.qualifier = qualifier;
        this.date1 = predicate.arg2.value;
      }
    }
  ]
});
